mysociety/alaveteli

app/views/general/search.html.erb, app/views/public_body/show.html.erb, app/views/request/_request_filter_form.html.erb, app/views/request/_request_search_form.html.erb, app/views/request/_sidebar.html.erb, app/views/request/list.html.erb, app/views/track/_rss_feed.html.erb, app/views/track/_tracking_links.html.erb, app/views/user/show.html.erb
Fixes #2032 
This PR preserves existing layout. To move the filters to a different location, simply remove the `:locals` block from `request/request_search_form` and render the partial elsewhere:
```erb
<div id="left-column">
<%= render :partial => 'request/request_filter_form' %>
</div>
<div id="right-column">
<%= render :partial => 'request/request_search_form' %>
</div>
```
=> [#2032] Extract body show partials

app/views/user/sign.html.erb, spec/integration/alaveteli_dsl.rb
=> [#1680] Reorder Sign in/Sign up forms

app/models/info_request.rb
The functionality is in `set_defaults`
=> Remove duplicate method.

Gemfile, Gemfile.lock
=> [#2072] gemfile version specifiers

app/views/admin_public_body/import_csv.html.erb
=> Tidy Public Body CSV import buttons

app/models/public_body.rb, spec/models/public_body_spec.rb
Work towards #2112 
PublicBodyCategory requires a description, so #2112 is voided.
This PR is some of the tidying up and specs made while investigating.
=> [#2112] type of authority locale

app/assets/stylesheets/responsive/_global_style.scss, app/assets/stylesheets/responsive/_signin_layout.scss, app/assets/stylesheets/responsive/_signin_style.scss, app/views/user/_signin.html.erb, app/views/user/_signup.html.erb, app/views/user/sign.html.erb, spec/integration/alaveteli_dsl.rb
This is ready for review now. Closes #1680 
Part of #1526
=> Design and wording changes to sign-in/sign-up screen

app/views/request/select_authority.html.erb, config/general.yml-example, doc/CHANGES.md, lib/configuration.rb
=> [#2101] country specific select authority

app/views/user/_signin.html.erb
=> [#2129] Increase target size of remember_me checkbox

app/assets/stylesheets/responsive/_global_style.scss, app/assets/stylesheets/responsive/_lists_layout.scss, app/helpers/public_body_helper.rb, app/models/public_body.rb, app/views/general/search.html.erb, app/views/public_body/_body_listing_single.html.erb, app/views/public_body/_search_ahead.html.erb, app/views/public_body/show.html.erb, app/views/public_body/view_email.html.erb, app/views/request/new.html.erb, spec/helpers/public_body_helper_spec.rb, spec/models/public_body_spec.rb, spec/views/public_body/show.html.erb_spec.rb
=> Add make request button to search results

docs/customising/themes.md
Add some basic info. Depends on https://github.com/mysociety/alavetelitheme/pull/35
=> Theme tests

app/assets/stylesheets/main.scss, app/assets/stylesheets/responsive/_global_style.scss, app/assets/stylesheets/responsive/_new_request_layout.scss, app/assets/stylesheets/responsive/_new_request_style.scss, app/assets/stylesheets/responsive/_public_body_layout.scss, app/assets/stylesheets/responsive/_public_body_style.scss, app/assets/stylesheets/responsive/_request_style.scss, app/controllers/public_body_controller.rb, app/helpers/public_body_helper.rb, app/models/track_thing.rb, app/views/info_request_batch/_batch_sent.html.erb, app/views/public_body/_search_ahead.html.erb, app/views/public_body/show.html.erb, app/views/request/_request_filter_form.html.erb, app/views/request/_request_sent.html.erb, app/views/request/_search_ahead.html.erb, app/views/request/new.html.erb, app/views/request/preview.html.erb, app/views/request/select_authorities.html.erb, app/views/request/select_authority.html.erb, spec/views/public_body/show.html.erb_spec.rb
Most of the smaller bits of #1526
=> [#1526] Redesign make request process

docs/installing/macos.md
=> Add a better note for new postgres users.

app/views/info_request_batch/_batch_sent.html.erb, app/views/request/new.html.erb
=> 2178 improve batch sent notice

Vagrantfile
via https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck
Been running this for a few days and seems stable. Haven't noticed a massive performance increase but its bound to help.
=> Give VirtualBox access to all host CPU cores

config/crontab-example, doc/CHANGES.md, script/compact-xapian-database
Fixes #2165
Fixes #1506 
~~Haven't tested yet and not sure why it was restarting apache originally.~~
Tested on Debian Wheezy and works.
#2189 preventing testing on Ubuntu Precise
=> [#2165] Restart alaveteli rather than apache

docs/running/admin_manual.md
=> Add sections on rate limiting and batch requests.

_layouts/page.html, docs/running/admin_manual.md, docs/running/holding_pen.md, docs/running/requests.md
OK so you've seen this page before because it snuck into `gh-pages` -- but here it is as a pull request so the Alaveteli devs can fact-check it, etc. Thanks team!
=> new page about administering requests (metadata)

docs/running/admin_manual.md, docs/running/requests.md
=> Add info on moving requests and resending them.

lib/languages.rb
Just updating to first caps to match GUI context
=> Update Croatian language

app/assets/stylesheets/admin.scss, app/controllers/admin_public_body_categories_controller.rb, app/controllers/admin_public_body_controller.rb, app/controllers/admin_public_body_headings_controller.rb, app/models/public_body.rb, app/models/public_body_category.rb, app/models/public_body_heading.rb, app/views/admin_public_body/_form.html.erb, app/views/admin_public_body_categories/_form.html.erb, app/views/admin_public_body_categories/_locale_fields.html.erb, app/views/admin_public_body_headings/_form.html.erb, app/views/admin_public_body_headings/_locale_fields.html.erb, spec/controllers/admin_public_body_categories_controller_spec.rb, spec/controllers/admin_public_body_controller_spec.rb, spec/controllers/admin_public_body_headings_controller_spec.rb, spec/integration/admin_public_body_category_edit_spec.rb, spec/integration/admin_public_body_heading_edit_spec.rb, spec/models/public_body_category_spec.rb, spec/models/public_body_heading_spec.rb, spec/models/public_body_spec.rb
Continued from https://github.com/mysociety/alaveteli/pull/2166
=> [#2140] translations failed validation r3d

lib/tasks/gettext.rake
We don't really want to make all the translators retranslate strings
that are basically the same but slightly tweaked in the English version.
So this task just replaces the msgid in the app.po files for each locale.
Mappings at https://gist.github.com/crowbot/76f706150a3ee3754212
=> Add rake task for uppdating locale files with slightly changed msgids

docs/installing/next_steps.md
=> Add some guidance about how to add public holidays.

app/controllers/general_controller.rb, spec/controllers/general_controller_spec.rb
=> Add an autodetect feed for the frontpage list of requests

config/initializers/alaveteli.rb, locale/es_NI/app.po
=> Update Nicaragua translations

app/views/help/unhappy.html.erb
=> [#2222] Remove pledgebank mention

_layouts/es/default.html
Fixes https://github.com/mysociety/alaveteli/issues/2292
=> Update lang attribute to 'es' for Spanish pages

app/views/request_game/play.html.erb
I started by fixing the mixed content warning then I noticed the HTML wasn't valid and that the alt text could be improved.
=> Stop categorisation game causing mixed content warning

app/controllers/admin_general_controller.rb
=> Don't list defunct authorities in admin list of authorities missing email addresses

app/models/user.rb
Both ends of the association should be defined
=> Add RequestClassification association to User

app/views/admin_public_body/edit.html.erb
=> Fix link to admin show page.

app/models/holiday_import.rb, spec/models/holiday_import_spec.rb
=> [#2374] Rescue from unknown region when importing holidays

app/controllers/admin_general_controller.rb, app/models/info_request.rb, app/views/admin_general/index.html.erb, spec/models/info_request_spec.rb
=> [#2241] admin summary performance

lib/health_checks/checks/days_ago_check.rb, lib/health_checks/health_checkable.rb, lib/health_checks/health_checks.rb, spec/lib/health_checks/checks/days_ago_check_spec.rb, spec/lib/health_checks/health_checkable_spec.rb, spec/lib/health_checks/health_checks_spec.rb
I broke this out of #2461 since it involves a small module API change.
=> Simplify HealthCheckable API

app/models/info_request.rb
=> Extract a method to add conditions from extra_params in InfoRequest

lib/world_foi_websites.rb
Added Croatian Alaveteli to the list of world FOI websites
=> Adding Croatian Alaveteli to world FOI websites

app/controllers/public_body_controller.rb, app/views/public_body/show.html.erb, spec/views/public_body/show.html.erb_spec.rb
Fixes the main part of #286 that's not covered by other issues.
=> Only include visible requests in count on body page

app/models/comment.rb, app/models/info_request.rb, app/models/user.rb, app/views/user/_user_listing_single.html.erb, app/views/user/show.html.erb
Removes an unused method and replaces a method with a scope.
=> Scope comments

lib/mail_handler/backends/mail_backend.rb, lib/normalize_string.rb, spec/fixtures/files/non-utf8-filename.email, spec/lib/basic_encoding_spec.rb, spec/lib/mail_handler/backends/mail_backend_spec.rb
=> Force filenames to utf8

community/index.md, docs/developers/index.md, docs/installing/manual_install.md, docs/running/security.md, docs/running/upgrading.md, es/community/index.md, es/docs/developers/index.md, es/docs/installing/manual_install.md, es/docs/running/security.md, es/docs/running/upgrading.md
Also reflect the fact that it is the default branch in a couple of
github links.
=> Update references to rails-3-develop branch to develop branch.

deployments.md
=> Include Hong Kong's accessinfo.hk in deployments page

app/mailers/contact_mailer.rb, spec/mailers/contact_mailer_spec.rb
=> Use address_from_name_and_email to correctly format from field.

script/request-creation-graph, script/user-use-graph
Same as #2541 except without putting password on command-line.
=> Eliminate TODO in shell scripts

app/models/concerns/public_body_derived_fields.rb, app/models/public_body.rb, spec/controllers/admin_public_body_controller_spec.rb, spec/models/public_body_spec.rb
Fixes the issue reported in https://github.com/mysociety/alaveteli/pull/2521
=> Updating derived atts for translations 

README.md
Link to http://alaveteli.org/deployments/ show how many deployments
exist.
=> Add link to more example deployments

app/controllers/request_controller.rb, app/models/censor_rule.rb, app/models/foi_attachment.rb, app/models/incoming_message.rb, lib/alaveteli_text_masker.rb, lib/attachment_to_html/adapter.rb, lib/mail_handler/backends/mail_backend.rb, lib/normalize_string.rb, spec/controllers/request_controller_spec.rb, spec/lib/alaveteli_text_masker_spec.rb, spec/lib/basic_encoding_spec.rb, spec/models/censor_rule_spec.rb, spec/models/foi_attachment_spec.rb
=> Binary or utf8 attachment bodies

docs/installing/manual_install.md, es/docs/installing/manual_install.md
This change was made in #2390.
=> Update the extension of the daemon scripts.

app/assets/stylesheets/responsive/_frontpage_layout.scss, app/assets/stylesheets/responsive/_frontpage_style.scss, app/controllers/general_controller.rb, app/views/general/_frontpage_requests_list.html.erb
=> backport improved homepage list of requests

app/assets/stylesheets/responsive/_frontpage_layout.scss, app/assets/stylesheets/responsive/_frontpage_style.scss, app/views/general/_frontpage_how_it_works.html.erb, app/views/general/frontpage.html.erb
=> Added simplfied how it works section, backported from WDTK

app/assets/stylesheets/responsive/_header_layout.scss, app/assets/stylesheets/responsive/all.scss, app/controllers/application_controller.rb, app/views/general/_locale_switcher.html.erb
Changes the locale switcher to include markup that will be used for JS dropdown functionality in themes
=> Add new style locale switcher HTML code

app/views/widgets/new.html.erb, doc/CHANGES.md
=> [#2661] Make widgets/new template translatable

.travis.yml, Gemfile, config/application.rb
Fixes #2588
Only 1.9+ is supported now
=> [#2588] Remove platform constraint for rack-utf8_sanitizer

Gemfile, Gemfile.lock
=> Use latest version of Xapian.

docs/developers/i18n.md
Introduced in https://github.com/mysociety/alaveteli/pull/2619
=> Add Internationalised Sorting documentation

app/controllers/general_controller.rb, app/models/info_request_event.rb, app/models/request_classification.rb, doc/CHANGES.md, spec/controllers/general_controller_spec.rb, spec/factories/request_classifications.rb
Fixes #2587 
Target version: `0.22.2.0`
=> [#2587] Transaction stats json

docs/customising/config.md
Docs for #2387 
Counterpart to #2616 
Needs translation
=> [#2387] Add spam score filtering docs

app/controllers/admin_censor_rule_controller.rb, app/controllers/admin_comment_controller.rb, app/controllers/admin_holiday_imports_controller.rb, app/controllers/admin_holidays_controller.rb, app/controllers/admin_incoming_message_controller.rb, app/controllers/admin_info_request_event_controller.rb, app/controllers/admin_outgoing_message_controller.rb, app/controllers/admin_public_body_categories_controller.rb, app/controllers/admin_public_body_change_requests_controller.rb, app/controllers/admin_public_body_controller.rb, app/controllers/admin_public_body_headings_controller.rb, app/controllers/admin_raw_email_controller.rb, app/controllers/admin_request_controller.rb, app/controllers/admin_spam_addresses_controller.rb, app/controllers/admin_track_controller.rb, app/controllers/admin_user_controller.rb, app/controllers/concerns/translatable_params.rb, app/helpers/admin_public_body_category_helper.rb, app/views/admin_public_body_categories/_form.html.erb, app/views/admin_public_body_categories/edit.html.erb, app/views/admin_public_body_categories/new.html.erb, app/views/admin_public_body_headings/_form.html.erb, app/views/admin_public_body_headings/edit.html.erb, app/views/admin_public_body_headings/new.html.erb, config/application.rb, doc/CHANGES.md, spec/controllers/admin_public_body_categories_controller_spec.rb, spec/controllers/admin_public_body_headings_controller_spec.rb, spec/controllers/concerns/translatable_params_spec.rb
Standardising some patterns in the admin controllers.
=> Use standard patterns in all admin controllers.

.hound.yml, .ruby-style.yml
=> [#2486] hound

app/assets/stylesheets/responsive/_print_style.scss, app/assets/stylesheets/responsive/_utils.scss, app/views/general/_responsive_header.html.erb
There may be one or selectors that don't exist here yet, but they will when other PRs are merged in
=> add backported print styles from WDTK

spec/integration/create_request_spec.rb
Otherwise create_request will fail due to the absence of
Geraldine Quango e.g. https://travis-ci.org/mysociety/alaveteli/jobs/79274938
=> Make sure fixtures are available in xapian for spec.

app/assets/stylesheets/responsive/_request_style.scss, app/assets/stylesheets/responsive/_sidebar_layout.scss, app/assets/stylesheets/responsive/_sidebar_style.scss, app/views/request/_sidebar.html.erb, doc/CHANGES.md
This is because #follow_box was being blocked by adblock plugins
Closes #2763
=> rename #follow_box to #track-request

app/assets/stylesheets/responsive/_request_layout.scss
=> [#2795] Wrap long links in correspondence boxes

app/controllers/application_controller.rb, spec/controllers/general_controller_spec.rb
=> Check that the post_redirect_token is valid before trying to use it

app/models/info_request.rb, app/models/public_body.rb, app/views/general/_frontpage_bodies_list.html.erb, app/views/public_body/_body_listing_single.html.erb, db/migrate/20151009162421_add_info_requests_visible_count_to_public_bodies.rb, spec/controllers/public_body_controller_spec.rb, spec/fixtures/public_bodies.yml, spec/models/info_request_spec.rb, spec/views/general/frontpage.html.erb_spec.rb, spec/views/public_body/list.html.erb_spec.rb
=> Only count visible requests when rendering the public body list

spec/integration/admin_spec.rb
Fixes #2842 (and hopefully stops the random spec fail)
=> Remove fixture dependencies from integration/admin_spec

app/views/admin_request/edit.html.erb
=> Add confirmation dialog when destroying a request

app/models/public_body.rb, spec/models/public_body_spec.rb
=> Destroy dependencies when calling PublicBody#destroy

app/assets/stylesheets/responsive/_frontpage_layout.scss, app/assets/stylesheets/responsive/_global_layout.scss, app/views/general/_responsive_header.html.erb, app/views/layouts/default.html.erb
=> [#2783] Reposition homepage flash

.travis.yml
Followed the instructions on
https://codeclimate.com/repos/513a2c727e00a42468000685/coverage_setup
=> Send code coverage reports to code climate

app/models/info_request.rb
=> [#2387] Add log line to monitor incoming mail rejections

app/views/info_request_batch/_batch_sent.html.erb, app/views/request/_act.html.erb, app/views/request/_request_sent.html.erb
We are consolidating our social media channels.
Closes #2797.
=> Switch @alaveteli_foi to @mySocietyIntl.

app/models/info_request_event.rb, app/views/admin_request/_params.html.erb, app/views/admin_request/show.html.erb, spec/models/info_request_event_spec.rb, spec/views/admin_request/_params.html.erb_spec.rb
=> Tidy InfoRequestEvent

app/controllers/user_controller.rb, spec/controllers/user_controller_spec.rb
=> Recreate expired redirect token for signup and signin actions

.ruby-style.yml
https://github.com/bbatsov/rubocop#enabled
=> Disable all style checks by default

app/models/info_request_event.rb
=> Reduce queries in InfoRequestEvent#latest_status

app/assets/stylesheets/responsive/_header_layout.scss
=> Fix CSS bug that prevented nav menu from closing

app/models/info_request.rb, config/general.yml-example, doc/CHANGES.md, lib/configuration.rb, spec/models/info_request_spec.rb
=> [#2827] Configurable stop new responses

app/assets/stylesheets/responsive/_one_time_passwords_layout.scss, app/assets/stylesheets/responsive/_one_time_passwords_style.scss, app/assets/stylesheets/responsive/all.scss, app/controllers/one_time_passwords_controller.rb, app/controllers/password_changes_controller.rb, app/models/user.rb, app/views/one_time_passwords/_help_guide.html.erb, app/views/one_time_passwords/show.html.erb, app/views/password_changes/edit.html.erb, app/views/user/_show_user_info.html.erb, config/general.yml-example, config/routes.rb, doc/CHANGES.md, lib/configuration.rb, spec/controllers/one_time_passwords_controller_spec.rb, spec/controllers/password_changes_controller_spec.rb, spec/models/user_spec.rb
Fixes #2697
Todo when we're happy:
=> [#2697] Add two factor auth

app/models/info_request.rb, app/models/public_body.rb, app/models/user.rb, spec/integration/parameter_stripping_spec.rb
=> Remove methods deprecated for 0.23

app/controllers/admin_public_body_categories_controller.rb, app/controllers/admin_public_body_controller.rb, app/controllers/application_controller.rb, app/controllers/general_controller.rb, app/controllers/password_changes_controller.rb, app/controllers/public_body_controller.rb, app/controllers/request_controller.rb, app/views/user/sign.html.erb, spec/controllers/admin_public_body_categories_controller_spec.rb, spec/controllers/password_changes_controller_spec.rb, spec/controllers/public_body_controller_spec.rb, spec/controllers/user_controller_spec.rb, spec/views/user/sign.html.erb_spec.rb
Fixes suggested by Brakeman for the new release.
=> Brakeman fixes

script/site-specific-install.sh
=> [#2776] Idempotently attempt to create template_utf8

docs/customising/config.md, docs/glossary.md
Depends on https://github.com/mysociety/alaveteli/pull/2734
=> Add documentation about the GEOIP_DATABASE param.

docs/customising/config.md, docs/running/requests.md
=> Config docs 0.23

app/models/info_request.rb, app/models/info_request_event.rb, spec/models/info_request_spec.rb
=> Make InfoRequestEvent#request_title_request call InfoRequest#url_title

docs/installing/manual_install.md
=> Add Thin cluster setup steps to the manual install page

config/sysvinit-passenger.example
Fixes https://github.com/mysociety/Non-Site-Specific/issues/672
=> Symlink down file instead of copying

app/models/info_request.rb, app/models/public_body.rb, config/general.yml-example, config/initializers/alaveteli.rb, config/test.yml, doc/CHANGES.md, lib/configuration.rb, lib/default_late_calculator.rb, spec/lib/default_late_calculator_spec.rb, spec/models/info_request_spec.rb
=> [#625] Extract school logic

docs/customising/config.md, docs/installing/next_steps.md, docs/running/categories_and_tags.md, es/docs/customising/config.md
Part of #625
Only used for UK-specific school rules
=> [#625] Remove SPECIAL_REPLY_VERY_LATE_AFTER_DAYS config

app/views/request/describe_state_message.html.erb
=> [#3022] Fix untranslatable string

docs/installing/deploy.md
=> Add notes about capistrano and rbenv

app/controllers/help_controller.rb, app/controllers/public_body_controller.rb, app/controllers/services_controller.rb, app/helpers/application_helper.rb, app/views/help/unhappy.html.erb, app/views/public_body/_list_sidebar_extra.html.erb, app/views/public_body/list.html.erb, lib/world_foi_websites.rb, spec/controllers/services_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/lib/world_foi_websites_spec.rb
=> [#2457] AsktheEU References

docs/customising/themes.md
=> Add instructions for including logo@2.png files with themes

docs/running/upgrading.md
=> Include file permissions in upgrading docs

app/controllers/admin_censor_rule_controller.rb, app/models/censor_rule.rb, app/views/admin_censor_rule/_form.html.erb, app/views/admin_censor_rule/_show.html.erb, app/views/admin_censor_rule/edit.html.erb, app/views/admin_censor_rule/index.html.erb, app/views/admin_censor_rule/new.html.erb, app/views/admin_general/_admin_navbar.html.erb, app/views/admin_public_body/show.html.erb, config/routes.rb, doc/CHANGES.md, spec/controllers/admin_censor_rule_controller_spec.rb, spec/factories/censor_rules.rb, spec/models/censor_rule_spec.rb
=> [#2551] Manage global and public body censor rules through admin UI

app/views/followups/_followup.html.erb, app/views/request/show.html.erb, app/views/request_mailer/overdue_alert.text.erb, app/views/request_mailer/very_overdue_alert.text.erb, spec/views/request_game/play.html.erb_spec.rb
Fixes #625 
Extracted in to https://github.com/mysociety/whatdotheyknow-theme/pull/290
=> [#625] Remove uses of PublicBody#is_school?

app/controllers/admin_censor_rule_controller.rb
The filter no longer only sets an InfoRequest.
=> Rename filter for setting subject

docs/running/redaction.md
Part of #2551 
Updates due to https://github.com/mysociety/alaveteli/pull/3021
=> [#2551] Admin censor rules documentation

config/crontab-example, doc/CHANGES.md, script/cleanup-holding-pen
=> Add holding pen cleanup to cron list

doc/CHANGES.md
#2941 
Will need to update the changed views after https://github.com/mysociety/alaveteli/pull/3073 is merged.
=> [#2941] Update changelog

docs/running/adwords.md
Includes @MyfanwyNixon's changes to demystify Ad Groups and Campaigns and the expanded section on using Google's help system. Will address the structural changes separately.
---
---
connects to #3069
=> Update Adwords page with latest changes

doc/CHANGES.md, script/current-theme, script/diff-theme-override
Adds two scripts:
- `script/current-theme`: Prints the name or path of the current theme
- `script/diff-theme-override`: Diffs the theme file against the matching file in alaveteli core
Here's an example of just getting a rough picture of how much change there is in a theme (the error lines here are files that don't have an alaveteli-core counterpart):
```
vagrant@vagrant-ubuntu-precise-64: ~/alaveteli
$ find $(script/current-theme -v) -type f -name "*.erb" -exec script/diff-theme-override -e "--numstat" {} \;
error: Could not access './app//home/vagrant/alaveteli-themes/whatdotheyknow-theme/assets/images/browserconfig.xml.erb'
error: Could not access './app//home/vagrant/alaveteli-themes/whatdotheyknow-theme/assets/images/manifest.json.erb'
error: Could not access …
```
=> Add tools for comparing theme overrides against core files

docs/installing/ami.md
=> Update AMI docs to say we are not routinely updating the image

app/models/incoming_message.rb, app/models/info_request_event.rb, app/models/outgoing_message.rb, app/models/track_thing.rb
Misc minor code cleanup; was on the train with no internet access.
=> Code cleanup

lib/tasks/stats.rake
Originally authored by @jacksonj04 in
c305b548e976c6105774fb7410cdb2c0e074730e for WhatDoTheyKnow.
=> [#3114] Add a task to output requests made to top 20 bodies

app/views/request/describe_notices/_not_held.html.erb
/new does note exist
First part of https://github.com/mysociety/whatdotheyknow-theme/issues/304
=> [#304] Fix invalid URL

app/controllers/api_controller.rb
Found while looking in to https://github.com/mysociety/alaveteli/issues/3114
=> [#3114] Remove duplicated conditional

lib/tasks/temp.rake
Reducing changes for https://github.com/mysociety/alaveteli/issues/3114
=> [#3114] Remove Wdtk temp tasks

Gemfile.lock
=> [#3161] Upgrade xml-simple to 1.1.5

Gemfile, Gemfile.lock
=> [#3161] Upgrade pg to 0.18.4

Gemfile.lock
=> [#3161] Upgrade rspec-activemodel-mocks to 1.0.3

app/mailers/outgoing_mailer.rb, app/models/outgoing_message.rb, doc/CHANGES.md, spec/factories/outgoing_messages.rb, spec/mailers/outgoing_mailer_spec.rb, spec/models/outgoing_message_spec.rb
=> [#2819] OutgoingMessage #to, #from and #subject

app/models/incoming_message.rb, spec/models/incoming_message_spec.rb
Work on #2819
Added some specs and documentation to the attribute overrides on `IncomingMessage` to figure out if what I'm doing in #3149 is correct.
=> [#2819] document IncomingMessage attribute overrides

Gemfile.lock
=> [#3161] Upgrade rack-utf8_sanitizer to 1.3.2

Gemfile, Gemfile.lock, lib/normalize_string.rb
=> [#3161] Upgrade charlock_holmes to 0.7.3

lib/tasks/graphs.rake, script/request-creation-graph, script/user-use-graph
Sets a default y-range start point of 0 and avoids trying to plot a cumulative value line from a single datapoint.
Closes #3126
=> Stop triggering gnuplot warning messages

config/initializers/alaveteli.rb, lib/alaveteli_gettext/fuzzy_cleaner.rb, lib/tasks/gettext.rake, spec/lib/alaveteli_gettext/fuzzy_cleaner_spec.rb
RE: https://github.com/mysociety/alaveteli/issues/3204
=> Add task for removing fuzzy translations.

lib/tasks/stats.rake
=> Fix ambiguous clause.

app/views/request/new.html.erb
=> Fix untranslatable string

script/request-creation-graph, script/user-use-graph
=> Reinstate the --silent flag for the graph generation scripts

app/models/info_request.rb
=> Remove dup method

app/views/request/new.html.erb
Closes #3259
Introduces a new translation - should I do anything extra in this PR for that?
=> Add advice panel line asking users to check info not already published

app/views/mail_server_logs/index.html.erb
Fixes #3251 
Log loading is delayed until the current log is rotated by logrotate.
=> [#3251] Reword "check back for mail server logs" message

app/models/user.rb, config/initializers/alaveteli.rb, db/migrate/20160526154304_add_confirmed_not_spam_to_users.rb, doc/CHANGES.md, lib/tasks/cleanup.rake, lib/user_spam_scorer.rb, spec/lib/user_spam_scorer_spec.rb, spec/models/user_spec.rb
Work on #3180
Most of the users found by the AR query are spam accounts, but there are a handful that aren't.
Users for potential banning are sorted by spam score so that we hopefully get through obviously spammy users first.
There are some TODOs in UserSpamScorer that will increase the accuracy of it.
I'm thinking that we can take a spam score on signup and alert admins to potentially spam accounts. Might be able to instantly reject/ban very obvious spam.
Reasonably happy that this is scoring users in around the right ball park. Some spam users are getting low scores, but that would be improved by the addition of spam-words and Akismet checks.
```ruby
results.sort_by(&:last).take(5).each do |user_id, spam_score|
puts "Spam Score: #{spam_score}"
puts User.find(user_id).about_me
puts …
```
=> [#3180] User spam scorer

spec/controllers/admin_incoming_message_controller_spec.rb, spec/lib/acts_as_xapian_spec.rb
Fixes errors like https://travis-ci.org/mysociety/alaveteli/jobs/134157087
=> Don't require a specific order on array match.

app/views/admin_incoming_message/_actions.html.erb, app/views/admin_raw_email/show.html.erb, doc/CHANGES.md
Also standardize on a button representation for it.
Fixes #3280
=> Add download option to incoming message admin page.

app/controllers/admin_user_controller.rb, app/views/admin_user/_form.html.erb, app/views/user/_show_user_info.html.erb, app/views/user/show.html.erb, lib/tasks/cleanup.rake, lib/user_spam_scorer.rb, spec/controllers/admin_incoming_message_controller_spec.rb, spec/controllers/admin_user_controller_spec.rb, spec/lib/acts_as_xapian_spec.rb, spec/lib/user_spam_scorer_spec.rb
=> [#3180] spam user tweaks

app/controllers/user_controller.rb, app/views/general/exception_caught.html.erb, config/routes.rb, spec/integration/parameter_stripping_spec.rb
Fixes #3296 (– I think; Added by GR)
=> 3296 match routes specify method

app/models/comment.rb, app/models/info_request.rb, app/models/info_request_batch.rb, app/models/public_body_change_request.rb, app/models/request_classification.rb, app/models/track_thing.rb, app/models/user.rb, db/migrate/20160613145644_add_comments_count_to_users.rb, db/migrate/20160613151127_add_info_requests_count_to_users.rb, db/migrate/20160613151912_add_track_things_count_to_users.rb, db/migrate/20160613152433_add_request_classifications_count_to_users.rb, db/migrate/20160613153739_add_public_body_change_requests_count_to_users.rb, db/migrate/20160613154616_add_info_request_batches_count_to_users.rb, spec/controllers/user_controller_spec.rb
=> [#3283] Transaction counter caches

script/replicate-xapian-database
PR for review, per https://github.com/mysociety/sysadmin/issues/654
=> Add new script for replicating Xapian full text search databases

lib/mail_handler/backends/mail_extensions.rb, spec/fixtures/files/utf-7-subject.email, spec/lib/mail_handler/mail_handler_spec.rb
Fixes https://github.com/mysociety/alaveteli/issues/3328
=> Handle UTF-7 Subject

Gemfile, Gemfile.lock, app/models/user.rb, app/models/user/transaction_calculator.rb, doc/CHANGES.md, spec/models/user/transaction_calculator_spec.rb, spec/models/user_spec.rb, spec/spec_helper.rb
=> [#3283] User#transactions

app/assets/stylesheets/responsive/_request_style.scss, app/views/request/_outgoing_correspondence.html.erb
=> [#3341] delivery status link display bugs

app/models/incoming_message.rb, doc/CHANGES.md, spec/models/incoming_message_spec.rb
=> Format IncomingMessage body HTML with <p> tags rather than many <br>s

index.md
Fixes https://github.com/mysociety/alaveteli/issues/3363
=> Correct spelling of GitHub

_includes/footer.html
Part of https://github.com/mysociety/standard-footer/issues/9
=> UTM params for mysociety.org links in alaveteli.org footer

app/controllers/request_controller.rb, spec/controllers/request_controller_spec.rb
=> Make request#list only respond to html requests

app/models/user.rb, spec/models/user_spec.rb
=> Add nil check and strip of input.

app/models/info_request.rb, doc/CHANGES.md, spec/models/info_request_spec.rb
=> Make the holding pen hidden.

config/routes.rb
Fixes #3385
Tracks on user profile page get updated by a form POST.
=> [#3385] Fix broken track URL

app/views/admin_public_body/import_csv.html.erb, doc/CHANGES.md
The second commit (2500c3e) relies on my understanding of the phrase "import tag" being correct. See https://github.com/mysociety/alaveteli/issues/3325#issuecomment-229682964
Closes #3325
=> Improve on-page CSV upload docs

app/models/incoming_message.rb, spec/models/incoming_message_spec.rb
=> Destroy raw email record when destroying incoming message.

app/views/admin_general/index.html.erb
Thanks to input from @kingqueen3065.
=> Make the distinction between lists a bit clearer.

app/assets/stylesheets/responsive/_request_layout.scss, app/assets/stylesheets/responsive/_request_style.scss, app/views/request/_incoming_correspondence.html.erb, app/views/request/_outgoing_correspondence.html.erb
=> Redesigned correspondence section of request page

app/views/general/_localised_datepicker.html.erb, app/views/layouts/default.html.erb, app/views/public_body/statistics.html.erb, app/views/request/new.html.erb, app/views/request/select_authority.html.erb, app/views/user/set_crop_profile_photo.html.erb
=> Improve page load

app/controllers/admin_general_controller.rb, app/views/admin_general/debug.html.erb, spec/integration/admin_spec.rb
The debug page has had some bugs that have annoyed me since I started hacking on Alaveteli and I finally decided to fix them :smile: 
In a cleaning-as-you-go spirit I've also tidied up a few things.
=> Admin debug page fixes

README.md
Nice thing to do plus part of our terms of use
=> Add shoutout to Browserstack in README

README.md
As per the  Creative Commons Attribution-ShareAlike 4.0
International License.
Closes #3469
=> Add MaxMind credit.

app/models/info_request.rb, doc/CHANGES.md, spec/models/info_request_spec.rb
Prevents unnecessary work in #3417 and helps with #3461.
=> Remove deprecated methods

app/models/mail_server_log.rb, app/models/mail_server_log/delivery_status_serializer.rb, app/models/outgoing_message.rb, db/migrate/20160907144809_add_delivery_status_to_mail_server_logs.rb, spec/fixtures/files/exim-mainlog-2016-04-28, spec/models/mail_server_log/delivery_status_serializer_spec.rb, spec/models/mail_server_log_spec.rb
=> [#3335] Cache message delivery status

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, doc/CHANGES.md
=> Install better_errors in development for awesome debugging

app/assets/stylesheets/responsive/_request_style.scss, app/views/comment/_single_comment.html.erb
=> [#3441] Use the link-to-this box for annotations

app/assets/stylesheets/responsive/_frontpage_style.scss, app/assets/stylesheets/responsive/_lists_style.scss
Continuing from https://github.com/mysociety/alaveteli/pull/3527
=> Match status color

app/views/followups/new.html.erb
Fixes #3539 
Fixes https://github.com/mysociety/belgium-theme/issues/21
=> Fix broken email link in followup template

app/models/public_body.rb, app/views/public_body/statistics.html.erb, spec/integration/statistics_spec.rb, spec/models/public_body_spec.rb
Copy of #3534 because pushing to a remote repo was too hard for a Friday afternoon
=> Openaustralia 3532 fix public body stat totals

app/assets/stylesheets/admin.scss, app/helpers/admin_users_helper.rb, app/views/admin_user/_user_table.html.erb, doc/CHANGES.md, spec/helpers/admin_users_helper_spec.rb
=> [#3564] banned user styles

app/controllers/admin_comment_controller.rb, app/helpers/admin_comments_helper.rb, app/models/comment.rb, app/views/admin_comment/index.html.erb, app/views/admin_general/_admin_navbar.html.erb, config/routes.rb, doc/CHANGES.md, spec/controllers/admin_comment_controller_spec.rb, spec/helpers/admin_comments_helper_spec.rb, spec/models/comment_spec.rb
=> [#3565] admin comments list

app/controllers/user_controller.rb
`User.find_by_email` now strips and nil-checks.
=> Don't strip email in controller.

app/controllers/general_controller.rb, app/models/user.rb, doc/CHANGES.md, lib/tasks/graphs.rake, lib/tasks/stats.rake, spec/controllers/general_controller_spec.rb, spec/models/user_spec.rb
=> Exclude banned users from stats and graphs

app/views/public_body/view_email.html.erb
...but adds HTML to the translation file and is harder to quickly fix
the translation
=> Better link construction

app/assets/stylesheets/admin.scss, app/controllers/admin_user_controller.rb, app/helpers/admin_helper.rb, app/views/admin_user/index.html.erb, doc/CHANGES.md, spec/controllers/admin_user_controller_spec.rb, spec/helpers/admin_helper_spec.rb
=> [#3566] Add sorting to admin users list

app/models/outgoing_message.rb, spec/controllers/request_controller_spec.rb, spec/models/outgoing_message_spec.rb
=> Updating OutgoingMessage.default_letter should update default body text

app/models/info_request.rb, spec/integration/alaveteli_pro/request_creation_spec.rb, spec/models/info_request_spec.rb
Closes mysociety/alaveteli-professional#123
=> [Pro] Fix issues with validating empty requests on pro request form

app/views/alaveteli_pro/info_requests/_info_request.html.erb
Closes https://github.com/mysociety/alaveteli-professional/issues/129
=> [Pro] Remove request list actions.

app/assets/javascripts/alaveteli_pro/authority_select.js, app/views/alaveteli_pro/info_requests/new.html.erb
Closes mysociety/alaveteli-professional#96
=> [Pro] Fill in the authority salutation when one is selected

app/models/embargo.rb, spec/models/embargo_spec.rb
Closes https://github.com/mysociety/alaveteli-professional/issues/135
=> [Pro] Set a default duration of 3 months on new embargos

app/controllers/application_controller.rb
This is the matching PR for https://github.com/mysociety/whatdotheyknow-theme/pull/375
Related to mysociety/alaveteli-professional#137
=> [Pro] Don't show donate banner to pros

Gemfile, Gemfile.lock, doc/CHANGES.md, lib/tasks/export.rake
Currently is dumping csvs files in 'exports'  - there might be a better location than that.
Connects to #3734
=> Created research export rake

app/models/incoming_message.rb, doc/CHANGES.md
Ported from https://github.com/nzherald/alaveteli/pull/1
=> Replaced call to MySociety::Config.get

app/views/user/bad_token.html.erb
=> Update login link expiry text to reflect shorter duration

app/views/request/_sidebar.html.erb
WDTK-theme was using this, so add it to core.
=> Use decorated prominence

app/views/alaveteli_pro/info_requests/new.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/193
=> [Pro] Add summary suggestion.

app/controllers/alaveteli_pro/info_requests_controller.rb, spec/integration/alaveteli_pro/request_creation_spec.rb
Closes mysociety/alaveteli-professional#145
=> [Pro] Append user's name to initial request template

app/assets/javascripts/request-attachments.js, app/views/request/_bubble.html.erb, doc/CHANGES.md
=> Make "Show all" and "Show fewer" attachment links translatable

lib/tasks/export.rake
Otherwise it raises an error which aborts the script run
Connects to #3734
=> Make export task skip lines with encoding problems

app/models/user.rb, app/views/comment/_comment_form.html.erb, app/views/comment/preview.html.erb, lib/alaveteli_pro/post_redirect_handler.rb, spec/controllers/request_controller_spec.rb, spec/models/user_spec.rb, spec/views/comment/new.html.erb_spec.rb
=> [Pro] Rails 4 Spec fixes

.travis.yml
=> Stop sending Travis notifications to freenode

community/index.md
=> Replace IRC #mschat info with Slack details

lib/tasks/users.rake
=> Pass the start_date param to UserStats.count_dormant_users

community/index.md
Fixes #3829 
Fixes #3773 
Fixes #3772
=> Update / fix the community page

app/controllers/application_controller.rb, app/controllers/public_body_controller.rb, config/initializers/alaveteli.rb, doc/CHANGES.md, lib/typeahead_search.rb, spec/controllers/public_body_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/lib/typeahead_search_spec.rb
=> Handle short suffixes in typeahead search

lib/tasks/assets.rake
So that it appears in `rake -T`
=> Add description to link_non_digest task

doc/CHANGES.md, lib/world_foi_websites.rb
=> Update CZ country name in world_foi_websites

app/controllers/user_controller.rb, doc/CHANGES.md, lib/user_spam_scorer.rb, spec/controllers/user_controller_spec.rb, spec/lib/user_spam_scorer_spec.rb
...and prevent new user signups from spam domains.
Closes #3752
=> [#3752] Distinguish domains we're pretty sure are spam from mere suspicious ones

app/controllers/request_controller.rb, doc/CHANGES.md, spec/controllers/request_controller_spec.rb
Fixes mysociety/askyourgovug-theme#17
=> [Uganda#17] Prevent direct visits to /request/search_ahead raising errors

app/controllers/request_controller.rb, app/views/followups/preview.html.erb, app/views/request/preview.html.erb, doc/CHANGES.md, spec/integration/alaveteli_dsl.rb, spec/integration/alaveteli_pro/view_request_spec.rb
=> Send and Publish buttons

spec/controllers/admin_public_body_headings_controller_spec.rb
=> Fix spec expectation

app/assets/javascripts/alaveteli_pro/authority_select.js, app/assets/javascripts/alaveteli_pro/selectize.js
The `dist` versions of files in `selectize` only get updated on a release, so this is a version produced locally from the `master` branch. This incorporates the fixes made in https://github.com/selectize/selectize.js/pull/1193 which appear to fix https://github.com/mysociety/alaveteli-professional/issues/254
@stevenday I haven't restored the edit you made to `selectize.js` in 017180fad400598ddd41cfdb7cb0f0b5e0972e99 as I wasn't sure it's still needed - is it?
=> [Pro] Update selectize from the source at commit 1e2dba

Rakefile, app/controllers/admin_user_controller.rb, app/controllers/outgoing_messages/delivery_statuses_controller.rb, app/controllers/public_body_controller.rb, app/controllers/user_controller.rb, app/helpers/alaveteli_pro/info_requests_helper.rb, app/models/alaveteli_pro/activity_list/list.rb, app/models/alaveteli_pro/request_filter.rb, app/models/incoming_message.rb, app/models/info_request.rb, app/models/info_request_event.rb, app/models/outgoing_message.rb, config/application.rb, config/database.yml-example, config/environment.rb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb, config/initializers/assets.rb, config/initializers/mime_types.rb, config/initializers/secret_token.rb, config/initializers/session_store.rb, config/routes.rb
=> [#3799] Update generated templates

app/controllers/admin_public_body_categories_controller.rb, app/controllers/admin_public_body_headings_controller.rb, app/controllers/admin_raw_email_controller.rb, app/controllers/admin_user_controller.rb, app/controllers/outgoing_messages/delivery_statuses_controller.rb, app/controllers/public_body_controller.rb, app/controllers/request_controller.rb, app/controllers/services_controller.rb, app/controllers/user_controller.rb, app/helpers/alaveteli_pro/info_requests_helper.rb, app/models/alaveteli_pro/activity_list/list.rb, app/models/alaveteli_pro/request_filter.rb, app/models/incoming_message.rb, app/models/info_request.rb, app/models/info_request_event.rb, app/models/outgoing_message.rb, app/models/public_body_category.rb, app/models/public_body_heading.rb, app/views/admin_public_body_categories/_form.html.erb, config/application.rb
=> [#3799] rails 4 1 gr

spec/fixtures/public_body_category_translations.yml, spec/fixtures/public_body_heading_translations.yml
Both me and @crowbot saw issues with Postgres constraint violations without
these.
=> Add timestamps to spec fixture files

docs/customising/config.md, docs/customising/themes.md, docs/glossary.md, docs/installing/manual_install.md, docs/installing/next_steps.md, docs/running/admin_manual.md, docs/running/hiding_information.md, docs/running/holding_pen.md, docs/running/redaction.md, docs/running/requests.md, es/docs/customising/config.md, es/docs/glossary.md, es/docs/installing/next_steps.md, es/docs/running/admin_manual.md
=> Update the documentation to reflect the use of the admin role.

app/controllers/request_controller.rb, spec/controllers/request_controller_spec.rb
=> Call block_spam_requests instead of block_spam_request

app/controllers/request_game_controller.rb, doc/CHANGES.md, spec/controllers/request_game_controller_spec.rb
=> Fix categorisation game bug where there are no requests

app/models/public_body.rb
Split out of #3968 to make it easier to review.
=> Fix code style and indenting issues in PublicBody code

app/controllers/admin_general_controller.rb, spec/controllers/admin_general_controller_spec.rb
=> Use Rails 4 syntax for grouped counts

app/controllers/admin_censor_rule_controller.rb, app/models/censor_rule.rb, app/models/public_body.rb, doc/CHANGES.md, spec/controllers/admin_censor_rule_controller_spec.rb, spec/integration/admin_censor_rule_spec.rb, spec/models/censor_rule_spec.rb, spec/models/info_request_spec.rb, spec/models/public_body_spec.rb, spec/models/user_spec.rb
=> Expire associated requests when adding an authority censor rule

lib/alaveteli_spam_term_checker.rb
Variants of these are generating a lot of search traffic; found while
looking in Google Search Console.
=> Add new spam terms

app/views/general/_frontpage_bodies_list.html.erb, app/views/general/_frontpage_requests_list.html.erb, app/views/general/blog.html.erb
=> Allow plural form translations for any text that takes a count variable

app/models/concerns/public_body_derived_fields.rb, spec/controllers/public_body_controller_spec.rb, spec/fixtures/public_bodies.yml, spec/fixtures/public_body_translations.yml, spec/models/public_body_spec.rb
Uncontroversial commits extracted from #4066
=> Globalize minor tweaks

doc/CHANGES.md, spec/models/public_body_spec.rb
Extracted from #4041 so that this PR only adds specs.
Will pull in the specs that add additional validations later.
=> Public body validations specs only

app/models/public_body.rb, app/views/admin_public_body/show.html.erb, app/views/public_body/_more_info.html.erb, db/migrate/20170704143210_drop_unconventional_public_body_constraints.rb, doc/CHANGES.md, lib/i18n_fixes.rb, lib/public_body_csv.rb, spec/controllers/admin_public_body_controller_spec.rb, spec/lib/public_body_csv_spec.rb, spec/models/public_body_spec.rb
=> Remove unconventional PublicBody constraints and defaults

config/packages.debian-wheezy, config/packages.generic, config/packages.ubuntu-precise, doc/CHANGES.md
Noticed memcached wasn't available in my newly built VM.
=> Missing packages

lib/tasks/import.rake
* Fix indenting
* Single quotes instead of double unless interpolating
=> Tidy lib/tasks/import.rake

.ruby-style.yml
Been a bit slack recently, so added 15 instead of the usual 5. Most are
related though :)
=> Add some more hound checks

app/controllers/admin_info_request_event_controller.rb, app/models/info_request_event.rb, doc/CHANGES.md, spec/controllers/admin_info_request_event_controller_spec.rb, spec/models/info_request_event_spec.rb
=> Fixing 'was clarification' button

doc/CHANGES.md
=> Update changelog for Rails 4.2

app/assets/javascripts/general.js, app/views/layouts/default.html.erb
This line is the one that stops the popup from displaying if
you've already closed it. @wrightmartin it does result in FOUC though - any ideas?
=> Remove commenting (presumably added by mistake)

app/views/user/_user_listing_single.html.erb, doc/CHANGES.md, spec/views/user/_user_listing_single.html.erb_spec.rb
=> Show visible, not total, request count in user search results

app/views/alaveteli_pro/account_request/new.html.erb
Discussed in "Memberships" meeting on 2017-09-18.
=> Reduce free period for Pro beta accounts

docs/running/server.md
Prompted by
https://medium.freecodecamp.org/how-i-hacked-hundreds-of-companies-through-their-helpdesk-b7680ddc2d4c
=> Add a note about using an organisational domain

app/assets/stylesheets/responsive/_global_layout.scss, app/assets/stylesheets/responsive/_global_style.scss, app/assets/stylesheets/responsive/_settings_layout.scss, app/assets/stylesheets/responsive/_settings_style.scss, app/assets/stylesheets/responsive/alaveteli_pro/_pro_layout.scss, app/assets/stylesheets/responsive/alaveteli_pro/_pro_style.scss, app/assets/stylesheets/responsive/all.scss, app/views/alaveteli_pro/dashboard/index.html.erb, app/views/alaveteli_pro/plans/show.html.erb
https://github.com/mysociety/alaveteli-professional/issues/336
Basic design for the contract page
=> [pro#336] Contract page design

app/assets/stylesheets/responsive/_houdini.scss, app/assets/stylesheets/responsive/all.scss
This is really essential to the display of some pro pages
so should belong in core.
=> Adding houdini to core from WDTK

docs/customising/make_a_new_theme.md
Hopefully this should fix links issue #4259.
=> Fixing #4259

app/views/general/exception_caught.html.erb, app/views/outgoing_mailer/_followup_footer.text.erb
First steps in introducing embargoed requests to FOI officers.
Fixes https://github.com/mysociety/alaveteli-professional/issues/186.
=> [pro#186] Add notes about delayed publication

app/controllers/alaveteli_pro/base_controller.rb, app/controllers/alaveteli_pro/payment_methods_controller.rb, app/controllers/alaveteli_pro/plans_controller.rb, app/controllers/alaveteli_pro/subscriptions_controller.rb, app/controllers/user_controller.rb, app/views/alaveteli_pro/plans/index.html.erb, spec/controllers/alaveteli_pro/plans_controller_spec.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb
Connects to mysociety/alaveteli-professional#338
Connects to mysociety/alaveteli-professional#339
Connects to mysociety/alaveteli-professional#340
Closes mysociety/alaveteli-professional#343 (webhook for failed payment to be implemented later)
[previous demo](https://user-images.githubusercontent.com/27760/30656065-b77fa90e-9e2a-11e7-8bde-7f95eb43c946.gif)
=> [WIP][pro#339] Pro Signup

app/views/alaveteli_pro/plans/show.html.erb
Closes mysociety/alaveteli-professional#375
(Actual T&Cs copy still required)
=> Require acceptance of Terms and Conditions before signup

app/views/alaveteli_pro/account_request/_account_request_form.html.erb, app/views/alaveteli_pro/account_request/new.html.erb, spec/views/alaveteli_pro/account_request/new.html.erb_spec.rb
Closes mysociety/alaveteli-professional#341
=> [pro#341] Link to signup start point from marketing page

app/views/help/legal.html.erb
Work on https://github.com/mysociety/alaveteli-professional/issues/346
=> Add placeholder for T&Cs

app/controllers/application_controller.rb
https://github.com/presidentbeef/brakeman/blob/master/docs/warning_types/cross-site_request_forgery/index.markdown
=> Use :with_exception argument to protect_from_forgery

app/assets/stylesheets/responsive/_settings_layout.scss, app/assets/stylesheets/responsive/_settings_style.scss, app/helpers/alaveteli_pro/account_helper.rb, app/views/alaveteli_pro/plans/index.html.erb, app/views/alaveteli_pro/subscriptions/_card.html.erb, app/views/alaveteli_pro/subscriptions/_subscription.html.erb, app/views/alaveteli_pro/subscriptions/show.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/368
=> [pro#368] Basic design for /profile/subscriptions page

app/views/admin_request/show.html.erb, spec/views/admin_request/show.html.erb_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/231
=> [pro#231] Add embargo label to admin requests view

app/views/alaveteli_pro/batch_request_authority_searches/new.html.erb, app/views/alaveteli_pro/info_requests/index.html.erb, app/views/alaveteli_pro/info_requests/new.html.erb, app/views/alaveteli_pro/info_requests/preview.html.erb
Fixes some missed class changes from https://github.com/mysociety/alaveteli/commit/6c236e8ad35b3ad73a1c57c0a0bc03d7d249e2f1
=> Fix canvas refactor from alaveteli pro development

app/models/incoming_message.rb, app/models/user.rb, lib/mail_handler/backends/mail_backend.rb, spec/lib/mail_handler/backends/mail_backend_spec.rb, spec/models/user_spec.rb
=> [#4298] sanitize on entry

app/assets/javascripts/alaveteli_pro/embargo_dropdown.js, app/helpers/alaveteli_pro/info_requests_helper.rb, app/views/alaveteli_pro/info_request_batches/_embargo_info.html.erb, app/views/alaveteli_pro/info_request_batches/_form.html.erb, app/views/alaveteli_pro/info_requests/_embargo_info.html.erb, app/views/alaveteli_pro/info_requests/_form.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/278
~~This works fine for the unbatched requests but there seems like it would be bigger change required to get this working for batched requests~~
=> [pro#278] Update embargo text when changing duration

Gemfile.lock
ToDo - link to https://github.com/teamcapybara/capybara/blob/master/History.md
(This PR is currently to see if updating breaks anything)
=> Upgrade capybara gem

app/assets/stylesheets/responsive/alaveteli_pro/_pro_style.scss
=> Add icon offsets for overdue statuses

app/assets/javascripts/alaveteli_pro/authority_select.js, app/assets/stylesheets/responsive/alaveteli_pro/_new_request_style.scss, app/controllers/alaveteli_pro/public_bodies_controller.rb, app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb, spec/controllers/alaveteli_pro/public_bodies_controller_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/236
~~This is functional and just needs to be styled as per designs in the above issue.~~
Looks like this:
=> [pro#236] Show public body notes after using authority filter

app/models/alaveteli_pro/to_do_list/expiring_embargo.rb, app/models/alaveteli_pro/to_do_list/new_response.rb, app/models/alaveteli_pro/to_do_list/overdue_request.rb, app/models/alaveteli_pro/to_do_list/very_overdue_request.rb, app/models/concerns/alaveteli_pro/phase_counts.rb, app/models/user.rb, app/views/alaveteli_pro/dashboard/_projects.html.erb, spec/models/alaveteli_pro/to_do_list/expiring_embargo_spec.rb, spec/models/alaveteli_pro/to_do_list/new_response_spec.rb, spec/models/alaveteli_pro/to_do_list/overdue_request_spec.rb, spec/models/alaveteli_pro/to_do_list/very_overdue_request_spec.rb, spec/models/user_spec.rb, spec/support/shared_examples_for_phase_counts.rb
Making a new PR from https://github.com/mysociety/alaveteli/pull/4195 with squashes applied, reverted commits dropped, and rebased on to `develop`.
=> [#4166] Fewer summary selects rebased squashed

app/controllers/admin_track_controller.rb, spec/controllers/admin_track_controller_spec.rb
=> 4333 destroy track

app/controllers/alaveteli_pro/embargoes_controller.rb, app/models/info_request.rb, app/models/info_request/prominence/been_published_query.rb, app/models/info_request_batch.rb, spec/controllers/alaveteli_pro/embargo_controller_spec.rb, spec/factories/info_requests.rb, spec/models/info_request/prominence/been_published_query_spec.rb, spec/models/info_request_batch_spec.rb, spec/models/info_request_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/205
=> [pro#205] Don't stop followups if a request has never been published

app/assets/stylesheets/responsive/_settings_style.scss, app/controllers/alaveteli_pro/subscriptions_controller.rb, app/views/alaveteli_pro/plans/show.html.erb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/377
=> [pro#377] Add ability to enter Stripe coupon on Pro signup

app/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb, app/views/alaveteli_pro/info_request_batches/_form.html.erb, app/views/alaveteli_pro/info_requests/_embargo_form.html.erb, app/views/alaveteli_pro/info_requests/_embargo_note.html.erb, app/views/alaveteli_pro/info_requests/_form.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/248
=> [pro#248] Review embargo notes and expand details for batch requests

.ruby-style.yml
=> Hound checks

doc/CHANGES.md, lib/tasks/temp.rake
=> Add task for reparsing missing cached attachments

app/views/general/_frontpage_requests_list.html.erb
https://github.com/mysociety/alaveteli/issues/4342#issuecomment-342435523
=> Close unclosed div on front page

lib/quiet_opener.rb, spec/helpers/info_request_helper_spec.rb, spec/models/alaveteli_pro/to_do_list/overdue_request_spec.rb, spec/models/alaveteli_pro/to_do_list/very_overdue_request_spec.rb, spec/models/info_request/state/overdue_query_spec.rb, spec/models/info_request/state/very_overdue_query_spec.rb, spec/models/info_request_spec.rb, spec/models/user/transaction_calculator_spec.rb
Identified a few specs which were broken when running the test suite locally which needed minor changes to get passing.
=> Spec fixes

app/controllers/admin_controller.rb, app/controllers/application_controller.rb, doc/CHANGES.md, spec/integration/errors_spec.rb
Fixes #4289
Also improves request spec behaviour.
=> [#4289] Dont render exceptions in admin interface

app/controllers/alaveteli_pro/subscriptions_controller.rb, app/views/alaveteli_pro/subscriptions/_signup_message.html.erb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb
Closes mysociety/alaveteli-professional#413
=> [pro#413] expand new signup welcome message

app/views/alaveteli_pro/general/_log_in_bar_links.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/412
Will need to rename path helper after #4368 is merged
=> [pro#412] Add pro nav link to "My subscription"

app/views/alaveteli_pro/plans/show.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/418
Control them with a feature flag until we have some content.
=> [#pro418] Hide /plans/show FAQs

app/controllers/alaveteli_pro/subscriptions_controller.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb
Closes mysociety/alaveteli-professional#417
=> [pro#417] avoid duplicate payments

app/assets/stylesheets/responsive/alaveteli_pro/_plans_style.scss, app/views/alaveteli_pro/account_request/index.html.erb, app/views/alaveteli_pro/plans/index.html.erb
Some work on https://github.com/mysociety/alaveteli-professional/issues/415.
I haven't got anything great for the "we're a non-profit" yet, but will add that in a separate PR once I've given it some more thought.
=> [#pro415] Review /pro/pricing

app/assets/stylesheets/responsive/alaveteli_pro/_pro_marketing.scss, app/views/alaveteli_pro/account_request/index.html.erb
I think we should now stop talking about the service in general
as being in beta.
=> Remove beta reference

app/views/alaveteli_pro/plans/index.html.erb
* Fix incorrect link
* Add missing translation wrapper
=> Plans page fix

app/assets/stylesheets/responsive/_header_layout.scss, app/assets/stylesheets/responsive/_header_style.scss, app/assets/stylesheets/responsive/alaveteli_pro/_dashboard_layout.scss, app/views/general/_log_in_bar.html.erb
Fixes, improves and refactors the user drop down menu
=> Cosmetic fix to user dropdown menu

app/assets/stylesheets/responsive/_global_layout.scss, app/assets/stylesheets/responsive/_settings_layout.scss, app/assets/stylesheets/responsive/_settings_style.scss, app/assets/stylesheets/responsive/alaveteli_pro/_dashboard_layout.scss, app/assets/stylesheets/responsive/alaveteli_pro/_dashboard_style.scss, app/views/alaveteli_pro/dashboard/_projects.html.erb, app/views/alaveteli_pro/subscriptions/index.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/411
- Adds left hand navigation to pro profile screen
- Adds new reusable styles for left hand navigation
- Refactors the pro dashboard navigation to use these styles
=> [#Pro411] Implement account settings navigation

app/controllers/alaveteli_pro/stripe_webhooks_controller.rb, config/general.yml-example, config/routes.rb, lib/configuration.rb, spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb
Closes mysociety/alaveteli-professional#425
=> [pro#425] Implement basic webhook listener

app/assets/stylesheets/responsive/alaveteli_pro/_dashboard_style.scss, app/assets/stylesheets/responsive/alaveteli_pro/_requests_layout.scss, app/assets/stylesheets/responsive/alaveteli_pro/_requests_style.scss, app/views/alaveteli_pro/info_request_batches/_info_request.html.erb, app/views/alaveteli_pro/info_requests/_info_request.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/406
Add number of incoming_messages to the pro dashboard for both normal and batch requests
=> [pro#406] Show number of replies to requests on dashboard

app/views/general/_frontpage_bodies_list.html.erb, app/views/request/_request_sent.html.erb
* Makes the frontpage bodies list button consistent with the frontpage
authorities list
* Adds some styling hooks to the request sent paragraph
=> Backport some interface tweaks from WDTK

.travis.yml
Error is:
+/home/travis/.rvm/gems/ruby-2.0.0-p648/bin/bundle:23:in `load':
cannot load such file --
/home/travis/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/gems/2.0.0/gems/bundler-1.16.1/exe/bundle
(LoadError)`
=> Travis cannot load such file exe/bundle fix

app/assets/javascripts/alaveteli_pro/alaveteli_pro.js, app/assets/javascripts/alaveteli_pro/authority_select.js, app/assets/javascripts/alaveteli_pro/selectize.no_results.js, app/assets/stylesheets/responsive/alaveteli_pro/_new_request_style.scss, app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/410
=> [pro#410] Show message when not able to find an authority

docs/installing/vagrant.md
We note this in the changelog (f01444917) but should specify it here too.
Prompted by a report on alaveteli-dev [1].
[1] https://groups.google.com/forum/#!topic/alaveteli-dev/PLcOSkG48hU
=> Add -b option to rails server

app/controllers/alaveteli_pro/stripe_webhooks_controller.rb, app/controllers/alaveteli_pro/subscriptions_controller.rb, spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb, spec/fixtures/stripe_webhooks/customer.subscription.deleted.json
Closes mysociety/alaveteli-professional#371
=> [pro#371] remove pro role on sub expiry

app/controllers/alaveteli_pro/stripe_webhooks_controller.rb, spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb
Closes mysociety/alaveteli-professional#440
(branch is based on 371-remove-pro-role-on-sub-expiry)
=> [pro#440] Update Stripe charge description

app/controllers/alaveteli_pro/subscriptions_controller.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb
=> Use flash error for error messages

Gemfile, Gemfile.lock, app/models/user.rb, app/models/user/authenication.rb, db/migrate/20171222121709_change_user_salt_null.rb, spec/controllers/password_changes_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/factories/users.rb, spec/models/user_spec.rb
Closes https://github.com/mysociety/alaveteli_security/issues/5 & Closes #3404
=> [sec#5] Change password encryption to use bcrypt

app/controllers/alaveteli_pro/plans_controller.rb, app/controllers/alaveteli_pro/stripe_webhooks_controller.rb, app/views/alaveteli_pro/plans/show.html.erb, spec/controllers/alaveteli_pro/plans_controller_spec.rb, spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/450
=> [#Pro450] Support annual billing

.ruby-style.yml
=> Add some hound checks

app/controllers/public_body_controller.rb, app/models/public_body.rb, spec/controllers/public_body_controller_spec.rb, spec/models/public_body_spec.rb
Refactoring some Public Body queries so they can be reused in the batch browse UI.
=> Refactor public body queries

app/controllers/alaveteli_pro/info_request_batches_controller.rb, spec/integration/alaveteli_pro/batch_request_spec.rb
Fixes mysociety/alaveteli-professional#267
=> Set a default embargo when creating a batch request

app/assets/stylesheets/responsive/_request_layout.scss, app/assets/stylesheets/responsive/_request_style.scss
=> Avoid drawing border under final attachment in list

app/assets/stylesheets/responsive/alaveteli_pro/_requests_style.scss, app/views/alaveteli_pro/dashboard/_no_to_dos.html.erb, app/views/alaveteli_pro/info_requests/_no_requests.html.erb
also fixes broken hover state
Now looks like...
Fixes https://github.com/mysociety/alaveteli-professional/issues/212
=> [pro#212] Make the blank slate call to action a button

app/models/info_request.rb, doc/CHANGES.md, spec/controllers/admin_outgoing_message_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/models/info_request_spec.rb
Annoyed me when writing https://github.com/mysociety/alaveteli/pull/4532
=> Refactor InfoRequest#get_last_event

lib/acts_as_xapian/acts_as_xapian.rb
Just output the problems to STDERR – can tee that to a log then and deal
with later
=> TEMP: Ignore any errors in idexing

app/models/ability.rb, spec/models/ability_spec.rb
=> [#4404] Fix for anonymous requests ability check

doc/CHANGES.md
https://github.com/mysociety/alaveteli_security/issues/5
Document new feature in the change log 
Avoid unexpected changes when upgrading
=> Update changelog with password hashing switch

app/assets/stylesheets/responsive/alaveteli_pro/_batch_request_authority_search_layout.scss, app/assets/stylesheets/responsive/alaveteli_pro/_batch_request_authority_search_style.scss
Fixes https://github.com/mysociety/alaveteli-professional/issues/502.
=> Fix CSS bugs around authority names / buttons in Pro batch UI

app/assets/stylesheets/admin.scss, app/views/layouts/admin.html.erb, doc/CHANGES.md
Point admins at our Admin Manual and Community page.
Fixes https://github.com/mysociety/alaveteli/issues/1990
Fixes https://github.com/mysociety/alaveteli/issues/2530
=> Add an admin footer

app/views/user/rate_limited.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/246
People making lots of requests may benefit from Pro, so lets at least
tell them about it when they hit the rate limit.
This is definitely the MVP fix of the issue. Further issues can be created to prettify it.
* Screenshots
=> [pro#246] Add Pro upsell to user/rate_limited

community/index.md
See commit messages for details/reasoning.
c063505 is up for discussion, but I feel pretty strongly in favour of merging it.
=> Remove mentions of chat from alaveteli.org/community

app/controllers/admin_user_controller.rb
=> Reinstate missed method chaining

doc/CHANGES.md
In suggested execution order
Required for #4615 
(Used to work through an upgrade test from 0.31.x for Belgium)
=> Move required upgrade steps to the top of the section

app/models/public_body.rb
Required by #3969.
This removes usages of the undocumented `AliasTracker` class as the
private interface has changed between Rails versions causing many spec
failures in our Rails 5 branches.
This has the added benefit of improving the performance of chained
`without_tag` calls, as used in the `PublicBody.is_requestable`. This
was causing a slowdown in the batch request sending.
Fixes #5044
=> [Rails 5] Rework PublicBody tag scopes

spec/controllers/one_time_passwords_controller_spec.rb, spec/controllers/user_controller_spec.rb, spec/controllers/users/sessions_controller_spec.rb, spec/integration/search_request_spec.rb, spec/models/incoming_message_spec.rb, spec/models/info_request_event_spec.rb
Fixes #5077
Minor spec fixes (where Rails 5 changes were breaking the specs rather than there being a problem with the app code)
~The cherry-picked commit (33195ae) to update the Rails 5 lock file is only needed to allow CI to run against Rails 5 (avoids rebasing and losing the original history)~
=> [Rails 5] Small spec fixes

app/models/info_request.rb, doc/CHANGES.md, spec/controllers/alaveteli_pro/info_requests_controller_spec.rb, spec/controllers/alaveteli_pro/public_bodies_controller_spec.rb, spec/factories/public_bodies.rb, spec/models/public_body_spec.rb
#4902
Removes code marked for removal in Release 0.33
=> [#4902] Remove deprecated code

app/models/incoming_message_error.rb, spec/factories/alaveteli_pro/draft_info_request_batches.rb, spec/factories/alaveteli_pro/embargo_extensions.rb, spec/factories/alaveteli_pro/embargos.rb, spec/factories/alaveteli_pro/request_summaries.rb, spec/factories/alaveteli_pro/request_summary_categories.rb
Connects to #4902
Release is coming lets annotate the models so they are up-to-date
- To ensure defaults values don't change I set `TIME_ZONE=London` in config/general.yml. This matches what is set in production for WDTK
- Cleared the existing annotations with: `bundle exec annotate -d`
- Finally ran: `bundle exec annotate`
=> Annotate models

doc/CHANGES.md
=> Add database environment protection upgrade note

alaveteli-doc-master.txt, community/conferences/2012.md, docs/customising/config.md, docs/customising/states_informatazyrtare.md, docs/glossary.md, docs/installing/ami.md, docs/installing/email.md, docs/installing/manual_install.md, docs/installing/next_steps.md, docs/running/admin_manual.md, docs/running/handling_spam.md, es/docs/customising/config.md, es/docs/customising/states_informatazyrtare.md, es/docs/installing/ami.md, es/docs/installing/next_steps.md
Replace Alavateli with Alaveteli.
=> [docs] Fix spelling mistakes

app/models/notification.rb, app/models/webhook.rb, doc/CHANGES.md, spec/factories/notifications.rb, spec/factories/webhooks.rb, spec/models/notification_spec.rb, spec/models/webhook_spec.rb
Connected to #5229 
- Annotates models
- Add missing Changelog entries.
=> [#5229] Release prep for 0.35.0.0

app/views/alaveteli_pro/account_request/index.html.erb
Connects to #5294 
Broken in #5317
Closes a **strong** HTML tag.
=> [pro#587] Fix unclosed HTML tag

config/initializers/alaveteli.rb, doc/CHANGES.md, locale/cs/app.po, locale/en/app.po, locale/sv/app.po, locale_alaveteli_pro/sv/app.po
- Updates translations
- Bump alaveteli version
=> Hotfix for 0.34.0.1

.ruby-style.yml
Nothing really controversial here.
=> Enable hound checks

.ruby-style.yml
* Fix FlipFlop namespace
* Add some hound checks, mostly around conditionals
=> Hound checks 2019-10-01

lib/tasks/config_files.rake
Auto-correct Style/NilComparison
=> Auto-correct Style/NilComparison

app/controllers/announcements_controller.rb
bundle exec rubocop -a --only Style/EmptyLiteral
=> Auto-correct Style/EmptyLiteral

app/models/comment.rb
Fixes a bunch of rubocop violations in `Comment`
Likely to be working on this soon, so just did a bit of cleanup while I was on the train.
Couple of violations still remaining, but didn't have time to get to them. Can tackle in a later PR.
=> Clean Comment

app/views/admin_censor_rule/_form.html.erb, app/views/admin_censor_rule/edit.html.erb, app/views/admin_censor_rule/new.html.erb, doc/CHANGES.md, spec/integration/admin_censor_rule_spec.rb
* Tidy censor rule forms
* Better UI consistency
BEFORE
AFTER
=> Tidy censor rule forms

app/models/info_request/state/transitions.rb
Auto-correct Style/CommentAnnotation
Code cleanup
=> Auto-correct Style/CommentAnnotation

lib/date_quarter.rb
Auto-correct Style/WhileUntilDo
Code cleanup
=> Auto-correct Style/WhileUntilDo

app/mailers/track_mailer.rb
* Fix layout space before comment
* Fix line length
Code cleanup
=> Fix layout space before comment

spec/models/outgoing_message_spec.rb
Auto-correct Layout/SpaceBeforeSemicolon
Code cleanup
=> Auto-correct Layout/SpaceBeforeSemicolon

app/assets/stylesheets/responsive/_global_style.scss, app/assets/stylesheets/responsive/_sidebar_layout.scss, app/assets/stylesheets/responsive/_sidebar_style.scss, app/controllers/citations_controller.rb, app/controllers/request_controller.rb, app/models/ability.rb, app/models/citation.rb, app/models/info_request.rb, app/models/info_request_batch.rb, app/models/user.rb, app/views/alaveteli_pro/info_requests/_sidebar.html.erb, app/views/citations/new.html.erb, app/views/request/_citations.html.erb, app/views/request/_sidebar.html.erb, app/views/request/show.html.erb, config/routes.rb, db/migrate/20191211155455_create_citations.rb, spec/controllers/citations_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/factories/citations.rb, spec/models/citation_spec.rb, spec/views/request/_citations.html.erb_spec.rb, spec/views/request/_sidebar.html.erb_spec.rb, spec/views/request/show.html.erb_spec.rb
Part of #5483 
Add citations to info requests and batches
* `Citation`s for a given `InfoRequest` are a collection of `Citation`s specifically added to that request, plus any `Citation`s added to the parent `InfoRequestBatch`.
* `Citation`s for a given `InfoRequestBatch` are a collection of `Citation`s specifically added to that batch, plus any `Citation`s added to _any_ `InfoRequest` belonging to the batch.
No citations – authorised to create
---
Citations – authorised to create
---
With 1 citation – not authorised to create
---
No citations – not authorised to create
---
Add citation to a single request
---
Add citation to a request in a batch
TODO before merge:
NEW PRs:
* Uniqueness on `Citation#source_url`?
* "Show More" and citations index page
* Ability to destroy citations
* Move …
=> [#5483] Add citations to info requests and batches

lib/tasks/export.rake
Auto-correct Layout/SpaceAfterColon
Code cleanup
=> Auto-correct Layout/SpaceAfterColon

spec/models/public_body_spec.rb
Auto-correct Style/SymbolLiteral
Code cleanup
=> Auto-correct Style/SymbolLiteral

lib/world_foi_websites.rb
closes #5536 
Updates World FOI sites
Needed to add new sites
=> Add Sweden, France and Moldova

gems/alaveteli_features/alaveteli_features.gemspec
Auto-correct Layout/ExtraSpacing
Code cleanup
=> Auto-correct Layout/ExtraSpacing

app/helpers/application_helper.rb
Auto-correct Style/UnlessElse
Code cleanup
=> Auto-correct Style/UnlessElse

lib/fixture_set_table_rows_patch.rb, lib/mail_handler/backends/mail_extensions.rb
Auto-correct Style/RescueModifier
Code cleanup
=> Auto-correct Style/RescueModifier

_layouts/default.html, _layouts/es/default.html
https://github.com/mysociety/orgsites/issues/1124
Remove cookie storage from analytics
Team meeting decision to remove individual tracking 
None
None 
None
=> Remove cookie storage in GA

app/controllers/request_controller.rb, app/models/ability.rb, app/views/request/show.html.erb, app/views/request/show.text.erb, spec/models/ability_spec.rb
https://github.com/mysociety/alaveteli/issues/5542
Extracts some prep commits from https://github.com/mysociety/alaveteli/pull/5608
Makes it easier to review the core implementation of share by link without also needing to think about unrelated refactoring.
=> [#5542] share by link prep 1

app/controllers/attachments_controller.rb, app/controllers/concerns/public_tokenable.rb, app/controllers/public_tokens_controller.rb, spec/controllers/attachments_controller_spec.rb
https://github.com/mysociety/alaveteli/pull/5608
Adds nofollow headers to attachments
=> [#5542] share by link combined attachment noindex

app/controllers/concerns/fragment_cachable.rb, app/controllers/request_controller.rb, app/helpers/application_helper.rb, app/models/foi_attachment.rb, app/models/outgoing_message/template/internal_review.rb, app/models/raw_email.rb, config/boot.rb, config/initializers/acts_as_xapian.rb, config/initializers/health_checks.rb, config/initializers/theme_loader.rb, config/initializers/user_spam_scorer.rb, db/migrate/099_move_raw_email_to_filesystem.rb, db/migrate/112_add_api_key_to_public_bodies.rb, lib/acts_as_xapian/acts_as_xapian.rb, lib/mail_handler/mail_handler.rb, lib/tasks/config_files.rake, lib/tasks/geoip.rake, lib/tasks/gettext.rake, lib/tasks/temp.rake, lib/tasks/themes.rake, script/switch-theme.rb, spec/controllers/admin_incoming_message_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/lib/alaveteli_spam_term_checker_spec.rb, spec/models/outgoing_message/template/internal_review_spec.rb, spec/models/outgoing_message_spec.rb, spec/models/raw_email_spec.rb
Connected to attempt to auto correct all Rubocop warnings: https://github.com/mysociety/alaveteli/pull/5579
- Auto-correct Layout/TrailingWhitespace
- Auto-correct Lint/DeprecatedClassMethods
- And fixes broken spec which these auto correction have broken.
With these changes #5579 should be green.
=> Rubocop 2020-04-28

app/models/project.rb, app/models/project/membership.rb, app/models/project/resource.rb, spec/factories/project_memberships.rb, spec/factories/project_resources.rb, spec/factories/projects.rb, spec/models/project/membership_spec.rb, spec/models/project/resource_spec.rb, spec/models/project_spec.rb
1. Moves ProjectMembership and ProjectResource to the Project namespace
2. Annotates Project models
We already have Project::Submission so lets be consistence and tidy.
=> [fnf] Project models

app/controllers/projects/extracts_controller.rb, app/models/dataset/value.rb, app/models/dataset/value_set.rb, app/views/projects/dataset/keys/_boolean_key.html.erb, app/views/projects/dataset/keys/_key.html.erb, app/views/projects/extracts/_form.html.erb, app/views/projects/extracts/_sidebar.html.erb, app/views/projects/extracts/show.html.erb, spec/controllers/projects/extracts_controller_spec.rb, spec/factories/dataset_value_sets.rb, spec/models/dataset/value_set_spec.rb, spec/models/dataset/value_spec.rb
Prevents empty Value sets from being saved and fixes extract form when there are errors.
=> [fnf#20] Extract form fixes

app/assets/javascripts/general.js, app/controllers/projects/extracts_controller.rb, app/models/project/queue/extractable.rb, app/views/projects/extracts/_form.html.erb, config/routes.rb, spec/controllers/projects/extracts_controller_spec.rb, spec/models/project/queue/extractable_spec.rb, spec/support/project_queue_context.rb
Requires https://github.com/mysociety/alaveteli/pull/5691
Uses queues for extraction like we added in https://github.com/mysociety/alaveteli/pull/5691 for classifications.
=> [fnf#28] extract queue

app/views/projects/projects/show.html.erb
Enable project extraction
Just making a PR so that we can merge when we're ready to deploy.
=> [fnf#20] Enable project extraction

_includes/es/footer.html, _includes/footer.html
Also fix unescaped ampersands in utm tracking links.
=> Update company details in footer

app/models/incoming_message.rb, app/models/legislation.rb, app/models/legislation/constants.rb, app/models/legislation/reference.rb, app/models/legislation/reference_collection.rb, spec/models/incoming_message_spec.rb, spec/models/legislation/reference_collection_spec.rb, spec/models/legislation/reference_spec.rb, spec/models/legislation_spec.rb
Connected to #5909
Detects references to legislation in incominng messages
So we can offer refusal advice
=> [#5909] Legislation detection

spec/spec_coverage.rb, spec/spec_helper.rb
Extract coverage setup. Did this while moving to GitHub actions where we need to change this setup a bit to get it working.
=> Extract converage setup

.gitignore, config/xapian.yml-example
Add example Xapian configuration
This will be used when the application is next deployed.
=> Add example Xapian configuration

spec/factories/info_requests.rb
Closes #6165 
See #6165 and in addition I have updated the final commit, which fixes Rubocop warnings, to only fix lines which have been changed by the PR. For example Rubocop "fixes" the generated model annotation comments which leads to unnecessary changes in the diff
=> Use traits in info requests factory

app/models/refusal_advice.rb, spec/models/refusal_advice_spec.rb
Fixes:
NoMethodError: undefined method `inject' for nil:NilClass
=> Fix snippets error when there are no suggestions

lib/tasks/graphs.rake
Minor reduction of complexity that I couldn't help fixing when creating
https://github.com/mysociety/alaveteli/issues/6298.
=> Reduce complexity of setting minimum_data_size

docs/installing/cron_and_daemons.md
=> Document change to erb template files

script/site-specific-install.sh
=> Hide unnecessary output

app/controllers/alaveteli_pro/info_requests_controller.rb
Nothing controversial. Removes a little complexity and cleans up methods.
=> Use guard clauses over conditionals

app/views/admin_general/stats.html.erb, script/switch-theme.rb
File.exists? -> File.exist?
Dir.exists? -> Dir.exist?
=> Replace depreciated Ruby core methods

docs/running/resources_for_owners.md
Fixes https://github.com/mysociety/alaveteli-project/issues/138
* Strip trailing spaces and newlines
* Link to more videos for site owners
=> [project#138] Add more videos

spec/controllers/attachments_controller_spec.rb
Fixes #6436
Prevent attachment controller cached files from being written to disk
expect for one test where we need to check the file permissions.
Without this re-running the same spec more than once could result in an
error due to the normal execution being stopped early.
For example running this spec twice would error due to the standard
ability check to be skipped:
```
rspec ./spec/controllers/attachments_controller_spec.rb:212
Ability.new(#<User>, {:project=>#<Project>})
expected: 1 time with arguments: (#<User>, {:project=>#<Project>})
received: 0 times
```
Still need to consider:
> While looking at this it has made me wounder why the cache callback is happening before the authenication callbacks... should these be the other way around? …
=> [#6436] Improve test ENV attachment caching

doc/CHANGES.md
Required for #6347 
Update changelog
=> Update changelog for 0.40 release

app/models/user.rb
* Move `expire_requests` to be closer to conceptually similar
`reindex_referencing_models`
* Extract `expire_comments` for clarity
=> Refactor User#reindex_referencing_models

doc/CHANGES.md, lib/acts_as_xapian/acts_as_xapian.rb
https://github.com/mysociety/sysadmin/issues/1409#issuecomment-815632882
Add support for Glass Xapian database format 
Framework modernisation
=> Add support for Glass Xapian database format

docs/running/resources_for_owners.md
- Added the TICTeC RTK videos
- Changed the titling from the name of the service to the language that it's in, to reflect user needs rather than our own subdivisions
=> Adding videos from TICTeC RTK day

doc/CHANGES.md, lib/tasks/storage/storage.rb, lib/tasks/temp.rake
Fixes #6717
Update storage tasks for issues found when migrating WDTK to `ActiveStorage`
- Reduce number of downloads from cloud storage for new raw email responses
- Help make re-users experience easier.
=> [#6717] Update storage tasks

docker-compose.yml, docker/Dockerfile
* Expose postgres to host machine
* Bump Docker Ruby version
=> Minor Docker tweaks

app/controllers/admin_request_controller.rb, app/mailers/outgoing_mailer.rb, app/models/incoming_message.rb, app/models/info_request.rb, app/models/outgoing_message.rb, app/views/admin_incoming_message/bulk_destroy.html.erb, app/views/admin_request/show.html.erb, app/views/request/_incoming_correspondence.html.erb, app/views/request/_incoming_correspondence.text.erb, db/migrate/20220210120801_rename_incoming_message_mail_from_columns.rb, script/clear-caches, spec/factories/incoming_messages.rb, spec/fixtures/incoming_messages.yml, spec/mailers/outgoing_mailer_spec.rb, spec/models/incoming_message_spec.rb, spec/models/outgoing_message_spec.rb
Refactor after #6773
Refactor mail from attributes
Consistency and will save confusion about what each attribute return.
=> [#6769] Refactor mail from attributes

app/models/user.rb, spec/models/user_spec.rb
Various minor cleanup and refactoring of methods in `User`
Nothing controversial; just had half an hour at the end of the day and wanted to do something that didn't need too much brainpower.
=> User Clean & Refactor

app/helpers/admin_helper.rb, app/views/admin_comment/edit.html.erb, app/views/admin_comment/index.html.erb, app/views/admin_request/_some_annotations.html.erb, app/views/admin_request/_some_requests.html.erb, doc/CHANGES.md
* [Use prominence_icon for admin request listing](https://github.com/mysociety/alaveteli/commit/88be5c9db0c5aa368ec44a0953ff05d2dd89e5c5)
* [Link comment listing to request](https://github.com/mysociety/alaveteli/commit/ca493bb2cf17b5e581d8b969fce9fd240122df45)
* [Improve comment metadata on admin edit page](https://github.com/mysociety/alaveteli/pull/6813/commits/970f1f9ee001dc45c3eed4dfe0f34d8b15574828)
* [Add comment metadata to AdminComment#index](https://github.com/mysociety/alaveteli/pull/6813/commits/84fb99ee3bce9da5ed0b42d97ae5e0804c6f606e)
=> Admin comment list improvements

app/views/admin_user/index.html.erb
Minor improvements to make better use of the Bootstrap UI elements.
=> Clean up admin user search form

app/views/admin_general/_change_request_summary.html.erb, doc/CHANGES.md
Make it easier to investigate the source of the proposed changes.
Fixes https://github.com/mysociety/alaveteli/issues/6901.
=> [#6901] Link to PublicBodyChangeRequest#source_url

app/models/user.rb, spec/models/user_spec.rb
Convenience method for closing `User` records through the console.
=> Add User#close

app/models/concerns/taggable.rb, app/models/public_body.rb, app/models/public_body_category.rb, app/models/public_body_category_link.rb, app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb, app/views/alaveteli_pro/batch_request_authority_searches/_public_bodies.html.erb, config/initializers/alaveteli_features.rb, db/migrate/20220519094420_rename_has_tag_string_model_column.rb, lib/has_tag_string/has_tag_string.rb, lib/tasks/export.rake, spec/fixtures/has_tag_string_tags.yml, spec/models/has_tag_string_tag_spec.rb, spec/models/public_body_category_link_spec.rb
Working towards #6862 with fixes for #7021, #7016 and #6866
Comparison for loading `/en/alaveteli_pro/batch_request_authority_searches?category_tag=school&mode=browse`
Note we currently [exclude the `school` category](https://github.com/mysociety/alaveteli/blob/2fa4871847c15c20712cb97a144920a555365f00/app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb#L17 )
Before:
> Completed 200 OK in 62590ms (Views: 53984.8ms | ActiveRecord: 8550.2ms | Allocations: 67679974)
After:
> Completed 200 OK in 13762ms (Views: 13316.2ms | ActiveRecord: 424.4ms | Allocations: 22740334)
=> Batch category UI improvements

app/controllers/help_controller.rb, spec/controllers/help_controller_spec.rb
Changes required for https://github.com/mysociety/whatdotheyknow-theme/issues/1179
Refactor the help controller to allow easier theme overrides.
=> [wdtk#1179] Help controller refactor

script/install-as-user
Fixes a bug with the installer
There was a bug in the installer
=> fix: cp should take two arguments and does not write output to new file

app/views/alaveteli_pro/info_requests/_embargo_note.html.erb
Previous version didn't really make sense.
Fixes https://github.com/mysociety/alaveteli/issues/7155.
=> [#7155] Improve phrasing of embargo note

app/controllers/admin/tags_controller.rb, app/helpers/admin/tag_helper.rb, app/models/application_record.rb, app/models/concerns/taggable.rb, app/models/info_request.rb, app/models/outgoing_message/snippet.rb, app/models/public_body.rb, app/views/admin/outgoing_messages/snippets/_snippet.html.erb, app/views/admin/outgoing_messages/snippets/index.html.erb, app/views/admin/tags/_filters.html.erb, app/views/admin/tags/_scope.html.erb, app/views/admin/tags/_tagging.html.erb, app/views/admin/tags/index.html.erb, app/views/admin/tags/show.html.erb, app/views/admin_public_body/_one_list.html.erb, app/views/admin_public_body/_public_body.html.erb, app/views/admin_public_body/index.html.erb, app/views/admin_public_body/show.html.erb, app/views/admin_public_body_categories/_form.html.erb, app/views/admin_request/_info_request.html.erb, app/views/admin_request/_some_requests.html.erb, app/views/admin_request/index.html.erb, config/routes.rb, spec/controllers/admin/tags_controller_spec.rb, spec/helpers/admin/tag_helper_spec.rb
Fixes #6992
Adds administration UI for tags
We need somewhere to add generalised notes to a tag #6994 which means we an admin UI for tags.
/admin/bodies/tags
/admin/requests/tags
/admin/snippets/tags
/admin/bodies/tags?query=coins
/admin/snippets/tags?query=:s12
/admin/bodies/tags/department
/admin/bodies/tags/department?query=dpr:Z
/admin/bodies
/admin/requests
/admin/snippets
=> [#6992] Adds administration UI for tags

app/helpers/alaveteli_pro/batch_request_authority_searches_helper.rb, app/helpers/alaveteli_pro/public_bodies_helper.rb, app/helpers/notes_helper.rb, app/models/public_body.rb, app/views/alaveteli_pro/batch_request_authority_searches/_search_result.html.erb, app/views/alaveteli_pro/draft_info_request_batches/_summary.html.erb, app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb, app/views/public_body/_body_listing_single.html.erb, app/views/public_body/show.html.erb, app/views/request/new.html.erb, app/views/request/new_defunct.html.erb, lib/public_body_csv.rb, spec/helpers/alaveteli_pro/batch_request_authority_searches_helper_spec.rb, spec/helpers/alaveteli_pro/public_bodies_helper_spec.rb, spec/helpers/notes_helper_spec.rb, spec/lib/public_body_csv_spec.rb, spec/models/public_body_spec.rb, spec/views/alaveteli_pro/info_requests/new.html.erb_spec.rb, spec/views/alaveteli_pro/public_bodies/_search_result.html.erb_spec.rb, spec/views/general/frontpage.html.erb_spec.rb, spec/views/public_body/list.html.erb_spec.rb
Fixes #7218
Refactor notes rendering
General improvements to help with implementing #387 & #4478
Should be independent to other PRs and doesn't actually change how notes are rendered.
=> Refactor notes rendering

doc/CHANGES.md
Fixes #7267
Update changelog. Include new notes feature and upgrade note.
=> [#7267] Update changelog

docker/README.md
Just some simple usage examples for now
=> Add a readme for using Docker

app/views/admin_incoming_message/edit.html.erb
Consistent styling as per 20efd94 [1].
[1] https://github.com/mysociety/alaveteli/commit/20efd9459a238eb07282b19c06d7566fb4016862
=> Use `btn-success` for save button

_layouts/page.html, docs/customising/make_a_new_theme.md, docs/installing/ami.md, docs/installing/docker.md, docs/installing/index.md, docs/installing/vagrant.md
Depreciate Vagrant in the process.
=> Add Docker installation page

README.md
See: https://github.com/badges/shields/issues/8671
Update Readme shields
=> Update Readme shields

.github/dependabot.yml
Get automated PRs for commonlib changes.
=> Update Git Submodules using Dependabot

.github/workflows/rubocop.yml
- Display cop names in offense messages.
- Display extra details in offense messages.
- Display style guide URLs in offense messages.
=> Add rubocop flags to display useful information

app/controllers/users/messages_controller.rb, config/general.yml-example, doc/CHANGES.md, lib/configuration.rb, spec/controllers/users/messages_controller_spec.rb
Similar to request & comment content checking, just applied to user to user messages.
=> Check user to user message content for spam

app/controllers/users/messages_controller.rb, app/models/user.rb, app/models/user_message.rb, db/migrate/20230222154014_create_user_messages.rb, spec/controllers/users/messages_controller_spec.rb, spec/factories/user_messages.rb, spec/models/user_message_spec.rb
Record when a User sends a UserMessage 
We can later use this to moderate use of the system.
=> Record user messages

config/alert-tracks-debian.example, config/poll-for-incoming-debian.example, config/send-notifications-debian.example, config/sysvinit-thin.example, lib/tasks/config_files.rake, script/site-specific-install.sh
Refactor configuration files generation tasks 
To simplify the code and make it easier to add support for systemd services.
=> Refactor configuration files generation tasks 

lib/tasks/config_files.rake, script/site-specific-install.sh
Connected to #7581 #7575
Add support for systemd services
This will be needed to add services for Puma and Sidekiq.
=> Add support for systemd services

app/controllers/general_controller.rb, app/models/blog.rb, app/views/alaveteli_pro/general/_nav_items.html.erb, app/views/general/_nav_items.html.erb, app/views/general/blog.html.erb, spec/controllers/general_controller_spec.rb, spec/models/blog_spec.rb, spec/views/general/blog.html.erb_spec.rb
Connected to #6589
Refactor loading of blog items to happen in a class rather than controller
To continue with the development of the #6589
=> [#6589] Blog refactor

app/models/info_request_event.rb, spec/models/info_request_event_spec.rb
* Tidy InfoRequestEvent acts_as_xapian configuration
* Privatise InfoRequestEvent methods
=> Minor tidying of InfoRequestEvent

app/controllers/api_controller.rb, app/models/incoming_message.rb, app/models/info_request.rb, app/models/mail_server_log.rb, app/models/outgoing_message.rb, app/models/public_body.rb, lib/alaveteli_text_masker.rb, spec/lib/alaveteli_rate_limiter/ip_rate_limiter_spec.rb, spec/mailers/alaveteli_pro/embargo_mailer_spec.rb
N/A
Changes to satisfy the following cops:
- Lint/IneffectiveAccessModifier
- Lint/ShadowingOuterVariable
- Lint/ImplicitStringConcatenation
Conforming to coding standards to help maintainability of Alaveteli code base
=> Rubocop linting

app/helpers/link_to_helper.rb
Connected to #285
Commits extracted from #7702 which are ready for review.
Minor refactorings link to helpers and applying censor rules. These changes will make it easier to implement the #285.
=> [#285] Add OutgoingMessage#from_name prep

app/models/foi_attachment.rb, lib/attachment_to_html.rb, lib/attachment_to_html/adapters/google_docs_viewer.rb, spec/lib/attachment_to_html/adapters/google_docs_viewer_spec.rb, spec/lib/attachment_to_html/attachment_to_html_spec.rb, spec/models/foi_attachment_spec.rb
Couple of small refactorings I took the opportunity to make while reviewing https://github.com/mysociety/alaveteli/pull/7681.
=> `FoiAttachment` cleanup

app/views/admin/blog_posts/_about.html.erb
Describe when the feed is imported, and make it easy to force an import yourself by just following the link.
=> Update admin blog import documentation

_layouts/default.html, _layouts/es/default.html
Part of https://github.com/mysociety/sysadmin/issues/1768
Updates alaveteli.org to GA4
=> [pages] Add hack to support GA4 without cookies

app/helpers/analytics_helper.rb, app/views/alaveteli_pro/dashboard/_ga_events.html.erb, app/views/application/_ga_code.html.erb, app/views/request/_ga_events.html.erb, spec/helpers/analytics_helper_spec.rb
Backport #7779 for 0.43.1 release
=> Backport #7779 for 0.43.1 release

app/models/public_body.rb, spec/lib/public_body_csv_spec.rb, spec/models/public_body_spec.rb
Reasonable to expect this is the default these days!
=> Use HTTPS for `PublicBody#calculated_home_page`

doc/CHANGES.md
None
Reformats list of changed templates
it's easier to read :)
=> Update CHANGES.md to reformat list of changed templates

app/models/public_body.rb, spec/models/public_body_spec.rb
Fixes #7948
Add PublicBody#disclosure_log to JSON
=> [#7948] Add PublicBody#disclosure_log to JSON

.github/workflows/ci.yml
#7983
Update CI GitHub workflow
Ensure push events still work. After the changes in 053f8b1 the workflow errored.
=> Update CI GitHub workflow

.github/workflows/changelog.yml
Allow changelog entries to be missed by Dependabot.
=> Update GitHub changelog workflow

app/helpers/admin/holding_pen_helper.rb, app/views/admin_raw_email/_holding_pen.html.erb, doc/CHANGES.md, spec/helpers/admin/holding_pen_helper_spec.rb
Make it easier to visually spot a good match.
Requires https://github.com/mysociety/alaveteli/pull/8063.
=> Colourise holding pen guess scores

app/assets/stylesheets/admin.scss, app/controllers/admin/citations_controller.rb, app/views/admin/citations/index.html.erb, app/views/admin_general/_admin_navbar.html.erb, config/routes.rb, doc/CHANGES.md, spec/controllers/admin/citations_controller_spec.rb
=> Add basic admin list of all citations

app/views/admin_public_body/_tag_help.html.erb, app/views/admin_public_body/import_csv.html.erb
Fixes #8176
Update admin list of authority tags
<hr>
=> [#8176] Update admin list of authority tags

app/models/note.rb, app/views/admin/notes/_form.html.erb, app/views/admin/notes/_warnings.html.erb, app/views/admin/notes/edit.erb, app/views/admin/notes/new.html.erb, spec/models/note_spec.rb
**BEFORE**
**AFTER**
**ADMIN GUIDANCE**
=> Tweak note ordering

app/controllers/alaveteli_pro/batch_request_authority_searches_controller.rb, app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb, app/models/public_body.rb, app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb, app/views/alaveteli_pro/batch_request_authority_searches/_public_bodies.html.erb
Move into the model as a class accessor allowing this to be modified in themes.
=> Extract public body batch search excluded tags

docs/pro/pricing.md
=> Clarify that STRIPE_NAMESPACE is not exposed to users

lib/tasks/gettext.rake
Allow tasks to work on a single locale by setting environment variable.
<hr>
=> Update gettext rake tasks

config/nginx-ssl.conf.example, config/nginx.conf.example, doc/CHANGES.md
Add sidekiq config to allow web UI assets to be served through the Rails
application.
Fix broken assets.
=> Update nginx config

config/logrotate-example, doc/CHANGES.md, lib/tasks/config_files.rake, script/site-specific-install.sh
Fixes #6260
Add example logrotate config
Generate config when using the Alaveteli install scripts.
=> [#6260] Add example logrotate config

docs/installing/cron_and_daemons.md
Depends to #8352 
Depends to #7581 
- Change from init scripts to systemd services.
- Switch to puma over thin
- Add sidekiq service
- Add logrotate config
=> Update cron jobs and daemon page

spec/mailers/previews/notification_mailer_preview.rb, spec/mailers/previews/request_mailer_preview.rb
Minor updates to mailer previews and adds previews for the NotificationMailer actions.
<hr>
=> Add notification mailer previews

funding.json
https://floss.fund/funding-manifest/
=> Add funding.json

app/assets/stylesheets/responsive/alaveteli_pro/_pro_upsell.scss, app/assets/stylesheets/responsive/all.scss, app/views/user/rate_limited.html.erb, doc/CHANGES.md
Fixes #8535
Add Pro upsell on the user rate limited page
=> [#8535] Add Pro upsell on the user rate limited page

app/assets/javascripts/general.js, app/controllers/alaveteli_pro/subscriptions_controller.rb, app/views/alaveteli_pro/subscriptions/_cancel_subscription.html.erb, doc/CHANGES.md, spec/views/alaveteli_pro/subscriptions/_cancel_subscription.html.erb_spec.rb
Fixes #8563
Update Pro subscription cancellation
Collect cancellation reason and pass this to Stripe.
Will allow us to analyse why Pro users cancel their subscriptions.
https://github.com/user-attachments/assets/48959ffd-1f1e-4f23-a90c-3f1f3b321162
=> [#8563] Update Pro subscription cancellation

app/helpers/classifications_helper.rb, app/models/request_classification.rb, spec/helpers/classifications_helper_spec.rb
=> Update request classification milestones

app/models/user.rb, app/models/user/internal_admin.rb
Extract isolated and non-core behaviour to a concern to reduce length of main User class.
=> Extract User::InternalAdmin concern

app/assets/stylesheets/responsive/alaveteli_pro/_pro_upsell.scss
Fixes: https://github.com/mysociety/alaveteli/issues/8866
- Added responsive behaviour
- Fixed screenshor overlap on left text
https://github.com/user-attachments/assets/3126907c-8bc0-469c-afc4-963772a02e44
<hr>
=> Improved layout/styling of Rate Limited page

app/controllers/comments_controller.rb, app/controllers/followups_controller.rb, app/controllers/request_controller.rb, app/controllers/users/messages_controller.rb, app/mailers/request_mailer.rb, app/models/notification.rb, app/models/user.rb, spec/controllers/comments_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/models/user_spec.rb
Fixes #8890
Refactor user exceeded content limits handling
- Bug introduced in #8859
- Refactoring code for consistency and improved readability
<hr>
=> [#8890] Refactor user exceeded content limits handling
