app/views/request/show.html.erb
Fixes #2036
Make strings to be translated full sentences rather than concatenating
together. See http://mysociety.github.io/internationalization.html
=> [#2036] Use translatable strings

app/controllers/request_controller.rb, app/views/info_request_batch/_batch_sent.html.erb, app/views/info_request_batch/show.html.erb, app/views/request/_request_sent.html.erb, app/views/request/show.html.erb, spec/controllers/request_controller_spec.rb
=> [#1682] Extract "just made a request" notice to partial

app/assets/stylesheets/responsive/_public_body_layout.scss, app/assets/stylesheets/responsive/_public_body_style.scss, app/controllers/public_body_controller.rb, app/controllers/request_controller.rb, app/controllers/services_controller.rb, app/views/public_body/show.html.erb, spec/controllers/public_body_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/controllers/services_controller_spec.rb
Fixes #2051 
Store the search parameters in the flash when a search is made via the
select_authority_path page. Stores the parameters for both POST and 
AJAX typeahead searches.
The presence of stored search params renders the link on the
PublicBodyController#show template.
“keep”s the search params in PublicBodyController#show so that if the
user clicks the browser’s back button the “Back to search results” link
can still be rendered on the next search result they click.
“keep”s the search params in ServicesController#other_country_message
as it’s called through AJAX and ends up sweeping the flash. [1]
[1] More details about this:
http://mikenaberezny.com/2007/09/08/keep-the-flash-and-test-it-too/
=> [#2051] Add a “Back to search results” link

app/views/track/_tracking_links.html.erb
Looks like 'follower_count && follower_count > 0' was being interpreted as the argument to defined?, resulting in a return value of 'expression'.
Closes #2082
=> Add brackets to remove ambiguity about defined? arguments

app/controllers/general_controller.rb, app/views/general/search.html.erb, config/initializers/alaveteli.rb, spec/controllers/general_controller_spec.rb
The pages for these search results are extremely slow to load. This
is not an ideal solution by any means. Really we want to dig into why
high offsets are so slow, and whether there's anything we can do to
fix that.
Fixes #2111.
=> Do not allow requests for search results after the first 500

app/controllers/user_controller.rb, app/models/user.rb, app/views/user/set_draft_profile_photo.html.erb, app/views/user/set_profile_about_me.html.erb, app/views/user/show.html.erb, spec/controllers/user_controller_spec.rb, spec/models/about_me_validator_spec.rb, spec/models/user_spec.rb
Fixes #2160 
Stops banned users editing their about me and profile photo.
4e9b1b8 is a refactoring of `AboutMeValidator`, as I was originally going to use this to reject edits from banned users. Its probably better now, but not consistent with `ChangeEmailValidator` so I don't mind if we drop the commit.
=> [#2160] Banned user profile editing

app/controllers/request_controller.rb, app/models/info_request.rb
Since 80ad2d4c31075ffc994e8c48ea25e6e3c486c364
no themes have been loaded by tests unless explicitly specified, so I think it's safe to
remove the code added in 3dfc53f6b82b3c5da79a4c710d45b859f61f4f5f
=> Allow custom states to be tested.

_layouts/page.html, docs/glossary.md, docs/running/admin_manual.md, docs/running/holding_pen.md
Closes #2063
Promotes the Holding Pen into a concept with its own page -- but (obviously) I am happy with this because the admin guide seems like the place for instructions, and I'm slowly making it more navigable section by section.
The "how Alaveteli works" at the top of this page probably deserves a diagram -- but actually such a diagram would belong in a more overiew-y place. Will think about this separately.
=> Add page explaining holding pen, update links in glossary & admin_guide

docs/installing/macos.md
=> Remove obsolete instructions for not getting vendored rails.

config/deploy.rb, config/deploy.yml.example, config/sysvinit-thin.ugly, doc/CHANGES.md, script/site-specific-install.sh
Fixes #2163 
Fixes #2185
~~Add `daemon_name` to [deploy docs](http://alaveteli.org/docs/installing/deploy/#set-up)~~ #2187
- daemon_name defaults to "alaveteli"
- daemon_name can be set per-environment in config/deploy.yml
=> [#2163] Restart alaveteli by service command during capistrano deploy

config/general.yml-example
The install script generates a config from this, which we want to
default to development. Closes #2225
=> Set STAGING_SITE to 1 in the example config.

script/wad
Hi,
From what I can tell `script/wad` was a tool designed for diagnosing bundler issues on Travis by tarring up an archive and sending to to S3. I wonder if this is still required (or an issue with Ruby 1.9.3 and below being deprecated). 
Also in the way of a suggestion would installing the `ca-certificates` apt package and using the `fog` gem possibly make the amount of required code smaller and remove the need to include certificates at the end of the file?
Unfortunately Travis includes a security feature which prevents secure environment variables being read for forks of repositories (http://docs.travis-ci.com/user/pull-requests/). The solution this PR proposes is to skip the `put` method call if `ENV['S3_CREDENTIALS']` are blank.
This should allow forks to be tested by Travis.
Thanks, …
=> Add a guard in script/wad for the S3 credentials ENV vars being missing

config/initializers/missing_source_file.rb
Rails 2.3 temporarily had an issue with Ruby 1.9.3. Fortunately this project has moved passed Rails 2.3, making this initializer no longer required. (https://github.com/rails/rails/pull/3745)
Also - tests will be run if mysociety/alaveteli#2250 is merged.
Thanks,
Caleb
=> Removed a Rails 2.3 hack

Gemfile, Gemfile.lock
Hi again!
In this (also tiny) PR I updated `eventmachine` (change just in the Gemfile.lock) due to running into this error https://github.com/eventmachine/eventmachine/issues/509. I'm working on creating a [Docker container](https://github.com/nzherald/alaveteli-docker) (with a base image of Debian Jessie and using Ruby 2.2).
This also includes updating the sqlite gem, as the native extension fails to build on Jessie unless updates as well.
I also removed one additional occurrence of whitespace at the end of a line in the Gemfile.
Tests will be run if mysociety/alaveteli#2250 is merged.
=> Update eventmachine due to install issue

app/assets/javascripts/general.js
Some devices (IOS) scroll and zoom the screen to the position of a form input when it is selected. This causes the screen to scroll to the bottom of the page when the 'link to this' icon is clicked, because the browser scrolls before the box is positioned on screen. This is what causes https://github.com/mysociety/alaveteli/issues/2264
This commit changes the order of steps in script for the 'link to this' widget, so that the input is selected *after* the box is positioned.
This stops the browser from jumping to the bottom of the page.
Tested in Chrome, Safari and IOS simulator on Mac OSX.
Fixes #2264
=> Fix bug in 'link to widget' causing IOS devices to scroll to bottom of the page

app/assets/stylesheets/responsive/_header_layout.scss, app/assets/stylesheets/responsive/_header_style.scss, app/assets/stylesheets/responsive/_utils.scss, app/views/general/_responsive_topnav.html.erb
There are a number of usability problems with the header search form that particularly impact citizens using assistive technology.
See issue https://github.com/mysociety/alaveteli/issues/2210
These commits improve the accessibility of the form by:
* adding a text label that can be associated with the input by assistive tech
* adds a submit button to the form to provide more ways to trigger the form with difference inputs (tap/mouse)
* adds the 'search' aria role to the form
* adds type and placeholder attributes to the text input
The submit button (using the magnifying-glass icon) has been moved from the left to righthand side. This works better for keyboard access and is a more familiar design pattern, on this site and the web generally.
Note that this changes both the form markup and …
=> Accessibility improvements to header search form

app/assets/stylesheets/responsive/_global_style.scss
Not needed, causing spacing problems on themes, so they just revert it anyway
=> remove para declaration

app/controllers/application_controller.rb, app/views/general/_frontpage_search_box.html.erb, app/views/general/_header.html.erb, app/views/general/_responsive_topnav.html.erb, config/initializers/alaveteli.rb, doc/CHANGES.md, spec/integration/alaveteli_dsl.rb, spec/integration/search_request_spec.rb
Now that we use global CSRF authenticity checks, searches were logging
logged-in users out as the form is an HTML form, not a Rails-generated
form with a CSRF token. So form submission raised an InvalidAuthenticityToken
error and reset their session.  We could generate the form in Rails, but we
also want to minimise the number of non-logged in people who have a
session cookie, so that varnish can cache pages extensively. So we don't
want to put the CSRF token for the search form in everyone's session.
=> Use GET for search form, not POST.

app/views/request/new.html.erb
It looks clumsy to me and I'm pretty sure it's unnecessary.
=> Remove extra full stop after question mark

app/models/public_body.rb
On my machine the integration test "Editing a Public Body can add a
translation for multiple locales" (http://git.io/vvv9t) was failing
because when it submitted the form to update one locale it created
empty records for all locales resulting in the test
(http://git.io/vvv93) for a nil locale to fail.
It was doing this because when it submitted the form it included a
notes field with a single newline character and so this method
evaluated as false and therefore a largely blank translation was
created.
I've changed it to check for blank values now which I think is more what we want anyway... and my tests pass :)
=> Fix admin public body edit test

app/views/request/new.html.erb
When you're starting a request to an authority that has no existing
requests we display a handy link to "Browse other requests for
examples of how to word your request". However this currently sends
you to a page that has no requests (a blank request search page).
This change sends you to the list of successful requests as these are
most likely to have wording that will help the requester.
=> Change link to browse other requests to one that has requests

app/assets/stylesheets/responsive/_global_layout.scss, app/assets/stylesheets/responsive/_request_style.scss, app/views/comment/_single_comment.html.erb, app/views/request/_followup.html.erb, app/views/request/_incoming_correspondence.html.erb, app/views/request/_outgoing_correspondence.html.erb, app/views/request/_resent_outgoing_correspondence.html.erb, app/views/request/show.html.erb
I was looking at an issue on the [Right To Know](https://www.righttoknow.org.au/) theme ( https://github.com/openaustralia/righttoknow/issues/479 ) and was finding the way padding was implemented on correspondence confusing.
This PR adds a generic box class which is then applied to the different elements through the site that have a coloured box with padding effect.
I think will make it easier to adjust this style in the future, and makes it much simpler for theme editors to adjust this aspect of the correspondence layout.
This then makes the padding on the different correspondence boxes consistent.
=> add and use a generic box style to add padding to boxes

config/varnish-alaveteli.vcl
Since the authentication cookies are removed it means that admins can't download raw emails.
I also stripped trailing spaces to clean up this file so the diff of this PR is a bit noisy, the main commit is db2db066394a99f33321fa1681a57c17e270e4e6.
Downstream issue: openaustralia/righttoknow#513
=>  Don't remove cookies from txt files in suggested Varnish configuration

app/helpers/health_checks_helper.rb, spec/helpers/health_checks_helper_spec.rb
Minor tweak to the status check helper module.
Currently it produced HTML that looks like this when the health check is successful:
`<b style="{}">The last user was created in the last day: 2015-04-20 09:40:53 +1200</b> `
This change uses a blank string instead of an empty hash
=> Fix status check helper

app/models/public_body.rb, spec/models/public_body_spec.rb, spec/views/public_body/show.html.erb_spec.rb
This makes is so if you've got the `override_all_public_body_request_emails` config option set you can still see how Alaveteli behaves when there's no request email set.
=> Don't override blank request emails

app/views/request/new_bad_contact.html.erb
You get to this page by attempting to make a request and being asked
to contribute an email for an authority that's missing an email so it
makes sense to just send them to the change request page for this
authority.
=> Send people to new change request instead of generic contact page

lib/acts_as_xapian/acts_as_xapian.rb, spec/integration/xapian_search_highlighting_spec.rb
It seems that `term.is_a?(String) ? term.force_encoding('UTF-8') : term` doesn't work with Regexp instances, so this PR fixes string encoding at the point of interpolation.
Also included is a test.
=> Fix Xapian macron highlighting

app/mailers/request_mailer.rb, spec/mailers/request_mailer_spec.rb
Previously requests with titles including symbols such as quote marks would generate email subject lines that had these HTML encoded. For example a request titled `Here's a request` would generate an email subject line such as, `New response to your FOI request - Here&#x27;s a request`. This pull request fixes that bug.
Factories made testing this soo much easier so thanks for that :) The request mailer spec could do with a tidy up but I decided against doing it as part of this because I didn't want to have a big crazy diff that was hard to understand.
=> Email subject HTML entities

script/site-specific-install.sh
This is so that they can access mail log files. `adm` group members
have access to read log files in /var/log.
Closes #2402.
=> Add the site user to the 'adm' group.

app/controllers/admin_request_controller.rb, app/models/info_request.rb, app/models/public_body.rb, spec/models/info_request_spec.rb
Handles issue of moving a request to a public body with a different law.
=> Don't initialize PublicBody when initializing InfoRequest

app/models/info_request_event.rb, app/models/post_redirect.rb, config/application.rb, spec/models/info_request_event_spec.rb, spec/models/post_redirect_spec.rb
Items cached in 1.8 can't safely be retrieved in 1.9
=> Make the namespace for memcached dependent on ruby version.

config/initializers/alaveteli.rb, lib/ruby19.rb
This was added because TMail calls String#is_binary_data? which
does not exist in Ruby 1.9.2 onwards, so is no longer needed.
=> Remove monkeypatch required when running Rails 2.3 under Ruby 1.9

config/packages.debian-wheezy
The cron jobs look for this font when running on Debian Wheezy.  Make sure it is listed as a required
package.
=> Add the ttf-bitstream-vera package to provide Vera.ttf to the cron jobs.

app/models/censor_rule.rb, app/models/info_request.rb, app/models/outgoing_message.rb, spec/factories/info_requests.rb, spec/integration/download_request_spec.rb, spec/models/censor_rule_spec.rb, spec/models/outgoing_message_spec.rb
Pass the censor rules to outgoing message rather than duplicating the logic like in https://github.com/mysociety/alaveteli/pull/2384
Has a few failing specs that should be relatively easy to fix if we're happy with the general idea.
Could also improve further with https://github.com/mysociety/alaveteli/commit/e7bf72a5489e18cb2140f74ee6a2c6cc3bc61c27
=> Alternative approach for speeding up InfoRequest#initial_request_text

app/models/user.rb, config/initializers/alaveteli.rb
Without this line, strings created in the file will use the default
external encoding set by the ENV variable LANG. When processes are
forked or run in cron, this may not be preserved, so better to
set explicitly. Fixes #2433
=> Add UTF-8 encoding line.

script/request-creation-graph
On a fresh installation with no reports yet, the cron job emit lots of gnuplot errors,
causing new site admins to worry what is going wrong.  Detect the situation and
give a more clear warning about the problem instead.
=> Detect empty databases and report sensible warning.

app/models/incoming_message.rb, config/initializers/alaveteli.rb, spec/models/incoming_message_spec.rb
mb_chars provides a multibyte-aware wrapper for strings. It should
have no effect on ruby 1.9.3 and above. Although ruby 1.8.7 wouldn't
raise errors on a badly sliced multibyte string, on upgrading to ruby
1.9.3 and above, string operations such as gsub, match and join may
produce ArgumentErrors with the message "invalid byte sequence in UTF-8".
Additionally, a database with 'UTF-8' encoding may produce the error
"PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8""
=> Use mb_chars to prevent slicing multibyte chars under ruby 1.8

app/models/foi_attachment.rb
`Hash#[]` is faster, but harder to read. If this method can be proven to be a performance bottleneck (it would have to be called thousands/millions of times per request to make a difference), `Set#member?` can be used (both fast and easy to read).
=> FoiAttachment: Use simpler Array#include? instead of Hash#[]

app/views/public_body_change_requests/new.html.erb
A string in the text shown when asking to update the email
address of an authority is not translatable.  Fix the typo.
=> Make a 'Your email:' string translatable.

app/controllers/admin_comment_controller.rb, app/controllers/admin_public_body_controller.rb, app/controllers/admin_public_body_headings_controller.rb, app/controllers/admin_request_controller.rb, app/controllers/admin_user_controller.rb, app/controllers/request_controller.rb, app/controllers/user_controller.rb, app/views/comment/_comment_form.html.erb, lib/acts_as_xapian/acts_as_xapian.rb, lib/acts_as_xapian/tasks/xapian.rake, lib/attachment_to_html/adapter.rb
Some of these ternary operations are entirely redundant (the value is already a boolean), others are unnecessary (truthy/falsy values are fine), and others are more idiomatic as `!!condition`.
=> Avoid unnecessary ternary operations

.codeclimate.yml
Adding JS code quality in #2439 has destroyed the progress that had been made on Code Climate score. See https://codeclimate.com/github/mysociety/alaveteli/compare/rails-3-develop
=> Don't analyze JavaScript code quality

Gemfile
As we're using nokogiri as the XmlMini backend as of bd6e94fc7c9c1790622ba29655f6e7e27044dd64,
it should be in the default gem group.
=> Add nokogiri to main group

script/handle-mail-replies, script/mailin
It is reliable in the case where the script is sourced from another
script.
=> Use BASH_SOURCE to return the script path.

Gemfile, config/application.rb, spec/integration/parameter_stripping_spec.rb
Unfortunately, the conditional used in 090531bf2d2b763e5bb281658e91b58905912130
results in `Gemfile.lock` being inconsistent with `Gemfile` under ruby 1.8.7 so
we can't use it until after Alaveteli release 0.22, which is the last release
that will support ruby 1.8.7. If we merge this, I think we should immediately create a ticket for extending it to ruby 2.0.0 after release 0.22
=> Use :platform to add rack-utf8_sanitizer

app/controllers/application_controller.rb
Not in an initializer to avoid any risk of popping up in mail
handling contexts.
=> Add deprecation notice for ruby 1.8.7

app/assets/javascripts/admin/admin.js.coffee
Looks like this has changed behaviour in the later version of jquery
we now use https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnattrvalue-val-no-longer-sets-properties
=> Replace .attr("value", val) with .val(val)

config/database.yml-example
Debian Wheezy and Ubuntu Precise supply postgres 9.1, so 8.4 is not our default.
Don't really know what the comment was referring to – port number has changed I guess?
If so, we might want to change this default.
=> Remove postgres 8.4 comment

app/models/public_body.rb, spec/models/public_body_spec.rb
The public body model contains fields that provide information on the
number of request types (such as success count, not held count) that
were previously not returned in the JSON representation of the public
body.  This PR adds those fields in a sub-map called info.
This should close #2627
=> Adds the info fields to the json response for a body

config/general.yml-example, doc/CHANGES.md, lib/configuration.rb
Fixes #2618
Makes sense to add this to make it available for https://github.com/mysociety/alaveteli/pull/2631/
=> [#2618] Add FACEBOOK_USERNAME configuration option

app/mailers/contact_mailer.rb, spec/mailers/contact_mailer_spec.rb
If the MTAs for the people on the support alias for the site check
SPF, this is the field they check, so it should be something we
control. Closes #2635.
=> Set the return-path for the contact form mail.

app/controllers/public_body_controller.rb, config/initializers/alaveteli.rb, doc/CHANGES.md, lib/database_collation.rb, spec/controllers/public_body_controller_spec.rb, spec/lib/database_collation_spec.rb
Fixes #2482 
~~WIP for initial review~~
~~Specs will fail unless nn_NO language is available:~~
```sh
$ sudo apt-get install language-pack-nn
```
=> [#2482] Fix translated public body sort

script/install-as-user, script/site-specific-install.sh
Fixes #2636
```sql
postgres=# \l
List of databases
Name          |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------------------+----------+----------+-------------+-------------+-----------------------
alaveteli_development | vagrant  | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 |
alaveteli_production  | vagrant  | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 |
alaveteli_test        | vagrant  | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 |
postgres              | postgres | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 |
template0             | postgres | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 | =c/postgres          +
|          |          |             |             | postgres=CTc/postgres
template1             | postgres | UTF8     | en_GB.UTF-8 | en_GB.UTF-8 | =c/postgres          + …
```
=> [#2636] Create template_utf8 for new databases

script/request-creation-graph
The cron job complained about empty data files because there were
no requests of a given category used in the graph.  This change make
sure every data set have at least one zero value data point.
https://github.com/mysociety/alaveteli/issues/619
=> Quiet down graph generating cron job on new installations.

docs/customising/config.md
This arose because a user asked for clarification: in fact,
the config setting is a little misleadingly named since
(as hopefully described here) it's really about forcing
registration at the *start* of the new request process,
and doesn't mean no registration is required at all.
Please check that what I've put here (in the config setting's explanation) is true :-)
=> add explanation to FORCE_REGISTRATION_ON_NEW_REQUEST docs

docs/installing/email.md, es/docs/installing/email.md
These transports are applied to all domains, not just the domains
handled by the server, so there's a risk of matching a local part
of a remote domain here. Matches #2764.
=> Use more specific regular expressions in Postfix transports.

script/site-specific-install.sh
Otherwise mail for other domains matching the local part will
be directed into Alaveteli.
=> Use regex that includes hostname for incoming mail pipe.

spec/controllers/general_controller_spec.rb, spec/controllers/user_controller_spec.rb
Replace `should` with `expect` as in 753c784fa9e568493819d830348f302886fc7bcd
and `any_instance.stub` with `allow_any_instance_of`
=> Update some more deprecated syntax instances for rspec 3.

config/environments/production.rb
Easier to identify what you're getting alerted about if you manage multiple
Rails apps.
=> Add domain to exception notification subject line

spec/models/incoming_message_spec.rb
Without forcing a mail reparse, these tests would fail when the
order of tests meant that there was already data stored on the
message from the usual raw_email.
=> Explicitly force a mail reparse when we set the mail or raw_email.

app/controllers/user_controller.rb, app/models/user.rb, app/views/user/_signup.html.erb, spec/controllers/admin_user_controller_spec.rb, spec/controllers/user_controller_spec.rb, spec/models/user_spec.rb
Adds email address uniqueness validation to the User model. Have added it as a custom method rather than using `validate_uniqueness_of` so that we get to use the custom `find_user_by_email` method.
Fixes #2515 
Fixes #2393
=> Fix unique email validation errors

lib/xapian_queries.rb, spec/controllers/public_body_controller_spec.rb
Unfortunately it looks as though the `query = params.fetch(:query) { '' }` syntax only returns a blank string if the requested key is absent from the params hash. In this case the key is present but empty which is treated as if a null value has been intentionally supplied. Adding a guard to catch the unwanted `nil`
Fixes #2724
=> Prevent empty query param from breaking pages

app/mailers/request_mailer.rb, doc/CHANGES.md, spec/mailers/request_mailer_spec.rb
The path should be checkable by SPF.
=> Set blackhole return-path for admin report mails.

app/mailers/request_mailer.rb, app/models/info_request.rb, app/models/info_request/response_gatekeeper.rb, app/models/info_request/response_gatekeeper/authority_only.rb, app/models/info_request/response_gatekeeper/base.rb, app/models/info_request/response_gatekeeper/nobody.rb, app/models/info_request/response_gatekeeper/spam_checker.rb, app/models/info_request/response_rejection.rb, app/models/info_request/response_rejection/base.rb, app/models/info_request/response_rejection/bounce.rb, app/models/info_request/response_rejection/holding_pen.rb, doc/CHANGES.md, spec/models/info_request/response_gatekeeper/authority_only_spec.rb, spec/models/info_request/response_gatekeeper/base_spec.rb, spec/models/info_request/response_gatekeeper/nobody_spec.rb, spec/models/info_request/response_gatekeeper/spam_checker_spec.rb, spec/models/info_request/response_gatekeeper_spec.rb, spec/models/info_request/response_rejection/base_spec.rb, spec/models/info_request/response_rejection/bounce_spec.rb, spec/models/info_request/response_rejection/holding_pen_spec.rb, spec/models/info_request/response_rejection_spec.rb, spec/models/info_request_spec.rb
#2387
WIP refactoring work.
I'm reasonably happy with this as is, so making a PR for a first-pass review.
Flog score has dropped considerably:
```
130.0: InfoRequest#receive              app/models/info_request.rb:422
44.9: InfoRequest#receive              app/models/info_request.rb:422
```
I basically followed the ideas in Sandi Metz's [All the Little Things talk](http://confreaks.tv/videos/railsconf2014-all-the-little-things).
- I couldn't find a good way of dynamically finding the `ResponseGatekeeper` because they need different initialisation arguments. I think we could get around this with more refactoring elsewhere. The main problem is needing to pass the `Mail` instance for the calculation. It would be better if we only needed the `InfoRequest` instance, because then we could …
=> [#2387] Refactor InfoRequest#receive

app/models/incoming_message.rb, app/models/info_request_event.rb, spec/models/incoming_message_spec.rb, spec/models/info_request_event_spec.rb
Uses the Rails `:dependent => :destroy` and `:dependent => :nullify` options to correctly dispose of dependent objects, allowing a simplified `fully_destroy` method to request the destruction of the raw email files then defer everything else to the `destroy` method.
Fixes #2608
=> Make IncomingMessage#fully_destroy delete related attachments

_layouts/page.html, docs/glossary.md, docs/running/admin_manual.md, docs/running/hiding_information.md, docs/running/redaction.md
fixes #2062 -- unless Alavetelians think this is not strong enough on the "provide public reasons for taking material down" aspect?
Includes new overview of why/how things can be removed from Alaveteli, linking to existing instructions (which are in both requests or the admin_guide, depending on their nature) which themselves have been updated;  also expanded the Redaction page. Gareth had done sterling work on the Nicaraguan example (thanks for all the screenshots) but I felt it needed more context/qualification because it jumped straight into the Nicaraguan use-case. (Also did so style/rewording on that text).
=> docs on hiding

app/models/comment.rb, spec/controllers/user_controller_spec.rb, spec/models/comment_spec.rb
It looks as though the `visible` scope in the comments model was causing comments on hidden requests to be included in the visible comments count. Hopefully this is what's been causing the discrepancies in the annotation counts on the profile pages.
Fixes #2216
=> Prevent comments on hidden requests being counted as visible

app/controllers/admin_censor_rule_controller.rb, app/controllers/admin_controller.rb, app/controllers/admin_incoming_message_controller.rb, app/controllers/admin_outgoing_message_controller.rb, app/controllers/admin_request_controller.rb, app/models/incoming_message.rb, app/models/info_request.rb, app/models/outgoing_message.rb, app/models/raw_email.rb, app/models/track_thing.rb, app/models/user.rb, spec/controllers/admin_censor_rule_controller_spec.rb, spec/controllers/admin_incoming_message_controller_spec.rb, spec/controllers/admin_outgoing_message_controller_spec.rb, spec/controllers/admin_request_controller_spec.rb, spec/controllers/general_controller_spec.rb, spec/models/incoming_message_spec.rb, spec/models/info_request_spec.rb, spec/models/outgoing_message_spec.rb, spec/models/raw_email_spec.rb, spec/models/track_thing_spec.rb, spec/script/mailin_spec.rb
Fixes the destroy dependency chain using Rails' `:dependent => :destroy` rather than manually destroying dependencies in `fully_destroy` methods (fixes #2609)
Attempts to get rid of the `fully_destroy` methods for `InfoRequest` and `IncomingMessage` in favour of `before_destroy` callbacks. (Isolated in their own commits in case these are an "enhancement" too far, but it does clean up the destroy dependencies quite nicely).
Moves the expiry of `InfoRequest` data from the `AdminController` to new `InfoRequest#expire` and `User#expire_requests`methods (the latter calls `InfoRequest#expire` on a specific user's requests).
All of which *should* get rid of the "frozen hash" error (caused by calling `expire` after deleting the request's incoming_messages - fixes #2400) and the various destroy …
=> Destroying and expiring InfoRequest data

app/controllers/general_controller.rb, spec/controllers/general_controller_spec.rb
Passes the error message through rather than trying to get a string representation of the error object.
Fixes #2775
=> Search errors should be passed through to flash for display

app/controllers/admin_public_body_controller.rb, app/views/admin_public_body/edit.html.erb, spec/controllers/admin_public_body_controller_spec.rb
empty? was returning true for an unloaded collection.
This seems like a bug in the association. Similar, but not identical
behaviour is described in
http://stackoverflow.com/questions/14737148/empty-collection-check-returning-false-with-no-entries-ruby-on-rails#comment20620674_14737148
Update the method used in the destroy action for consistency.
=> Use count rather than empty to determine if requests exist.

app/controllers/track_controller.rb, app/models/track_thing.rb, db/migrate/20151020112248_set_longer_length_for_track_things_track_query.rb, doc/CHANGES.md, spec/controllers/track_controller_spec.rb, spec/models/track_thing_spec.rb
New migration to extend the length of the `track_things.track_query` field from 255 chars to 500
Validates that the query fits within the 500 char limit to avoid the user seeing a database error if they exceed the field length
Fixes #937
=> Prevent user seeing field length SQL error when creating a search track

Gemfile, Gemfile.lock, app/models/user.rb, db/migrate/20151006101417_add_otp_enabled_to_users.rb, db/migrate/20151006104552_add_otp_secret_key_to_users.rb, db/migrate/20151006104739_add_counter_for_otp_to_users.rb, spec/fixtures/users.yml, spec/models/user_spec.rb
Required for #2697
This PR just adds the model-level stuff for a `User` instance being able to enable, set and validate an OTP.
=> [#2697] Add User OTP

docs/running/redaction.md
Note this doesn't cover the case-insensitive example well: as @schlos asked https://github.com/mysociety/alaveteli/issues/2056#issuecomment-93829106
about how to add the "options" that regexp users might expect.
I don't think the Nicargauan example really covers this because it adds the regexp within the source code -- is there a case for adding "options" as a (JS-revealed?) selection in the admin if someone chooses "regexp"?
If we can show it (that is: explicit case insensitivity and multiline regexps) in the admin interface, that would be great but I'm not sure how to do that: as it happens, I've simulated
* case-insenstitive (by using character class [Aa] on one letter)
* multiline (by using whitespace \s)
both of which would be better if I was bolder about saying "this is how to do …
=> add "simple" example of censor rule (word match and regexp)

app/models/info_request.rb, app/views/outgoing_mailer/initial_request.text.erb, app/views/request/_request_sent.html.erb, app/views/request/followup_bad.html.erb, app/views/request/new.html.erb, app/views/request/new_bad_contact.html.erb, app/views/request/preview.html.erb, app/views/request/show.html.erb, app/views/request/show_response.html.erb, app/views/request_mailer/comment_on_alert.text.erb, app/views/request_mailer/comment_on_alert_plural.text.erb, app/views/request_mailer/new_response.text.erb, app/views/request_mailer/not_clarified_alert.text.erb, app/views/request_mailer/old_unclassified_updated.text.erb, app/views/request_mailer/overdue_alert.text.erb, app/views/request_mailer/requires_admin.text.erb, app/views/request_mailer/stopped_responses.text.erb, app/views/request_mailer/very_overdue_alert.text.erb, doc/CHANGES.md, spec/mailers/request_mailer_spec.rb, spec/models/info_request_spec.rb, spec/views/request/show.html.erb_spec.rb
Fixes #2822
Note - opted not to move all the functionality of `title_formatting` to a built-in validation as the RegEx required for "does not match this pattern" is not obvious and would probably be harder to read than the current arrangement.
=> Tidy up InfoRequest

app/models/track_thing.rb, app/views/user/sign.html.erb, spec/views/user/sign.html.erb_spec.rb
Looking at this again, I think I was wrong in pushing back on this
original solution. The problem is that strings containing quotes etc,
interpolated into translated strings, get html escaped and marked as
`html_safe`. This is fine when they are immediately displayed in a
template as the `html_safe` marker means they don't automatically get
escaped again. However, when the resulting strings are stored in a `PostRedirect`
`reason_params` field as YAML and then pulled out again for display
on the signup page, the html_safe attribute is lost, so the string
is double escaped.
The `web` param of a track is only ever displayed via a `PostRedirect`
on the `sign` template, I think it's better to mark interpolated values
as safe originally, so that the whole string gets escaped in the template …
=> Implementation of @lizconlan's original fix for #2736.

script/switch-theme.rb
Earlier today I had a total n00b moment where I accidentally cloned [asktheeu-theme](https://github.com/mysociety/asktheeu-theme/) into `~/mysociety/` rather than `~/mysociety/alaveteli-themes/` and was completely stumped as to why `script/switch-theme.rb` wouldn't let me switch to the theme.
Since I assumed I'd cloned it into the right directory, I was convinced the problem must be my limited Alaveteli knowledge, and that there had to be some config file I was meant to edit somewhere.
This PR makes `scripts/switch-theme.rb` output a clear warning when you specify a theme that doesn’t exist in your themes directory, rather than just outputting usage information.
```
~/mysociety/alaveteli:zarino $ script/switch-theme.rb foobar
Theme 'foobar' not found in …
```
=> Improve switch-theme help when you specify a non-existent theme

docs/developers/index.md, docs/getting_started.md, docs/installing/manual_install.md, docs/installing/script.md, es/docs/developers/index.md, es/docs/getting_started.md, es/docs/installing/manual_install.md, es/docs/installing/script.md
Fixes https://github.com/mysociety/alaveteli/issues/2582
It it end of life in Feb 2016, and doesn't package ruby 1.8.7. Depends on #2738
=> Remove references to Debian 6 (squeeze).

app/mailers/request_mailer.rb, app/models/incoming_message.rb, app/models/info_request.rb, app/models/info_request_event.rb, app/views/admin_request/_some_requests.html.erb, app/views/admin_request/show.html.erb, db/migrate/20151104131702_add_last_public_response_at_to_info_request.rb, spec/fixtures/info_requests.yml, spec/mailers/request_mailer_spec.rb, spec/models/incoming_message_spec.rb, spec/models/info_request_event_spec.rb, spec/models/info_request_spec.rb
Adds `last_public_response_at` to `InfoRequest`, which is updated when a new `InfoRequestEvent` is added  or deleted, and when an `IncomingMessage` is updated.
To get the old unclassified events, the query can use the new field to get the date of the last public response rather than using 2 nested loops to read through all of incoming_messages and info_request_events to find the most recent relevant dates.
A broader discussion of potential performance impact and possible alternatives is included in the [comments below](#issuecomment-155034131).
Fixes #2843
=> Add a cached field to InfoRequest to avoid expensive query

app/controllers/request_controller.rb, app/models/user.rb, spec/controllers/request_controller_spec.rb
Fixes #2396 
Part of #2665
Only used for a really specific UK case and no longer required.
=> [#2396] Deprecate User#can_leave_requests_undescribed?

app/models/outgoing_message.rb, doc/CHANGES.md, spec/models/outgoing_message_spec.rb
Now behaves more like the code for incoming messages, skips the 67 char line break code and squishes extra line breaks. (Would it better for the preview screen not to do that second bit?)
Closes #2913
=> Stop wrapping html version of outgoing emails at 67 chars

app/controllers/request_controller.rb, app/models/info_request.rb, app/views/request/preview.html.erb, doc/CHANGES.md, spec/controllers/comment_controller_spec.rb, spec/models/info_request_spec.rb
* Light refactor of the code for `InfoRequest#update_url_title` so that it's easier to follow
* Sneak in a few tests for the above
* Add a new validation so that if there is a `url_title` clash the user will be prompted to try again rather than receiving an app error page
* Prevent the new request form submit button from being pressed twice which should hopefully prevent the error condition from occurring
Fixes #390
=> Improve handling of duplicate url_titles

Vagrantfile, doc/CHANGES.md
Adds a bit more guidance to the vagrant box motd message
Fixes #2908 
And the text that appears when the vagrant provisioning process completes
Fixes #2909
=> Improve Vagrant onscreen instructions

lib/tasks/themes.rake
Each `install_theme` prints a success message with the name of the theme and the install directory unless there was an earlier error (relies on errors halting execution). Also prints a blank line so that it's easier to see where one install ends and a new one began if there are multiple themes in the config.
Example output:
$ bundle exec rake themes:install
Installing theme whatdotheyknow-theme from git://github.com/mysociety/whatdotheyknow-theme.git
Running uninstall hook in /home/vagrant/alaveteli/lib/themes/whatdotheyknow-theme
d9deda5ec0ca803752388c4b4905c54b67f2a57e
Checking out origin/develop
HEAD is now at d9deda5... Add fix for flash not appearing on frontpage.
Running install hook in /home/vagrant/alaveteli/lib/themes/whatdotheyknow-theme
Running post_install hook in …
=> Make rake themes:install print success message

config/sysvinit-thin.example, lib/tasks/config_files.rake
Supplying a value for CPUS to the generation script will start
(and stop) the specified number of thin processes. If no value
is supplied, it will default to launching a single process.
Part of fix #2952
=> Allow sysvinit to be generated with support for thin clustering

lib/tasks/temp.rake
This is to support research work on semantic tagging.
=> Add a temporary rake task to output requests made to top 20 bodies

config/packages, config/packages.debian-wheezy, config/packages.ubuntu-precise
The executable provided isn't used anywhere.
Closes #2566.
=> Remove package requirement for xlhtml

app/assets/stylesheets/responsive/_header_layout.scss
Part of #2989.
This still means we have to massage nav link wording if we want the links to fit on a single line. But at least now, if the links *are* too long, they’ll wrap onto a new line so people can still click them.
Before:
After:
=> Stop long nav links from disappearing behind search box

config/general.yml-example, lib/configuration.rb
Work on #2819
Initial feature flag for allowing requests to be referred to an
Information Commissioner. Will later be expanded to support multiple
officers.
=> [#2819] Add EXTERNAL_REVIEWERS config

spec/spec_helper.rb
Don't think anyone really uses these. Removing because manually
excluding the coverage directory in project-wide searches is tiresome.
Happy to keep these if they help someone.
=> Don't generate local code coverage reports

lib/tasks/config_files.rake
Doesn't check for required variables, other than the script to convert.
Useful for less-used scripts like config/run-with-rbenv-path.example
=> Add a generic task for converting config files

app/models/outgoing_message.rb, spec/models/outgoing_message_spec.rb
Work on #2819 
Adding some coverage so that I can add `external_review` to the values allowed in `OutgoingMessage#what_doing`.
=> [#2819] outgoing message what doing specs

docs/getting_started.md
Updated wording on http://alaveteli.org/docs/getting_started/ to invite would-be users to apply for help through the Open Calls process rather than just asking them to email us with no further guidance.
Fixes #3028
=> Link to our Open Calls process page rather than direct email

app/mailers/reminder_mailer.rb, app/views/reminder_mailer/public_holidays.text.erb, config/crontab-example, lib/tasks/reminder.rake, script/send-public-holiday-reminder, spec/mailers/reminder_mailer_spec.rb
Sends a longer email which is suitable for sending to the site admins rather than the Alaveteli team.
Moves the email sending to a rake task and uses a mailer template so that it can be overridden by a theme to account for variations in practice or local language-specific instructions.
Currently doesn't attempt to translate the subject line which may not be correct.
Closes #2896
=> Send public holiday reminder email to site admins

app/models/mail_server_log.rb, app/models/outgoing_message.rb, doc/CHANGES.md, spec/models/outgoing_message_spec.rb, spec/support/email_helpers.rb
Part of #624 
Basic framework for collecting exim MTA logs for a specific `OutgoingMessage`.
Based on my current understanding, the last bits to add to get an `OutgoingMessage#delivered?` value are:
```ruby
def delivered?
delivery_message ? true : false
end
def delivery_message
m = delivery_line.match(/C="(.*)"/i)
m ? m[0] : nil
end
def delivery_line
mail_server_logs.
where("line ILIKE :mta AND line ILIKE :msgtype",
mta: "%#{ mta_id.last }%", msgtype: "%=>%").
last.
line
end
```
=> [#624] Add OutgoingMessage#mail_server_logs

app/assets/javascripts/admin/admin.js.coffee, app/controllers/admin_incoming_message_controller.rb, app/models/info_request.rb, app/views/admin_incoming_message/bulk_destroy.html.erb, app/views/admin_request/show.html.erb, config/routes.rb, doc/CHANGES.md, spec/controllers/admin_incoming_message_controller_spec.rb, spec/models/info_request_spec.rb
Using some hacky javascript to avoid overlapping forms (due to the hidden edit panels in the message list), adds some checkboxes to the "Incoming messages" section of the admin's edit request screen to allow deletion of one or more messages.
Selecting a message enables the "Delete selected messages" button (the button does not appear if there are no incoming messages).
Clicking through submits to a summary screen where pressing "Yes" will destroy the message(s) and redirect back to the edit request screen ("No" redirects back with no action taken).
Connected to #2769
=> Add checkboxes to allow deletion of incoming messages from a request

app/views/widgets/show.html.erb, doc/CHANGES.md
Tracks widget clicks as an event of category 'widgets', sets the action as 'track', 'vote' or 'unsubscribe' and attempts to populate the label with the address of the page it's embedded in inside the iframe. Does not fire if the GA code for the site has not been set.
Closes #3059
=> Add tracking code to widgets

lib/alaveteli_geoip.rb, spec/lib/alaveteli_geoip_spec.rb
Alaveteli is currently crashing when `GEOIP_DATABASE` and `GAZE_URL` are both blank.
=> Fix crash when neither Geoip nor Gaze are configured

app/mailers/outgoing_mailer.rb, app/views/layouts/contact_mailer.text.erb, app/views/layouts/outgoing_mailer.text.erb, app/views/layouts/request_mailer.text.erb, app/views/layouts/user_mailer.text.erb, app/views/track_mailer/event_digest.text.erb, app/views/user_mailer/confirm_login.text.erb, doc/CHANGES.md
Produces email without any artificial line breaks, leaving the email client to sort it out as this seems to be the [advice these days](https://www.campaignmonitor.com/dev-resources/guides/design/#two) (and using the Unicode equivalent soft line break character doesn't seem to be well understood by clients - Mutt ignores it and Gmail treats it as an extra space):
Liz,
Please click on the link below to confirm your email address. Then you can change your password on Alaveteli
http://example.com/link
We will not reveal your email address to anybody unless you
or the law tell us to.
-- the Alaveteli team
Note that this can still lead to imperfect formatting, as per the last paragraph of this example - the text is drawn from the translation file which, on my machine at time of testing, …
=> Stop using text wrapping formatters for plain text emails

app/controllers/application_controller.rb, app/controllers/comment_controller.rb, app/views/followups/new.html.erb, app/views/general/_advanced_search_tips.html.erb, app/views/general/search.html.erb, app/views/help/officers.html.erb, app/views/help/requesting.html.erb, app/views/help/unhappy.html.erb, app/views/request/_after_actions.html.erb, app/views/request/_request_sent.html.erb, app/views/request/_wall_listing.html.erb, app/views/request/describe_notices/_successful.html.erb, app/views/user/_user_listing_single.html.erb, app/views/user/banned.html.erb, app/views/user/show.html.erb, config/general.yml-example, doc/CHANGES.md, lib/configuration.rb, spec/controllers/comment_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/views/request/_after_actions.html.erb_spec.rb
This adds a new config option `ENABLE_ANNOTATIONS` which defaults to `true`
but which allows you to turn off the commenting on InfoRequests if desired.
I've implemented this in two places - firstly in the "after actions" view, to
hide or show the comment link, and then on the `before_filter` for the actual
comment form action. Is that everywhere we offer the ability to comment?
(There are various open tickets about providing bulk annotations, or
redirecting straight to the annotation form after submission, but I couldn't
find anything like that actually in the code at the moment).
Closes #2955
=> Add a config option to turn off comments/annotations site-wide

app/controllers/public_body_controller.rb, app/views/public_body/list.html.erb, spec/controllers/public_body_controller_spec.rb
Fixes #3094.
Translation was constructed in two parts. Note that the @title ivar in
the view is still dynamically constructed, but it should be in a way that
makes sense.
For example, a translator in a RTL language could translate "Public
authorities - {{description}}" as "{{description}} - Public
authorities". The hyphen is signifying a breadcrumb in the page title,
so the existing translation for {{description}} should still work.
=> [#3094] Fix dynamically created translation

app/views/request/new.html.erb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/301.
Users don't enter their name on the page but it _will_ be displayed
publicly alongside the request.
=> [wdtk#301] Clarify user's name will be displayed publicly

app/models/outgoing_message.rb, spec/models/outgoing_message_spec.rb
Work on #2819
TODO: For a better spec, requires #3149 so that the factory we create is a followup, rather than initial request; that said, we use `:initial_request` for the external review spec.
=> [#2819] Allow an OutgoingMessage to be an external_review

app/models/outgoing_message.rb, spec/models/outgoing_message_spec.rb
Work on #624
smtp message ids used to get stored with enclosing angle brackets.
They're never used in the mail server logs, so now
OutgoingMessage#smtp_message_ids removes them for use in
OutgoingMessage#mail_server_logs.
=> [#624] Handle old-style smtp message ids

_layouts/page.html, docs/running/admin_manual.md, docs/running/handling_spam.md, docs/running/hiding_information.md, docs/running/requests.md
=> Gh pages handling spam

app/controllers/user_controller.rb, app/views/user/_signup.html.erb, config/general.yml-example, doc/CHANGES.md, lib/configuration.rb, spec/controllers/user_controller_spec.rb
If `USE_RECAPTCHA_FOR_REGISTRATION` is set to true (defaults to false) then reCAPTCHA will be used on the signup form regardless of whether the user is visiting the site from the same country or not.
Also moves the country check to a controller filter so that that signin and signup can both just check `@use_recaptcha`
Closes #3146
=> [#3146] Allow general use of reCAPTCHA for signup

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/environments/production.rb, config/environments/test.rb, lib/quiet_opener.rb
Currently the last working version which still has Ruby 1.9 support
Connects to #3161
=> [#3161] Update to exception_notification 4.0.1

app/controllers/application_controller.rb
All strings in Alaveteli itself should be encoded as UTF-8. The
message coming back from Xapian is ASCII-8BIT though, causing an
'incompatible character encodings: UTF-8 and ASCII-8BIT' error if
the search term has non-ascii characters in it. Not clear to me
at the moment where the best place to set the encoding would be -
I think the error is generated in the ruby xapian bindings, which
are produced with SWIG.
Closes #3226.
=> Force the encoding of the Xapian error message.

app/views/layouts/default.html.erb, app/views/widgets/show.html.erb, doc/CHANGES.md
Checking whether we were using any custom code took longer than making any of the changes.
Will still have to double check that none of the analytics code has been overridden in themes before deploying to a site.
May have a knock-on effect for some tickets which are currently in review (see links in the ticket itself)
Fixes #3107
=> [#3107] Migrate analytics code from `ga.js` to `analytics.js`

app/helpers/analytics_helper.rb, app/views/general/_responsive_footer.html.erb, app/views/info_request_batch/_batch_sent.html.erb, app/views/request/_act.html.erb, app/views/request/_request_sent.html.erb, app/views/widgets/show.html.erb, config/initializers/alaveteli.rb, doc/CHANGES.md, lib/analytics_event.rb, spec/helpers/analytics_helper_spec.rb
Creates a Google Analytics event whenever someone exits the site using a social media link (Experiment 71)
Events reporting example:
Also adds a new helper for constructing the event code string to go in the `onclick` attribute
=> Track social media clicks

app/models/censor_rule.rb, app/models/comment.rb, app/models/info_request.rb, app/models/public_body_change_request.rb, app/models/public_body_heading.rb, app/models/widget_vote.rb, spec/models/public_body_change_request_spec.rb
The second commit isn't really in, er, scope, but it had the word scope in it and it seems to work so throwing it in as an added extra. (Feel free to throw it out again.)
Closes #3166
=> [#3166] Change scope macros to lambdas

public/robots.txt
Robots file should discourage crawlers from storing and accessing change request pages, i.e. */change_request/new?body=turisticka_zajednica_knin
=> Discourage crawlers on change_request

app/mailers/contact_mailer.rb, app/mailers/request_mailer.rb, spec/controllers/public_body_change_requests_controller_spec.rb, spec/controllers/reports_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/controllers/user_controller_spec.rb, spec/mailers/contact_mailer_spec.rb
If the from address is used, mails from domains with strict DMARC
policies may be refused. Fixes #3205
=> Use reply-to for user email addresses to better handle DMARC.

app/views/admin_censor_rule/edit.html.erb, app/views/admin_holidays/_edit_form.html.erb, app/views/admin_incoming_message/_actions.html.erb, app/views/admin_incoming_message/bulk_destroy.html.erb, app/views/admin_outgoing_message/edit.html.erb, app/views/admin_public_body_categories/edit.html.erb, app/views/admin_public_body_headings/edit.html.erb, app/views/admin_request/edit.html.erb, app/views/admin_spam_addresses/index.html.erb, app/views/one_time_passwords/show.html.erb
`:confirm => "Are you sure?"` is deprecated in Rails 4 in favour of `:data =>  { :confirm => "Are you sure?" }` this PR intends to change all our views to match
Closes #3219
=> [#3219] Change :confirm in helpers to :data => { :confirm }

lib/tasks/cleanup.rake
Avoids the possibility of getting a Rails error if the holding_pen request does not exist by fetching it using the `InfoRequest.holding_pen_request` method so that it will be created if it's missing.
Tidies up the rake task a bit and suppresses output - in theory using `--silent` should be enough as the generated output is being piped to `$stderr` but hiding it with checks on `verbose` and `dryrun` to be certain.
Closes #3163 
Closes #3128
=> [#3163] cleanup holding pen bugfix

app/controllers/mail_server_logs_controller.rb, app/models/outgoing_message.rb, app/views/request/_outgoing_correspondence.html.erb, spec/controllers/mail_server_logs_controller_spec.rb, spec/models/outgoing_message_spec.rb
Part of #624 
Makes the mail server logs "public" to admins and request owners. Hidden from anyone else.
=> [#624] requester only mail logs

lib/normalize_string.rb
Upgrading to CharlockHolmes 0.7.3 (c843943325248) changed the behaviour
of `.detect` to potentially return either nil or an empty string. In
some situations that would mean we're trying to ask `nil` for the
`:encoding` Hash key, hence the new conditional.
In some cases `guessed_encoding` can be `nil` after the conditional.
This is a heavy-handed fix to just assign an empty String to `guessed_encoding`
if we end up with `nil` after the encoding detection. Could probably re-write
the conditional in a nicer way, but I don't fully understand the change to
CharlockHolmes, so this just reverts to the old behaviour of at least
having a String to work with.
=> Fix regression where detect returns nil

app/controllers/mail_server_logs_controller.rb, app/models/mail_server_log.rb, spec/controllers/mail_server_logs_controller_spec.rb, spec/models/mail_server_log_spec.rb
https://github.com/mysociety/alaveteli/issues/624#issuecomment-219257191
Redacts the `idhash` for anyone other than admins
=> [#624] Redact idhash from mail server logs

Gemfile, Gemfile.lock
https://github.com/heapsource/active_model_otp/pull/27 is now merged.
=> Return to source repo for active_model_otp

app/assets/stylesheets/main.scss, app/assets/stylesheets/responsive/_global_style.scss, app/assets/stylesheets/responsive/_utils.scss, app/views/layouts/default.html.erb
Fixes https://github.com/mysociety/alaveteli/issues/3267
This adds keyboard activated 'skip to' links to alaveteli's templates
**KNOWN BUG**
On the homepage, the content ```id``` appears below the hero area. The skip-to link on the homepage skips past the hero content. It probably shouldn't do this
=> add skip to links to templates

app/controllers/general_controller.rb, doc/CHANGES.md
Fixes #3286
Bots make requests for weird formats, presumably to poke at security
holes. Here's an example:
$ curl -I -H "Accept: application/vnd.ms-excel" \
-H "Content-Type: application/vnd.ms-excel" \
-X GET \
http://10.10.10.30:3000?q=user
This was causing an ActionView::MissingTemplate error.
This change results in a 406 Not Acceptable response, saving us a bunch
of exception notification mail. We should probably do this elsewhere,
but / and /blog seem to be the most common targets.
See http://www.justinweiss.com/articles/respond-to-without-all-the-pain/
for a bit more detail.
=> Add accepted formats to frontpage and blog

docs/developers/api.md
Fixes #3295 
We've discontinued FOI Register, so remove the mention of it as the link is now broken.
Also labelled the "Write API" as experimental now that we have no real users of it.
=> Remove mention of FOI Register

app/controllers/general_controller.rb, doc/CHANGES.md, spec/controllers/general_controller_spec.rb
Only accepts requests for HTML and issues a 404 instead of running expensive search controller code in all other cases.
Not as neat as 1644cbf but was really keen to avoid calls to Xapian where the results are instantly discarded.
Closes #2920
=> Prevent search from processing non-html requests

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/widgets_controller.rb, config/initializers/secure_headers.rb
Upgrade guide (from 2.x to 3.x) here - https://github.com/twitter/secureheaders/blob/master/README.md
Not entirely convinced I've translated the old settings to the new format correctly
Connects to #3161
Fixes #2986
=> [#3161] Upgrade secure_headers to 3.1.2

app/models/outgoing_message.rb, doc/CHANGES.md, spec/models/outgoing_message_spec.rb
Fixes #3258
May need to be reworked if a hotfix is required.
=> Check `default_letter` when checking if OutgoingMessage body has changed

app/controllers/general_controller.rb, spec/controllers/general_controller_spec.rb
It looks as though this bug is only being triggered if someone has manipulated the url, although it might be an honest attempt to try different search params.
Toyed with adding a filter to attempt to repair the wildcard param `combined` if ".." had been incorrectly parsed as the start of a `format` param but it didn't seem to achieve anything useful for the user as it was no more likely to provide useful search results. 
FWIW, the filter code would have looked something like:
```rb
def fix_search_format
if params[:format] && params[:combined] && params[:combined][-1] == "."
params[:combined] = "#{params[:combined]}.#{params[:format]}/advanced"
request.format = :html
end
end
```
Closes #3319
=> Prevent search from crashing when format is nil

app/controllers/user_controller.rb, app/controllers/user_profile/about_me_controller.rb, app/models/about_me_validator.rb, app/models/user.rb, app/views/user/_show_user_info.html.erb, app/views/user_profile/about_me/edit.html.erb, config/routes.rb, doc/CHANGES.md, lib/user_spam_scorer.rb, spec/controllers/user_controller_spec.rb, spec/controllers/user_profile/about_me_controller_spec.rb, spec/lib/user_spam_scorer_spec.rb, spec/models/about_me_validator_spec.rb, spec/models/user_spec.rb
Fixes #3301 
Doesn't allow `User#about_me` updates if a non-whitelisted user looks like spam.
=> [#3301] Proactive spam checker

app/controllers/password_changes_controller.rb, spec/controllers/password_changes_controller_spec.rb
Can happen if the user went to /profile/change_password/new,
then logged out in another window, then submitted the form.
Closes #2927
=> Handle the case where there's no user and no email

config/routes.rb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/326
- `RequestGameController#stop` is only ever POSTed to
- `RequestGameController#play` accepts GET (for user display) and POST
(to shuffle requests)
=> [wdtk#326] Fix broken categorisation game routes

app/controllers/user_profile/about_me_controller.rb, spec/controllers/user_profile/about_me_controller_spec.rb
Fixes [#3382]
We've had a few examples of spammers submitting invalid params (just
`[:about_me]`, rather than `[:user][:about_me]` causing an undefined
method `[]' for nil:NilClass error.
This just redirects such requests to the user profile page. When we
upgrade to strong params, we can require the `:user` key and (I think)
remove this commit.
=> [#3382] Add temporary fix for invalid params

app/views/admin_public_body/import_csv.html.erb
Addition to #3355
Moves the help section below the form to make the actual input options clearer.
Move the "Standard tags" to a sidebar next to the help as the list can
get pretty long (see WDTK).
Minor rewording of the link to alaveteli.org documentation to be more
inline with Admin Censor Rules inline help.
=> [#3325] Improve layout of Public Body CSV Import

app/controllers/user_controller.rb, spec/controllers/user_controller_spec.rb
Fixes #3422
Prevents an ActiveModel::ForbiddenAttributes error.
=> [#3422] Fix sign in attempt with invalid email

app/controllers/followups_controller.rb, spec/controllers/followups_controller_spec.rb
Fixes #3423
Allow a followup when not explicitly replying to an incoming message.
=> [#3423] Fix creating a followup

app/assets/stylesheets/responsive/_lists_style.scss, app/assets/stylesheets/responsive/_sidebar_style.scss, app/views/request/_request_listing.html.erb, app/views/request/_request_listing_single_short.html.erb, app/views/request/_sidebar.html.erb
This makes the similar requests sidebar on the request page a lot neater, but removing some of the information presented 
Part of #3269
=> Redesigned sidebar list of requests

app/assets/javascripts/general.js, app/assets/stylesheets/responsive/_popups_layout.scss, app/assets/stylesheets/responsive/_popups_style.scss, app/assets/stylesheets/responsive/_request_layout.scss, app/assets/stylesheets/responsive/_request_style.scss, app/assets/stylesheets/responsive/_utils.scss, app/views/layouts/default.html.erb, app/views/request/_incoming_correspondence.html.erb, app/views/request/_outgoing_correspondence.html.erb, spec/fixtures/locale/en/app.po, spec/fixtures/locale/en_GB/app.po, spec/fixtures/locale/es/app.po
Part of #3269
Now uses a click to copy style method in the footer of each correspondence element
The form uses flexbox for the layout, but includes no fallback layout for browsers that don't support it. Instead the form is slightly more vertical. 
**TODO**
=> replaced the pop-up driven 'link to this widget'

Gemfile, Gemfile.lock, spec/spec_helper.rb
It doesn't work properly with RSpec 3 and it doesn't seem to be
maintained any more. Furthermore no one noticed it was broken after
upgrading to RSpec 3 so I guess it's not being used by the development
team. When Rails gets upgraded to Rails 4 then we can use Spring.
=> Remove Spork

app/assets/stylesheets/responsive/_request_layout.scss, app/assets/stylesheets/responsive/_request_style.scss, app/views/request/_bubble.html.erb, app/views/request/show.html.erb, spec/controllers/request_controller_spec.rb
Part of #3269 
This adds a redesigned attachments section to correspondence
(I can't add a screenshot atm due to poor wifi, but will shortly)
- Improve the handling of long lists of attachments by hiding lists longer than 3, with a 'reveal more' button
- Adds the HTML for a 'download all' attachments button (needs implementing)
todo:
=> Redesign attachments display

app/views/request/_incoming_correspondence.html.erb, app/views/request/_outgoing_correspondence.html.erb
Fixes #3434 
Also remove the pipe after incoming correspondence admin links because
its no longer needed now the old link-to-this icon has been removed.
=> [#3434] Add admin link to outgoing correspondence

Gemfile.lock
Related to https://github.com/mysociety/alaveteli/issues/3240
Version 1.1.0 doesn't eager load translation files.
This seems to make a good performance improvment for me: 
Before:
```
time bundle exec rake environment | sort
real    0m14.249s
user    0m11.801s
sys     0m1.209s
```
After: 
```
time bundle exec rake environment | sort
real    0m7.538s
user    0m5.479s
sys     0m1.128s
```
=> Upgrading fast_gettext.

app/views/request_game/play.html.erb
When rendered, these unclosed table cells create an extra cell. You
don't see this visually unless the table has borders or something.
I noticed this problem on Right To Know where table styles leaked in
from elsewhere recently.
This commit closes the <td> tags.
=> Close table cell tags

app/controllers/request_controller.rb, app/views/layouts/default.html.erb, app/views/request/show.html.erb, doc/CHANGES.md
Closes #3360. See also https://github.com/mysociety/whatdotheyknow-theme/pull/329
=> Track new requests as Google Analytics virtual pageviews.

app/controllers/request_controller.rb, spec/controllers/request_controller_spec.rb
Otherwise we'll override default values set in initialising the
object. Closes #3448
=> Only populate message attributes from non-nil params.

app/models/user.rb, spec/models/user_spec.rb
Note that destroying users is not available from the admin interface,
so the expected use case is from the command line. Fixes #3407.
=> Destroy associations when destroying user.

app/mailers/request_mailer.rb, app/views/request_mailer/stopped_responses.text.erb, spec/mailers/request_mailer_spec.rb
This could be a vector for distributing spam via backscatter.
Closes #2097
=> Don't include original mail in bounce messages

app/views/public_body/view_email_captcha.html.erb
You don't need to enter words with recaptcha any more so the sentence
was wrong. Since it's pretty self-explanatory now I've just removed the
sentence altogether.
=> Remove intro sentence on view public body email page

app/assets/stylesheets/responsive/_lists_style.scss, app/views/request/show.html.erb
This neatens up and redesigns the way request status appears around alaveteli.
Unfortunately, request states are too complex to adhere to the desired design #3269
=> Redesign request status messages

.travis.yml
This reverts commit 7fe278c99aa3b68651c85f27ad02cb4be69dc0d7.
We no longer support Ruby 1.8.7, so it doesn't seem to make sense to
downgrade rubygems any longer. We use rubygems 1.8.23 in production, so
this downgrade doesn't appear to be related to environment parity.
Fixes #3489.
=> Revert "Downgrade rubygems to 2.1.11"

docs/running/admin_manual.md
When I just tried these instruction my user didn't have an Otp secret
key. However I did find I could just click this link, which also seems
easier.
=> Fix instructions on logging in to change password when deleting a user

app/assets/stylesheets/responsive/_lists_layout.scss, app/assets/stylesheets/responsive/_lists_style.scss, app/views/public_body/_body_listing_single.html.erb, app/views/public_body/_search_ahead.html.erb, spec/controllers/public_body_controller_spec.rb, spec/views/public_body/list.html.erb_spec.rb
Fixes #3457 
- Removed 'date added'
- Moved 'make request' button out of result body to improve scannability
- Add some typographical hierarchy
TODO
to other data shown
=> improve display of authority list in search results

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, doc/CHANGES.md
This reverts commit bbe784558aa7ad437f8833b3f24d125658d38e63, reversing
changes made to d7637650d279f154b7040079be456341b6d7c8ae.
Debian Wheezy only has bundler 1.1.4 by default, which does not support
the `:ruby_20` platform symbol.
=> Revert "Merge branch 'better-errors' into develop"

lib/tasks/translation.rake
In the `translation:preview_emails` task, if your translated email text contains non-ascii characters, your preview ends up looking like this:
```
Description of email: Initial Request
Subject line: Liberté d'accès à l'information demande - The cost of boring
Date: Tue, 11 Oct 2016 15:32:16 +0000
From: Bob Smith <foi+request-105-abe9100b@alaveteli.10.10.10.30.xip.io>
To: =?UTF-8?B?TGliZXJ0w6kgZCdhY2PDqHMgw6AgbCdpbmZvcm1hdGlvbiBkZW1hbmRlcyDD?= =?UTF-8?B?oCBEZkg=?= <humpadink-requests@localhost>
Message-ID: <ogm-4+57fd05ff2695f-0ea8@alaveteli.10.10.10.30.xip.io>
Subject: =?UTF-8?Q?Libert=C3=A9_d'acc=C3=A8s_=C3=A0_l'information_demande_-?=
=?UTF-8?Q?_The_cost_of_boring?=
Mime-Version: 1.0
Content-Type: text/plain;
charset=UTF-8
Content-Transfer-Encoding: quoted-printable
How much was spent …
```
=> More readable previews of translated emails

lib/tasks/reindex.rake
Logs output - and errors, if there are any - to a separate log file - "reindex.log"
Example log file content:
```
run started... 2016-10-18 10:50:55 +0000
* queued batch ending: 909
* queued batch ending: 919
* queued batch ending: 929
reindex queuing complete!
```
(Purposely run with a BATCH_SIZE of 10 rather than 300 for testing purposes - test box only has 30 events.)
For https://github.com/mysociety/whatdotheyknow-theme/issues/344
=> Reindex events task

app/views/request/select_authorities.html.erb
Wasn't in a `content_for` tag so was getting loaded before its
dependencies.
Fixes https://github.com/mysociety/alaveteli/issues/3538.
=> [#3538] Fix broken select authorities javascript loading

doc/CHANGES.md, lib/user_spam_scorer.rb
=> [#3570] Add yopmail and yandex to default spam TLDs

.rspec
It was used by spork, which we don't use any more.
=> Remove drb argument from rspec

doc/CHANGES.md, lib/tasks/cleanup.rake
Useful if dealing with a spam attack.
Fixes #3579
=> [#3579] Add task to export last 2 days of requests

app/views/admin_public_body/edit.html.erb, app/views/admin_public_body/new.html.erb
Needs to get filled in for each locale, even if its identical. This is a
stopgap solution before we implement a default locale fallback.
See https://github.com/mysociety/alaveteli/issues/3134 for background.
=> [#3134] Add note to admin interface for multiple translations of request email

app/models/ability.rb, gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb, spec/models/ability_spec.rb, spec/spec_helper.rb
The title change is hopefully fairly simple and self explanatory, but there's
an aspect to the testing that I'd appreciate some other eyes on @crowbot /
@garethrees
Do the methods in AlaveteliFeatures::SpecHelpers seem like a good way to
enable/disable feature flags in specs?
In django there's a decorator for tests that lets you override settings, which
is kinda what I was going for here, but I'm not sure if there's a cleaner way
to do it?
=> Add a CanCan ability for accessing alaveteli pro

app/views/request/select_authority.html.erb, doc/CHANGES.md
Fixes https://github.com/mysociety/alaveteli/issues/3458
=> [#3458] Add required attribute to select authority form to prevent blank searches

app/controllers/alaveteli_pro/draft_info_requests_controller.rb, app/controllers/alaveteli_pro/info_requests_controller.rb, app/helpers/alaveteli_pro/info_requests_helper.rb, app/models/draft_info_request.rb, app/models/embargo.rb, app/models/info_request.rb, app/models/mail_server_log.rb, app/models/user.rb, app/views/alaveteli_pro/info_requests/_embargo_info.html, app/views/alaveteli_pro/info_requests/new.html.erb, app/views/alaveteli_pro/info_requests/preview.html.erb, config/routes.rb, db/migrate/20161116121007_create_draft_info_requests.rb, db/migrate/20161128095350_add_duration_to_embargo.rb, gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb, spec/controllers/alaveteli_pro/info_requests_controller_spec.rb, spec/factories/draft_info_requests.rb, spec/factories/embargos.rb, spec/factories/mail_server_logs.rb, spec/factories/users.rb, spec/integration/alaveteli_dsl.rb, spec/integration/alaveteli_pro/request_creation_spec.rb, spec/models/draft_info_request_spec.rb, spec/models/embargo_spec.rb, spec/models/info_request_spec.rb
So far I have:
- A draft request model
- A new request form
- A create action
- A "preview" page
- An edit form
- An update action
Next is the big question, what happens when we "send" the request.
You can see that I've tried to simplify the data model a bit by moving the
message body into the Draft, rather than creating an OutgoingMessage alongside
it. My working assumption was that next I'd add a method to InfoRequest called
`new_from_draft` or something similar. This could do the transfer of data,
make an outgoing message an so on. Alternatively, this could happen in a new
controller (we'll need one anyway, so it's maybe a moot point).
My main question is what happens with any validation errors. Right now both
the message and the request do some, so we'd need a way to combine that and …
=> Controller & Actions for Pro request process

app/controllers/comment_controller.rb, app/controllers/followups_controller.rb, app/controllers/help_controller.rb, app/controllers/reports_controller.rb, app/controllers/request_controller.rb, app/controllers/track_controller.rb, app/controllers/widget_votes_controller.rb, app/models/comment.rb, app/models/info_request/prominence/not_embargoed_query.rb, spec/controllers/admin_info_request_event_controller_spec.rb, spec/controllers/comment_controller_spec.rb, spec/controllers/followups_controller_spec.rb, spec/controllers/help_controller_spec.rb, spec/controllers/reports_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/controllers/track_controller_spec.rb, spec/controllers/widget_votes_controller_spec.rb, spec/factories/info_request_events.rb, spec/factories/info_requests.rb, spec/factories/track_things.rb, spec/integration/alaveteli_dsl.rb, spec/integration/incoming_mail_spec.rb, spec/integration/track_alerts_spec.rb, spec/models/info_request_event_spec.rb, spec/spec_helper.rb, spec/views/track_mailer/event_digest.text.erb_spec.rb
=> Issues/alaveteli pro 93/404 embargoed requests

app/controllers/track_controller.rb, config/routes.rb, spec/integration/search_request_spec.rb
Partially reverts eef48cb to restore the search tracking functionality
and fixes the bug in the way format was being evaluated in
`atom_feed_internal` so that it responds to JSON request appropriately
rather than defaulting to XML
Fixes #3517
=> Fix search tracking bug

app/assets/stylesheets/responsive/_lists_style.scss
Fixes https://github.com/mysociety/alaveteli/issues/3629
Delayed should be "pending" – not "failure" – given the icon is orange.
Also added line breaks to shared style selectors for clarity.
=> Match delayed status background with icon colour

app/controllers/alaveteli_pro/info_requests_controller.rb, app/controllers/application_controller.rb, app/controllers/request_controller.rb, spec/controllers/request_controller_spec.rb, spec/integration/alaveteli_pro/request_creation_spec.rb
Redirects the select_authority page (so that most links to make a request
work automatically for pros) and then the actual request form (in case anyone
has bookmarked the url or somehow gets direct linked to it). In the latter
case I've made sure that the selected public body is carried through too.
=> [Pro] Redirect pros to their request form from the non-pro process

app/models/statistics.rb, doc/CHANGES.md
For the axis labels prefer the body short name (full name appears in the
tooltip, and the HTML table), and truncate it if its still too long.
Fixes https://github.com/mysociety/alaveteli/issues/1485
Fixes https://github.com/mysociety/asktheeu-theme/issues/60
=> [#1485] Prevent body name overflowing on stats axis labels

app/mailers/request_mailer.rb, app/models/embargo.rb, spec/factories/embargos.rb, spec/mailers/request_mailer_spec.rb, spec/mailers/track_mailer_spec.rb, spec/models/embargo_spec.rb
I decided that some new specs were probably the easiest way to be sure of this
Todo:
So all but one of the alerts that goes to the requestor are still sent. It feels like we should be consistent here, perhaps sending reminders about new responses for now, until we have an alternative alerting system in place? (I've added a spec for this, which is currently failing)
=> [Pro] Check that scheduled emails are sent for embargoed requests

app/controllers/comment_controller.rb, app/controllers/followups_controller.rb, app/controllers/request_controller.rb, app/views/alaveteli_pro/comment/_suggestions.html.erb, app/views/alaveteli_pro/followups/_embargoed_form_title.html.erb, app/views/comment/_suggestions.html.erb, app/views/comment/new.html.erb, app/views/followups/_followup.html.erb, app/views/followups/_form_title.html.erb, app/views/request/show.html.erb, spec/controllers/comment_controller_spec.rb, spec/controllers/followups_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/integration/alaveteli_pro/view_request_spec.rb, spec/views/comment/new.html.erb_spec.rb, spec/views/followups/_followup.html.erb_spec.rb, spec/views/request/show.html.erb_spec.rb
embargoed request. This PR adjusts those where a pro user *should* be able to
do something to one of their embargoed requests so that they can.
Todo:
Questions:
for if you are not the request owner (rather than just 404/403ing the
request to follow up). Why is this? (It could simplify the code a fair
bit if we removed it and I can't see an obvious UX reason over just
hiding the follow up action from non-owners completely).
because everything is doing that slightly differently, it's hard to separate/generalise. 
For example, we  could just have a `can(:followup, request)` or `can(:annotate, request)`. The 
main issue is that each view reacts slightly differently to failures - sometimes it's a 403 page, 
other times a custom message, or a 404 for embargoed requests, etc. Does anyone have …
=> [Pro] Enable pro users to do things to embargoed requests

app/helpers/mailer_helper.rb, app/mailers/request_mailer.rb, config/general.yml-example, lib/configuration.rb, spec/mailers/request_mailer_spec.rb
This adds a new contact address/name for pro-specific contact, and then uses
this in the requires_admin mailer to send requests for admin attention on
embargoed requests to that address instead of the normal one.
Questions:
whether they're embargoed or not?
Closes mysociety/alaveteli-professional#116
=> [Pro] Send requests for admin attention to a separate email address

app/models/embargo.rb, spec/factories/embargos.rb, spec/models/embargo_spec.rb
Converting back from a Date to a DateTime on saving causes time zone
errors as Dates are not time zone aware.
=> [Pro] Use beginning_of_day (a DateTime) not today (a Date).

app/assets/javascripts/alaveteli_pro/authority_select.js, app/models/outgoing_message/template/initial_request.rb, app/views/alaveteli_pro/info_requests/new.html.erb, spec/models/outgoing_message/template/initial_request_spec.rb
This technically fixes mysociety/alaveteli-professional#133, however, it's a
bit of naive hack at the moment because to do this properly requires changing
how `OutgoingMessage` templates initial requests:
Right now, `OutgoingMessage::Template::InitialRequest` seems to require a public
body name in the list of replacements passed into it, so I've altered the
method that provides one to give a default string if there's no body.
This is a bit of a bug at the moment really, as the template looks like it's
trying to enforce the presence of a body name, but it's actually happy with
nil data being passed so long as the key is present (which gives a slightly
dud salutation in the message).
There are lots of methods involved in templating this message, but I *think*
the best way forward is to copy …
=> [Pro] Use translated strings for authority salutation

app/models/info_request.rb
These deprecations will go out in 0.27, so the methods need to
be removed in 0.28.
=> [Pro] Fix the release no. in which methods will be removed.

app/assets/stylesheets/responsive/_utils.scss, doc/CHANGES.md
Fixes #3646 
(This should probably be a hotfix when it grow up so we can roll it out to existing sites that have the new statistics page - although we could fix it in themes for now)
=> Force visually-hidden elements to act as block-level elements

app/controllers/help_controller.rb, app/mailers/application_mailer.rb, app/mailers/contact_mailer.rb, app/mailers/info_request_batch_mailer.rb, app/mailers/request_mailer.rb, app/mailers/track_mailer.rb, app/mailers/user_mailer.rb, config/general.yml-example, lib/configuration.rb, lib/mail_handler/reply_handler.rb, script/handle-mail-replies.rb, spec/controllers/help_controller_spec.rb, spec/fixtures/files/normal-contact-reply.email, spec/fixtures/files/pro-contact-reply.email, spec/lib/mail_handler/reply_handler_spec.rb, spec/mailers/contact_mailer_spec.rb, spec/script/handle-mail-replies_spec.rb
This combines mysociety/alaveteli-pro#75 mysociety/alaveteli-pro#138 and
mysociety/alaveteli-pro#140 into a single branch, since they're all related
and need each other to really work correctly.
This PR:
- Refactors bounce handling so that non-bounce replies to emails are sent to
two different addresses, one for replies from pro users and one for
everything else
- Adds a new contact address for pro user support
- Refactors all of the mailers to:
- Share Return-Path, Reply-To and other related header setting wherever
possible
- Be aware of the new pro contact address and use it when emailing pros
Closes mysociety/alaveteli-pro#75
Closes mysociety/alaveteli-pro#138
Closes mysociety/alaveteli-pro#140
=> [Pro] Site email handling for pro users

app/models/info_request.rb
This was added to app.po in 63055c52, but that is erased when updating translation files from Transifex.
This should persist.
=> Add translators' note for string which can't contain double quotes

config/initializers/alaveteli.rb, doc/CHANGES.md, lib/tasks/email_domain_actions.rake, lib/tasks/users.rake, lib/user_stats.rb, spec/lib/user_stats_spec.rb
Connects to #3651 
Contains 3 hopefully useful rake tasks...
Produces a top 20 (or fewer) table listing number of signups per domain based on email address
e.g.
```
" domain            |  count "
"------------------ | -------"
" gmail.com         |  332"
" hotmail.com       |  93"
" hotmail.co.uk     |  57"
" yahoo.co.uk       |  51"
" yahoo.com         |  50"
" webgarden.com     |  41"
" outlook.com       |  31"
```
Accepts optional ENV var `START_DATE` to limit scope (date range is inclusive)
Prints the total number of users and the percentage of spammers and dormant accounts for the required domain
e.g.
```
"total users: 5"
"     spam %: 40% (2)"
"  dormant %: 40% (2)"
```
Requires the ENV var `DOMAIN` (e.g. 'hotmail.com')
Accepts optional ENV var `START_DATE` to limit scope (date …
=> Add some rake tasks for dealing with users on a per domain basis

app/models/info_request.rb, doc/CHANGES.md, spec/models/info_request_spec.rb
* Drops the string length limit for mixed case to be applied
* Adds a minimum length requirement of ~~4~~ 3 characters
* Allows mixed case exemptions for:
* all upper case, single word strings of less than 6 chars (on the grounds that they're probably an acronym)
* a multiword string starting with a number 
Fixes #3653
=> Prevent info requests with titles such as "re"

app/assets/stylesheets/responsive/_print_layout.scss, app/assets/stylesheets/responsive/_print_style.scss, doc/CHANGES.md
Before / After:
EDIT: ^ Actually that's not quite true, in that there's a bug in core (https://github.com/mysociety/alaveteli/issues/3733) which is affecting layout that I'm looking in to. Those are from wdtk-theme.
Fixes https://github.com/mysociety/alaveteli/issues/3733
Fixes https://github.com/mysociety/alaveteli/issues/3102
=> Hide admin nav in PDF download

app/controllers/outgoing_messages/delivery_statuses_controller.rb, app/models/mail_server_log.rb, app/models/outgoing_message.rb, doc/CHANGES.md, spec/controllers/outgoing_messages/delivery_statuses_controller_spec.rb, spec/models/mail_server_log_spec.rb, spec/models/outgoing_message_spec.rb
RE: https://github.com/mysociety/sysadmin/issues/799
Measures to handle WDTK move to using a smarthost for outgoing mail.
This PR gets us to the point of being able to switch over to `/var/log/all_servers_mail.log*`. When we change the config flag, we'll also need to create `MailServerLogDone` records with the same filename and `last_stat` as the most recent `all_servers_mail.log` files so that we don't try to ingest logs that we've effectively already got.
When we switch over, we'll end up importing some duplicate lines.
```sh
$ ls /var/log/exim4/exim-mainlog-* | sort | tail -3
/var/log/exim4/exim-mainlog-20170208.gz
/var/log/exim4/exim-mainlog-20170209.gz
/var/log/exim4/exim-mainlog-20170210                 # This is the last file imported
$ ls /var/log/all_servers_mail.log* | sort | …
```
=> New mail log parsing

spec/integration/alaveteli_dsl.rb, spec/integration/alaveteli_pro/request_creation_spec.rb, spec/integration/create_request_spec.rb
Should solve transient CI failures where public body not found
when creating request. The cause of this is the body not being in
the xapian index (depending on what other specs have previously
run). So, we're now passing the public body to the create_request
method, and updating the xapian index to ensure it's there.
Change body name, as since 9f1fe3ca, searching for a name with
fewer than 3 characters in the last word causes zero results to
be returned.
=> Pass public body when calling create_request, update xapian index

app/controllers/request_controller.rb, doc/CHANGES.md, spec/controllers/request_controller_spec.rb
Fixes #3740
~~WIP because I've attempted to add a spec for this, but I just can't get it to pass, even though the problem is fixed by the code changes. Maybe with some fresh eyes I can figure it out…~~
The "state transition variables" were not set, causing the describe
state form to get rendered without any state transitions.
When downloading a Zip, `@transitions` is nil, causing an `undefined
method `[]' for nil:NilClass`, so I've added a `nil` check in
`state_transitions_empty?`.
~~Then called `assign_state_transition_variables` so that the describe
state form isn't rendered when rendering the PDF.~~
Then set instance variables in `assign_variables_for_show_template` so
that we don't render the describe state form at all when rendering to file.
I've tidied up the setting of some of …
=> [#3740] Fix ZIP download of unclassified requests

app/models/mail_server_log.rb, app/models/outgoing_message.rb, spec/models/outgoing_message_spec.rb
e.g:
2014-03-25 15:35:55 [3721] 1WSTOA-0000xz-JF == #{ body_email }
R=dnslookup T=remote_smtp defer (-44): SMTP error from remote mail
server after RCPT TO:<#{ body_email }>: host
mx.core.canterbury.ac.uk [127.0.0.1]: 451-127.0.0.2 is not yet
authorized to deliver mail from\\n451-<#{ request_email }> to <#{
body_email }>.\\n451 Please try later.
=> Handle log lines where a delivery status can't be parsed

app/assets/javascripts/alaveteli_pro/authority_select.js, app/assets/javascripts/alaveteli_pro/selectize.js, app/assets/stylesheets/responsive/alaveteli_pro/_request_form_style.scss, app/assets/stylesheets/responsive/all.scss, app/controllers/alaveteli_pro/public_bodies_controller.rb, app/controllers/request_controller.rb, app/helpers/alaveteli_pro/info_requests_helper.rb, app/views/alaveteli_pro/info_requests/new.html.erb, app/views/general/_nav_items.html.erb, app/views/public_body/_search_ahead.html.erb, app/views/request/select_authority.html.erb, config/routes.rb, spec/controllers/alaveteli_pro/public_bodies_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/integration/alaveteli_dsl.rb, spec/integration/alaveteli_pro/request_creation_spec.rb, spec/views/alaveteli_pro/info_requests/new.html.erb_spec.rb
Rather than dumping all the bodies into a select box, this turns the To field
back into a basic text box, then uses selectize's ability to load data from a
remote source via ajax to query xapian for results instead.
For non-js users, the same text box can be used to submit a query into the
existing select_authority page, presenting that in a pro livery and allowing
pagination/searching etc to take place before redirecting the user back into
the pro form with the body selected.
Closes mysociety/alaveteli-professional#159
=> [Pro] Update pro authority selecting js to search via xapian

app/models/info_request/state/calculator.rb, app/views/alaveteli_pro/info_requests/_info_request.html.erb, spec/models/info_request/state/calculator_spec.rb
This adds the overdue versions of the waiting_response status to the phase
calculator.
Fixes mysociety/alaveteli-professional#149
=> [Pro] Fix missing states in Phase calculations

app/views/alaveteli_pro/info_requests/new.html.erb, spec/integration/alaveteli_dsl.rb, spec/integration/alaveteli_pro/request_creation_spec.rb
Makes it clearer that this is going to be the subject line of the
email.
=> Replace "Summary" with "Subject".

app/views/alaveteli_pro/general/_log_in_bar_links.html.erb, app/views/general/_log_in_bar.html.erb, lib/alaveteli_pro/post_redirect_handler.rb, spec/factories/post_redirects.rb, spec/lib/alaveteli_pro/post_redirect_handler_spec.rb, spec/views/general/_log_in_bar.html.erb_spec.rb
Pro logins could end up trying to redirect to the "Make a request" page for
pros when the PostRedirect wasn't really for that page, because the regex that
tried to match urls wasn't specific enough.
Similarly, post redirects could end up getting saved that caused problems when
a pro user logged out, because signing out of a pro page set a redirect path
back in to the pro area, which an anonymous user couldn't follow.
For mysociety/alaveteli-professional#196
For mysociety/alaveteli-professional#134
=> [pro] Fix issues with signing in and out as a pro

app/controllers/help_controller.rb, spec/controllers/help_controller_spec.rb
I've got two approaches here which I'd like some feedback on @crowbot / @garethrees
The main issue is that when you visit the help form the controller searches
for a `last_request_id` in your cookies and adds this to the context if it
can find it. In f43d64533065272974412c0ab1d51f88baea738b @crowbot limited this
lookup to non-embargoed requests, but now we let pros view requests too
(through the same controller as other requests). Therefore, when you try to
send a help message as a pro who last viewed an embargoed request, you get a 404.
My first thought was to make this lookup a bit smarter:
21a0965dcd1b0de139dc56eefae0fafa1ecd0e28 and ad032e4bf377aeea30151006e5b040b126cd8ac8
add a new scope to InfoRequest that looks up any request the pro user can access,
embargoed or not.
However, this …
=> [Pro] - WIP - Stop contact form raising a 404 for pros with an embargoed last_request_id

lib/tasks/export.rake
So that we can rescue any Exception to ensure the run finishes
(with a view to examining the error output afterwards)
At least 2 examples of bad practice in here - worth considering refactor once we've proved whether it's useful
Connects to #3734
=> Rescue all the research_export errors and only output redacted data

lib/tasks/export.rake
Allow `CUTOFF_DATE` and `MODELS`to be passed in to the research_export task to manually specify a cutoff date (rather than just allow it to pick the current date at the start of the run) and to allow reports for one or more specified models to be produced rather than needing to complete the entire run each time.
(I've tested the new features locally and they seem to work)
example usage:
* `bundle exec rake export:research_export MODELS="OutgoingMessage,FoiAttachment"`
* `bundle exec rake export:research_export MODELS="OutgoingMessage" CUTOFF_DATE="2008-01-01"`
Connects to #3734
=> Improve export task

app/assets/javascripts/alaveteli_pro/authority_select.js, app/assets/stylesheets/responsive/alaveteli_pro/_new_request_style.scss, app/controllers/alaveteli_pro/public_bodies_controller.rb, app/views/alaveteli_pro/info_requests/new.html.erb, app/views/alaveteli_pro/public_bodies/_search_result.html.erb, spec/controllers/alaveteli_pro/public_bodies_controller_spec.rb, spec/views/alaveteli_pro/public_bodies/_search_result.html.erb_spec.rb
Because we need to translate body names and other text in our search results,
as well as pluralise things like request counts. This moves the HTML rendering
for each search result into a Rails view, passing it to the javascript in the
existing JSON we return.
On my dev box, this is noticeably slower than the previous version. Can anyone
shed any light on why that might be? Looking at the times reported by the
dev server in the console, there's nothing obvious (all the db/xapian stuff is
unchanged and the new partial view rendering seems to run very quickly).
For mysociety/alaveteli-professional#155
=> [Pro] Render authority search results in rails instead of JS

lib/tasks/stats.rake
=> Rails 4 - fixup `.includes` join references

app/assets/stylesheets/responsive/_global_style.scss, app/assets/stylesheets/responsive/alaveteli_pro/_new_request_layout.scss, app/controllers/alaveteli_pro/embargo_extensions_controller.rb, app/mailers/alaveteli_pro/embargo_mailer.rb, app/models/alaveteli_pro/activity_list/embargo_expiry.rb, app/models/alaveteli_pro/request_filter.rb, app/models/alaveteli_pro/to_do_list/expiring_embargo.rb, app/views/alaveteli_pro/comment/_suggestions.html.erb, app/views/alaveteli_pro/embargo_mailer/expiring_alert.text.erb, app/views/alaveteli_pro/followups/_embargoed_form_title.html.erb, app/views/alaveteli_pro/info_requests/_draft_info_request.html.erb, app/views/alaveteli_pro/info_requests/_embargo_info.html.erb, app/views/alaveteli_pro/info_requests/_info_request.html.erb, app/views/alaveteli_pro/info_requests/_sidebar.html.erb, app/views/alaveteli_pro/info_requests/new.html.erb, config/general.yml-example, lib/configuration.rb, spec/controllers/alaveteli_pro/embargo_extensions_controller_spec.rb, spec/integration/alaveteli_dsl.rb, spec/integration/alaveteli_pro/request_creation_spec.rb, spec/integration/alaveteli_pro/view_request_spec.rb, spec/mailers/alaveteli_pro/embargo_mailer_spec.rb, spec/models/alaveteli_pro/activity_list/embargo_expiry_spec.rb, spec/models/alaveteli_pro/request_filter_spec.rb, spec/models/alaveteli_pro/to_do_list/expiring_embargo_spec.rb, spec/views/comment/new.html.erb_spec.rb
- Embargo becomes 'privacy period'
- Embargo (speaking of the feature) becomes 'privacy'
Does not change any of the logic, where it is still known as embargo.
(this does not update any tests - as we've not decided this should be the change yet)
=> [Pro] Rename 'Embargo' in the user interface to 'privacy'

app/assets/javascripts/alaveteli_pro/alaveteli_pro.js, app/assets/javascripts/alaveteli_pro/embargo_dropdown.js, app/assets/stylesheets/responsive/alaveteli_pro/_sidebar_style.scss, app/assets/stylesheets/responsive/all.scss, app/controllers/alaveteli_pro/embargo_extensions_controller.rb, app/helpers/alaveteli_pro/info_requests_helper.rb, app/views/alaveteli_pro/info_requests/_embargo_info.html.erb, app/views/alaveteli_pro/info_requests/_sidebar.html.erb, spec/controllers/alaveteli_pro/embargo_extensions_controller_spec.rb
Submits the form automatically on selection of an extension, and updates the
displayed expiry text immediately.
Also fixes a missed usage of the old unfriendly expiry dates in a flash message
For mysociety/alaveteli-professional#120
=> [Pro] Javascript up the embargo extension form

app/controllers/comment_controller.rb, spec/controllers/comment_controller_spec.rb
#2968 – Prevents the original comment being overwritten with a new blank one when moving from Preview back to New
=> Prevent re-edited comment from being erased

config/initializers/alaveteli.rb, lib/patch_tag_helper.rb, spec/lib/patch_tag_helper_spec.rb
The affected code is in a different file in 4.0 to 4.2 but it's still `ActionView::Helpers::TagHelper` so it mostly works as-is. Needed to patch `ERB::Util` as well to include the `unwrapped_html_escape` method and `HTML_ESCAPE_REGEXP`
Connects to #2968
=> [#2968] Include security fix for CVE-2016-6316

app/controllers/help_controller.rb
Related to #2968.
The "Rails 3" version doesn't actually produce deprecation warnings, but
`find_by()` seems to be the preferred Rails 4 style. The SQL is exactly
the same:
request = InfoRequest.find_by_id('1016'.to_i)
InfoRequest Load (1.4ms) SELECT "info_requests".* FROM "info_requests" WHERE
"info_requests"."id" = 1016 LIMIT 1
request = InfoRequest.find_by(id: '1016'.to_i)
InfoRequest Load (0.9ms)  SELECT "info_requests".* FROM "info_requests" WHERE
"info_requests"."id" = 1016 LIMIT 1
=> [#2968] Remove Rails 3 code

config/environments/development.rb
Related to #2968 and #3809.
Assets are served as separate files in the order they are specified in the
manifest file when `assets.debug` is `true`.
This commit sets the default to `false` for better performance.
To enable, simply restart the Rails server with `ASSETS_DEBUG=1`.
See more at
http://guides.rubyonrails.org/v4.0/asset_pipeline.html#turning-debugging-off
=> [#2968] Allow assets.debug config to be controlled by ENV

config/routes.rb, spec/controllers/request_controller_spec.rb
This is used in the absence of javascript. Fixes #3789
=> Allow POST-ing to the select_authorities action.

Gemfile, Gemfile.lock, doc/CHANGES.md, spec/controllers/request_controller_spec.rb, spec/spec_helper.rb
This removes the test unit gem. A few notes:
- Having test_unit in the gemfile causes an issue with negating rspec's
render_template matcher as described in the commit message.
- Nothing in alaveteli uses test-unit, but commonlib does and recommends that
you [run it's specs from within the including project](https://github.com/mysociety/commonlib/blob/master/rblib/tests/README). We need to decide if
we care about that, and what to do about it if we do.
- We'll need to check that re-users aren't using test-unit in their themes
For #3228
=> [#3228] Remove test-unit

doc/CHANGES.md, lib/alaveteli_text_masker.rb, spec/lib/alaveteli_text_masker_spec.rb
The tests break a few rules but I wanted to be really sure about what arguments `AlaveteliExternalCommand` was going to run with
Closes #3766
=> Limit pdftk to 512MB of RAM

app/views/followups/_followup.html.erb, doc/CHANGES.md
Discovered while working on the Belgian site, we are accidentally imposing a UK-centric "more information" link on everyone. This links to `help/unhappy#internal_review` (already a required section) instead
Related to #2665
=> Make info link for internal reviews a help page section

app/assets/stylesheets/responsive/_request_style.scss, app/controllers/admin_comment_controller.rb, app/controllers/admin_general_controller.rb, app/controllers/reports_controller.rb, app/helpers/admin_helper.rb, app/models/comment.rb, app/models/info_request_event.rb, app/views/admin_comment/_params.html.erb, app/views/admin_comment/edit.html.erb, app/views/admin_general/index.html.erb, app/views/comment/_single_comment.html.erb, app/views/reports/new.html.erb, db/migrate/20170216101547_add_attention_requested_to_comment.rb, doc/CHANGES.md, spec/controllers/admin_comment_controller_spec.rb, spec/controllers/reports_controller_spec.rb, spec/helpers/admin_helper_spec.rb, spec/integration/reports_controller_spec.rb, spec/models/comment_spec.rb, spec/models/info_request_event_spec.rb, spec/views/reports/new.erb_spec.rb
Fixes #3645 
Supersedes https://github.com/mysociety/alaveteli/pull/3694
@lizconlan I've reworked #3694 a bit. The main problem was that some of the original commits changed unrelated code in the same commit, and then that was compounded by the fixup commits doing similar and not applying cleanly. This made it really tricky to review, so I decided to go through the code and make new commits as I went.
I've left fixups in place where I could to illustrate changes, but worth checking through everything.
The final diff was good. I've made a few minor changes along the way, so would be good to get your comments on:
- Make the actions in `ReportsController` 404 if you pass an invalid `comment_id`. This seemed to make the behaviour more predictable (rather than e.g. ignoring the comment param, …
=> [#3645] Report comments

doc/CHANGES.md, lib/alaveteli_text_masker.rb, spec/lib/alaveteli_text_masker_spec.rb
This reverts commit 5ea8a2a29bb4102b6e6cf74c6b7b5fc3447caf45.
=> Revert "Limit pdftk to 512MB of RAM"

app/controllers/reports_controller.rb, spec/controllers/reports_controller_spec.rb
The form always posts a comment_id because of the hidden field. Ignore
it if its empty, otherwise a `RecordNotFound` is raised when reporting
requests.
Fixes https://github.com/mysociety/alaveteli/issues/3871
=> [#3871] Ignore empty comment_id param

app/assets/javascripts/alaveteli_pro/batch_authority_search/pagination.js
I've scoped the selector used to find pagination links to one of the special
`.js-*` classes we wrap the search results in.
Fixes #3874
=> Fix #3874 - pagination links being disabled by pro batch js

doc/CHANGES.md, script/install-as-user
Rails 4.0.13 depends on bundler < 2.0, >= 1.3.0.
Wheezy installs 1.1.4, so update it through rubygems if we find that
version installed.
Fixes #3850
=> [#3850] Update bundler if its too old

app/controllers/admin_outgoing_message_controller.rb, app/views/admin_outgoing_message/edit.html.erb, app/views/admin_request/show.html.erb, doc/CHANGES.md, spec/controllers/admin_outgoing_message_controller_spec.rb
Fixes #3781 
[Here's a demo](https://gist.github.com/garethrees/b38b5cfa8236c3ca1f84aecf09d20602) that you can run in the rails console to see how deleting an outgoing message is fine, as long as it doesn't belong to the `last_event_forming_initial_request`.
=> [#3781] Prevent destroying initial outgoing message

Gemfile, Gemfile.lock
This installs the latest version of pry (that is also supported by
pry-debugger) on all platforms under the test and development groups for
handy debugging.
=> Install pry

app/models/mail_server_log.rb, doc/CHANGES.md, spec/models/mail_server_log_spec.rb
The original spec wasn’t catching a breakage for existing records
because the fallback serialisation was happening when creating the
factory.
* Create the record to ensure the spec is loading from the database.
* Use update_attribute to set an invalid delivery_status, so that no
validation or serialisation is run.
* Add a spec to test that it persists the MTA-agnostic value after
recalculating. Uses some hacky code to pull out the serialised value,
but I can’t find a better way of getting this.
* Add a warning when parsing an invalid cached status is rescued to
remind maintainers to update their caches. Don’t display in Rails’
test env as we’re explicitly testing this behaviour.
* Update changelog upgrade notes.
=> Fix handling cached MTA-specific statuses

app/models/mail_server_log.rb, spec/models/mail_server_log_spec.rb
Because we're calling #save after rescuing from an ArgumentError,
delivery_status was returning true instead of the delivery status.
Use the serialiser after this to ensure the DeliveryStatus is loaded.
This was missed because even `#update_attribute` does weird things with the
serialiser, so set the value manually with SQL.
Also tidy up the happy-path so that set_delivery_status is only called
if the delivery_status attribute is not present for a bit clearer code.
=> Further fix for MailServerLog#delivery_status

app/assets/stylesheets/responsive/_new_request_layout.scss
Hi 
Request preview in the current framework of Alaveteli has the text of the class `correspondence_text` out of line and looked something like this in the website of WhatDoTheyKnow: 
This was also visible in the current development copy of RightToKnow as currently pointed in one of their [issues](https://github.com/openaustralia/righttoknow/issues/670)
*Correction Made:*
Removed the left padding of the class and now it is in line with the subject and the title and looks like this in the theme of RightToKnow: 
This resolves the [issue](https://github.com/openaustralia/righttoknow/issues/670) of RightToKnow of OpenAustralia Foundation and would also improve the formatting of "Preview Your Request" of WhatDoTheyKnow after merging upstream changes.
=> Corrected formatting of Preview Your Request

app/models/info_request.rb, doc/CHANGES.md, lib/tasks/temp.rake, spec/models/info_request_spec.rb
=> [#3827] Prevent line breaks in request titles 

app/assets/javascripts/alaveteli_pro/alaveteli_pro.js, app/assets/javascripts/alaveteli_pro/draft_batch_summary/write-button.js, app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb, app/controllers/alaveteli_pro/info_request_batches_controller.rb, app/models/alaveteli_pro/draft_info_request_batch.rb, app/models/info_request_batch.rb, app/views/alaveteli_pro/batch_request_authority_searches/new.html.erb, app/views/alaveteli_pro/info_request_batches/_authority_list.html.erb, app/views/alaveteli_pro/info_request_batches/_form.html.erb, app/views/alaveteli_pro/info_request_batches/_message_preview.html.erb, app/views/alaveteli_pro/info_requests/_form.html.erb, app/views/alaveteli_pro/info_requests/_message_preview.html.erb, app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb, app/views/alaveteli_pro/info_requests/new.html.erb, app/views/alaveteli_pro/info_requests/preview.html.erb, app/views/request/_email_override_warning.html.erb, app/views/request/new.html.erb, config/routes.rb, db/migrate/20170323165519_add_embargo_duration_to_draft_info_request_batch.rb, db/migrate/20170328100359_add_embargo_duration_to_info_request_batch.rb, spec/controllers/alaveteli_pro/draft_info_request_batches_controller_spec.rb, spec/controllers/alaveteli_pro/info_request_batches_controller_spec.rb, spec/factories/alaveteli_pro/draft_info_request_batches.rb, spec/factories/info_request_batches.rb, spec/integration/alaveteli_dsl.rb, spec/integration/alaveteli_pro/batch_request_spec.rb, spec/integration/alaveteli_pro/request_creation_spec.rb, spec/models/alaveteli_pro/draft_info_request_batch_spec.rb, spec/models/info_request_batch_spec.rb, spec/support/xapian_index.rb
This adds some new routes and controllers to allow us to write batch requests,
save them as drafts and preview them in a similar way to normal requests.
There are a couple of tweaks to the existing authority picking page to enable
this, as well as generalisation of the new/preview views for pro request
writing.
The main thing I'm not totally happy with it the use of the outgoing message templates in the draft request, as it seems like something that might trip up someone who makes future changes to the templates?
=> [Pro] Batch request message writing

lib/data_export.rb, lib/tasks/export.rake, spec/lib/data_export_spec.rb
* Removes the InfoRequest body from the report as it can be retrieved via the matching InfoRequest content (by matching its `id` field to  `info_request_batch_id` in the InfoRequest data) instead (and there's currently no means of applying censor rules - that I can see - to the body data)
* Applies the cutoff date to the InfoRequest batch table
* Includes authority names
* Calls the correct methods on IncomingMessage to retrieve the body content
* Rough refactor to use a lib file (more improvements possible but out of scope here)
* Tested(:tada:) exclusion of embargoed requests
Fixes #3801
Fixes #3803 
Fixes #3852
=> Improve research export task

app/controllers/alaveteli_pro/base_controller.rb, app/controllers/application_controller.rb, app/controllers/comment_controller.rb, app/controllers/followups_controller.rb, app/controllers/info_request_batch_controller.rb, app/controllers/request_controller.rb, app/models/ability.rb, spec/controllers/info_request_batch_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/factories/info_request_batches.rb, spec/factories/info_requests.rb, spec/models/ability_spec.rb
This PR adds a few things:
- Redirecting of embargoed batch requests to the pro version and non-embargoed
requests which are requested in the pro version back to the public
- Access control via CanCanCan so that only pros and pro admins can access an
embargoed batch
- Changes to the listing of requests in a batch, so that embargoed requests
are included when they should be.
There's a couple of caveats to this which we'll need to think about or address
in further work:
1. We're assuming that a batch's embargo status represents the whole set of
requests in it, so users shouldn't be able to selectively embargo or
publish requests inside it. That's not true at the moment, as they can do
the latter. I think perhaps we should enforce this by adding a sidebar to
this batch show page with embargo …
=> [Pro] Control access to embargoed batch requests

doc/CHANGES.md, lib/tasks/users.rake
With this amendment, the output would have been:
```
$ bundle exec rake users:ban_by_domain DOMAIN="webgarden.com"
"total users: 375"
"   banned %: 303 (80.8%)"
"  dormant %: 374 (99.73%)"
""
"Do you want to ban all the non-admin users for webgarden.com(y/N)"
y
"72 accounts banned"
```
(Also banned users would have been told "Banned for spamming" rather than "Hey, this is why we thought you were spam")
Fixes #3892
=> [#3892] Better domain stats

app/views/request_mailer/stopped_responses.text.erb, doc/CHANGES.md, spec/views/request_mailer/stopped_responses.text.erb_spec.rb
Fixes #3843 
Test by:
- Set info request to no replies
```ruby
InfoRequest.find(108).update_attributes(:allow_new_responses_from => 'nobody')
```
- Send a message to its request email
```
cat << EOF | script/mailin
From: "FOI Person" <foiperson@localhost>
To: "Bob Smith" <foi+request-108-86900a32@localhost>
Date: Thur, 6 Apr 2017 17:19:55 +0000
Subject: Reply to FOI
Testing bounce reply
EOF
```
- Look at the last message in the log
```
tail -n 30 log/development.log
```
Expected snippets:
```
…sent to Robin Houston <foi+request-108-86900a32@localhost> to…
```
```
…to ask us to reopen the request. You can then resend the response.
```
=> [#3843] tweak authority bounce message

app/views/alaveteli_pro/general/_nav_items.html.erb
Not totally obvious what the right thing to do for the user's public requests is here - should they highlight the 'browse public requests' tab, or the 'requests' tab, as in this PR?
=> [Pro] When viewing individual pro requests, highlight the 'requests' tab.

Gemfile.lock
Work on #3799
Rebased our changes on to the current master (1.8.0).
Note thats strip_attributes has not been supporting Ruby 1.9.x since 1.6.0:
https://github.com/rmm5t/strip_attributes/commit/2793e00d3c4695abad805679ccedf41956e89e96
=> [#3799] Update strip_attributes

app/views/public_body/_more_info.html.erb, config/routes.rb, doc/CHANGES.md, spec/integration/public_body_change_request_spec.rb
This allows the public body `url_name` to be part of the url rather than
relying on a querystring param as the param is not persisted if the
user clicks on the sign in link before filling in the form
(Saner than trying to persist the `url_name` via sessions through the login - it's a click to login rather than a forced redirect via `authenticated?` so the usual `PostRedirect` trick isn't available.) 
Fixes #3816
=> Add a new route for change requests to existing public bodies

Gemfile, Gemfile.lock
Using a branch makes updating the fork from the upstream repo really difficult.
If you rebase globalize3 on upstream/master and force push, you lose the
previous SHA, so old versions become uninstallable.
=> Install strip_attributes from git ref

app/views/admin_general/index.html.erb
Using `#inspect` was causing the following error on IPV:
An I18n::InvalidLocale occurred in admin_general#index:
:en is not a valid locale
app/views/admin_general/index.html.erb:203:in `_app_views_admin_general_index_html_erb___4193968884139696355_74739300'
app/controllers/application_controller.rb:113:in `record_memory'
lib/strip_empty_sessions.rb:13:in `call'
Wrapped in a `with_locale` block so that it uses English if possible;
otherwise it reverts to the default locale. I think the error above must
be caused by Rails trying to default to `:en` when it isn't a configured
locale.
=> Use helper to display distance of time

app/models/outgoing_message.rb, doc/CHANGES.md, spec/models/outgoing_message_spec.rb
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/392.
Syslog prefixes the exim log line with date, hostname and process info,
so shifted the exim message id from the 4th element to the 9th after
splitting on whitespace.
The message id is a consistent format [1] so we can parse it out
reliably with a regex.
* The first `#compact` makes sure that we're not trying to match against
`nil` values.
* The second `#compact` makes sure that no `nil` values are returned if
a message id was not found.
[1]
http://www.exim.org/exim-html-current/doc/html/spec_html/ch-how_exim_receives_and_delivers_mail.html#SECTmessiden
=> [#wdtk-392] Parse correct MTA ID from syslog-format logs

app/models/mail_server_log.rb, doc/CHANGES.md, spec/models/mail_server_log_spec.rb
Fixes a bug where the prefix isn't stripped when the line ends in a
newline.
=> Strip syslog prefix when line ends in newline

app/models/mail_server_log/delivery_status.rb, app/models/mail_server_log/delivery_status/translated_constants.rb, app/views/request/_outgoing_correspondence.html.erb, doc/CHANGES.md, spec/fixtures/locale/en/app.po, spec/fixtures/locale/en_GB/app.po, spec/fixtures/locale/es/app.po, spec/models/mail_server_log/delivery_status_spec.rb
Fixes #3908 
```diff
diff --git a/locale/es/app.po b/locale/es/app.po
index a27a9ac..2e0057b 100644
--- a/locale/es/app.po
+++ b/locale/es/app.po
@@ -4688,3 +4688,6 @@ msgstr "{{user}} hizo esta solicitud de {{law_used_full}}"
msgid "« Back to search results"
msgstr "Volver a los resultados de tu búsqueda"
+
+msgid "unknown"
+msgstr "desconocido"
```
=> [##3908] Allow translation of delivery statuses

doc/CHANGES.md, spec/controllers/public_body_controller_spec.rb, spec/fixtures/public_body_categories.yml, spec/fixtures/public_body_category_links.yml, spec/fixtures/public_body_category_translations.yml, spec/fixtures/public_body_heading_translations.yml, spec/fixtures/public_body_headings.yml, spec/models/public_body_heading_spec.rb, spec/spec_helper.rb
Forever creating these after recreating dev database, so add some
fixtures so that they get created in load-sample-data.
Destroy fixtures for specs that rely on exact counts, or specific
records existing.
=> Add sample public body headings and categories

Vagrantfile
`export ALAVETELI_VAGRANT_USE_NFS=true` will turn on vagrant's NFS support for
shared folders, which I find a noticeable speedup over the original settings.
=> Allow NFS to be used in vagrant if you specify an env variable

app/controllers/request_controller.rb
0dd537e rendered the HTML as plain text. Need to explicitly make the
String html_safe so that it will render as HTML.
Fixes https://github.com/mysociety/alaveteli/issues/3972.
=> [#3972] Fix broken rendering of get_attachment_as_html

spec/integration/alaveteli_pro/batch_request_spec.rb
This test doesn't seem to require an explicit order, so use match_array
to prevent transient failures.
=> Use match_array to prevent transient failure

app/assets/stylesheets/responsive/_lists_style.scss, app/views/public_body/_list_sidebar_extra.html.erb
The extra items blur in to the category lists above. This adds a subtle
border to differentiate the sections.
Closes #3941.
=> [#3941] Make sidebar extra items more obvious

app/views/general/_responsive_header.html.erb, app/views/layouts/admin.html.erb, app/views/layouts/default.html.erb, app/views/layouts/no_chrome.html.erb
Since Rails 4.1 flash messages have been preventing HTML rendering. This
always renders the flash without escaping tags. We should ensure that
all user input is escaped before adding it to the flash.
Fixes #3971
=> [#3971] Always render HTML in flash messages

app/models/info_request_batch.rb
Seems like it might be helpful to have the bodies in a default alphabetical order, and also should fix test failures like https://travis-ci.org/mysociety/alaveteli/jobs/232363981.
=> Add an alphabetical order on public bodies in an info request batch.

app/mailers/alaveteli_pro/embargo_mailer.rb, app/mailers/request_mailer.rb, app/models/info_request.rb, app/models/role.rb, db/migrate/20170509210708_add_use_notifications_to_info_request.rb, db/seeds.rb, doc/CHANGES.md, lib/tasks/temp.rake, spec/factories/info_requests.rb, spec/factories/users.rb, spec/fixtures/info_requests.yml, spec/mailers/alaveteli_pro/embargo_mailer_spec.rb, spec/mailers/request_mailer_spec.rb, spec/models/info_request_spec.rb, spec/models/role_spec.rb, spec/models/user_spec.rb
Step one of #216, this adds a new `use_notifications` field to InfoRequest, a
new role `notifications_tester` and then sets `use_notifications` to true on
requests in notifications testers' batches.
Each type of basic request notification/reminder email is then disabled for
requests where use_notifications is true.
Requires a migration, a run of `rake db:seed` and a run of
`rake temp:set_use_notifications` to initialise it to `false` on all existing
requests.
For mysociety/alaveteli-professional#272
=> [Pro] Add a use_notifications flag and disable emails for requests with it

gems/alaveteli_features/lib/alaveteli_features.rb
As the commit comment says, this is a more robust test for whether the feature
flags should use the db to store feature state. The current method isn't
working on the live site currently, as @garethrees noticed in the logs this
morning.
=> Test for feature flipping db tables better

app/mailers/request_mailer.rb, spec/mailers/request_mailer_spec.rb
This should hopefully fix the issue with pro users not getting a login prompt
for new responses on their embargoed requests. I didn't limit it to embargoed
requests only because I wanted to ensure pros always get the same experience
from the emails.
This is just copied from what other links which require a logged in user do,
so I might have missed some nuance, but it seems to work ok for me.
For mysociety/alaveteli-professional#222
=> [Pro] Fix new response links for pro users

Vagrantfile, doc/CHANGES.md
Vagrant kept setting my number of cpus as 4 instead of 2 (which
VirtualBox then complains about) as `hw.ncpu` counts a hyperthreaded
core as 2 processors. `hw.physicalcpu` should return the number of
physical cores instead.
Syntax borrowed from https://coolaj86.com/articles/get-a-count-of-cpu-cores-on-linux-and-os-x/
=> Use hw.physicalcpu to get cpu count for Mac OS

doc/CHANGES.md, lib/no_constraint_disabling.rb, script/load-sample-data
* Sets a load order for the fixture files to avoid foreign key constraints
* Uses a temporary file for the loading script rather than using the /dev/stdin hack as that doesn't appear to work anymore (rails/rails#26343)
* Updates no_constraint_disabling and uses it in the data loader script
Fixes #3977
=> Fix the load-sample-data script

app/models/info_request.rb, doc/CHANGES.md, spec/models/info_request_spec.rb
As withdrawing a request emails the authority, an automated response
would automatically set the request back to awaiting_description
Fixes #3939
=> Prevent autoreplies causing withdrawn requests to require classification

.ruby-style.yml
Fixes RuboCop related Hound errors, e.g.:
Some files could not be reviewed due to errors:<details><summary>/tmp/d20170601-10374-14upuqb/.rubocop.yml: Style/DotPosition has the wrong na...</summary><pre>/tmp/d20170601-10374-14upuqb/.rubocop.yml: Style/DotPosition has the wrong namespace - should be Layout<br>/tmp/d20170601-10374-14upuqb/.rubocop.yml: Style/AccessModifierIndentation has the wrong namespace - should be Layout<br>/tmp/d20170601-10374-14upuqb/.rubocop.yml: Style/AlignArray has the wrong namespace - should be Layout<br>/tmp/d20170601-10374-14upuqb/.rubocop.yml: Style/AlignHash has the wrong namespace - should be Layout<br>/tmp/d20170601-10374-14upuqb/.rubocop.yml: Style/AlignParameters has the wrong namespace - should be Layout<br>/tmp/d20170601-10374-14upuqb/.rubocop.yml: …
=> Fix Hound config

app/views/admin_general/index.html.erb, doc/CHANGES.md, spec/controllers/admin_general_controller_spec.rb
As there is already a guard for empty messages, it could be
that unicode spaces are causing blank text links to be created.
Possibly related to a known bug in String.strip that affects Ruby 1.9.2
and 1.9.3 - https://bugs.ruby-lang.org/issues/7845
Fixes #2689
=> Ensure the admin link for misdelivered messages has text

.ruby-style.yml, Gemfile, Gemfile.lock, app/models/concerns/alaveteli_pro/request_summaries.rb, app/models/info_request.rb, spec/controllers/alaveteli_pro/info_requests_controller_spec.rb, spec/factories/alaveteli_pro/request_summaries.rb, spec/integration/alaveteli_pro/request_list_spec.rb, spec/models/alaveteli_pro/request_filter_spec.rb, spec/models/alaveteli_pro/request_summary_category_spec.rb, spec/models/alaveteli_pro/request_summary_spec.rb, spec/models/info_request_spec.rb, spec/spec_helper.rb, spec/support/shared_examples_for_request_summaries.rb, spec/views/alaveteli_pro/dashboard/_projects.html.erb_spec.rb
This fixes mysociety/alaveteli-professional#306, (in ca1aca3 specifically) but I also had to include the code from #4035 because doing so uncovered another instance of the issues with the request summary callbacks firing at the wrong time.
I've included one of @crowbot's suggestions from that PR, to make the new after_commit callback fire on create and update only, but I haven't touched refactoring the RequestSummary methods it actually calls. Partly to keep this small, but also because on review there's actually more shared code between the create and update actions than different, so I'm not sure it will be too helpful.
=> Update request summaries when logging events on an InfoRequest

app/controllers/alaveteli_pro/info_requests_controller.rb, app/controllers/alaveteli_pro/public_bodies_controller.rb, app/views/request/new_defunct.html.erb, spec/controllers/alaveteli_pro/info_requests_controller_spec.rb, spec/controllers/alaveteli_pro/public_bodies_controller_spec.rb, spec/factories/public_bodies.rb
This adds the same `is_requestable?` checking that the existing request
controller does. I note from testing that we still seem to allow people to
select defunct bodies in the search, but I thought we'd fixed this already?
For mysociety/alaveteli-professional#228
=> [Pro] Check that a body is requestable before previewing/creating requests

app/models/alaveteli_pro/request_summary.rb, spec/models/info_request_spec.rb
RequestSummary#update_from_request is called by code that has access to
a guaranteed-most-up-to-date copy of the request, but it discards it
and accessess it's own copy through .summarisable instead. In the case
of status updates through InfoRequest#set_described_state (and perhaps
in other cases) this meant that the summary wasn't seeing changes to
its request's status, because it's local copy was cached. I could have
forced a reload in the method but it seemed better to utilise the copy
of the request that was already present by passing it in, making the
update and create methods more consistent in the process.
For mysociety/alaveteli-professional#310
=> Fix issue with response_received folder not updating in pro dashboard

docs/glossary.md
Spotted three rude `</p>` tags showing up in [the glossary](http://alaveteli.org/docs/glossary/#blackhole).
Removed them.
=> remove spurious closing p-tags from glossary

app/controllers/request_controller.rb, doc/CHANGES.md, spec/controllers/request_controller_spec.rb
Sneaky spammers started using Ɓ instead of B, so just convert everything
to ASCII so that our regexps have a better chance of picking this kind
of obfuscation up.
=> Handle unicode in spam request titles

app/views/admin_comment/index.html.erb, doc/CHANGES.md
Default value made it difficult to spot spam without manually expanding
each comment. This should reveal enough so that admins can just scan the
list.
**Before**
**After**
=> Increase truncation length of admin comments index

app/models/alaveteli_pro/request_summary.rb, db/migrate/20170621112453_remove_default_value_from_request_created_at_and_request_updated_at_on_request_summary.rb, spec/factories/alaveteli_pro/request_summaries.rb, spec/models/alaveteli_pro/request_summary_spec.rb
This PR:
- Adds a migration to remove the default value from `request_created_at` and
`request_updated_at`
- Adds some validation to check that those fields are set
- Adds some additional validation to make clearer the relationship between
RequestSummaries and the things they summarise.
The latter point involved a slight tweak to the factories to allow us to be
more granular about whether we want to have a unique request summary or not
(as is the case when testing the validation). I've also improved the factory
so that it creates fully valid summaries on create or build.
Fixes #4032
=> Fix hardcoded timestamps in RequestSummary and improve validation

lib/tasks/temp.rake
The temp:populate_request_due_dates task used a :conditions => param, which
doesn't seem to be allowed under Rails 4.1
=> Fix Rails 3-ism in temp rake task

app/mailers/notification_mailer.rb, app/models/info_request.rb, app/models/role.rb, app/models/user.rb, app/views/notification_mailer/new_response.text.erb, app/views/request_mailer/new_response.text.erb, db/seeds.rb, doc/CHANGES.md, lib/tasks/temp.rake, script/send-daily-notifications, script/send-daily-notifications-daemon, script/send-notifications, script/send-notifications-daemon, script/site-specific-install.sh, spec/factories/users.rb, spec/fixtures/files/notification_mailer/new_response.txt, spec/fixtures/files/notification_mailer/new_response_pro.txt, spec/mailers/notification_mailer_spec.rb, spec/models/info_request_spec.rb, spec/models/role_spec.rb, spec/models/user_spec.rb, spec/views/notification_mailer/new_response.text.erb_spec.rb
This PR is part two of the split up #3994, following on from #4043. It covers:
- Copying the new response notification methods and emails into the
notification mailer. This is a change from #3994 where we moved them
wholesale because we want to keep that old code path alive for the time
being.
- Adding a new set of methods for sending instant notifications
- Updating the daemon and associated scripts in #4043 to send both types of
notifications
- Adding an additional feature flag condition when we choose what to do with a
new incoming mail in `InfoRequest#receive`. This caused me some confusion,
hence the slightly elaborate comment there, but I think it's necessary for
now to keep these two slightly competing sets of controls on when we send
emails. Eventually, we should be able to reduce …
=> Extend notification usage to cover new responses for opted in users

lib/alaveteli_spam_term_checker.rb
A handful of these have come through, so lets just be sure no correctly
formed attempts get made unnoticed:
An ArgumentError occurred in request#new:
invalid %-encoding
(%3ca+href%3dhttp%3a%2f%2fbitbon.club%2fbirzha_bitbon%3e%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD+bitbon%3c%2fa%3e+%0d%0a+%0d%0a%3ca+href%3dhttp%3a%2f%2fbitbon.in.ua%2fabout%3e%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD+%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD+%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%EF%BF%BD%3c%2fa%3e+%0d%0a+%0d%0a%3ca+href%3dhttp%3a% …
=> Add bitbon to spam terms

app/views/request/_outgoing_correspondence.html.erb, doc/CHANGES.md
In some cases the delivery status can get cached, but on clicking the
dropdown the info is refreshed and shows a message not inline with the
cached status.
The front end caching can now be removed because the calculation is cheaper
since https://github.com/mysociety/alaveteli/pull/3476.
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/404.
=> [WDTK#404] Remove fragment caching of delivery status

app/controllers/admin_raw_email_controller.rb, app/models/alaveteli_pro/draft_info_request_batch.rb, app/models/concerns/public_body_derived_fields.rb, app/models/info_request_batch.rb, app/models/public_body.rb, db/migrate/20170717141302_drop_public_body_translated_columns.rb, spec/fixtures/public_bodies.yml, spec/fixtures/public_body_versions.yml, spec/models/alaveteli_pro/draft_info_request_batch_spec.rb, spec/models/info_request_batch_spec.rb, spec/models/public_body_spec.rb
1. Checkout develop
1. Drop and recreate database
1. Load sample data
1. Checkout this branch
1. Run migrations
1. Test as follows...
As normal user on site:
Through admin interface:
=> 3800 globalize after drop constraints

app/assets/stylesheets/responsive/_global_layout.scss, app/assets/stylesheets/responsive/_global_style.scss, app/views/alaveteli_pro/info_requests/_after_actions.html.erb, app/views/request/_after_actions.html.erb
The action menus at the top and bottom of the page were
either both projecting to the left (on embargoed requests)
or to the right (on public requests). This commit alters
the css so that the left projection is applied only to the
action menu in the header (which is positioned to the
right hand side of the request).
Given that this is possible, I don't think there's a need
to specify in the element classes whether they are right
or left positioned.
=> Menu side set in css by page context, not in markup

config/environments/test.rb
Reportedly has a good (~6%) speed improvement [1].
[1] https://jtway.co/speed-up-your-rails-test-suite-by-6-in-1-line-13fedb869ec4
=> Disable logging in test environment

spec/spec_helper.rb
The test suite leaves these files in place after the run.
$ rm -rf files/raw_email_test/
$ be rspec spec/models/info_request_spec.rb
$ find files/raw_email_test -type f | wc -l
115
In some cases I've had nearly 1000 files in this directory:
$ ~/top-bushy-folders .
1.       1218 files in:  ./tmp/cache/assets/development/sprockets/v3.0
2.       899 files in:   ./files/raw_email_test
Lots of files in a VirtualBox share can cause performance problems, so
I don't see any reason not to clean these up.
=> Clean up raw emails directory after spec run

Vagrantfile
Doesn't seem to have the same transient failure issues as
xip.io
=> Use nip.io by default

.gitignore, bin/rails, bin/setup, config.ru, config/application.rb, config/boot.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/assets.rb, config/initializers/cookies_serializer.rb, config/initializers/to_time_preserves_timezone.rb
Extracted from http://railsdiff.org/4.1.16/4.2.9
Mostly harmless / boilerplate changes except for the `squash!` commits which introduce config or other changes that would benefit from closer attention:
* adding `assets.digest = true` sounds like it might have unintended consequences but I'm not certain
* the `bin/setup` file feels to me like we should replace most of the content with a TODO comment and consider it separately
* `ActiveSupport.to_time_preserves_timezone` looks like it might save us some major headaches down the line
The commit message for moving the cookies_serializer config is a bit misleading - pulling it out into its own file was introduced in 4.1 but it appears I opted to configure it inside application.rb instead.
=> Add Rails 4.2 generated template changes

app/helpers/application_helper.rb, app/views/general/_stylesheet_includes.html.erb, spec/helpers/application_helper_spec.rb
Connects to #4148 
Fix inspired by https://github.com/rails/sprockets-rails/issues/237#issuecomment-231940436
(and the immediate followups).
Placed in a helper wrapper to allow us to force UTF-8 and handle the minor faff of checking whether the Enumerator actually contains anything without a bunch of extra stuff to the template.
After deploying, we may need to clear zip file caches for attempted downloads as I suspect it's cached an HTML file containing the File Not Found message
=> Add a new helper to return the contents of an asset file

app/models/incoming_message.rb, doc/CHANGES.md, spec/models/incoming_message_spec.rb
Similar to 6c8490b, sometimes we try to save null bytes to the cache,
raising an ArgumentError.
This just strips any out before saving.
=> Prevent null bytes in attachment text cache

script/rails
We don't use this, and it causes problems in our deployment environment.
Running e.g. `script/mail-server-logs` errors because `rails` cannot be
found – this script appears to be interferring somehow; presumably
because its executable and `bundle exec` is trying to execute this
instead of the `rails` binary provided in the bundle.
$ script/load-mail-server-logs
bundler: failed to load command: rails (rails)
RuntimeError: path locale could not be found!
/RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/fast_gettext-1.1.0/lib/fast_gettext/translation_repository/base.rb:40:in `find_files_in_locale_folders'
/RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/fast_gettext-1.1.0/lib/fast_gettext/translation_repository/po.rb:12:in `find_and_store_files'
/RAILS_ROOT/vendor/bundle/ruby/2.3.0/gems/fast_gettext-1.1.0/ …
=> Remove script/rails

SUPPORT.md
Point users to the Alaveteli community via GitHub's `SUPPORT.md`. This adds a
link to the `SUPPORT.md` file when creating new issues.
See https://github.com/blog/2400-support-file-support for more info.
=> Add a SUPPORT file

app/controllers/application_controller.rb, app/controllers/request_controller.rb, app/controllers/user_controller.rb, spec/integration/alaveteli_dsl.rb, spec/integration/alaveteli_pro/admin_spec.rb, spec/integration/create_request_spec.rb
Closes #3613 and #3904 (which is triggered the second time a pro admin tries to confirm a request for a non-pro user).
=> Don't use pro overrides when administering non-pro requests

app/controllers/application_controller.rb, app/controllers/user_controller.rb
Ideally I think we want to show users who don't have cookies enabled some kind of warning. But I don't feel totally confident that the only cases where this code will be reached is a) bots b) real users who have cookies disabled. So this PR adds some extra information logging to find out more. Related to #3961
=> Log some information if we can't find the post redirect in the session

app/assets/javascripts/alaveteli_pro/embargo_dropdown.js, app/controllers/alaveteli_pro/embargo_extensions_controller.rb, app/controllers/alaveteli_pro/embargoes_controller.rb, app/helpers/alaveteli_pro/info_requests_helper.rb, app/models/ability.rb, app/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb, app/views/alaveteli_pro/info_request_batches/_embargo_info.html.erb, app/views/alaveteli_pro/info_request_batches/_form.html.erb, app/views/alaveteli_pro/info_requests/_embargo_form.html.erb, app/views/alaveteli_pro/info_requests/_sidebar.html.erb, app/views/alaveteli_pro/info_requests/preview.html.erb, app/views/info_request_batch/show.html.erb, config/routes.rb, spec/controllers/alaveteli_pro/embargo_controller_spec.rb, spec/controllers/alaveteli_pro/embargo_extensions_controller_spec.rb, spec/integration/alaveteli_pro/batch_request_spec.rb, spec/models/ability_spec.rb
This PR:
- Makes it so that you can't edit an embargo on a batch request singularly
- Adds new controller actions for extending and publishing a whole batch
- Adds a form to do those things to the batch request page
- Updates existing request forms to act on the whole batch when showing a
request from a batch, with a suitable confirmation step
- Fixes a bug which I think resolves #3985 / mysociety/alaveteli-professional#278
- Fixes a couple of other bugs in specs or missing specs entirely for existing embargo controllers
For mysociety/alaveteli-professional#258
=> Add form to manage embargoes across a whole batch request

app/mailers/request_mailer.rb
Should improve performance in production but still be available for
development and debugging if needed.
Closes #4143
=> Write incoming messages to the debug instead of info log

app/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb, app/views/alaveteli_pro/info_requests/_embargo_form.html.erb, app/views/alaveteli_pro/info_requests/_info_request.html.erb
Show the embargo expiry on mouseover using the title element.
Extended to the sidebar of the request and draft request page views as it looks as though it would be useful there as well:
**Edit:** Now with more text, per review comments:
Closes mysociety/alaveteli-professional#227
=> [pro#227] Add embargo date to padlock

app/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb
Fixes mysociety/alaveteli-professional#354.
This was causing the tag to close around the status update forms,
effectively hiding them because of the icon's visibility settings.
Introduced in 583f961.
Before:
After:
=> [pro#345] Add missing closing tag

.vagrant.yml.example, Vagrantfile
* Default to the dynamic calculation
* Allow hard-coding of CPU count
* Removes unrequired local var in `#cpu_count`
=> Make number of Vagrant CPUs configurable

app/controllers/admin_general_controller.rb
See https://docs.google.com/document/d/1_bDeethGcXyvHFhVBnucpr1EXW5h7YC_WvVCk3Fgzu4/edit#
This query has started to run indefinitely on WDTK. It locks a passenger
process, so eventually results in a queue full error.
The query itself runs fine (in an SQL console), but for whatever reason
running it through arel just hangs.
Running it through `#find_by_sql` seems to work okay in the console.
Fixes https://github.com/mysociety/alaveteli/issues/4208.
=> [#4208] Run problematic query through #find_by_sql

docs/customising/config.md, docs/installing/manual_install.md
This doesn't currently include information about setting up your MTA to redirect incoming messages to a POP3 mailbox and set up that mailbox on a server. I wonder if we should be giving instructions to people to use an external service like Gmail as described in https://github.com/mysociety/alaveteli/issues/3111, which references [discourse](https://meta.discourse.org/t/set-up-reply-via-email-support-e-mail/14003) as an example.
=> Add POP polling documentation

lib/tasks/config_files.rake
If this is not set by a reuser, we end up receiving their cron
notifications.
This sets the value to the default used in `config/general.yml-example`
(assuming the default user `alaveteli` is chosen).
=> Change default MAILTO generated by convert_crontab

app/mailers/request_mailer.rb, doc/CHANGES.md
Lots of users reply to this email – probably because the subject is
phrased as a question.
This makes the subject more obvious that they must complete an action.
Fixes https://github.com/mysociety/alaveteli/issues/775.
=> [#775] Update subject line of new_response_reminder_alert

spec/fixtures/pro_accounts.yml, spec/fixtures/roles.yml, spec/fixtures/users.yml, spec/fixtures/users_roles.yml, spec/lib/user_stats_spec.rb
These get loaded as sample data to make development on pro easier.
Adds:
* A pro user
* A pro admin
* A user who is a pro, an admin _and_ a pro admin
=> Add fixtures for pro users

app/controllers/request_controller.rb, app/models/info_request.rb, app/views/request/_sidebar.html.erb, doc/CHANGES.md, spec/models/info_request_spec.rb
Connects to https://github.com/mysociety/alaveteli/issues/4165
The expensive part of the operation (for larger installs) is the
calculation of similar requests in xapian. We were previously
duplicating the meaningful data that was cached by using locale
as a cache key. The similar requests for a request are identical
over locales. This was causing us to use cache space unnecessarily.
We also were caching the template contents that rendered the
similar requests. Again, this uses cache space on content that can
be fairly cheaply regenerated. Here we cache only the expensive-to-
generate list of ids, which will not take up as much cache room, and
therefore increase the likelihood that any given cache item will
be used before it is evicted.
=> [#4165] Cache similar requests as ids at the model level

lib/user_spam_scorer.rb
Had a bunch of wgz.cz spam on WDTK recently, and we've banned lots of
webgarden.com in the past.
=> Add webgarden variations as spam domains

app/assets/stylesheets/responsive/_header_layout.scss, doc/CHANGES.md
This is intended as an addition to mysociety/whatdotheyknow-theme#405 rather than a replacement but the 2 fixes are independent.
The WDTK theme work fixes the theme-specific styling issues, whereas this adds a new class (rather hackily, improvements welcome) to identify a logged in Pro user (there's currently no way to work this out in CSS) and uses some additional margin space to force the `logged_in_bar` to be wider than the available space so it will appear below the login link as per @stevenday's [original suggestion](https://github.com/mysociety/whatdotheyknow-theme/pull/405#pullrequestreview-44873829)
Connects to mysociety/alaveteli-professional#162
=> [pro#162] extra menu tweaks

spec/models/alaveteli_pro/request_summary_spec.rb
This spec fails on a daily basis, only to run successfully on a CI
rerun. This is getting pretty frustrating, so this commit skips the spec
until we diagnose the issue.
Has to be `skip` because `pending` always expects a failing spec.
=> Skip spec with frequent transient failures

spec/fixtures/pro_accounts.yml
Otherwise this breaks when running `load-sample-data` with a blank database
=> Give pro_account fixture own id

doc/CHANGES.md
We don't use it as it wasn't stable on testing
=> Deprecate the use of Varnish purging

app/models/user.rb, db/migrate/20170922160120_remove_admin_level.rb, doc/CHANGES.md, lib/tasks/temp.rake, spec/factories/users.rb, spec/fixtures/users.yml, spec/models/user_spec.rb
Made obsolete in dd584a1c347b3ca3ebefe7fabf0f131acbe6b337
Closes #3805 - we're keeping `ProAccount` to track how long someone's had a ProAccount for.
=> Remove user attribute admin_level

app/controllers/alaveteli_pro/payment_methods_controller.rb, app/controllers/alaveteli_pro/plans_controller.rb, app/controllers/alaveteli_pro/subscriptions_controller.rb, app/models/pro_account.rb, app/views/alaveteli_pro/subscriptions/_subscription.html.erb, config/routes.rb, spec/controllers/alaveteli_pro/payment_methods_controller_spec.rb, spec/controllers/alaveteli_pro/plans_controller_spec.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb, spec/factories/pro_accounts.rb, spec/models/pro_account_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/333
Adds basic cancellation of the `Stripe::Subscription`.
=> [#Pro333] Cancel Account

app/models/user/with_activity_query.rb, lib/tasks/users.rake
Closes https://github.com/mysociety/alaveteli-professional/issues/361
Add users:pro_activity task
Prints a list of pro users in order of activity. Field list and date
range is customisable through the environment – see the task description
for more.
Examples:
$ bundle exec rake users:pro_activity | head -n 5
id,name,email,activity
19,Batch User,batch-user-1@example.com,18840
7,Pro User 1,person1@example.com,371
8,Pro User 2,person2@example.com,329
15,Pro User 9,person9@example.com,227
$ bundle exec rake users:pro_activity FIELDS="id,activity" | head -n 5
id,activity
19,18840
7,371
8,329
15,227
$ bundle exec rake users:pro_activity END_DATE="2009-01-01" | head -n 5
id,name,email,activity
1,Bob Smith,bob@example.com,2
8,Pro User 2,person2@example.com,0
9,Pro User 3,person3@example.com,0 …
=> [#Pro361] User activity

app/controllers/request_controller.rb, spec/controllers/request_controller_spec.rb
Work on https://github.com/mysociety/alaveteli-professional/issues/372.
Also fixes https://github.com/mysociety/alaveteli-professional/issues/367.
* Removes the `is_pro?` filter from the redirect to the pro path. We
will perform this redirect for all embargoed requests.
* Sets `@in_pro_area` for all embargoed requests so that its clearer
that the request is still embargoed.
=> [#pro372] Allow ex-pro users to view embargoed requests

app/controllers/user_controller.rb, app/models/info_request.rb, app/models/info_request/prominence/visible_to_requester_query.rb, app/models/user.rb, app/views/request/_request_listing_single.html.erb, app/views/user/show.html.erb, app/views/user/show/_show_batches.html.erb, app/views/user/show/_show_profile.html.erb, app/views/user/show/_show_requests.html.erb, app/views/user/show/_show_same_name_users.html.erb, app/views/user/show/_show_track_things.html.erb, app/views/user/show/_show_undescribed_requests.html.erb, spec/controllers/user_controller_spec.rb, spec/models/info_request/prominence/visible_to_requester_query_spec.rb
Work on https://github.com/mysociety/alaveteli-professional/issues/372.
This PR covers the display of private requests on the user profile / "my requests" page.
Here's the difference between the display of the request game:
**Before:**
**After:**
=> [#Pro372] Cancelled view requests

app/controllers/application_controller.rb
This was originally added in to improve testing for error handling
but removing it doesn't appear to affect any current tests.
Removed in response to Brakeman warning
https://brakemanscanner.org/docs/warning_types/information_disclosure/
=> Remove override of show_detailed_exceptions?

app/models/pro_account.rb, spec/models/pro_account_spec.rb
=> Prevent ProAccount#active? throwing an error without stripe customer id

app/controllers/alaveteli_pro/embargoes_controller.rb, app/models/alaveteli_pro/embargo.rb, spec/controllers/alaveteli_pro/embargo_controller_spec.rb, spec/integration/alaveteli_pro/add_remove_embargo_spec.rb
Connects to mysociety/alaveteli-professional#384
This fixes the problems that are preventing embargoed requests which time out and expire or are published manually by the owner from being displayed on all pages on the site. It also pre-empts mysociety/alaveteli-professional#132 by making sure pre-existing requests which become embargoed are hidden in search results.
Embargoes which have already expired, will have to be found and flagged for reindexing manually (see [query in ticket](https://github.com/mysociety/alaveteli-professional/issues/384#issuecomment-336820465))
A secondary problem is that publishing from the request page using the "Publish request" button has not been logging the expiry event, 98e2f02c48bddd9ffb3b4162d3e11ea52faa7c09 aims to fix that.
=> [pro#384] Fix expired embargoes not displaying bug

app/assets/stylesheets/responsive/_request_layout.scss, app/views/request/details.html.erb, doc/CHANGES.md
Example:
https://www.whatdotheyknow.com/details/request/land_economy_applicants_11
Before:
After:
Closes mysociety/whatdotheyknow-theme#425
=> Make event history table responsive

app/assets/javascripts/general.js, app/assets/stylesheets/responsive/_global_style.scss, app/assets/stylesheets/responsive/_settings_layout.scss, app/assets/stylesheets/responsive/_settings_style.scss, app/assets/stylesheets/responsive/alaveteli_pro/_pro_style.scss, app/views/alaveteli_pro/subscriptions/_cancel_subscription.html.erb, app/views/alaveteli_pro/subscriptions/_subscription.html.erb, app/views/alaveteli_pro/subscriptions/show.html.erb, spec/views/alaveteli_pro/subscriptions/_cancel_subscription.html.erb_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/344.
* Extracts cancellation messaging to a partial.
* Adds logic to show appropriate messaging for an active or cancelled
subscription.
=> [pro#344] Display Subscription cancellation consequences

config/application.rb
https://github.com/mysociety/alaveteli/issues/4297
An 'IP spoofing attack?!' error is triggered by a conflict between
the CLIENT_IP and X_FORWARDED_FOR headers. When using the example
nginx config, nginx should be setting X_FORWARDED_FOR which is used in
preference to CLIENT_IP when the spoofing check is disabled. So this
setting should just prevent false positive errors when requests have
a CLIENT_IP header set.
Note when testing this PR - in development, we have the `web-console` gem enabled. This calls `GetIp` directly (in order to see if the calling IP is whitelisted for console use) without going through the `RemoteIp` middleware, which is what the `config.action_dispatch.ip_spoofing_check` param is applied via. This means that in development mode, the proposed fix will appear not to …
=> [#4297] Set `ip_spoofing_check` to false

.rubocop.yml, .ruby-style.yml
Fixes #4314 
If you have rubocop gem install locally you'll need to update to 0.51.0.
=> Update Ruby style to be Rubocop 0.51.0 compatible

app/models/outgoing_message.rb, app/models/outgoing_message/template/internal_review.rb, spec/models/outgoing_message_spec.rb
Uses the message_replacement options to set a flag to indicate that
the request is under embargo in order to decide whether to include the
link to the request history
Fixes mysociety/alaveteli-professional#320
=> [pro#320] Remove links back to embargoed requests from internal review email text

.ruby-style.yml
This now checks that you _don't_ include the encoding comment [1].
Support for analysing Ruby 1.9 code was dropped in 0.51.0 [2] and thus
the cop changed behaviour.
So, I've disabled this cop for now until we drop support for Ruby 1.9
ourselves [3].
[1]
https://github.com/bbatsov/rubocop/blob/v0.51.0/manual/cops_style.md#styleencoding
[2]
https://github.com/bbatsov/rubocop/commit/56e5036924cf9498ba0aee4fea11cae7844d6ab7#diff-3f2ebe9c9435b29358487264049625a4
[3] https://github.com/mysociety/alaveteli/pull/4209
=> Disable Style/Encoding cop

app/controllers/user_controller.rb, spec/controllers/user_controller_spec.rb
Fixes #4318
We check authenticity tokens for logged in users as a CSRF
protection. We don't check or generate tokens for non
logged in users so that we can strip cookies and cache
pages in varnish and serve them up to any non logged in
user.
If a user who is logged in tries to log in again or sign up
with a form generated before they logged in, the absence of
authenticity token would cause an `InvalidAuthenticityToken`
error.
We recently switched to handling these by raising an
exception rather than nullifying their session, so we
have greater visibility of the fact that users who
are already logged in are logging in again or signing
up.
I don't think showing an error page (or indeed
nullifying their session) is the best thing to do
here, and I also think it's safe to remove the CSRF …
=> Better handle a logged in user logging in or signing up

app/models/incoming_message.rb, spec/models/incoming_message_spec.rb
Xapian indexing calls `IncomingMessage#get_body_for_quoting`, which
mutates `get_main_body_text_folded` causing it to get cached without the
`FOLDED_QUOTED_SECTION` marker.
Sometimes the requester will view the request before the indexing
happens, so the cache will contain the (correct) calculation from
`IncomingMessage#get_body_for_html_display`.
Introducing a `#dup` call allows the stripping of the marker to have no
effect on the cached value.
Fixes https://github.com/mysociety/alaveteli/issues/4189.
=> [#4189] Fix caching of cached_main_body_text_folded

app/views/alaveteli_pro/info_requests/_new_request_advice.html.erb
Copy the sidebar helper text about your message being public (with a modification to account for embargoes) to the pro sidebar template
Connects to mysociety/alaveteli-professional#235
=> [pro#235] Missing cautionary text

app/controllers/alaveteli_pro/public_bodies_controller.rb, app/helpers/alaveteli_pro/public_bodies_helper.rb, app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb, spec/helpers/alaveteli_pro/public_bodies_helper_spec.rb, spec/views/alaveteli_pro/info_requests/new.html.erb_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/380
The error when clicking the authority search box was:
Uncaught TypeError: Failed to execute 'appendChild' on 'Node':
parameter 1 is not of type 'Node'.
This took us to the `groups[optgroup].appendChild(option_html);` line. I
jammed a `console.log(option_html);` above it to see what the value was:
`undefined`.
Okay so then try performing the operation only `if(option_html)`… it
works!
That's about the limit of my understanding of this fix, so I think we
might want to report upstream in
https://github.com/selectize/selectize.js/issues/1188 with our proposed
fix to see what they think about it. It might well have unforseen
consequences.
=> [pro#380] Fix changing the recipient of a draft

app/views/user/show/_show_requests.html.erb
`info_requests.size` exposes a rough idea of the amount of private
requests a pro user has made.
Since private requests are not indexed by Xapian, the
`matches_estimated` will provide the correct pagination.
Fixes https://github.com/mysociety/alaveteli-professional/issues/396.
---
Didn't add specs because we don't have any existing view specs, and this area is due an overhaul soon.
To test in the browser, you basically want to create a pro user with 1 public request, and many private requests:
```ruby
require 'rspec/rails'
require 'factory_girl'
require Rails.root.join('spec', 'support', 'load_file_fixtures')
require Rails.root.join('spec', 'support', 'email_helpers')
RSpec.configure do |config|
config.fixture_path = Rails.root.join('spec', 'fixtures')
end
user = …
```
=> [pro#396] Use Xapian results to set page count

README.md
Related to https://github.com/mysociety/alaveteli/pull/4209
=> Remove ruby-1.9.3 from the compatibility section of the README file

app/controllers/user_controller.rb, doc/CHANGES.md, spec/controllers/user_controller_spec.rb, spec/integration/sign_in_with_redirect_spec.rb
We shouldn't render the signin form if a user is already logged in. Its
confusing and results in weird behaviour.
For example, if a user is signed in, receives a "You have a new response
" email and follows the URL within the email, they shouldn't need to
sign in again before being redirected to their new response, as the
session already exists.
Fixes https://github.com/mysociety/alaveteli-professional/issues/288
(and also fixes this for non-pro users).
=> [#pro288] Pass-through signin form if already logged in

app/models/alaveteli_pro/subscription_with_discount.rb, app/views/alaveteli_pro/subscriptions/_subscription.html.erb, spec/models/alaveteli_pro/subscription_with_discount_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/382
Page looks almost the same when a coupon is used, only difference is with the next payment date - this is because stripe won't create new subscriptions each month for trials.
Trial:
Coupon:
=> [Pro#382] Support trials on profile subscription page

app/assets/javascripts/alaveteli_pro/authority_select.js
The default action is not needed as selectize will load results via AJAX. In fact sometimes the action event is triggered without selectize capturing the text inputted so this fixes https://github.com/mysociety/alaveteli-professional/issues/389
=> [pro#389] Prevent default public authority search action

app/controllers/admin_user_controller.rb, app/controllers/admin_users_sessions_controller.rb, app/controllers/users/confirmations_controller.rb, app/models/post_redirect.rb, app/views/admin_user/show.html.erb, config/routes.rb, spec/controllers/admin_user_controller_spec.rb, spec/controllers/admin_users_sessions_controller_spec.rb, spec/controllers/users/confirmations_controller_spec.rb, spec/factories/users.rb
Moves `AdminUserController#login_as` to its own controller.
=> Extract login as

.gitignore
You need this directory in place for the theme switcher to work. If you
install manually, it doesn't get created so you get errors when setting
up theme switching.
The install script installs the default alavetelitheme, so the directory
gets created for you, which is probably why this has gone unnoticed.
=> Keep the lib/themes directory in version control

app/assets/stylesheets/responsive/_utils.scss
Ensure that the keyboard only 'skip to' link doesn't add erroneous whitespace to the site footer
Closes https://github.com/mysociety/alavetelitheme/issues/100
=> Fix for footer whitespace bug

app/views/admin_general/index.html.erb
This link has been in place for a few releases now, so reusers should
be fairly familiar with where to find the summary stats.
Just a bit of minor cleanup while I was looking at this page.
=> Remove the link to moved summary stats

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/helpers/currency_helper.rb, app/helpers/stripe_helper.rb, app/views/alaveteli_pro/plans/show.html.erb, app/views/alaveteli_pro/subscriptions/_card.html.erb, app/views/alaveteli_pro/subscriptions/_subscription.html.erb, config/general.yml-example, config/initializers/money.rb, config/test.yml, lib/configuration.rb, spec/helpers/currency_helper_spec.rb, spec/helpers/stripe_helper_spec.rb
Fixes the following parts of https://github.com/mysociety/alaveteli-professional/issues/363
> - [x] Better handling of number_to_currency unit symbol
> - [x] Update card form does not ask for postcode
And these related parts have already been improved on `develop`
> - [x] Make ProAccount#stripe_customer handle fetching the Stripe::Customer object.
> - [x] Disable the "Pay with Card" / "Update card" buttons after the first click so you can't bring up the Stripe panel a second time before the page redirect completes (see the example video in mysociety/alaveteli#4242)
> - [x] maybe some code to format customer input to match
There is now a new `ISO_CURRENCY_CODE` configuration which is used to display the currency in the correct format but not linked to the Stripe plan yet.
=> [pro#363-2] Currency, Stripe and Pro signup improvements

.travis.yml
* Adds comment to each version explaining where the version is available
* Adds missing versions that are available in supported operating
systems
* Adds latest upstream release of highest supported version (2.3.5) in
this case
* Sets `allowed_failures` [1] on less supported Rubies so that we retain
reasonable speed in development (just waiting on 3 builds) but at
least have some visibility of issues on other systems.
* Sets `fast_finish` [2] so that we get a build status as soon as the
required builds have finished (or failed).
[1]
https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail
[2] https://docs.travis-ci.com/user/customizing-the-build/#Fast-Finishing
=> Add Ruby versions of supported operating systems

app/controllers/alaveteli_pro/concerns/stripe_namespace.rb, app/controllers/alaveteli_pro/plans_controller.rb, app/controllers/alaveteli_pro/subscriptions_controller.rb, config/general.yml-example, lib/configuration.rb, spec/controllers/alaveteli_pro/concerns/stripe_namespace_spec.rb, spec/controllers/alaveteli_pro/plans_controller_spec.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb
Work on https://github.com/mysociety/alaveteli-professional/issues/407
This allows plans/ subscriptions & coupons to be easily distinguishable within Stripe
=> [pro#407] Add namespace for Stripe plans and coupons

app/mailers/info_request_batch_mailer.rb, app/mailers/notification_mailer.rb, app/mailers/request_mailer.rb, app/mailers/track_mailer.rb, app/views/notification_mailer/info_request_batches/messages/_overdue.text.erb, app/views/notification_mailer/info_request_batches/messages/_very_overdue.text.erb, app/views/notification_mailer/info_requests/messages/_overdue.text.erb, app/views/notification_mailer/info_requests/messages/_very_overdue.text.erb, doc/CHANGES.md, spec/fixtures/files/notification_mailer/daily-summary.txt, spec/fixtures/files/notification_mailer/overdue.txt, spec/fixtures/files/notification_mailer/very_overdue.txt, spec/integration/track_alerts_spec.rb, spec/mailers/info_request_batch_mailer_spec.rb, spec/mailers/notification_mailer_spec.rb, spec/mailers/request_mailer_spec.rb, spec/views/notification_mailer/info_request_batches/messages/_overdue.text.erb_spec.rb, spec/views/notification_mailer/info_request_batches/messages/_very_overdue.text.erb_spec.rb, spec/views/notification_mailer/info_requests/messages/_overdue.text.erb_spec.rb, spec/views/notification_mailer/info_requests/messages/_very_overdue.text.erb_spec.rb
Auto-login URLs are a security problem, as users sometimes forward
emails or tweet the confirmation URLs, so others can then log in as the
user.
We opted to remove these for Pro users given the sensitivity of
requests, and given the confusion it creates for regular users (and
additional maintenance for developers), this removes them entirely.
In some cases, we don't automatically get a sign-in form if we try to
complete the action, so instead we pass through the sign-in form. If the
user is already signed in, they'll get redirected without noticing. If
they need to sign in, they'll get redirect after that.
Some actions still generate auto-login links:
* Confirming your account
* Changing your password
* Changing your email address
* Authority upload URLs
At this point in time, I'm not …
=> [#Pro325] Reduce usage of auto login links

app/controllers/alaveteli_pro/subscriptions_controller.rb, app/views/alaveteli_pro/dashboard/_ga_events.html.erb, app/views/alaveteli_pro/dashboard/index.html.erb, spec/controllers/alaveteli_pro/dashboard_controller_spec.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb, spec/integration/alaveteli_pro/view_request_spec.rb
Connects to mysociety/alaveteli-professional#124
The Goal and funnel steps for WDTK have been created but left switched off for now:
=> [pro#124] Add virtual pageview for pro signup funnel

app/views/alaveteli_pro/plans/index.html.erb
signup_path is a POST only route - the forms for both signin and
signup are displated at signin_path.
=> Fix URL for signup page

app/controllers/alaveteli_pro/account_request_controller.rb, app/views/alaveteli_pro/account_request/index.html.erb, config/routes.rb, spec/controllers/alaveteli_pro/account_request_controller_spec.rb, spec/views/alaveteli_pro/account_request/index.html.erb_spec.rb
Fixes issue discussed today's in pro planning meeting.
Allow pro training session to continue using the current account request form under a new URL at `/pro/training`
=> [pro] Add new pro training signup route

app/controllers/alaveteli_pro/plans_controller.rb, app/views/user/sign.html.erb
Previously the h1 text was 'Confirm your account on WhatDoTheyKnow Pro,
create an account or sign in', which doesn't really make sense.
Also changes 'Got an account?' to 'Got a WhatDoTheyKnow account?',
which seems clearer.
=> Improve the guidance text on Pro signup

app/controllers/admin_general_controller.rb, app/models/public_body.rb, app/views/admin_general/_to_do_list.html.erb, app/views/admin_general/index.html.erb, spec/factories/public_bodies.rb, spec/models/public_body_spec.rb
This solves locally for me the slowness issue described in https://docs.google.com/document/d/1sQIPhQrC4yb6E6c02I5QNFGEA888D947aqB_4eRxosU/edit#. If we agree on the general approach, we can create a hotfix for `0.28`.
=> More efficiently find and count authorities with blank contacts

lib/alaveteli_mail_poller.rb, spec/lib/alaveteli_mail_poller_spec.rb
Fixes #4221 
Rescue from the parent class of `Net::OpenTimeout` and `Net::ReadTimeout`. I haven't implemented the retry loop as this is already handled by the `AlaveteliMailPoller.poll_for_incoming_loop` loop.
=> Rescue from POP poller timeouts

app/controllers/password_changes_controller.rb, app/controllers/users/confirmations_controller.rb, app/views/password_changes/new.html.erb, config/routes.rb, spec/controllers/password_changes_controller_spec.rb, spec/controllers/users/confirmations_controller_spec.rb, spec/factories/users.rb
Fixes #4038 hopefully, unable to reproduce but suspect there is an issue retrieving the post redirect from the session store.
Have switched away from storing `change_password_post_redirect_id` in session and instead use post redirect token in the URLs for the `edit` and `update` actions
=> [#4038] Fix password reset loop

app/controllers/admin_raw_email_controller.rb, app/views/admin_raw_email/show.html.erb, config/initializers/mime_types.rb, doc/CHANGES.md, spec/controllers/admin_raw_email_controller_spec.rb
I almost _always_ want to open the email in Apple Mail so that I can
extract attachments that we had trouble parsing.
To do that, I download the raw email, _rename the file extension_ and
then open in Apple Mail. This adds a really annoying step to the task at
hand.
This commit downloads the email with a `.eml` extension so that
double-clicking the file opens it in Apple Mail (or your chosen mail
client) automatically.
Its still plain text, so nothing needs to be done when operating on the
file with command line tools.
=> Download RawEmail as .eml instead of .txt

Gemfile.lock, config/newrelic.yml-example
This version removes `developer_mode`, more information at
https://discuss.newrelic.com/t/feedback-on-the-ruby-agent-s-developer-mode/46957
=> Update newrelic_rpm to latest version

doc/CHANGES.md, lib/tasks/stats.rake
comment_on_own_request_conditions references the info_requests table, so
we need to tell ActiveRecord that we're doing that.
Fixes #4420
=> [#4420] Fix stats:show task

app/controllers/alaveteli_pro/embargoes_controller.rb, app/models/ability.rb, app/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb, app/views/alaveteli_pro/info_requests/_embargo_form.html.erb, spec/controllers/alaveteli_pro/embargo_controller_spec.rb, spec/controllers/alaveteli_pro/embargo_extensions_controller_spec.rb, spec/integration/alaveteli_pro/batch_request_spec.rb, spec/integration/alaveteli_pro/view_batch_request_spec.rb, spec/integration/alaveteli_pro/view_request_spec.rb, spec/models/ability_spec.rb, spec/support/shared_examples_for_viewing_requests.rb
~~Closes~~ ~~Connects to~~ Closes mysociety/alaveteli-professional#374
Tightens up access controls for existing embargo functionality.
The outstanding issue is adding the ability to retrospectively add an embargo to an existing batch which should be subject to the same checks (as it doesn't yet exist, this PR is excused from restricting it) - split out to mysociety/alaveteli-professional#447
=> [pro#374] restrict access to embargo settings for non-pro users

app/views/alaveteli_pro/subscriptions/_add_card.html.erb, app/views/alaveteli_pro/subscriptions/index.html.erb
(Annoyingly I can't see a way to test this without having javascript support in Capybara)
Uses the same form as updating a payment method but without providing the old card details
Closes mysociety/alaveteli-professional#420
=> Allow pro users without a payment card to add one

app/models/pro_account.rb, app/models/role.rb, app/models/user.rb, gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb, spec/controllers/alaveteli_pro/payment_methods_controller_spec.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb, spec/factories/users.rb, spec/models/pro_account_spec.rb, spec/models/role_spec.rb, spec/models/user_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/426 & Fixes https://github.com/mysociety/alaveteli-professional/issues/431
If pro pricing is enabled, when an user is made a pro we now create a ProAccount and setup the user on Stripe. Emails address are then kept in sync between the app DB and Stripe so receipts are sent to the correct location
=> [pro#426 & pro#431] Admin adding pro accounts

app/assets/stylesheets/responsive/alaveteli_pro/_new_request_layout.scss, app/controllers/alaveteli_pro/batch_request_authority_searches_controller.rb, app/controllers/alaveteli_pro/info_requests_controller.rb, app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb, spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb, spec/integration/alaveteli_pro/batch_request_spec.rb, spec/integration/alaveteli_pro/request_creation_spec.rb
Up for ~~early~~ review ~~requesting feedback on how linking through to the batch form should work.~~ (Probably not like this... although it's bearable as an extension of the current beta functionality. **Edit:** after discussion, we've decided that this is an adequate solution for the **beta** functionality - need to capture the concerns somewhere so we can work out what the full release version needs to do.)
I think the first bit (adding a filter to check for the feature flag and redirecting without it) is correct **but** the link across to the batch request form needs some more thought.
At the moment it looks like this...
If you click the link, you get the batch form (great). If you click the link after filling in some data, the data is lost (not ideal). Also, the wording is a …
=> [pro#335] Add pro batch feature flag

doc/CHANGES.md, script/site-specific-install.sh
Based on the Remove Wheezy branch (#4462) for simplicity's sake. Part of dropping Ruby 1.9 (#4209), will be hard for release candidate testers to assess the new version without it as anything other than Jessie or Stretch will spin up with Ruby 1.9 and the install will fail
=> Make our vagrant boxes use Ruby 2.x

app/controllers/alaveteli_pro/subscriptions_controller.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb
We want to make POP polling the default for pros, but some installs may
not have POP polling enabled.
=> Only enable POP polling for pros if configured

script/test-vagrant-provisioning
Allows the site to bind to localhost:3000 instead of the expected IP address and incorrectly reports that the test has failed.
Technically a bug in 0.30
=> Fix the test-vagrant-provisioning script

.vagrant.yml.example
The comment was getting included in the value instead of just '2',
breaking the VirtualBox config.
=> Fix comment in .vagrant.yml.example

app/controllers/alaveteli_pro/stripe_webhooks_controller.rb, spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb
Handle an Invoice with no charge 
Trial customers receive invoices with no attached charge, so we're
trying to update a `nil` charge in some cases.
Here, we only update the charge if one exists.
Fixes mysociety/alaveteli-professional#449.
Also includes some refactoring.
=> [#Pro449] Update zero charge invoice

config/environments/production.rb
We keep getting notifications from these for malformed requests.
Since Rack is generating these, it doesn't look like we can rescue them
in `ApplicationController#render_exception`. [1]
We could try utf8-cleaner [2] but I'm not sure its worth adding a new
dependency.
Instead, lets just ignore notifications about this error.
I wasn't able to test this – couldn't see any indication of exception
notification sending a mail in the logs – so I'm not 100% sure without a
second pair of eyes.
Fixes https://github.com/mysociety/alaveteli/issues/4398
[1] https://stackoverflow.com/q/24807592/387558
[2] https://github.com/singlebrook/utf8-cleaner
=> [#4398] Ignore ActionController::BadRequest notifications

app/models/concerns/admin_column.rb, doc/CHANGES.md
Dropping the translated columns [1] meant that `for_admin_column`
stopped returning these attributes, resulting in admins having to click
"edit" on a public body to be able to see these values.
This commit includes the translated attributes in `for_admin_column`.
Retrieving the translated attribute columns is a little clunky.
* First we get the translated attributes, as
`Translation.content_columns` returns extra attributes like `locale`
and timestamps. `PublicBody` doesn't have a `#locale` method so we get
a `NoMethodError` when passing it to `send` in the `yield`.
* After we've got the attributes we're interested in, pull out the
matching column instances.
* Use the existing `non_admin_columns` filter
Fixes #4183
[1] #4066
=> [#4183] Restore PublicBody translated attributes in admin

app/views/request/new.html.erb, lib/analytics_event.rb
Records two new Google Analytics events when users click on either the suggested FOI requests, or the link to Google the authority’s official website, in the JavaScript-powered typeahead box on the "Make a request" form.
We use the existing `track_analytics_event` helper function, so we don’t have to worry about re-handling the case where google analytics hasn’t loaded. And we’re already opening the links in a new window, so we don’t have to worry about a page navigation cancelling the `ga('send')` call.
Fixes #4514.
=> Track clicks on "Possible related requests"

app/views/admin_incoming_message/_actions.html.erb
b229a0caaa switched the format of raw email downloads from `.txt` to
`.eml`, breaking this link.
Fixes https://github.com/mysociety/alaveteli/issues/4482.
=> [#4482] Fix Raw Email download button

spec/spec_helper.rb
We don't need to do really expensive hashing while running specs, so
this should reduce the spec time a bit.
The controller specs seemed to go from ~17 minutes to ~12 minutes with
this change when I tried it, but I was doing other things at the time so
it wasn't a totally scientific test.
=> Use low BCrypt cost in specs

app/models/pro_account.rb, spec/models/pro_account_spec.rb
I don't think this is required for the Belgium upgrade as `pro_account` seems to mostly be called by the pricing / signup / subscription code in the current release, so the error condition shouldn't be occur without `pro_pricing`. It does feel like something we should fix though (I stumbled across this by accident while working on the batch limit code)
=> Don't call out to Stripe::Customer.create with pro_pricing disabled

app/views/request/show.text.erb, doc/CHANGES.md
Fixes https://github.com/mysociety/alaveteli/issues/4516:
A NameError occurred in request#download_entire_request:
undefined local variable or method `outgoing_message' for #<#<Class:0x00005652cbfce828>:0x00007fb4595aa928>
Did you mean? outgoing_message_url
app/views/request/show.text.erb:15:in `block in _app_views_request_show_text_erb___318332926424240026_70206280268940'
Just manually tested this as it doesn't seem worth adding a spec for an obvious typo.
=> [#4516] Fix download zip when request contains a resent message

Vagrantfile, bin/vagrant-jessie, bin/vagrant-stretch, bin/vagrant-trusty
Found these useful while testing vagrant box builds.
The `config.vm.define` setting allows us to have more than one vagrant box per repo without using snapshots or destroying the VM. In the binstubs this is assigning by using an ENV variable so we can call `./bin/vagrant-stretch up` & `./bin/vagrant-jessie up` at the same time
=> Added Binstubs for supported vagrant OSs

app/helpers/admin_helper.rb, app/models/concerns/admin_column.rb, app/models/info_request.rb, app/views/admin_request/show.html.erb, doc/CHANGES.md, spec/helpers/admin_helper_spec.rb
Makes it easier to see when the request is in a non-default state. This [caught me out](https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli-pro/Nin3XrrWBkU) recently.
**Before:**
**After:**
Fixes #4510
Really simple version, but better than nothing.
---
See commits for further notes.
=> Admin request page improvements

.ruby-style.yml, lib/normalize_string.rb
Don't extend an instance initialized by Struct.new. Extending it
introduces a superfluous class level and may also introduce weird
errors if the file is required multiple times
https://github.com/bbatsov/ruby-style-guide#no-extend-struct-new
=> Don't extend Struct.new

lib/has_tag_string/has_tag_string.rb, spec/models/has_tag_string_tag_spec.rb
Adds specs for `.find_by_tag` and then refactors so that it uses less Ruby and returns a chainable `ActiveRecord::Relation`. See commit messages for more details.
=> Refactor find by tag

app/assets/stylesheets/responsive/_ms_edge.scss, app/assets/stylesheets/responsive/alaveteli_pro/_batch_request_authority_search_layout.scss, app/assets/stylesheets/responsive/alaveteli_pro/_batch_request_authority_search_style.scss, app/assets/stylesheets/responsive/all.scss, app/models/public_body.rb, app/views/admin_public_body/_form.html.erb, app/views/alaveteli_pro/batch_request_authority_searches/_search_result.html.erb, app/views/alaveteli_pro/draft_info_request_batches/_summary.html.erb, app/views/general/_responsive_stylesheets.html.erb, spec/models/public_body_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/356.
MVP of adding important notes to the batch builder. Here we just show
any notes if the authority has any notes. We want to be more selective
about which notes we show, but that will come in a future commit.
I think this is a good-enough implementation of this, given we lost a bunch of time this sprint.
**Initial load:**
**Open notes:**
**Long notes:**
**Added to the batch:**
**Read & closed the notes**
> The notes are closed by default in the search results pane. When a user
adds them, the notes are automatically expanded in the selected
authorities pane.
This sounded like a good idea, but the "cheap" wait of adding the `open` attribute to the `<details>`  tag means that _all_ notes get opened when you add an authority. …
=> [#pro356] Show public body notes in the batch builder

app/mailers/request_mailer.rb, app/models/info_request.rb, spec/models/info_request_spec.rb
Finding requests is a responsibility of `InfoRequest`, so lets move it
there. Now `RequestMailer` simply extracts the email addresses we're
interested in and asks `InfoRequest` for the matching requests.
=> Extract requests matching email

app/models/info_request.rb, app/models/info_request_event.rb, doc/CHANGES.md, spec/models/info_request_spec.rb
Events are logged when editing `allow_new_responses_from` through the admin interface, but not when we run a background task to bulk-update requests.
Fixes #4531
=> [#4531] Log an event when we change allow_new_responses_from

Vagrantfile
Rather than downloading a fresh copy of `install-site.sh` during the provisioning process, Vagrant will now use the `install-site.sh` script from `/home/vagrant/commonlib`, which is included as a git submodule.
This means users will *really* need to make sure they run:
git submodule update --init
(as documented at http://alaveteli.org) before they start setting up their Vagrant VM.
The benefit is that you can now work off a modified `install-site.sh`, and you’ll no longer be left wondering why your changes to `commonlib/bin/install-site.sh` are being mysteriously ignored during provisioning.
Big thanks to @garethrees and @gbp for helping me track this one down!
=> Use install-site.sh from commonlib during Vagrant provisioning

spec/support/shared_examples_for_phase_counts.rb
Fixes intermittent failing specs.
`1.month` ago is not guaranteed to be enough days to make request appear
overdue, causes failures during short months.
=> [WIP] Correct creation of overdue request in shared spec

app/views/user/_signup.html.erb
Forgot this was now a limitation when signing up with a test user.
Hopefully prevent a few people getting frustrated after entering a
password thinking its okay, and then getting told its not.
I was going to put this in a placeholder as I saw on
https://highrisehq.com, but the `form_item_note` is more consistent with
the other form notes.
=> Add notes about password length.

app/assets/stylesheets/responsive/alaveteli_pro/_batch_request_authority_search_layout.scss
Fixes mysociety/alaveteli-professional#462.
We were using `grid-row()` as a shortcut to implementing a max-width "container" around the `.batch-builder` children, but it turns out, once we _also_ turn `.batch-builder` into a flex container, Safari got confused and messed up the layout.
As @wrightmartin noticed in mysociety/alaveteli-professional#462, it was the `clearfix()` part of `grid-row()` that was causing the issues – I think maybe Safari was treating `clearfix()`’s `:before` and `:after` pseudo-elements as flex children, and that was messing up the layout.
Anyway, we don’t actually _need_ the float clearing on `.batch-builder` because its children aren’t floated! So I‘ve pulled out `grid-row()` and replaced it with the just the container code it would have added. (Annoyingly, …
=> Fix CSS bug in Batch search UI in Safari

app/assets/stylesheets/responsive/alaveteli_pro/_batch_request_authority_search_style.scss
Adds a border between categories so that each element is clearer.
**Before**
**After**
=> Make browse-mode categories clearer

config/deploy.rb, doc/CHANGES.md, lib/acts_as_xapian/README.txt, lib/acts_as_xapian/acts_as_xapian.rb, lib/acts_as_xapian/tasks/xapian.rake, script/destroy-and-rebuild-xapian-index, script/rebuild-xapian-index, spec/integration/track_alerts_spec.rb, spec/models/info_request_spec.rb, spec/models/xapian_spec.rb, spec/support/xapian_index.rb
I had thought `rebuild_index` was effectively saying “mark each record
for reindex and then reindex it” rather than “destroy the index, then
reindex everything”.
This should be _really_ clear at the point of running the command.
=> Rename and warn about dangerous Xapian commands

app/views/alaveteli_pro/batch_request_authority_searches/_public_bodies.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/465.
You can't send FOI requests to defunct authorities, so don't even list
them here. There's not enough space to really explain why they appear,
but can't be added.
I think it would also be pretty tricky to display them, but disable the
"Add" button. How would we stop "Add all" adding it? What about non-JS
case, etc, etc.
This is obviously the extremely dumb solution. There are some problems
with implementing anything better:
* The bodies are actually fetched in
`batch_request_authority_searches/_public_bodies.html.erb` – hard to
add tests for this. Really the authorities that we want to display at
any given time should be fetched in a controller and assigned as an
instance variable.
* `HasTagStringTag` doesn't have a …
=> [pro#465] Don't list defunct bodies in batch browse mode

app/assets/javascripts/alaveteli_pro/batch_authority_search/results.js
Fixes https://github.com/mysociety/alaveteli-professional/issues/463
Only render when the content has changed.
This fixes the current scroll position being lost.
=> [pro#463] Limit rendering of batch authority search results

app/controllers/info_request_batch_controller.rb, app/views/info_request_batch/show.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/456
Allow will_paginate to apply offsets and limits so it can work out the
total number of records and pages. Previously due to our limit it
thought there was only a single page.
=> Fix pagination on InfoRequestBatchController#show

app/assets/javascripts/alaveteli_pro/authority_select.js
More work on https://github.com/mysociety/alaveteli/issues/4426.
We're seeing searches for some authorities return no results on the
first search after page load.
This is because the query string Xapian is trying to use is e.g.
`home%20office`. This is happening because `encodeURIComponent` is
encoding the `query` data parameter as `home%20office`, which is then
getting double-encoded to `home%2520office` by `getJSON` [1]. Rails
decodes this back to `home%20office`, but that's obviously not a correct
search term.
Something to note is that `getJSON` uses `+` instead of `%20`. This only
happens for `application/x-www-form-urlencoded` content [2], and is
consitent with `URI.encode_www_form_component`: [3]
URI.encode_www_form_component('home office')
This all gets handled correctly by Rails – …
=> [#4426] Remove double encoding from authority select

.ruby-style.yml
Updates `ruby-style.yml` to use updated rubocop namespaces.
Addresses error output from hound on [recent](https://github.com/mysociety/alaveteli/pull/4598#pullrequestreview-109254900) [PRs](https://github.com/mysociety/alaveteli/pull/4599#pullrequestreview-109265392).
=> Update rubocop config

Gemfile.lock
Update the charlock_holmes gem to v0.7.6
Needed due to 0.7.5 not building with icu4c 61.x 
Differences between versions: https://github.com/brianmario/charlock_holmes/compare/0.7.5...0.7.6
=> Update charlock_holmes gem

lib/tasks/temp.rake
This task kept failing because of unhandled errors. This addresses the
ones that came up. There might be more, but if we rescue from
`StandardError` we might miss the backtrace as it scrolls past, so I
think its better to just exit if we encounter a new type of error,
investigate, and then add more error handling if appropriate.
Related to https://github.com/mysociety/alaveteli/issues/4156.
=> [#4156] More error handling in temp:populate_missing_attachment_files

app/models/info_request.rb, doc/CHANGES.md, spec/models/info_request_spec.rb
There's no reason to keep an `Embargo` around after its `InfoRequest`
has been destroyed. This came up when writing code to reindex requests
with an attached `Embargo`. I had to add `try` in case the `Embargo`
returned `nil` when asking for the `info_request`:
AlaveteliPro::Embargo.find_each do |embargo|
embargo.info_request.try(:reindex_request_events)
end
I'd expect there to always be an `InfoRequest` when doing something like
this.
Fixes https://github.com/mysociety/alaveteli-professional/issues/501
=> [pro#501] Destroy embargoes with their info request

lib/acts_as_xapian/acts_as_xapian.rb, spec/lib/acts_as_xapian_spec.rb
* Add spec demonstrating failed xapian indexing
* Minor refactoring
* Prevent continuous retries of failing index jobs
As far as I can tell, an indexing error _does not_ block indexing for all other jobs. It just means that we retry the failing job over and over again. I think what we should be doing in response to this (when we get a flood of cron emails) is just removing the job from the `acts_as_xapian_jobs` queue, so that its not indexed any more. It might get re-added to the queue later (another response, an edit, etc), but we might have fixed the underlying problem by then. If not, we just remove and bump the ticket that we surely created describing the bug.  Rather than doing this manually, I've introduced the job removal here, so that we only get one email per failed job run, …
=> Improved handling of failed Xapian indexing

app/assets/javascripts/alaveteli_pro/batch_authority_search/browse.js, app/assets/stylesheets/responsive/alaveteli_pro/_batch_request_authority_search_style.scss, app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/466.
@gbp I thought this was going to be a bit of a nightmare to implement, but then I noticed we could just call `toggleCaret()` on the top level groups, and wrap a `.batch-builder__list__item__anchor` span around the group labels to make them clickable. Does that seem sensible to you? Obviously, if JavaScript fails to load for some reason, then the groups will be unfolded by default, but @garethrees says he’s happy with that.
=> Collapse top-level groups in Pro batch browse UI

app/models/alaveteli_pro/embargo_extension.rb, app/models/info_request.rb, spec/fixtures/files/notification_mailer/daily-summary.txt, spec/fixtures/files/notification_mailer/new_response.txt, spec/fixtures/files/notification_mailer/new_response_pro.txt, spec/mailers/notification_mailer_spec.rb, spec/models/info_request_spec.rb, spec/models/public_body_spec.rb, spec/support/email_helpers.rb, spec/support/load_file_fixtures.rb
Fixes #4487 by not hard coding IDs in the spec file
=> NotificationMailer transient specs errors

app/helpers/alaveteli_pro/batch_request_authority_searches_helper.rb, app/views/alaveteli_pro/batch_request_authority_searches/_search_result.html.erb, app/views/alaveteli_pro/draft_info_request_batches/_summary.html.erb, spec/helpers/alaveteli_pro/batch_request_authority_searches_helper_spec.rb
Work on #4549
We've got less space to show highly formatted notes here, so strip some
tags that break the display (mainly headings).
Heavily styled notes looked terrible
The actual HTML used for the home office has a stray closing `p` tag (NB: Don't update this through the web interface because it times out – too many requests!). Here's a fixed snippet:
```html
<h1>This website makes all correspondence public. Do not use this site for messages about your personal circumstances, instead use the <a href="https://www.gov.uk/government/organisations/home-office#org-contacts">direct contact information published by the Home Office</a></h1>
<h3>Do NOT use this page to contact the Home Office about your passport, …
```
=> [#4549] Sanitize PublicBody#notes in batch builder

app/models/incoming_message.rb, spec/models/incoming_message_spec.rb
Quick fix for a specific issue mentioned in
https://github.com/mysociety/alaveteli/issues/1278 (not a fix for the
entire ticket).
`noreply@` wasn't getting matched as we weren't using `.?`.
Also adds specs for no reply emails.
=> [#1278] Fix Regexp for handling no-reply emails

app/assets/javascripts/alaveteli_pro/batch_mode/mode-switcher.js, app/assets/javascripts/alaveteli_pro/draft_batch_summary/body-list.js, app/assets/javascripts/alaveteli_pro/draft_batch_summary/write-button.js, app/controllers/alaveteli_pro/batch_request_authority_searches_controller.rb, app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb, spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb, spec/controllers/alaveteli_pro/draft_info_request_batches_controller_spec.rb
Fixes #4568
Destroys the `AlaveteliPro::DraftInfoRequestBatch` when the last authority is removed from the selection.
While not _invalid_, an empty `AlaveteliPro::DraftInfoRequestBatch` results in a `NoMethodError` error (#4568) where we try to use the `#name` of the first `PublicBody` belonging to the record.
Rather than providing a fallback (which we still might want to do later), it seemed better to avoid creating these "empty" draft batches in the first place, so that users' "drafts" folder doesn't end up with loads of useless empty drafts that they currently can't delete (https://github.com/mysociety/alaveteli-professional/issues/266).
I found the tests really hard to get my head around with lots …
=> [#4568] Destroy DraftInfoRequestBatch when last body is removed

app/models/info_request.rb
Some departure-lounge minor code style tweaks to tidy `InfoRequest`.
Grouping class methods helps when you're trying to find stuff;
* You know they're at the top
* They don't get in the way of instance methods when you're looking in that layer
* Implementation notes:
Ignored the hound comments as I'm just moving stuff around
=> Info request refactoring

app/controllers/alaveteli_pro/batch_request_authority_searches_controller.rb, app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb, app/views/alaveteli_pro/batch_request_authority_searches/_search_results.html.erb
At the moment its possible to send a batch to authorities that no longer
exist, where FOI doesn't apply, or where we don't have an email address.
This is made worse by the new Batch Browse mode. For now, the easiest
option is to just prevent listing those authorities
* Exclude `not_apply` authorities from batch searches, as its currently
too complicated to explain that you can make a request to them, but
they don't have to answer.
* Extract the `exclude_tags` to a variable and switch to new-style Hash
syntax.
* Skip rendering results if the authority is not requestable. This
handles authorities with missing email addresses. In the normal
interface we point this out, but the user doesn't get told about this
until their batch sending has completed. Ideally we'd do this at
search time, but …
=> [pro#477] Delist unrequestable authorities from Batch

_includes/es/footer.html, _includes/footer.html
Change the footer links to the mySociety Twitter profile
The linked profile isn't associated with Alaveteli
=> Correct links to Twitter profile

app/views/request/details.html.erb
Add a link where we're telling people to figure it out for themselves
Given we already have the `@info_request` its trivial to just link to
the page we're referring to in the text.
Fixes https://github.com/mysociety/alaveteli/issues/2942.
* Screenshots
=> [#2942] Add link to main request JSON from details page

app/controllers/admin_users_account_suspensions_controller.rb, app/views/admin_user/_user_table.html.erb, app/views/admin_user/show.html.erb, config/routes.rb, doc/CHANGES.md, spec/controllers/admin_users_account_suspensions_controller_spec.rb
Adds a controller to handle account suspensions. It sets a default
suspension message, but the main use right now is to ban for spamming.
I've added buttons to the user list and user show page to quickly set a
"Banned for spamming" message.
This could later be extended with an
`AdminUsersAccountSuspensionsController#destroy` to unban users (reset
`User#ban_text` to `''`), or further buttons could be added with other
common suspension reasons.
This was prompted by an influx of "tech support" spam accounts and
having to manually copy/paste the ban text in each.
I wrote this quickly before tea… it might not be quite up to usual standards.
* Screenshots
=> Make it quicker to ban users in admin interface

doc/CHANGES.md, lib/user_spam_scorer.rb, spec/lib/user_spam_scorer_spec.rb
Fixes #4618
Add spam checking to user names
Help catch spam influxes of similar spam
Used existing pattern from `about_me` checking
=> [#4618] Add spam checking to user names

spec/models/public_body_spec.rb
Fixes #4631 
Hopefully fixes transient spec failures
Developer happiness
Using `match` fails if the order of the elements are different.
I search the project for other array matches, think I've caught them all.
=> [#4631] Use `match_array` in tests when comparing arrays

spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb
Fixes #4634
Reproducible by `rspec --seed 41168 spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb spec/controllers/alaveteli_pro/plans_controller_spec.rb`
Stub configuration options instead of changing the environment
`MySociety::Config` environment changes are kept between tests so this potentially breaks other tests. Which it does quite often for `./spec/controllers/alaveteli_pro/plans_controller_spec.rb`.
Stops specs from breaking and saving development time.
Quick project find for `MySociety::Config.load_default` within `./spec` shows other similar cases; will be worth looking at these too!
=> [#4634] Stripe transient spec errors

app/models/info_request_batch.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/362
Remove delay from batch sending for poller users
If the user has polling enabled we don't need to worry about overloading
the app with autoresponses.
Gets batch requests sent quicker, so pro users don't have to wait for hours to see all their sent requests.
I used the poller setting rather than checking whether a user is pro, as the poller mitigates the need for a delay. We can then start switching normal users across to the poller without needing to change the code here.
Pretty hard to add tests for this one given it checks `Rails.env.production?` and no existing specs. :(
=> [pro#362] Remove delay from batch sending for poller users

app/controllers/alaveteli_pro/info_request_batches_controller.rb, lib/alaveteli_rate_limiter/rate_limiter.rb, lib/alaveteli_rate_limiter/window.rb, spec/controllers/alaveteli_pro/info_request_batches_controller_spec.rb, spec/lib/alaveteli_rate_limiter/rate_limiter_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/404
Addd tiered rate monitoring to pro batches. We get notified if a pro makes more than 5 batch requests in either an hour, day or week period.
See rationale in https://github.com/mysociety/alaveteli-professional/issues/404#issuecomment-388870518. The gist is that we want to keep an eye on Batch usage, as it has potential to cause repetitional damage, but we don't want to get in the way of genuine power-user use.
I've plucked most of the code from existing patterns, with a few cleanups along the way. I think ideally the rate limiter library needs …
=> [#Pro404] Pro Batch Rate Monitoring

app/views/api/request_events.atom.builder, spec/controllers/api_controller_spec.rb, spec/support/xml_matchers.rb
Fixes #4677 
Removed the `updated` timestamp from the Atom API feed when there are no `InfoRequestEvent` to render.
So we return successful responses for API requests. This has been causing exceptions and email alerts every ~20 minutes.
=> [#4677] Correctly handle Atom feed responses with no events

app/models/info_request_batch.rb, app/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb, spec/integration/alaveteli_pro/view_batch_request_spec.rb, spec/models/info_request_batch_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/512
Disables the "Publish requests" button on the batch show page until all batch requests have been sent.
If a user publishes requests before an InfoRequestBatch has finished
sending, the existing requests are published but the remaining requests
get created with an Embargo. This means they get hidden from the
now-public InfoRequestBatchController#show action.
* Screenshots
I've got a few questions around the UI here – should we just hide the
button, or disable with a message, or a lodaing spinner or what? – but
I'll leave that for an "improvement" …
=> [pro#512] Disable batch embargo change during sending

app/models/info_request.rb, config/general.yml-example, doc/CHANGES.md, spec/models/info_request_spec.rb
Fixes https://github.com/mysociety/alaveteli/issues/4021.
Extends the time before we fully close requests. Instead of 2 ✕ the "old" value, we now use 4 ✕ the old value before requests are completely closed.
Authorities often wanted to respond later than 6 months, generally after an internal or external review compelling them to publish. They'd try to respond and get a bounce, and then we'd either have a bunch of admin work to do, or they'd send the response off-site.
Did a bit of spec cleanup while I was here.
I've had a look at the code climate warnings, but its pretty hard to refactor out the duplication. I think this is probably because there's no command/query separation in the …
=> [#4021] Extend time to fully close requests

app/models/user/authentication.rb, doc/CHANGES.md, lib/tasks/users.rake, spec/models/user_spec.rb
Fixes #4490 
* Adds `User.sha1` scope which returns all users with SHA1 password hashes
* Adds `bundle exec rake users:update_hashed_password` command
Security
As we can't tell what the original passwords are we just encrypt the SHA1 hash using bcrypt. When the user logs in the password hash is decrypted twice - this was already implemented in 19ea04139eda187a5024754cece49cb479ff68c5
=> [#4490] Add rake task to upgrade existing users' pasword hashes to bcrypt

app/models/incoming_message.rb, app/validators/reply_to_address_validator.rb, doc/CHANGES.md, spec/models/incoming_message_spec.rb, spec/validators/reply_to_address_validator_spec.rb
Fixes #1278 
Fixes #2930
* Some code cleaning of `IncomingMessage#_calculate_valid_to_reply_to`.
* Adds customisable values for no reply regexp and list of addresses that we can't use for replying to.
* Reusers couldn't easily translate no-reply addresses in the hard-coded regexp
* The no-reply regexp only acts on the local part of the domain, so addresses used by particular bodies (see #1278) couldn't be accounted for
I was intending to refactor the validation in to `ReplyToAddressValidator`, but ran out of time. I'll make a ticket for that.
=> [#1278] better no reply address handling

app/views/alaveteli_pro/general/_nav_items.html.erb
Tells the menu bar about the pro controllers for making and viewing batch requests
Otherwise the correct menu tabs were not being shown as selected/highlighted as per the non-batch behaviour.
Closes mysociety/alaveteli-professional#268
=> [pro#268] Highlight menu tabs for batch

app/views/general/_log_in_bar.html.erb, app/views/general/_responsive_topnav.html.erb, spec/views/general/_log_in_bar.html.erb_spec.rb, spec/views/general/_responsive_topnav.html.erb_spec.rb
Uses CanCanCan to check whether a user should be shown pro content in the header and user menu rather than relying on a check for the pro role being assigned as this can miss whether pro is enabled site-wide.
As we have a CanCanCan ability that checks for user presence, feature flag and the pro role, this PR also attempts to standardise on using that in place of the lengthier `@user && @user.pro && feature_enabled(:alaveteli_pro)` style checks.
We were missing the feature flag check for pro being enabled in some places resulting in inconsistent behaviour - sites which have not been configured for pro may show pro content and links (which will 404) to users that have been assigned the pro role.
Affects any site that includes the sample data as that has a mix of pro and non-pro users, or …
=> [pro#173] Check that 'pro' is enabled before showing pro content in the menu bar

Gemfile.lock
Upgrades fast_gettext as far as we can without dropping support for Ruby 2.0.
1.1.x is the last to support Ruby 2.0.0.
No official CHANGELOG but the (fairly short) diff is here:
grosser/fast_gettext@v1.1.0...v1.1.2
=> Bump fast_gettext from 1.1.0 to 1.1.2

app/assets/javascripts/admin.js, app/assets/javascripts/admin/admin.coffee, app/helpers/info_request_helper.rb, app/models/info_request.rb, app/views/admin_request/edit.html.erb, spec/helpers/info_request_helper_spec.rb
1. Prevents the text "this request has been hidden" from appearing against publicly visible requests.
1. Tries to alert admins via tooltip messages that they are leaving "invalid" requests (with a `described_state` of `not_foi` or `vexatious`) visible (this may be a valid choice in some cases although in the UK, the intention is usually to hide the requests).
1. Uses an "Are you sure?" dialog to allow the admin to correct the data if the combination is a mistake. 
It is not clear that setting 2 different attributes is required to hide a request when editing metadata. In the past we have had requests on WDTK that display "this request is hidden" text which then requires and admin to try to find all such requests and manually hide them.
Closes #3584
=> [#3584] Improve handling of 'not_foi' and 'vexatious' requests

app/assets/javascripts/alaveteli_pro/batch_authority_search/results.js
Adding an authority after paginating the batch authority search loses
the current authority selection. This is caused by the search results
losing the `value` of the `js-draft-id` hidden field after loading a new
page of results.
This ensures that element is updated after every refresh of the results
list.
Fixes https://github.com/mysociety/alaveteli-professional/issues/539
---
I'm not sure I've got the `.js-draft-id` scoped correctly, but I tried `$($results, '.js-draft-id').val(DraftBatchSummary.draftId);` and that didn't work.
=> [pro#539] Fix losing draft on pagination

app/assets/stylesheets/responsive/_request_layout.scss
Fixes #4018 (turns out the previous fix, in #4735, only worked for admins!)
Also fixes mysociety/whatdotheyknow-theme#487.
=> Prevent .hidden_message text content hitting bottom of container

app/helpers/admin_raw_emails_helper.rb, app/mailers/request_mailer.rb, app/models/incoming_message.rb, app/models/raw_email.rb, app/views/admin_raw_email/show.html.erb, spec/fixtures/files/bcc-contact-reply.email, spec/helpers/admin_raw_emails_helper_spec.rb, spec/mailers/request_mailer_spec.rb, spec/models/incoming_message_spec.rb, spec/models/raw_email_spec.rb
Some work on improving https://github.com/mysociety/alaveteli/issues/32.
The substantial bits are:
* Add specs for receiving Bcc responses
* Add parsed headers to AdminRawEmailController#show
The latter improves the visibility of Bcc addresses when handling email in the holding pen.
=> [#32] Bcc replies

app/models/info_request_batch.rb, spec/models/info_request_batch_spec.rb
Making this easier to recover from exceptions like: https://github.com/mysociety/alaveteli-professional/issues/523
Allow sending of batches to be resumed
If a exception is raised with `InfoRequestBatch#create_batch!` then it's
not possible to resume and we might be sent out some info requests but
not all.
Needed to add and extra `reload` due to Rails not automatically associating new info requests with the in-memory batch instance. This is strange why switching to an array of public bodies would cause this but it resulted in some unrelated specs breaking.
=> [pro#523] Allow sending of batches to be resumed

Gemfile, Gemfile.lock
We no longer need to pin to 0.18 now that we've dropped support for Ruby 1.9.
Pinned to 0.20 as 0.21 is a preparatory release for v1.0.0 which is not
compatible with Rails 4.2 so 0.21 effectively deprecates ActiveRecord 4.2 as it
brings up warnings for PGconn, PGresult, and PGError.
- [Changelog](https://bitbucket.org/ged/ruby-pg/src/v0.20.0/History.rdoc?fileviewer=file-view-default)
- [Commits](https://bitbucket.org/ged/ruby-pg/branches/compare/v0.20.0..v0.18.4)
=> Bump pg from 0.18.4 to 0.20

app/assets/stylesheets/responsive/_request_style.scss, app/helpers/info_request_helper.rb, app/models/public_body.rb, app/views/admin_public_body/_form.html.erb, app/views/followups/_followup.html.erb, app/views/notification_mailer/info_requests/messages/_very_overdue.text.erb, app/views/notification_mailer/very_overdue_notification.text.erb, app/views/request/_request_subtitle.html.erb, app/views/request/describe_notices/_waiting_response.html.erb, app/views/request/describe_notices/_waiting_response_overdue.html.erb, app/views/request_mailer/very_overdue_alert.text.erb, doc/CHANGES.md, spec/fixtures/files/notification_mailer/daily-summary.txt, spec/fixtures/files/notification_mailer/very_overdue.txt, spec/helpers/info_request_helper_spec.rb, spec/integration/alaveteli_dsl.rb, spec/integration/request_controller_spec.rb, spec/models/public_body_spec.rb, spec/views/followups/_followup.html.erb_spec.rb, spec/views/request/show.html.erb_spec.rb
1. Adds a `PublicBody#not_subject_to_law?` method which allows us to identify authorities which are not subject to FOI law but are still considered eligible to receive information requests (returns true always if `authority_must_respond` has been set to false in config)
1. Alters the status text for "waiting_response_overdue" and "waiting_response_very_overdue" requests from authorities not subject to the law to remove text that states their legal obligation (and link to the #authorities section on the help page instead of #quickly_response)
1. Alters the text for messages shown after classifying a request
1. Alters the text - and help links - that appears when sending a followup message for overdue requests
1. Alters the text in overdue request mailer alerts
1. Alters the text in overdue …
=> [#4499] Prevent requests from authorities tagged as not subject to legislation from showing "By law..." in status text

app/views/alaveteli_pro/dashboard/index.html.erb, app/views/alaveteli_pro/info_requests/index.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/552
Don't render "Get started" help message for pro users who've already sent a batch as it prevents them from seeing their batches and request messages.
=> [pro#552] Limit who sees "Get started" help message

app/assets/stylesheets/responsive/_user_style.scss, app/controllers/admin_user_controller.rb, app/controllers/general_controller.rb, app/controllers/user_controller.rb, app/controllers/user_profile/about_me_controller.rb, app/models/user.rb, app/views/admin_user/_user_table.html.erb, app/views/admin_user/show.html.erb, app/views/user/_show_user_info.html.erb, app/views/user/set_draft_profile_photo.html.erb, app/views/user/set_profile_about_me.html.erb, app/views/user/show/_show_profile.html.erb, app/views/user_profile/about_me/edit.html.erb, lib/tasks/cleanup.rake, lib/tasks/export.rake, lib/tasks/stats.rake, lib/tasks/users.rake, lib/user_stats.rb, spec/controllers/user_controller_spec.rb, spec/controllers/user_profile/about_me_controller_spec.rb, spec/models/user_spec.rb
Connects to #3074 
This adds scopes and methods for working out which user accounts are `active` or `suspended`. These are used instead of the existing calls to the `User#banned?` & `User.not_banned` methods.
This work will make it easier to add a `closed` state to the user accounts which they will be moved into when being anonymised. So `active` accounts will be those not banned and not closed, and `suspended` will be the inverse.
=> [#3074] User anonymisation preporation

app/models/info_request_batch.rb, spec/models/info_request_batch_spec.rb
Fixes #4749 
This should prevent `duplicate key value violates unique constraint`
errors from being raised while running `./script/send-batch-requests`.
Unfortunately we couldn't get this error to occur locally in development
or production environment so writing a spec for this hasn't been
possible.
=> [#4749] Don't re-summarise batch requests until all requests have been created

.github/PULL_REQUEST_TEMPLATE.md
Bullet points in markdown don't work that well when you add paragraph text underneath, which is how this has ended up being used.
Headings are clearer when rendered too.
=> Change bullet list to headings in PR template

app/assets/stylesheets/responsive/_global_layout.scss, app/assets/stylesheets/responsive/_global_style.scss, app/views/alaveteli_pro/info_requests/_sidebar.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/547
On desktop this makes the pro request sidebar sticky on scroll 
Part of improvements to the pro request experience https://github.com/mysociety/alaveteli/issues/4505
Precursor to https://github.com/mysociety/alaveteli-professional/issues/548
This implementation has limited support - especially for Internet Explorer 11 and below (https://caniuse.com/#feat=css-sticky). Support for older browsers will require a polyfill or JavaScript solution, suggest we discuss this.
=> [pro#547] Make the pro request sidebar sticky

app/assets/stylesheets/responsive/_header_layout.scss, app/assets/stylesheets/responsive/_header_style.scss, app/views/general/_log_in_bar.html.erb
Tweak to styling of logged in menu link and pro pill to ensure only the first name is truncated and not the 'pro' label
Fixes https://github.com/mysociety/alaveteli/issues/4780
Reimplements the fix in https://github.com/mysociety/alaveteli/pull/4763 with some changes to ensure the only the user name is truncated and not the contents of  the`pro-pill` element
=> Tweak to styling of logged in menu link and pro pill

app/assets/stylesheets/responsive/_global_layout.scss, app/assets/stylesheets/responsive/_request_layout.scss
Required a spacing change which then made the top of the request page look odd, so I've evened that up too (See screenshots)
Fixes https://github.com/mysociety/alaveteli-professional/issues/545
Adds a gap between the action menu and the sidebar in the mobile view and corrects a knock-on issue on desktop
Status message spacing before
Status message spacing afterwards
Pushing the sidebar higher on the page resulted in the status message looking cramped so I've fixed that here too
=> [pro#545] fix for action menu and sidebar clashing in mobile view

app/views/reports/new.html.erb
Fixes https://github.com/mysociety/alaveteli/issues/4815
Adds a translation helper around an untranslated string.
Allows the form label to be translated.
=> [#4815] Add missing translation wrapper

config/packages, config/packages.generic, config/packages_development
Fixes #4778
Adds imagemagick to package dependency files.
Imagemagick is a dependency of Alaveteli but isn't listed in the package files.
=> [#4778] imagemagick package

app/controllers/alaveteli_pro/subscriptions_controller.rb, app/views/alaveteli_pro/subscriptions/index.html.erb, config/general.yml-example, lib/configuration.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/543.
Allows developers to configure a referral code that's been set up in Stripe to be shown on `/profile/subscriptions` so that existing pro users can give friends or colleagues a signup discount.
We want to encourage our existing users to share Pro with their networks.
* This doesn't perform much error checking that the coupon code has been set up correctly, but I think this is a very beta feature at the moment so I think that's fine?
* The translation string may get a little clunky depending on what discount the site applies. I haven't thought through all the permutations ("1 month free", "first month free", "£5 off", etc), but again, I think this is one with us to live with and adapt to change if it becomes clear where …
=> [pro#543] Subscription page referral code

app/assets/javascripts/alaveteli_pro/request_navigation.js
The correct buttons are now re-enabled when moving between messages in very short threads.
Fixes mysociety/alaveteli-professional#559
=> Properly handle next/previous navigation on 2-message threads

spec/spec_helper.rb
Removes deprecation warning when running specs:
`[DEPRECATION] ::[] is deprecated. Use ::new instead`
Introduced by the update to coveralls 0.8.22 (d644285)
I note that simplecov got bumped from 0.10.0 to 0.16.1 so I'm assuming that's where the warning came from, but as the fix seems reasonable I've not taken the time to dig into [the simplecov repo](https://github.com/colszowka/simplecov) to find out for sure.
=> Fix spec_helper deprecation warning

spec/controllers/info_request_batch_controller_spec.rb, spec/factories/info_request_batches.rb, spec/integration/alaveteli_pro/batch_request_spec.rb, spec/integration/alaveteli_pro/view_batch_request_spec.rb, spec/models/ability_spec.rb, spec/views/notification_mailer/info_request_batches/messages/_embargo_expiring.text.erb_spec.rb
Extracted commits of spec improvements from https://github.com/mysociety/alaveteli/pull/4651
@gbp: "This would've been useful for the work on #4749 as it allows use to create a sent batch from the factory using traits (so we don't need to `create_batch!` in the specs). It is also chainable with other traits (EG `embargoed`) and sets up the relevant associations."
=> [pro#512] Batch spec factory improvements

app/assets/stylesheets/responsive/alaveteli_pro/_requests_layout.scss, app/views/alaveteli_pro/info_request_batches/_info_request_batch.html.erb
Fixes https://github.com/mysociety/alaveteli-professional/issues/561.
The removed style gives batch requests a double-height header, making it
look disjointed compared to single requests.
The class was only used in one place, so I've removed it from the markup
to avoid confusion.
Unify batch and individual request styling.
This looks less good, now I compare them, but this will make https://github.com/mysociety/alaveteli/pull/4835 look better.
=> [pro#561] Remove double-height batch margin

app/assets/stylesheets/responsive/alaveteli_pro/_requests_style.scss
Fixes https://github.com/mysociety/alaveteli-professional/issues/497.
This commit wraps each item in the list in a bounding box, making it
really clear that items are distinct.
When an individual request appears below a batch request in the pro
request list, the individual request visually appears to be _part of the
batch_. This is made even more extreme when the batch is public and the
individual request is private, due to the padlock icon indenting the
individual request title.
Does not address https://github.com/mysociety/alaveteli-professional/issues/561, which will be
addressed separately and make the spacing look better here.
A thicker border-bottom looked messy, as it conflicted with the progress
bar of the batch requests.
=> [pro#497] Distinguish requests vs batches in pro request list

app/assets/stylesheets/responsive/_global_style.scss, app/views/alaveteli_pro/info_requests/_sidebar.html.erb
Resolves some issues with keyboard operation (see https://github.com/mysociety/alaveteli-professional/issues/555 for more details)
Allows the user to switch status with keyboard (on the pro request page)
While working on this I've found a bug with the houdini component we're using for controls like these. I'll open a ticket with details, but the tldr is that it's got some issues with keyboard control that we need to look into
=> Allow users to switch status with keyboard

app/models/info_request_batch.rb, spec/integration/alaveteli_pro/batch_request_spec.rb, spec/integration/alaveteli_pro/request_list_spec.rb, spec/mailers/notification_mailer_spec.rb, spec/models/info_request_batch_spec.rb
Supplemental work on #4749
Depends on #4779 
Closes #4767 
* Improves logic around determine if a batch has completely sent
* Makes it so batch sending so it will be resumed if it exits early (by moving when `sent_at` is set).
Occasional exceptions (#4749) meant some batch requests were not sent straight away.
=> [#4749] Rework batch sending

app/helpers/application_helper.rb, app/views/general/_opengraph_tags.html.erb, doc/CHANGES.md, spec/helpers/application_helper_spec.rb, spec/views/general/_opengraph_tags.html.erb_spec.rb
Closes #4859 
Introduces a check for a theme version of the `logo-opengraph-pro.png` graphic and supplies the standard as a fallback `logo-opengraph.png` image if it's not there.
Otherwise anyone who upgrades their site and enables pro without supplying a pro-specific version of this image will share pro content (including the /pro promo page) with the generic "logo here" version from alaveteli-core.
The `theme_asset_exists?` helper method returns `true` if the asset file is available in core and there is no theme enabled, which seems counterintuitive but broadly follows the terminology of having enabled the "none" theme, which I _think_ is the right thing to do. The opposite argument is that if it immediately returned `false` on realising there's no theme path, it could save the …
=> [#4859] pro opengraph logo fallback

Vagrantfile, doc/CHANGES.md, script/test-vagrant-provisioning
Required by #4615 
1. Updates the Vagrantfile and the `test-vagrant-provisioning` script
1. Updates commonlib
1. The newer commonlib adds support for stretch
1. Our current config no longer works from scratch as the base boxes previously available for download at atlas.hashicorp.com have moved to app.vagrantup.com
1. The test script builds the Vagrant box and spins up a copy of the site then immediately checks that it's available. However it (probably still building/compiling the asset files?) will fail with a `Connection reset by peer` message from curl if called right away rather than either of the expected responses.
=> Update vagrantfile and test script

app/assets/stylesheets/responsive/_public_body_style.scss, app/views/public_body/show.html.erb, app/views/request/_request_subtitle.html.erb, spec/views/public_body/show.html.erb_spec.rb, spec/views/request/show.html.erb_spec.rb
Closes #4814 
* Adds a note to the authority page if the authority has the `foi_no` tag (is not subject to FOI law).
* Moves the note about the authority only being subject to environmental information requests to the top of the page (in the same space and format as the new `foi_no` message
* In the rare cases where both tags are used, `eir_only` takes precedence
* Updates the message added to the top of the request page to have the same messaging and behaviour re `eir_only` vs `foi_no`
Makes it clear from the authority page that a response is not legally mandated. Otherwise the only indicator is on the request page (when viewing the correspondence thread).
Uses the same text as the request page message to reduce the overhead for translation. Placed the message directly below the …
=> [#4814] Display `foi_no` authority note

app/assets/stylesheets/responsive/_header_layout.scss, app/assets/stylesheets/responsive/_header_style.scss, app/views/general/_log_in_bar.html.erb, app/views/general/_responsive_header.html.erb, app/views/general/_responsive_topnav.html.erb
Closes #4858 
Rearranges the header, moves the sign in/up and user menus out of the navigation menu area
Sites with long translation labels were struggling with the limited horizontal space in the old design
Tested with WDTK theme and alaveteli theme and both themes required changes. All themes will likely require styling changes to receive this upgrade
Before
After
Mobile
=> Move logged in menu and links to header

app/views/admin_general/_announcement.html.erb, app/views/alaveteli_pro/dashboard/_announcements.html.erb, app/views/general/_site_wide_announcement.html.erb, spec/views/admin_general/_announcement.html.erb_spec.rb, spec/views/alaveteli_pro/dashboard/_announcements.html.erb_spec.rb, spec/views/general/_site_wide_announcement.html.erb_spec.rb
Fixes #4877 
Uses sanitize when rendering the announcement content rather than putting raw HTML onscreen unfiltered.
To guard against a potential cross-site scripting attack, as notified by brakeman.
The standard set of `sanitized_allowed_tags` from the action_view config should be fine here as we're mostly screening out iframes & script tags.
=> Use sanitize to strip malicious code from admin announcements

_layouts/default.html, _layouts/es/default.html
As we switch to enforcing HTTPS, these generate mixed-content warnings.
The only thing flagged as failing to load due to mixed content in my console were these links, so I think that's all that's needed. 
Fixes https://github.com/mysociety/sysadmin/issues/1067
=> Update links to fonts.googleapis.com to use HTTPS

app/assets/stylesheets/admin.scss, app/models/user.rb, app/views/admin_user/_user_table.html.erb, app/views/admin_user/edit.html.erb, app/views/admin_user/show.html.erb, spec/models/user_spec.rb
Improvements to https://github.com/mysociety/alaveteli/pull/4806
* Moves the button from show to edit in a "Danger Zone" area. This allows a greater explanation of what the button does, and as its not an often-used button, the extra click isn't a problem.
* Only create the censor rule for name if the user has requests
* Addresses comments in https://github.com/mysociety/alaveteli/issues/3074#issuecomment-422776046
* Change redaction text from 'Account Removed' to 'Name Removed'
* …Add a bullet "Does not delete or hide a users' requests".
* Change "Redacts name from requests" to something like "Makes a naive attempt to redact the username from requests".
* This step is presumably, by design, very hard to reverse. That could be stated explicitly.
* Consider a pop up confirmation in line …
=> [#3074] User Anonymisation GR

app/assets/stylesheets/admin.scss, app/controllers/admin_users_account_suspensions_controller.rb, app/controllers/user_controller.rb, app/helpers/admin_users_helper.rb, app/models/user.rb, app/views/admin_user/_user_table.html.erb, app/views/admin_user/edit.html.erb, app/views/admin_user/show.html.erb, db/migrate/20180801085621_add_closed_at_to_users.rb, lib/tasks/graphs.rake, spec/controllers/admin_users_account_suspensions_controller_spec.rb, spec/controllers/user_controller_spec.rb, spec/factories/comments.rb, spec/factories/users.rb, spec/fixtures/users.yml, spec/helpers/admin_users_helper_spec.rb, spec/models/user_spec.rb
Resolves initial and main part of #3074 
- Adds a `closed_at` timestamp to the `User` model
- Update the `User#active?` to return false if the user account has been closed
- Adds `Close and anonymise` button in the admin UI for against active, non-pro, users.
- Creates censor rule before anonymising the user so that obvious uses of the user's name are removed automatically
- Adds missing functionality of hiding requests on profile and wall
To make it easier to handle GDPR requests.
This copies the same general approach as banning users. We might want to consider hiding these buttons under an ability check and prevent `User#close_and_anonymise` calls if the user doesn't have the correct permissions.
The original issue (#3074) said to 404 when viewing a closed user's profile, but this felt …
=> [#3074] User anonymisation

.codeclimate.yml
We're often getting CodeClimate fail PRs because it highlights
duplication in spec code. While I think in general its correct to
analyse specs, I think the "duplication" it points out is often either
helpful for readability, or really difficult to extract out at the
moment.
Currently, exclusions cannot be made for individual maintainability
checks. [1]
[1] https://docs.codeclimate.com/docs/excluding-files-and-folders
I'm only 80% sure of doing this.
I just noticed that it does give nice encouragement for keeping specs clean…
…but on the other hand I think its failing so often for duplication in specs that its becoming noise?
=> Disable CodeClimate for specs

app/controllers/concerns/user_spam_check.rb
We originally set this at 13 so that important combinations (e.g.
`ip_range_is_suspicious?` and `user_agent_is_suspicious?`) would hit the
threshold. Similarly, `email_from_spam_domain?` should automatically hit
the threshold.
`UserSpamScorer` checks that the score is _over_ the threshold though,
so reducing this to 12 means that a score of 13 will now prevent spam.
=> Reduce signin/signup spam score threshold

app/models/user.rb, spec/models/user_spec.rb
https://github.com/mysociety/alaveteli/issues/3148
* Refactoring
* Prevents users with a populated`closed_at` attribute signing in
Quickly enable us to prevent a few specific users from signing in.
`User.authenticate_from_form` is too complex, so needs refactoring, but refactoring the specs was a first step at least.
=> [#3148] Prevent closed users signing in

docs/customising/config.md
* Alters the config documentation to reflect the changed name of the reCAPTCHA config keys
* Replaces the outdated link to recaptcha.net
With release 0.32 we've introduced a new version of the `recaptcha` gem which uses different terminology of the reCAPTCHA public and private keys (now 'site' and 'secret'); we updated our code to match so the docs are out of date.
Also while editing noticed that the recaptcha.net page we were linking to no longer exists.
Should we add a sentence "previously called..." to the docs for re-users on older versions?
=> Update reCAPTCHA key info

app/controllers/track_controller.rb, spec/controllers/track_controller_spec.rb
Fixes #4871 
* Minor refactoring
* Handle a missing param rather than only an invalid param
I expect what's happened in https://github.com/mysociety/alaveteli/issues/4871 is someone has mistakenly "paused" a form submission (clicking "stop" or "back"?) and ended up on https://www.whatdotheyknow.com/track/update/81443. They've then hit reload and as the action responds to GET it submits with no params.
We don't handle that error very well – we try to concatenate `nil` in to a `String` which raises a `TypeError`. This handles that more gracefully.
We'll still get an error if someone does this again, but it will be much more descriptive. To prevent us getting errors at all, we should remove the ability for the action to respond to `GET`.
=> [#4871] Handle nil track_medium param in TrackController#update

app/views/admin_request/show.html.erb
Fix erroneously escaped HTML
At some point the omission links started to get escaped. I initially
thought it was introduced in e283db7, but it may have just been a rails
upgrade that change default escaping behaviour.
In any case, this fixes the problem by using a block to show extra
content when the text is truncated [1]. `omission` itself gets set to an
empty string so that we don't get a double `...`.
Fixes #4905.
Also includes minor refactoring.
=> [#4905] escaped html

lib/tasks/gettext.rake
Adds `remove_fuzzy` rake task for Pro translations
I noticed that there wasn't one (and that the existing `gettext:remove_fuzzy` task is scoped to the locale directory) while I was generating new translations for the release.
Not needed for the release, just making the PR while I think of it/still have the code handy
=> Add gettext:remove_fuzzy_alaveteli_pro

app/controllers/request_controller.rb, app/models/info_request.rb
Connects to #3969 
Replace depricated class and prevent `rescue in <class:InfoRequest>': class or module required for rescue clause (TypeError)` errors.
To allow Rails 5 to boot. Doesn't effect Rails 4 as `MissingSourceFile` is a subclass of `LoadError`.
=> [Rails 5] Fix custom state loading

.travis.yml
https://github.com/mysociety/sysadmin/issues/1078
* Remove "Latest Official 2.3.x" from allow_failures 
* Don't specify patch release of Ruby (so that we build against 2.3.8)
* Add Ruby 2.4.x to Travis config as a non-required build
Check that we can use 2.3.8 in production.
=> Update Travis config for Ruby 2.3.8

lib/acts_as_xapian/acts_as_xapian.rb
#4389
Rescues `NoMemoryError` to provide better cron notification output.
This should help us isolate specific files where we're getting the error so that we can debug further.
`NoMemoryError` isn't a descendent of `StandardError` so we don't get
the enhanced logging.
I couldn't consistently replicate #4389 locally. Duplicating the `ActsAsXapian.update_index` spec and changing `and_raise(StandardError)` to `and_raise(NoMemoryError)` passes, but I felt that's a lot of duplication for essentially the same behavior.
=> [#4389] Rescue NoMemoryError in ActsAsXapian.update_index

app/models/info_request_batch.rb, app/views/alaveteli_pro/info_request_batches/_embargo_form.html.erb, app/views/info_request_batch/show.html.erb, spec/factories/info_request_batches.rb, spec/factories/public_bodies.rb, spec/models/info_request_batch_spec.rb
Fixes #4891.
* Fixes some factories
* Prevents the embargo form iterating through each info request in a batch
* Minor refactoring
The `embargo_form` partial was relying on `all_requests_created?` to
decide whether to disable the change embargo button. On large batches,
this meant iterating through every request in the batch.
Now that `sent_at` is sent after the batch sending is completed rather
than after the first request in the batch was sent (4af4ff4) we can use
`sent_at` to confirm that it is safe to change the embargo.
Decided not to do anything about the "too many methods" check. I agree with it in principle, but there's not that much thats easy to do right now. I'll try to add some TODOs and/or tickets for where I think we can reduce the surface of this class. I'll also try a PR …
=> [#4891] Fix slow batch viewing

app/views/request/describe_notices/_not_held.html.erb
`/new` just redirects to the homepage.
Also update hash style
Noted in https://github.com/mysociety/whatdotheyknow-theme/issues/304.
=> Fix broken URL

Gemfile, config/initializers/rails_5.rb, config/initializers/test_after_commit.rb
Connects to #3969 
Requires #4893 
Stubs TestAfterCommit for Rails 5 to just call the inner block regardless. This allows us to keep the existing spec code for Rails 4 compatibility. Once Rails 5 is merged we'll need to remove the stub and go through the spec suite to remove TestAfterCommit blocks.
Rails 5 doesn't need TestAfterCommit as `after_commit` callbacks are automatically run.
Unused if having this in the initializer directory is the best places for these stubs. Happy to move if there is a better place.
=> [Rails 5] Stub TestAfterCommit

app/controllers/admin_outgoing_message_controller.rb, app/views/admin_outgoing_message/edit.html.erb, app/views/admin_request/show.html.erb, doc/CHANGES.md, spec/controllers/admin_outgoing_message_controller_spec.rb, spec/integration/admin_outgoing_message_edit_spec.rb, spec/views/admin_request/show.html.erb_spec.rb
Closes #4760 
* Uses `OutgoingMessage#raw_body` as the source of the editable message on the admin screen for editing outgoing messages so that the version of the text without the censor rules applied is shown.
* Appends `raw_body` data to the accordion view of the outgoing message on the `admin_request#show` page so that admins can see the original message data
* Sets the `raw_body` data as if it were the `body` data `InfoRequestEvent#params` when an update is made so that the original version of the text will appear in the event log going forward
Includes some minor code tidying to improve readability re param indenting and line length.
Admins were unable to edit outgoing messages with applicable censor rules without permanently applying redactions to the stored message. They were also …
=> [#4760] Don't apply censor rules to outgoing messages on the admin page

app/controllers/help_controller.rb, config/general.yml-example, doc/CHANGES.md, lib/configuration.rb, spec/controllers/help_controller_spec.rb
Closes #4865 
* Adds a `CONTACT_FORM_RECAPTCHA` config key so that the help controller knows whether to attempt to valid a reCAPTCHA on form submit
* Adds a `HelpController#recaptcha_required?` method that a theme can override if there are extra conditions - such as checking the originating IP of the request for a particular site
WDTK has started getting a high level of spam through the contact form so we wanted to add reCAPTCHA as a deterrent but without forcing it on to every Alaveteli instance.
Does this need a config key? Is that clearer than just having a `recaptcha_required` method in the controller or just more work for a reuser? (Some work required in all cases as there's no contact form in Alaveteli core, it's always implemented by the theme.)
Add a description of the new config …
=> [#4865] Enable optional reCAPTCHA on contact form

app/controllers/alaveteli_pro/stripe_webhooks_controller.rb, spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb, spec/fixtures/stripe_webhooks/customer.subscription.updated-cancelled.json, spec/fixtures/stripe_webhooks/customer.subscription.updated-renewed.json, spec/fixtures/stripe_webhooks/customer.subscription.updated-trial-end.json, spec/support/stripe_helpers.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/564
* Lots of refactoring of `AlaveteliPro::StripeWebhooksController`
* Adds a handler for a specific case of `customer.subscription.updated` to ignore new billing period webhooks.
New billing period webhooks require no action, but we're getting notified at a pretty frequent rate, which just adds noise to our exception notifications.
Lots of the refactoring took inspiration from early commits of https://github.com/mysociety/alaveteli/compare/pro564-renewed-stripe-webhooks. I did attempt to pull in the class-based approach, but it was getting pretty complex to implement in a well-tested way.
I ran out of time, so I implemented in a dumber way, but hopefully the cleanup I've done here will help make the next steps to pulling …
=> [pro#564] Handle new billing period webooks

app/views/public_body/show.html.erb, app/views/request/_request_subtitle.html.erb, spec/views/public_body/show.html.erb_spec.rb, spec/views/request/show.html.erb_spec.rb
Closes mysociety/whatdotheyknow-theme#525
Updates the EIR only wording show to users when an authority is only obliged to answer EIR requests
Clarifies the legal status of non-EIR requests (although we permit FOI requests via the site, EIR only authorities have no obligation to respond to anything other than EIR requests)
=> [wdtk#525] Update EIR only wording

Vagrantfile
Otherwise it only listens on the guest's localhost, so would be inaccessible from the host machine.
=> Add -b option to rails server examples

app/controllers/alaveteli_pro/stripe_webhooks_controller.rb, app/mailers/alaveteli_pro/subscription_mailer.rb, app/views/alaveteli_pro/subscription_mailer/payment_failed.text.erb, spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb, spec/fixtures/alaveteli_pro/subscription_mailer/payment_failed, spec/mailers/alaveteli_pro/subscription_mailer_spec.rb, spec/support/load_file_fixtures.rb, spec/views/alaveteli_pro/subscription_mailer/payment_failed.text.erb_spec.rb
Fixes https://github.com/mysociety/alaveteli-professional/issues/441
* Adds `AlaveteliPro::SubscriptionMailer#payment_failed`, which sends a "payment failed" notification to a given `User`.
* Handle the `invoice.payment_failed` Stripe webhook by sending a `#payment_failed` email to the `User`.
Less manual admin work, and manual mails started to get sent to spam.
There's some duplication around `auto_generated_headers`, but I'm not clear on how we solve that. I've created https://github.com/mysociety/alaveteli/issues/4938 to start thinking about it.
=> [pro#441] Handle invoice.payment_failed Stripe webhook

app/assets/javascripts/admin/admin.coffee, app/controllers/services_controller.rb, app/helpers/admin_requests_helper.rb, app/models/info_request/state.rb, app/views/admin_request/_hidden_user_explanation_reasons.html.erb, app/views/admin_request/hidden_user_explanation.text.erb, app/views/admin_request/hidden_user_explanation/_not_foi.text.erb, app/views/admin_request/hidden_user_explanation/_personal_information.text.erb, app/views/admin_request/hidden_user_explanation/_vexatious.text.erb, app/views/admin_request/show.html.erb, doc/CHANGES.md, spec/controllers/services_controller_spec.rb, spec/fixtures/admin_request/hidden_user_explanation, spec/helpers/admin_requests_helper_spec.rb, spec/integration/admin_spec.rb, spec/models/info_request/state_spec.rb, spec/views/admin_request/hidden_user_explanation.text.erb_spec.rb
Fixes #3543
* Refactors the construction of the hide request reasons
* Extracts components in to partials so that they're easier to override in themes
* Makes it easier to add custom messages for a given state
* Adds personal correspondence as a default option, putting the request in to a `not_foi` state
Users including personal information is a common occurrence, so something admins often need to hide.
As described in the commit message, the `hidden_user_explanation` helper is not ideal, but its more of a stopgap until we implement https://github.com/mysociety/alaveteli/issues/4688.
=> [#3543] Hide personal information

app/mailers/alaveteli_pro/subscription_mailer.rb, spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb, spec/mailers/alaveteli_pro/subscription_mailer_spec.rb
These end up getting routed to the `FORWARD_NONBOUNCE_RESPONSES_TO`
address, as BCC hides the `PRO_CONTACT_EMAIL` from
`ReplyHandler.get_forward_to_address` due to our internal routing.
In any case, we'll still get the `customer.subscription.updated` webhook
which sets the subscription to `past_due`, so we can use that as the
"FYI" email that a payment has failed.
=> Don't BCC the pro team on failed payment emails

Gemfile.lock
Addresses CVE-2018-16471.
Doesn't look like we're affected as we don't call `scheme` on a
`Rack::Request` directly.
https://groups.google.com/forum/#!topic/rubyonrails-security/GKsAFT924Ag
=> Bump rack version

app/controllers/user_controller.rb, app/views/user/contact.html.erb, config/general.yml-example, doc/CHANGES.md, lib/configuration.rb, spec/controllers/user_controller_spec.rb, spec/integration/send_user_message_spec.rb
Fixes #4939 
Allows site owners to optionally use reCAPTCHA on the user-to-user contact form (uses a new config setting `USER_CONTACT_FORM_RECAPTCHA` which defaults to false - i.e. no captcha shown).
We've seen some spam being sent with this method so this is a simple first step to making it harder to do so casually - or with a script - but without massively inconveniencing genuine users.
No theme override needed to use this on the basis of the config key alone on this one as the necessary template is included in Alaveteli core.
=> [#4939] Add reCAPTCHA to user-to-user contact form

Gemfile, Gemfile.rails5.lock, app/controllers/admin_public_body_headings_controller.rb, app/controllers/announcements_controller.rb, app/controllers/application_controller.rb, app/controllers/widget_votes_controller.rb, app/controllers/widgets_controller.rb, app/models/holiday.rb, app/models/incoming_message.rb, app/models/info_request_batch.rb, app/models/mail_server_log.rb, app/models/post_redirect.rb, app/models/track_things_sent_email.rb, config/application.rb, config/environments/test.rb, db/migrate/028_give_incoming_messages_events.rb, gems/alaveteli_features/lib/alaveteli_features.rb, lib/acts_as_xapian/acts_as_xapian.rb, lib/has_tag_string/has_tag_string.rb, spec/controllers/admin_public_body_headings_controller_spec.rb, spec/controllers/alaveteli_pro/base_controller_spec.rb, spec/controllers/help_controller_spec.rb, spec/models/info_request_spec.rb
Connects to #3969
* Fixes some essential bits of the Rails5 config allowing the test suite to run.
* Aims to reduce the deprecation warnings which are making it hard to see what we actually need to fix.
A bit scrappy at the moment, still seeing what works
=> [Rails 5] Reduce deprecation warnings

app/controllers/admin_raw_email_controller.rb, app/models/incoming_message.rb, app/models/info_request.rb, app/models/raw_email.rb, app/views/admin_incoming_message/_actions.html.erb, app/views/admin_raw_email/show.html.erb, doc/CHANGES.md, lib/mail_handler/backends/mail_backend.rb, spec/controllers/admin_raw_email_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/lib/mail_handler/backends/mail_backend_spec.rb, spec/models/incoming_message_spec.rb, spec/models/info_request_spec.rb, spec/models/raw_email_spec.rb, spec/support/email_helpers.rb
Fixes #162 
This ended up being a big PR for a pretty small change (c4ecbb85d).
In short, this PR:
* Refactors `IncomingMessage` and `RawEmail` to reduce exposure of the underlying `Mail` instance.
* Includes invalid email addresses when guessing for an `InfoRequest` in the holding pen.
Increasing the range of addresses that we can parse reduces manual volunteer work. Obvious win :+1:.
The refactoring was needed to make it easy to make the change that supported this.
Most of the refactoring was just pushing methods down the stack to improve encapsulation and reduce coupling across this part of the system.
This reduces the surface area of `IncomingMessage` so that we're not reaching across associations all the time.
Several of the methods added to `IncomingMessage` are internal, so they …
=> [#162] Improve holding pen guessing

script/parse-unparsed-pro
We use scripts to run tasks from cron, because `bundle exec` needs to be
executed from the app directory, but the crontab's working directory is
different.
Forgot to add in https://github.com/mysociety/alaveteli/pull/4920.
Related to https://github.com/mysociety/alaveteli/issues/4919.
=> Add script to run parse_unparsed_pro from cron

app/views/comment/_single_comment.html.erb, app/views/request/_incoming_correspondence.html.erb, app/views/request/_outgoing_correspondence.html.erb
#419 
Adds "report" buttons to incoming and outgoing correspondence bubbles
Hopefully reduces amount of general support mail that requires admin to figure out which request people are referring to when reported.
Also makes the issue visible in the admin interface.
As noted, the `incoming_message_id` and `outgoing_message_id` params don't do anything right now, but I'll make some tickets for that.
Note that I've made a theme PR to remove the blue from report buttons at https://github.com/mysociety/whatdotheyknow-theme/pull/538.
=> [#419] Encourage reporting correspondence through the request page

app/models/info_request.rb, app/views/followups/_followup.html.erb, doc/CHANGES.md, spec/controllers/followups_controller_spec.rb, spec/models/info_request_spec.rb, spec/views/followups/_followup.html.erb_spec.rb
Closes #426
* Prevents alternative contacts from being displayed where there are no authority responses
* Prevents duplicate contacts from earlier responses inadvertently being included
* Adds some extra specs to describe the behaviour of `InfoRequest#who_can_followup_to`
We occasionally show "alternative contacts" when there is only a single option, which is confusing.
=> [#426] Only show alternative contacts where this is helpful

lib/data_export.rb, lib/tasks/export.rake, spec/lib/data_export_spec.rb
1. Fixes bug where Regex chars in user names (e.g. `*`, `(`) broke the anonymise function
2. Recommends capturing task output
1. Broken data exports are bad
2. I forgot to capture the output on first attempt and had to re-run something that's a "come back tomorrow" task as that's where the error output (as well as the progress updates) get sent
=> Export fixes

app/mailers/contact_mailer.rb, app/models/public_body_change_request.rb, spec/mailers/contact_mailer_spec.rb, spec/models/public_body_change_request_spec.rb
Connects to #1764
* Uses the original subject line to set the suggested subject for admin replies to requests for updates/additions to authorities
* Moves the construction of the subject lines from `ContactMailer` to `PublicBodyChangeRequest`
* Simplifies `ContactMailer` to use a single method to deal with sending response to both types of change request
* Minor spec tidy up
Using unrelated subject lines for the initial request and the response was making it harder for admins to follow a change request conversation over email as the they did not appear in a single conversation thread.
The ticket mentions improving threading for requests for admin attention as well as change requests but I have …
=> [#1764] Improve email threading when responding to change requests

app/models/info_request_batch.rb
Fixes #4976 
Optimise loading of public bodies to use a single SQL query instead of one for each body.
This method is being called often. 1. When creating the batch 2. When updating summaries.
=> [#4976] Refactor `InfoRequestBatch#sent_public_bodies`

.ruby-style.yml
I'm often seeing Hash style violations that I'd comment on, so enabling these rather than deliberating whether to comment in PR reviews.
After merge, we should expect to clean up existing violations before making changes.
=> Add checks for Hash style

.ruby-style.yml
Use proc instead of Proc.new
Enforcing https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/Proc
=> Use proc instead of Proc.new

app/models/info_request.rb, spec/models/info_request_spec.rb
Fixes https://github.com/mysociety/alaveteli/issues/4996.
Adds stricter Integer conversion to `InfoRequest.guess_by_incoming_email`.
When we attempt to guess an `InfoRequest` by a malformed email address,
we may pass a malformed ID to `_extract_id_hash_from_email`.
`to_i` will strip any letters from the end of a `String` that starts
with numerical values.
'123ab'.to_i
This causes a transient spec failure when `FactoryBot` creates an
`InfoRequest` with the id `123` by chance, and this liberal conversion
results in us matching the request by `:id` instead of the expected
`:idhash`.
I've chosen to be strict here – rather than trying to parse out a
numeric value with a Regexp – because I think
`_extract_id_hash_from_email` should ether be able to extract the value
from the known format or …
=> [#4996] Be stricter about Integer conversion

app/controllers/admin_raw_email_controller.rb, app/models/info_request.rb, app/views/admin_raw_email/show.html.erb, doc/CHANGES.md, spec/controllers/admin_raw_email_controller_spec.rb, spec/models/info_request_spec.rb
Closes #118
* Attempts to match emails that come in to the holding pen:
* where the subject line looks like a reply to the `initial_request` email
* where the subject line matches - or is a reply to - an existing subject line of an `IncomingMessage`
(avoids returning matches that are in the holding pen)
* Makes `InfoRequest::Guess` more general to accommodate subject as well as email address matches, hopefully without altering the original intent
To improve automated guessing of emails that end up in the holding pen to reduce the amount of manual effort/searching required by the site admins.
A direct match...
...with the new wording for not-email-address guesses...
The `where(subject: …
=> [#118] Improve holding pen guessing by subject

spec/fixtures/info_requests.yml
* Sets a unique idhash for each info_request fixture
* Pads the one which was only 7 chars
These appear to be mistakes rather than deliberate test cases
They were not unique and one was too short (7 chars instead of 8).
The short idhash tripped me up while I was manually testing new idhash matching code as I unluckily ended up testing against a request with an invalid 7 char idhash which resulted in me getting an unexpected result:
```rb
[111, "b23457a"]
[11, "1b234567"]
```
=> Fix idhash values in info_request fixtures

app/controllers/admin_raw_email_controller.rb, app/models/info_request.rb, spec/models/info_request/response_rejection/holding_pen_spec.rb, spec/models/info_request_spec.rb
Adds a method for interrogating `InfoRequest` instances to find whether
they're the holding pen.
Reduces logic outside of models and removes duplication of `info_request
== InfoRequest.holding_pen_request`.
Returns early if the `url_title` attribute is the known holding pen
value (no point in an extra query if we already know its the holding
pen), otherwise compares against the looked-up record.
=> Add InfoRequest#holding_pen_request?

Gemfile, Gemfile.lock, Gemfile.rails5.lock
Connects to #3969
Lock Mail gem to 2.6.x
There are breaking changes in 2.7 which will require specs to be updated.
=> [Rails 5] Lock Mail gem to 2.6.x

app/controllers/admin_outgoing_message_controller.rb, app/controllers/followups_controller.rb, app/models/info_request.rb, doc/CHANGES.md, spec/controllers/admin_outgoing_message_controller_spec.rb, spec/controllers/followups_controller_spec.rb, spec/models/info_request_spec.rb
Closes #3080
Closes #863 
Closes #1335 
Closes #2953
* Adds some specs for when admins resend an outgoing message
* Adds a convenience method to `InfoRequest` to reopen a request to new responses (sets `allow_new_responses_from` to 'anybody' and `reject_incoming_at_mta` back to false)
* Calls the new `reopen_to_new_responses` method as part of the send and resend method 
I've added some specs for assurance / make it less likely we'll break it without realising but I think the closing-after-a-new-response issue noted in the tickets has already been solved by `OutgoingMessage#record_email_delivery` which causes the related request's `updated_at` attribute to get updated (resetting the "countdown" to when it will close to new responses).
(Unlike the calculations for `old_unclassified` which …
=> [#3080] Reopen request to new responses when [re]sending outgoing messages

app/helpers/public_body_helper.rb
Fixes: #5019 
Spec could fail when the PublicBodyCategory are returned out of order.
=> [#5019] Fix transient spec failure

.travis.yml
Bundler 2.0 drops support for Ruby < 2.3 so we can remove this
restriction and upgrade to the lastest version when 2.3 becomes our
lowest supported version.
This works around the problem by explicitly telling Travis to install a < 2.0 gem version.
(Not entirely sure why the stock gemset also fails for Ruby 2.3.7 but works for 2.1.5 but ... hey. Something something caching. Maybe.)
Travis builds for Ruby 2.0 (and slightly bafflingly 2.3) were [failing, unable to install bundler](
https://travis-ci.org/mysociety/alaveteli/jobs/474857943) since the new version was released https://github.com/bundler/bundler/releases/tag/v2.0.0
It looks like, because of the new gem requirements, the "RVM" portion of Travis's build script fails to build bundler into the stock gemset:
```
Requirements …
```
=> Fix Travis builds (make Travis install bundler < 2.0)

app/controllers/followups_controller.rb, spec/controllers/followups_controller_spec.rb
Fixes #5034
Prevents pro users from being served a 404 when they try to access the followup/reply page for a public request they do not have ownership of.
Provided an inconsistent experience for Pro users and made it impossible for admins with Pro status to view/check the followup page for other people's public requests.
=> [#5034] Allow Pro users to see followup form for other users' public requests

config/packages, config/packages.generic
Connects to #5040
Switches back to the `geoip-database` package (from `geoip-database-contrib`) as this packages the GeoLite data files whereas `-contrib` tries to download fresh copies from MaxMind's servers. (h/t @gbp for the suggested fix)
[MaxMind deprecated the v1 GeoLite files as legacy in 2018](https://support.maxmind.com/geolite-legacy-discontinuation-notice/) with a view to removing them from the site on Jan 2nd 2019. It appears that the files became unavailable during their [Jan 7th maintenance window](https://dev.maxmind.com/release-note/server-ip-changes-january-2019/); the download urls are currently returning a 404.
This prevents the package from installing which breaks new installs including VM builds and CI runs.
Only a temporary solution as we don't want to rely on cached …
=> Switch back to the geoip-database package

app/helpers/admin_helper.rb, app/views/admin_request/show.html.erb, doc/CHANGES.md, spec/helpers/admin_helper_spec.rb
A quick improvement, related to https://github.com/mysociety/alaveteli/issues/4915.
Doesn't entirely tackle all the issues mentioned in https://github.com/mysociety/alaveteli/issues/4915, but brings `prominence` in line with https://github.com/mysociety/alaveteli/pull/4525/commits/57a8f2f869c14aaa92c8769e948205c3d7e11b9c.
Highlights the prominence setting of requests and messages in the admin
interface, similar to how we highlight 'allow new responses from'.
Only highlights non-default cases.
Makes it easier to spot requests in a non-default prominence state
**Request:**
---
---
---
**Outgoing Messages:**
**Incoming Messages:**
=> Highlight prominence in admin interface

deployments.md
Update link to Informini
The previous link wasn't working due to SSL errors on the non www subdomain version of the site.
=> Update link to Informini

app/helpers/link_to_helper.rb, app/views/general/_locale_switcher.html.erb, spec/helpers/link_to_helper_spec.rb
Required by #3969  
Stops the following error message which was being outputted for many controller and integration specs:
`Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.`
Parameters weren't sanitized before being reused in `url_for`. Now we strip the problematic parameters and ensure we only ever return paths and not full URLs with protocol, host etc...
This was being outputted so often the Travis log was being truncated. Hopefully with this we can see how many specs are still failing.
=> [Rails 5] Add `current_path_with_locale` helper

app/views/followups/_choose_recipient.html.erb, app/views/followups/_followup.html.erb, spec/views/followups/_followup.html.erb_spec.rb
Closes #4985
* Prevents the followup form - or part thereof - from being displayed when the request is closed to new responses
* Moves the complex logic for displaying recipient choices into its own partial to make the main logic flow easier to see, and reduce complexity of theme overrides
* Improves readability of template - better line wrapping, modern hash syntax
* Rendering a broken page or a form that can't be submitted is a poor user experience and generates extra work for site admins to work out what happened
* Aims to make the template easier to work with in the future
The form is overridden by the WDTK theme so it will need this to implement the fix
https://github.com/mysociety/whatdotheyknow-theme/pull/557
=> [#4985] Prevent the followup form being rendered for closed requests

app/assets/stylesheets/admin.scss, app/views/admin_general/_to_do_list.html.erb, doc/CHANGES.md, spec/controllers/admin_general_controller_spec.rb, spec/factories/comments.rb, spec/views/admin_general/_to_do_list.html.erb_spec.rb
Closes #4564
Requires #4965 
* Shows the message from the user (if any, otherwise the text "None given") on the admin summary when a request has been marked as `requires_admin`, `error_message`, or `attention_requested`
* Additionally shows the report reason for `attention_requested` requests
To make it easier for admins to work out what's gone wrong with requests reported as requiring admin attention / in an error state
...and following feedback...
~~Full spec run passes locally, CI currently down because of a problem getting the MaxMind geo data (breaks the build)~~ Rebased on top of fixed `develop` branch
=> [#4564] Show message from user in the admin interface for requires_admin requests

spec/script/mailin_spec.rb
Sets `use_transaction_test=` instead of `use_transactional_fixtures=` when running under Rails 5 (to avoid the deprecation warning). Rails 4 convention retained as the new method is not backwards compatible.
Warning output:
```
DEPRECATION WARNING: use_transactional_fixtures= is deprecated
and will be removed from Rails 5.1 (use use_transactional_tests= instead)
```
=> [Rails 5] Avoid Rails 5 deprecation warning for use_transactional_fixtures

spec/models/info_request_spec.rb
Calls `destroy_all` on the results of a query instead of passing parameters to `destroy_all`  (deprecated in Rails 5.0)
Warning output:
```
DEPRECATION WARNING: Passing conditions to destroy_all is deprecated
and will be removed in Rails 5.1. To achieve the same use
where(conditions).destroy_all.
```
My fault - sorry!
=> [Rails 5] Avoid Rails 5 deprecation warning for passing conditions to destroy_all

app/models/info_request.rb, app/models/info_request/sluggable.rb, db/migrate/039_request_url_names.rb
Fixes #4975
This now does a single DB query to work out the next number suffix when
requests have the same title - EG batch requests.
```rb
InfoRequest.where('url_title LIKE ?', 'batch_test%').map(&:url_title)
=> ["batch_test", "batch_test_2"]
```
```rb
InfoRequest.new(title: 'batch test')
(0.2ms)  SELECT COUNT(*) FROM "info_requests" WHERE "info_requests"."url_title" = $1  [["url_title", "batch_test"]]
(0.2ms)  SELECT COUNT(*) FROM "info_requests" WHERE "info_requests"."url_title" = $1  [["url_title", "batch_test_2"]]
(0.3ms)  SELECT COUNT(*) FROM "info_requests" WHERE "info_requests"."url_title" = $1  [["url_title", "batch_test_3"]]
=> #<InfoRequest … url_title: "batch_test_3">
```
```rb
InfoRequest.new(title: 'batch test')
(0.4ms)  SELECT "info_requests"."url_title" FROM …
```
=> [#4975] Refactor URL title generation

app/models/info_request.rb, spec/models/info_request_spec.rb
Replacement for #5051 with a clearer commit history for the refactor of `InfoRequest#index_of_last_described_event`
* Rewrites `InfoRequest#index_of_last_described_event` to avoid use of `each_index`
* Refactors `InfoReuest#index_of_last_described_event` to make better use of `each_with_index` and remove some unnecessary variable assignments and only calculating values when needed
* Improves the specs for `InfoRequest#last_event_id_needing_description` (which relies on a call to `InfoRequest#index_of_last_described_event` so removing method stubs and mock models was directly useful here)
* Makes `InfoRequest#index_of_last_described_event` a private method as it's not called outside `InfoRequest` (and probably shouldn't be as it describes the internal state of the object) …
=> [Rails 5] Don't call `each_index` directly on an ActiveRecord Relation

spec/models/has_tag_string_tag_spec.rb
Fixes the specs for `HasTagString::HasTagStringTag` which break under Rails 5
Rails 5 detects that the automatically constructed index name is longer than the 63 character limit and fails to create the table (migration code is inside the spec file). All affected specs fail with:
```
ArgumentError:
Index name 'index_globalize_model_with_tag_translations_on_globalize_model_with_tag_id'
on table 'globalize_model_with_tag_translations' is too long;
the limit is 63 characters
```
=> [Rails 5] Fix broken HasTagStringTag specs

app/models/mail_server_log.rb
Fixes #5073 
Uses the new `[name_of_attribute]_will_change!` method instead of `save_changed_attribute` when forcing a value change.
`save_changed_attribute` was removed from the `ActiveRecord::AttributeMethods::Dirty` API in Rails 5
=> [Rails 5] Use `delivery_status_will_change!` to tell Rails to update the attribute

config/general.yml-example
Update recaptcha site URL
Old one was out of date – missed when doing https://github.com/mysociety/alaveteli/pull/4889
=> Update recaptcha site URL

config/general.yml-example
Followon from https://github.com/mysociety/alaveteli/pull/5083
Add note about reCAPTCHA version constraints.
We currently use V2, so that's the type of key you need to generate.
=> Add note about reCAPTCHA version constraints.

app/mailers/request_mailer.rb, app/mailers/track_mailer.rb
Fixes #5075 
Uses `*_url` mailer helpers with `only_path: true` (to retain the original functionality) in place of `*_path`.
Fixes spec errors of the type:
```
NoMethodError:
undefined method `show_request_path' for #<RequestMailer:0x000000000df16fa0>
Did you mean?  show_request_url
```
The `*_path` helpers are no longer available to  mailers in Rails 5
=> [Rails 5] Use *_url helpers in mailers instead of *_path

app/assets/stylesheets/responsive/_header_style.scss
Closes #5113
Removes the hard coded `/assets/` prefix from the CSS stylesheet, allowing the `assets:precompile` rake task to pick up and compile search.png
Browsing a production build that used search.png (such as the default theme) and compiled assets would invoke a 404 as it was not built into `public/assets/`
None
None, observe change to `responsive/application-[hash].css` and the resulting inclusion of `search-[hash].png` in the public assets folder.
=> Fix search.png to be compiled in assets:precompile

app/controllers/alaveteli_pro/stripe_webhooks_controller.rb, spec/fixtures/stripe_webhooks/customer.subscription.updated-renewed.json
It looks as though Stripe are now including `latest_invoice` in the
`previous_attributes` data of renewal webhooks. Between 17:15:58 and
20:02:01 on 22/02/2019, the Event description changed from "[customer]
has started a new billing period" to "[customer]'s subscription has
changed" and includeing the new attribute. This behaviour appears to be
consistent across paid and discounted subscriptions.
We were using the previous check to avoid sending support emails for unhandled Stripe Event webhooks for "renewals" (i.e. the billing period rolling over to the next month) as we only want to be notified if something unusual happens that we might need to react to.
Assumes that this is a permanent change and that we don't
have to look for renewals with and without `latest_invoice`.
I haven't …
=> Update the check for a Stripe renewal to include latest_invoice

app/controllers/application_controller.rb
Fixes #5087 
* Stops Rails 5 raising a `ArgumentError (wrong number of arguments (given 0, expected 1)` error when calling the `form_tag` helper with a logged in user
* Updates our override of `form_authenticity_token` so that is works as expected with Rails 4.2 and Rails 5.0
* Rails 5.0 wasn't working properly with forms when logged in to the site (see above)
* We were mistakenly running the old Rails 4.1 code for generating CSRF tokens against Rails 4.2+, unintentionally bypassing the newer `masked_authenticity_token` code - this may have been a contributing factor to the high number of `InvalidAuthenticityToken` errors we've been seeing in production (#4484)
This whole override appears to be the cause of the `InvalidAuthenticityToken` problem (at least in the case of passing in a blank …
=> Make our custom form_authenticity_token behaviour call the Rails method

app/controllers/admin_public_body_controller.rb, app/views/admin_public_body/edit.html.erb, doc/CHANGES.md, spec/controllers/admin_public_body_controller_spec.rb, spec/views/admin_public_body/edit.html.erb_spec.rb
Closes #5070 
* Disables the "Destroy {authority_name}" button when it's unavailable rather than hiding it
* No longer translates the button text
* Provides title text explaining why the button has been disabled
* Small bits of code tidying
* Moved a couple of tests that check HTML output from controller to view specs
Now that we have embargoed requests - which are invisible to non-Pro admins - it's confusing when the Destroy button is not displayed and there are apparently no requests blocking the destroy function.
Hopefully this is a bit clearer.
=> [#5070] Disable destroy authority button

app/models/info_request/sluggable.rb, doc/CHANGES.md, spec/models/info_request_spec.rb
Fixes #5140
Avoids unintentionally assigning a new suffix number to the url of an
existing `InfoRequest` that's in the middle of a sequence (we've seen this
in production with batch requests, but it applies to any `url_title` with
a numerical suffix)
When we update a request metadata in the admin interface, we [call `@info_request.update_attributes(info_request_params)`](https://github.com/mysociety/alaveteli/blob/d5f659e029b440727b9341fce8429389a8edd2cb/app/controllers/admin_request_controller.rb#L54) which always tries to update `InfoRequest#title` even if it hasn't changed, unintentionally renumbering mid-sequence `url_title` sequential suffixes. This results in broken URLs for the affected requests.
=> [#5140] Only update InfoRequest#url_title if the title has changed

spec/integration/alaveteli_pro/request_creation_spec.rb, spec/integration/create_request_spec.rb, spec/integration/request_controller_spec.rb, spec/integration/user_profile_updates_spec.rb, spec/views/alaveteli_pro/dashboard/_projects.html.erb_spec.rb
* Allows for non-normalised whitespace in specs
* Removes trailing whitespace from expectations
* Allows optional (and variable) whitespace in clickable links (e.g. on the Pro dashboard)
Our Rails 5 specs load capybara v3 (rather than v2) which [no longer normalises whitespace by default](
https://stackoverflow.com/a/54672926), which broke some of our specs.
=> [Rails 5] Fix capybara specs

app/controllers/application_controller.rb, app/helpers/link_to_helper.rb
Fixes #5074
Permits valid parameter key before they're passed into `url_for` 
Avoids Rails 5 raising `ArgumentError: Attempting to generate a URL from non-sanitized request parameters!`
=> [Rails 5] Prevent `non-sanitized request parameters!` errors

spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb, spec/support/stripe_helpers.rb
Fixes #5078 
* Refactors `stripe_webhooks_controller_spec.rb` (mostly to remove repetition)
* Uses the real Stripe method of computing signatures instead of recreating it ourselves
* Converts the mock payload into a hash rather than a string for Rails 5 tests (otherwise we get `undefined method symbolize_keys` errors - presumably a change to how controller params are handled)
* When creating a signature, converts the mock payload to a JSON representation of a string for Rails 5 (otherwise the string representation of our payload used when constructing the signature uses hashrockets and line breaks and doesn't match Stripe's expectation)
* Check against shorter versions of email subject lines as these are getting truncated under Rails 5
* Fixes 27 failing Rails 5 specs
* Stripe specs were …
=> [Rails 5][#5078] Fix stripe spec errors

about.md, community/index.md, docs/running/adwords.md
Part of wider quest to remove offers of support we aren't currently able to provide, and direct people towards community mailing lists rather than emailing mySociety directly (and the international email address in particular).
=> Small copy updates for documentation site

app/controllers/application_controller.rb, app/controllers/concerns/hashable_params.rb, app/controllers/concerns/translatable_params.rb, app/controllers/followups_controller.rb, spec/controllers/concerns/hashable_params_spec.rb, spec/controllers/concerns/translatable_params_spec.rb, spec/controllers/public_body_controller_spec.rb, spec/controllers/request_controller_spec.rb
Fixes #5057 
Handles the new `ActionController::Parameters` using Rails 5 safe methods like `merge!` and `to_unsafe_h` rather than `update, `clone` and direct comparisons with Hash objects. Prevents a deluge of deprecation warnings from appearing in spec output.
Rails 5 raises deprecation warnings when trying to treat parameters as if they were Hashes.
Subtlety/annoyance - blindly calling `.to_unsafe_h` on params, a) doesn't work in Rails 4, b) sometimes fails in Rails 5 as calling params can return either an instance of `ActionController::Parameters` or `{}` _sigh_
No, I'm not convinced that `HashableParams` is the right name for it either - would `ParamsHelper` be better or is it too easily confused with the Rails naming convention for View helpers? Suggestions welcomed.
=> [Rails 5] Fix Rails 5 parameter deprecation warnings

app/controllers/admin_user_controller.rb
Requires #5087 (too hard to test in browser otherwise)
Prevents Rails 5 raising a deprecation warning for `redirect_to :back`
```
DEPRECATION WARNING: `redirect_to :back` is deprecated and will be
removed from Rails 5.1. Please use
`redirect_back(fallback_location: fallback_location)` where `fallback_location`
represents the location to use if the request has no HTTP referer information.
(called from modify_comment_visibility at 
./app/controllers/admin_user_controller.rb:114)
```
=> [Rails 5] Redirect to the user admin page after updating comment visibility

spec/views/outgoing_mailer/initial_request.text.erb_spec.rb
Fixes #5118 
Updates the initial request mailer spec so that the expected email address is passed into the template properly
Under Rails 5, the stubbed `request_email` method was not being called when the public body was accessed as a relation. Setting the value in the initial data setup avoids the need for a stub without affecting the other specs that use the data.
=> [Rails 5][#5118] Wrong email address found by spec

spec/models/info_request_batch_spec.rb, spec/spec_helper.rb
* Fixes a spec failure caused by Rails 5 tests now triggering the `after_commit` hook (does not appear to be configurable via `use_transactional_fixtures`)
* Prevents `TestAfterCommit.enabled = false` being set under Rails 5, while this doesn't appear to cause any harm, we're removing the gem for Rails 5 as Rails itself now provides this functionality
=> [Rails 5] Fix spec issues related to transactions/commit hooks

app/models/alaveteli_pro/account_request.rb
Requires #5094 
Adds a guard clause to `AlaveteliPro::AccountRequest.initialize` so that it returns early when passed nil
Avoids the error (appears in specs):
```
Failure/Error:
attributes.each do |name, value|
send("#{name}=", value)
end
NoMethodError:
undefined method `each' for nil:NilClass
```
e.g. `./spec/controllers/alaveteli_pro/account_request_controller_spec.rb:80`
Rails 5 returns `nil` rather than an empty Hash when asked for a missing parameter value. So...
When in `controllers/alaveteli_pro/account_request_controller.rb` we call `AlaveteliPro::AccountRequest.new(params[:account_request])` without a value in params for account_request, it explicitly passes nil, bypassing the default param value and raising an `undefined method` error as above.
=> [Rails 5] Handle receiving nil param values

app/helpers/link_to_helper.rb, app/views/public_body/_list_sidebar_extra.html.erb, config/routes.rb, doc/CHANGES.md
Fixes #5059
* Fixes the `destroy_batch` route (prevents Rails 5 from seeing it)
* Replace the dynamic route that causes a Rails 5 deprecation warning
Changes in Rails 5 that caused:
* spec failures when trying to use the `destroy_batch` route (would probably have failed in the browser as well)
* an early warning that dynamic routes were going to be removed that caused spec failures because test which expected empty output were receiving a deprecation message instead
=> [Rails 5] Routing related fixes

app/controllers/request_controller.rb
Requires #5094
Forces html as a response type when presenting the 'hidden' template instead of the requested document.
Fixes specs that check for the expected content type and get the requested file type instead:
```
Failure/Error: expect(response.content_type).to eq("text/html")
expected: "text/html"
got: "application/pdf"
```
Fixes 4 spec failures (`./spec/controllers/request_controller_spec.rb`)
Rails 5 has changed the way it infers the requested response type and is using the file extension to respond to e.g. requests for a pdf file as `application/pdf` instead of `text/html`
=> [Rails 5] Respond to blocked file downloads with HTML

spec/controllers/admin_public_body_controller_spec.rb, spec/integration/admin_import_csv_spec.rb
Fixes #5117 
Moves the file upload spec that fails under Rails 5 (the change in parameters means the file upload handling works differently now) to be an integration spec that can do an end-to-end check instead of trying to intercept and override the passed file object.
The old spec was breaking under Rails 5...
```
AdminPublicBodyController GET #import_csv when handling a POST request if there is a csv file param should try to get the contents and original name of a csv file param
Failure/Error: expect(@file_object).to receive(:read).and_return('some contents')
(#<Rack::Test::UploadedFile:0x000000000e7aeb18 @content_type=nil, @original_filename="fake-authority-type.csv", @tempfile=#<Tempfile:/tmp/fake-authority-type.csv20190222-20042-13c5ezf>>).read(*(any args))
expected: 1 time with any …
```
=> [Rails 5][#5117] Fix file upload spec

app/views/alaveteli_pro/batch_request_authority_searches/_public_bodies.html.erb
https://github.com/mysociety/sysadmin/issues/1135
There was issues with both the outer and inner fragment caching calls.
The outer cache wasn't working due to there being no #cache_key method for a ActiveRecord::Relation. This method was added in Rails 5 [1] so for earlier Rails versions it ended up using an internal Ruby object ID in the cache key which changes every request and means the cached value is never used.
While the inner cache wasn't completely broken, the cache_key used included the public body translation cache_key [2] meaning we weren't stopping the extra SQL queries being performed for each public body in the category and causing a performance hit.
[1] https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/relation.rb#L335
[2] …
=> Fix cache keys for authority browse mode

app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb
mysociety/sysadmin#1135
Quickfix until we can fix this properly. Even though this might effect other installs WDTK is the only one currently using the batch browse mode as far as we know.
=> Skip rendering large category in batch browse mode

app/controllers/admin_request_controller.rb, spec/controllers/admin_request_controller_spec.rb, spec/lib/graphs_spec.rb, spec/lib/user_stats_spec.rb
Fixes #5076 
* Allows Rails 5 to check integers in params as integers rarther than strings
* Allows `admin_request_controller` spec in Rails 5 to handle strings and integers being passed to `InfoRequest.find`
To reduce spec failures around parameter expectations. And the related `InfoRequest.find` expectation error
=> [Rails 5] Fix spec expectations for integers passed in params

spec/controllers/alaveteli_pro/info_request_batches_controller_spec.rb, spec/factories/info_requests.rb, spec/views/admin_general/_to_do_list.html.erb_spec.rb
Fixes a couple of specs that break under Rails 5 due to apparent changes in ActiveRecord::Relation
Rails 5 appears to be performing live lookups of relational data rather than caching it in memory inside specs. This has led to the following issues for our test suite:
* if the underlying data has been deleted, its related collections are empty (fails comparison checks)
* method stubbing on a relation no longer works as the object reference changes when the code is run (see below for reproduction steps)
Proof of what's happening in 42c8988 (could not track down where the change was introduced - it's present in v5.0.0.beta4 which is where I stopped looking)...
In the spec (line 23-29):
```diff
it 'shows "None given" if there is no user message' do
alt_params = …
```
=> [Rails 5] Fix specs involving AR relations

lib/alaveteli_external_command.rb
Fixes https://github.com/mysociety/alaveteli/issues/5163
Fix the path detection for external commands.
For example: Incoming email with attachments crashed the request view as
the app couldn't find external utilities like elinks
=> Fix path problem for external commands used by alaveteli

Vagrantfile
Set friendly hostname for Vagrant VM
e.g. "alaveteli-xenial64"
https://www.vagrantup.com/docs/vagrantfile/machine_settings.html#config-vm-hostname
If you use e.g `10.10.10.30.nip.io` fqdn, your shell prompt ends up as `vagrant@10 $` on Xenial, which is a bit annoying.
=> Set friendly hostname for Vagrant VM

app/controllers/admin_general_controller.rb, app/views/admin_public_body/_locale_fields.html.erb, app/views/admin_public_body/edit.html.erb, spec/controllers/admin_general_controller_spec.rb
Fixes #5084
* Minor wording tweak
* Move request_email translation warning
* Fix broken display of blank contact authorities
* Add missing spec
* Minor cleanup
In the admin interface we list authorities without a request email, so
that admins can attempt to find an email for them.
Currently each locale must have a request email – there's no fallback to
the default locale (#3134).
In cases where we have an alternative translation that has some
attributes translated (e.g. Name) but no request email,
`PublicBody.without_request_email` finds these bodies, as it should.
The problem is that the `includes(:tags, :translations)` call results in
_only_ the translations of the locale of the missing `request_email`
being loaded. As the admin interface is only available in English, this
means that …
=> [#5084] Fix empty authorities in admin summary

.travis.yml, spec/support/test_response.rb
Connects to #5038 
Connects to #3969
Runs the test suite on Travis against Ruby 2.6. Add a monkey patch to `ActionController::TestResponse` for Rails 4 needed to get the specs running. This can be removed once we upgrade to Rails 5.
=> [#5038] CI builds against Ruby 2.6

app/views/admin_holidays/index.html.erb
Fixes #5201 
* Replace `content_tag_for` with `content_tag`
* Code cleanup
`content_tag_for` is removed in Rails 5.
=> [#5201] Remove record tag helpers

.ruby-style.yml
Enable `Layout/EmptyLines*` cops
Trying to continuously improve codebase health.
=> Enable Layout/EmptyLines* cops

db/migrate/20160613145644_add_comments_count_to_users.rb, db/migrate/20160613151127_add_info_requests_count_to_users.rb, db/migrate/20160613151912_add_track_things_count_to_users.rb, db/migrate/20160613152433_add_request_classifications_count_to_users.rb, db/migrate/20160613153739_add_public_body_change_requests_count_to_users.rb, db/migrate/20160613154616_add_info_request_batches_count_to_users.rb, db/migrate/20170718261524_add_expiring_notification_at.rb, db/migrate/20170825150448_add_stripe_customer_id_to_pro_account.rb, db/migrate/20180418154555_add_timestamps_to_foi_attachments.rb, db/migrate/20180418154949_add_timestamps_to_holidays.rb, db/migrate/20180418155632_add_timestamps_to_profile_photos.rb, db/migrate/20180418155850_add_timestamps_to_public_body_category_links.rb, db/migrate/20180418155927_add_timestamps_to_public_body_categories.rb, db/migrate/20180418160008_add_timestamps_to_public_body_headings.rb, db/migrate/20180418160048_add_timestamps_to_raw_emails.rb, db/migrate/20180418160204_add_timestamps_to_user_info_request_sent_alerts.rb, db/migrate/20180418160206_add_timestamps_to_acts_as_xapian_jobs.rb
Fixes #5205 
Fixes #5207 
Updates old migration for compatibility with Rails 5.0 and 5.1
There is still one deprecation warning for `#table_exists?` coming from the `acts_as_versioned` gem - we might need patch this or look at alternative versioning gems.
=> [Rails 5] Migrations updates

config/environments/production.rb
Part of #3969 
This fixes an error when booting the application:
!! Unexpected error while processing request: undefined method
`request_id' for #<ActionDispatch::Request>
Booting Rails 4 was broken.
=> [Rails 5] Don't use log tags in Rails 4

config/application.rb
Part of #3969
Limits which files are eager loaded to Ruby source files.
As theme is installed in the ./lib/themes/ and can contain RSpec files
we don't want to load these automatically in production environment.
=> [Rails 5] Only eager load Ruby source lib files

doc/CHANGES.md
#4902
Updates changelog, upgrade notes and changed templates
I don't think there are any specific notes for R5 prep. If we come across any we should update the changelog again, or, if we only find any when we upgrade WDTK, we can make a minor release which just adds changelog notes.
=> [#4902] Update changelog

app/helpers/link_to_helper.rb, app/views/admin_general/timeline.html.erb, app/views/layouts/default.html.erb, spec/helpers/link_to_helper_spec.rb
Part of #3969 
Fixes #5214 
An ArgumentError for non-sanitized parameters will be raised if
data is merged into request parameters and then used to generate
URLs with the `url_for` or `link_to` helpers.
We actually don't need to do this as these helpers already use the
current request parameters as a starting point for the URL generated.
=> [Rails 5] Fix URL generation

config/application.rb
The change in #5211 wasn't effective and caused dependency loading
issues as described in #5234.
This switches to the old style dependency loading which was used in
Rails 4. This only effects ./lib and the reset of the ./app code will
still be eagerly loaded.
Closes: #5234
=> [#5234] Fix dependency loading

app/controllers/application_controller.rb, spec/controllers/request_controller_spec.rb
Fixes #5241
Adds a call to `FileUtils.chmod` to `ApplicationController#foi_fragment_cache_write` to ensure that read permissions for 'group' and 'others' are added to the new cached file.
In https://github.com/rails/rails/commit/5d3b3cba4a1f450e14760c5114a73464a92730c3 Rails 5 updates `File.atomic_write` in a way that prevents the permissions of the containing directory from being used (per Rails 4) when not replacing an existing file so we are left with just the `Tempfile.new` permissions (read and write permissions for the owning user only).
Without this, the cached files can't be accessed by Apache or Nginx resulting in serving the user a 403 Forbidden error the second time anyone tries to access the file (the first read is not from the cache and works fine)
`File.atomic_write` is only …
=> [Rails 5] Make sure cache files get the correct read permissions

app/controllers/users/confirmations_controller.rb, spec/controllers/users/confirmations_controller_spec.rb
Found while brakeman scanning for #4902.
* Minor code cleanup
* Prevent possible unsafe redirect
Security – possible [off-site redirect](https://brakemanscanner.org/docs/warning_types/redirect/).
=> [#4902] Prevent unsafe redirect

app/models/info_request.rb
Found while brakeman scanning for #4902.
* Minor code cleanup
* Improve InfoRequest#title format validation
Security – possible [insufficient format validation](https://brakemanscanner.org/docs/warning_types/format_validation/)
As mentioned in the commit message of 35d4d5d, I don't think we're really improving security here as such. All we're validating is that the title isn't just a bunch of numbers or special characters, so this is mainly to suppress the Brakeman warning so that we don't have to remember why its not a problem each time. We could of course use the ignore file, but I figure its easier to just be explicit in the code for this one.
=> [#4902] Improve InfoRequest#title format validation

app/models/info_request.rb, spec/models/info_request_spec.rb
Required by #4902 
Fixes #5251 
Adds a guard so that `InfoRequest.guess_by_incoming_subject` returns early (with an empty array) if it's given an email address without a subject line.
We actually got a (spam) email without a subject line and this bug prevented the volunteers from being able open it and delete it from the holding pen.
Original error:
```
A NoMethodError occurred in admin_raw_email#show:
undefined method `gsub' for nil:NilClass
app/models/info_request.rb:301:in `guess_by_incoming_subject'
```
It needs to return an array otherwise we get:
```
A TypeError occurred in admin_raw_email#show:
no implicit conversion of nil into Array
app/controllers/admin_raw_email_controller.rb:32:in `+
```
...when it tries to add the subject line guesses to the email address guesses.
=> [#5251] Allow `InfoRequest.guess_by_incoming_subject` to handle emails without subject lines

Gemfile, Gemfile.lock, Gemfile.rails5.lock
Required by #5194 
Reinstates our original locks for the gettext_i18n_rails and fast_gettext gems
Avoids having to implement a new gettext API that breaks our current rake tasks - and may have an (untested) impact on translation workflow - as part of a minimal release to lock in the Rails update.
=> [Rails 5] Revert to old translation gem versions

doc/CHANGES.md, lib/tasks/temp.rake
Fixes #5264
Adds a post upgrade rake task to convert all exiting stored `params_yaml` fields to use `ActiveModel::Type::Integer` instead of `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer`
Rails 5.0 removed `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer` https://github.com/rails/rails/commit/aafee233fb3b4211ee0bfb1fca776c159bd1067e
Now attempting to call `InfoRequestEvent#params` on an event with serialized model IDs is causing the following error (and breaking the admin index page):
```
undefined class/module ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer
```
=> Add temp rake task to convert saved params to ActiveModel::Type::Integer

app/controllers/request_controller.rb, spec/controllers/request_controller_spec.rb
Fixes #5261 
* Fixes a spec without an expectation
* Forces `request/request/view_html_stylesheet` to output HTML when called within `RequestController#get_attachment_as_html`
* Code style fixes
Since upgrading to Rails 5.0, the partial will receive a format based on the file extension unless a format is passed in
https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L68-L78
Resulting in an error:
```
An ActionView::MissingTemplate occurred in request#get_attachment_as_html:
Missing partial request/_view_html_stylesheet with
{:locale=>[:en], :formats=>[:pdf], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee]}.
```
=> [Rails5] Fix RequestController#get_attachment_as_html

app/models/alaveteli_pro/embargo.rb, spec/models/alaveteli_pro/embargo_spec.rb
Fixes #4904
`AlavateliPro::Embargo.expire_publishable` now checks whether the request is part of a batch after it has removed an embargo so that it can remove the batch's `embargo_duration`.
Was causing errors in production where batches which had reached expiry still had an `embargo_duration` after the related `info_requests`'s  embargos had been deleted. Whenever the batch was displayed on the site, it would cause an attempted read of a deleted `embargo`, raising the following error:
```
undefined method `expiring_soon?' for nil:NilClass
```
=> [#4904] Fix batch embargo expiry bug

app/models/foi_attachment.rb, spec/models/foi_attachment_spec.rb
While debugging a request I found:
attrs[:filename]
We've made a fix to the problem in the attachment body in f18c5b9.
This commit deletes null bytes from the filename attribute.
The deletion of the null bytes must happen before the extension
calculation, otherwise the spec fails with:
expected: "Tender Loving Care Trust (Europe).pdf"
got: "Tender Loving Care Trust (Europe).pdf.pdf"
We need a `try` as sometimes the filename being assigned is `nil` and
calculated by `FoiAttachment#ensure_filename!`. I didn't think a spec
was worth adding here, as the behaviour is covered by the
`ensure_filename!` spec
In 6c8490b we attributed a similar problem to Tnef. I'm not sure of the
cause of the error in this case.
Fixes #5209.
=> [#5209] Prevent null bytes in attachment filename

app/controllers/followups_controller.rb, app/controllers/request_controller.rb, app/models/info_request.rb, app/models/info_request_event.rb, app/models/outgoing_message.rb, app/views/admin_general/_to_do_list.html.erb, app/views/request/_correspondence.html.erb, spec/controllers/followups_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/factories/info_request_events.rb, spec/models/info_request_event_spec.rb, spec/models/info_request_spec.rb, spec/models/outgoing_message_spec.rb, spec/support/shared_examples_for_network_errors_during_send.rb, spec/views/admin_general/_to_do_list.html.erb_spec.rb
Closes #2578, #5112 by preventing a request that fails to send from having a `nil` calculated `last_event_forming_initial_request`
Closes #5120 by way of saving outgoing_message before sending.
Wraps request mail sending tasks to catch exceptions from ApplicationMailer (`StandardError` used as all exceptions should derive from that task), and implement a new outgoing message handler to log message sending failures, setting the status to 'failed'.
Additionally, this change:
* alters delivery status logic to always return that a message failed to send if the outgoing message is in a 'failed' state, there are unlikely to be logs from the mail servers in this eventuality.
* isolates e-mail failures from templating issues which may also cause such failures (such at those alluded to in #2578), …
=> Handle failures in ActionMailer that may raise exceptions

Gemfile, Gemfile.lock, Gemfile.rails_next.lock, app/mailers/alaveteli_pro/metrics_mailer.rb, app/views/alaveteli_pro/metrics_mailer/weekly_report.text.erb, config/crontab-example, config/initializers/alaveteli.rb, doc/CHANGES.md, lib/alaveteli_pro/metrics_report.rb, lib/stripe_mock_patch.rb, script/send-pro-metrics-report, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb, spec/factories/users.rb, spec/lib/alaveteli_pro/metrics_report_spec.rb, spec/mailers/alaveteli_pro/metrics_mailer_spec.rb, spec/mailers/previews/alaveteli_pro/metrics_mailer_preview.rb, spec/spec_helper.rb
Closes #5247 
* Brings the pro metrics script we've been running manually into the codebase
* Addresses a possible omission from the `:pro_user` factory where it didn't create a `pro_account` for the created user
* Creates an email with the report results
* Adds a cron task to run and email the report [every Monday morning](https://crontab.guru/#37_8_*_*_1)
* We'd like to be able to automate the process of running the pro metrics script and have it send an email to the relevant Pro Team
* We'd like to be able to offer this as a metrics report for reusers who want to use the Pro features (without them needing to run a command line script!)
* The specs are not ideal as there are a couple of missing features in StripeMock:
- it doesn't model the [lifecycle for subscriptions …
=> [#5247] Pro Metrics weekly mailer

app/views/alaveteli_pro/metrics_mailer/weekly_report.text.erb, lib/alaveteli_pro/metrics_report.rb, spec/lib/alaveteli_pro/metrics_report_spec.rb, spec/mailers/previews/alaveteli_pro/metrics_mailer_preview.rb
Closes #5286 
Renames the report explanation string from 'Total requests made this week' to  'Estimated total number of Pro requests', and the related data key from `:total_new_requests` to
`:estimated_total_pro_requests`
'Total requests made this week' was a misleading description of the reporting data, doubly so as we're going to ask people to translate it!
Data key renamed to match for clarity.
=> Rename Pro Metrics 'Total requests made this week' report label

app/views/alaveteli_pro/webhook_mailer/digest.text.erb, spec/mailers/alaveteli_pro/webhook_mailer_spec.rb
Add line break after each webhook customer
Makes it easier to distinguish sublists in some mail clients.
For some reason my mail client strips the leading spaces from the sublist of webhooks.
This commit adds a newline so that each customer/webhooks group is more distinct.
**Problem client:**
**Before:**
**After:**
=> Add line break after each webhook customer

.gitignore
Reinstate public/alavetelitheme in .gitignore
This symlink gets created when switching themes to point at the theme's
public directory.
alavetelitheme ->
/home/vagrant/alaveteli-themes/whatdotheyknow-theme/public
=> Reinstate public/alavetelitheme in .gitignore

doc/CHANGES.md
Removes a dangerous upgrade note.
This task was renamed to `destroy_and_rebuild_index` in c452935.
Running the task as-is will destroy the search index and only rebuild it with the specified models, rather than just updating the index.
Later versions introduce `reindex:public_bodies`.
=> Remove dangerous upgrade note

config/initializers/stripe.rb
Required by mysociety/alaveteli-professional#590
Sets the Stripe API version in the code rather than using the default settings. We're starting with the '2017-01-27' version as that's what we've been using in production to date so we know it's compatible with everything we're using at the moment.
When a new Stripe account is created, it assigns a default API version based on the latest available release. As we need a predictable API across customer installs, it's better for us to set it and upgrade it as needed as part of our standard release process.
This seems to work with my "restricted" Stripe key (admittedly against my test account which defaults to the '2017-08-15' API version)
=> [pro#590] Set the Stripe API version in the initializer

app/views/alaveteli_pro/plans/show.html.erb
mysociety/alaveteli-professional#588
Adds the missing translation markup for `plans/pro` page
Avoids having untranslatable text in the Pro user signup process
Deliberately avoids adding translation markup to the example FAQ (hidden behind a feature flag)
=> [pro#588] Translatable Pro plan page

config/general.yml-example, config/initializers/alaveteli_features.rb, lib/configuration.rb
Connected to #5290 
Connected to https://github.com/mysociety/alaveteli-professional/issues/585
Add configuration setting to enable `pro_pricing`.
As we're going to be enabling this for other sites soon we should have a way to enable from the configuration settings.
=> Add configuration setting to enable pro_pricing

app/controllers/alaveteli_pro/plans_controller.rb, app/helpers/currency_helper.rb, app/views/alaveteli_pro/plans/index.html.erb, spec/controllers/alaveteli_pro/plans_controller_spec.rb, spec/helpers/currency_helper_spec.rb, spec/views/alaveteli_pro/plans/index.html.erb_spec.rb
Closes mysociety/alaveteli-professional#587
* Adds translation markup to the pro pricing page
* Extends the `CurrencyHelper#format_currency` method to allow us to display a price as e.g. '£15' rather than '£15.00' without assuming a particular pricing format
* Fetches the price from Stripe rather than hardcoding "£10" in a translatable string (encodes the assumption that the key plan id will be "pro")
So that the pricing page can be translated without overriding the entire template page in a theme
* The sample copy for testimonials and FAQs - hidden behind feature flags - was deliberately not included
* ~~I've left `WhatDoTheyKnow<sup>Pro</sup>` as-is rather than pass it in from `pro_site_name` (which would be without the `<sup></sup>` markup) but I'm not sure that's right, although …
=> [pro#587] Make pricing page translatable

config/initializers/alaveteli.rb, config/initializers/stripe.rb, doc/CHANGES.md, lib/alaveteli_pro/webhook_endpoints.rb, lib/tasks/stripe.rake, spec/lib/alaveteli_pro/webhook_endpoints_spec.rb
Closes mysociety/alaveteli-professional#590
(Replaces #5302 and steals the reviewer suggestions)
* Adds a new class method to the `Stripe` module to store the list of events we want our webhook endpoint to listen for
* Adds a rake task to:
- create a new Stripe webhook endpoint with the right:
* url
* api_version
* list of subscribed events
- outputs the signing secret to be added to the `general.yml` file
We can set the Stripe API version for the webhook so - although the wrapped Event data will still use the format set by the Stripe account (new accounts will take whatever the latest version is at the time they are created) - the webhook wrapper will take the expected form as set by the `api_version`.
Once the site re-users have set up a Stripe account and shared the API keys with us, …
=> [pro#590] Create webhook endpoint

app/models/info_request.rb, spec/models/info_request_spec.rb
Fixes #5316
Switch away from using ActiveRecord #find method as this raises
exceptions when a record can't be found.
This is occurring when admin's remove similar requests and the Xapian
search index hasn't be updated.
=> [#5316] Fix loading of similar requests

app/controllers/admin_user_controller.rb, app/views/admin_user/index.html.erb, doc/CHANGES.md, spec/controllers/admin_user_controller_spec.rb
Fixes #5303 
Adds User#about_me to the columns search where queering the user admin controller.
Requested by volunteers to make it easier to combat spam accounts.
=> [#5303] Improve admin user searching to include User#about_me

app/models/alaveteli_pro/subscription_with_discount.rb, app/models/alaveteli_pro/with_tax.rb
Closes https://github.com/mysociety/alaveteli/issues/5238
Required by #5229
Uses `BigDecimal()` instead of the deprecated `BigDecimal.new()`
BigDecimal.new() is deprecated and raises warning messages in Ruby 2.5+
This avoids the warning:
`warning: BigDecimal.new is deprecated; use BigDecimal() method instead`
=> [#5238] Call BigDecimal() instead of the BigDecimal.new()

app/assets/stylesheets/responsive/_sidebar_layout.scss, app/helpers/application_helper.rb, app/views/request/_batch.html.erb, app/views/request/_sidebar.html.erb, app/views/request/_sidebar_pro_upsell.html.erb, spec/helpers/application_helper_spec.rb
* Various code cleanup
* Add pro up-sell to request page sidebar
Direct more people to `/pro` for £££.
=> Add pro up-sell to request page sidebar

Vagrantfile, bin/vagrant-bionic, bin/vagrant-xenial, doc/CHANGES.md
Required by #5229 
* Drops support for Ubuntu 16.04 (Xenial)
* Replaces xenial binstub with one for Ubuntu 18.04 (Bionic)
On our [roadmap for release 0.35](https://gist.github.com/garethrees/ec3c403e1ea0744fb736381785e1e788)
Bionic is available on Travis but using it for Alaveteli is going to need more than just `s /xenial/bionic/` so I've opened a separate ticket #5322
=> Drop support for Ubuntu Xenial

.travis.yml, README.md, doc/CHANGES.md
Closes #5038
Required by #5229 
* Moves Ruby 2.6 into the support matrix
* Updates the README
* Adds a line to the release notes
We wanted to add Ruby 2.6 support in this release (per [roadmap](https://gist.github.com/garethrees/ec3c403e1ea0744fb736381785e1e788#035-1))
=> [#5038] Add Ruby 2.6 support

app/mailers/request_mailer.rb, spec/mailers/request_mailer_spec.rb
Fixes #3212 
* Adds missing spec
* Skips over requests that error while sending not clarified reminders
The original error was raised (5dccf06) if the request doesn't have a
last response event. This makes some sense, as there wouldn't be
a request to clarify if the authority didn't respond.
bc743d9 adds a "public" qualifier to this test, as prominence was
introduced (4e2c450) to `IncomingMessage`.
We now have a situation where this error can be raised when the request
is marked as `waiting_clarification`, but there's no last _public_
response due to the response prominence being set to hidden.
In the initial case, we should avoid allowing the user to classify as
`waiting_clarification`, but in the latter case a state of
`waiting_clarification` with a prominence of `hidden` is completely …
=> [#3212] Fix alert not clarified reminder error from no public last response

lib/alaveteli_geoip.rb, spec/lib/alaveteli_geoip_spec.rb
Adds a lookup for 'continent' data from MaxMind if 'country' is not available
Apparently some IPs are mapped to continents now and it's causing a bug in production 😞
=> Look for a continent mapping if country data not supplied

app/views/admin_incoming_message/_foi_attachments.html.erb, app/views/admin_incoming_message/edit.html.erb, doc/CHANGES.md
https://github.com/mysociety/sysadmin/issues/1169
* Minor code cleanup
* Lists `FoiAttachment`s related to an `IncomingMessage` at `AdminIncomingMessageController#edit`.
When handling data breaches we need to find the hexdigest of the
attachment to ensure it gets purged from all caches / backups etc.
Its quite hard to do this – even from the console – and any console
commands are prone to error. Its easier to just show the associated
attachments on the admin interface, along with some less user-friendly
information that's useful for admin purposes.
It turned out it was easier to add this than explain in our [internal guide](https://wiki.mysociety.org/wiki/Handling_a_data_breach_by_an_authority)
how to find the `hexdigest` of a particular attachment through the rails
console.
This might …
=> Show incoming message attachments in admin

app/controllers/application_controller.rb
Fixes #4479
Moving the before action callback before the protect_from_forgery action
ensure 'locale' instance variable is always defined. This is used on
every page, including when exceptions are rendered in production mode.
=> [#4479] Fix rendering of locale switcher

app/controllers/announcements_controller.rb
Fixes #4495
No need to protect this action as it doesn't handle any thing sensitive.
=> [#4495] Drop token check when dismissing announcements

.ruby-style.yml
We don't currently want to run this cop on spec files as it goes against
our current style for describe/context/it blocks.
We may switch to this style in the future but for now it will return too
many warnings when reviewing PRs.
=> Allow empty lines around block body in spec files

docs/installing/deploy.md, es/docs/installing/deploy.md
Alaveteli didn't upgrade to 3.x, which appears to have dropped the `-S`
flag we use in this guide. [1]
Personally I'd use `bundle exec cap…` to use the version bundled with
the rest of the gems Alaveteli uses, but this guide does say that you
may not actually have it fully installed on the deployment machine:
> checkout the Alaveteli repo (you need some of the files available
> locally even though you might not be running Alaveteli on this
> machine)
Fixes https://github.com/mysociety/alaveteli/issues/5386.
[1] https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/alaveteli-dev/ZFV2-1v2tok/yIX6tlpLBwAJ
=> [#5386] Fix capistrano version at latest 2.x release

script/rails-deploy-before-down
Related to https://github.com/mysociety/alaveteli/issues/5358.
Download geoip data on install
c10f6c6d005cd1dc1404cda46f5031bfe1696127 introduces a rake task to
download geoip data. Once configured correctly,
42d0c1b0ec2c4a06934dc72b46835dd18aeb9d4a handles keeping it updated.
This commit ensures that the data exists on the first install of the
app.
=> Download geoip data on install

.ruby-style.yml, spec/views/alaveteli_pro/batch_request_authority_searches/_search_results.html.erb_spec.rb
* Set minimum Ruby version for Rubocop
* Auto-correct Style/MethodCallWithoutArgsParentheses
Fix style violation
=> Fix method call without args parenthesises

_layouts/page.html, community/index.md
https://github.com/mysociety/alaveteli-project/issues/106
* Add AlaveteliCon 2019 to sidebar
* Add Conferences section to Community page
=> [ap#106] Add AlaveteliCon 2019 references

spec/support/xapian_index.rb
Out of nowhere I started getting these spec failures:
Failure/Error: FileUtils.cp_r($original_xapian_path, temp_path)
Errno::ENOENT:
No such file or directory @ rb_sysopen -
/home/vagrant/alaveteli/lib/acts_as_xapian/xapiandbs/test/postlist.baseB
`get_fixtures_xapian_index'
#
./spec/controllers/public_body_controller_spec.rb:446:in
`block (2 levels) in <top (required)>''
No idea what was causing them, or why they started. Tried rebuilding the
VM. Tried rebooting. Still there. So I stick a `binding.pry` in:
vagrant@alaveteli-bionic64:~/alaveteli$ bundle exec rspec
spec/controllers/public_body_controller_spec.rb:469
Run options: include
{:locations=>{"./spec/controllers/public_body_controller_spec.rb"=>[469]}}
Randomized with seed 29197
From: …
=> Fix loading Xapian database in Vagrant

app/views/password_changes/check_email.html.erb, doc/CHANGES.md
Fixes https://github.com/mysociety/alaveteli/issues/5397.
Fix wording on password change "check email" confirmation page
We shouldn't talk about changing an email when attempting to change your
password.
Introduced in f834524108. Restored translated string from c4d9a8e5f5.
=> [#5397] Fix wording on password change confirmation

app/controllers/alaveteli_pro/subscriptions_controller.rb, doc/CHANGES.md
Fixes: https://github.com/mysociety/alaveteli-professional/issues/597
Fixes missing Stripe errors for some cases
Errors for expired/invalid coupons and some card processing errors were
not being shown to the user due to the form submission being done via
AJAX.
When redirecting after an error the AJAX doesn't know how to handle the
response. Using the json_redirect_to method returns the URL of the
redirection to the frontend and is already handled in the JS [1].
[1] https://github.com/mysociety/alaveteli/blob/7025d65/app/assets/javascripts/alaveteli_pro/stripe.js#L146
Before - no page reload (note the disabled state of the processing button):
After - page reloaded and shows error message:
=> [pro#597] Fix rendering of Stripe errors

app/models/public_body.rb
Fixes: #5401
Scope the query to find the internal admin authority to the default
locale. This prevents multiple results for each translated locale.
Prevent exception warning of multiple internal admin bodies and breaking whole locales.
See: https://groups.google.com/forum/m/#!topic/alaveteli-dev/YoOrH_qVDxc
In order to test this you'll need to run: `PublicBody::Translation.create(url_name: 'internal_admin_authority', locale: 'cy', ...)` for a non-default configured locale.
=> [#5401] Fix multiple internal admin bodies

app/assets/javascripts/alaveteli_pro/marketing.js, app/assets/stylesheets/responsive/_global_layout.scss, app/assets/stylesheets/responsive/_global_style.scss, app/assets/stylesheets/responsive/_sidebar_layout.scss, app/assets/stylesheets/responsive/alaveteli_pro/_pro_marketing.scss, app/assets/stylesheets/responsive/alaveteli_pro/_requests_style.scss, app/controllers/alaveteli_pro/account_request_controller.rb, app/models/alaveteli_pro/account_request.rb, app/views/alaveteli_pro/account_mailer/account_request.text.erb, app/views/alaveteli_pro/account_request/_account_request_form.html.erb, app/views/alaveteli_pro/account_request/_self_serve_button.html.erb, app/views/alaveteli_pro/account_request/index.html.erb, config/general.yml-example, config/initializers/alaveteli_features.rb, config/routes.rb, doc/CHANGES.md, lib/configuration.rb, spec/controllers/alaveteli_pro/account_request_controller_spec.rb, spec/mailers/alaveteli_pro/account_mailer_spec.rb, spec/views/alaveteli_pro/account_request/index.html.erb_spec.rb, vendor/assets/stylesheets/foundation/components/_buttons.scss
https://github.com/mysociety/transparency-adessium/issues/16
Adds configuration variable and feature flag to enable self serve upgrades from a standard user account to a pro account.
Not all installations are able or will want to take payments for pro.
This reuses to account request feature which was initially used on WDTK for beta accounts while Pro was being developed. Any "beta" references should now be removed and the account request feature remains in place for installations who might want to manually approve who gets access to Pro.
=> Pro self serve

app/mailers/track_mailer.rb, doc/CHANGES.md, spec/mailers/track_mailer_spec.rb
Fixes: #4636
Track Mailer runs daily for every user set to receive email alerts. After running we set #last_daily_track_email to track when the mailer should next run. We shouldn't touch #updated_at while saving as it makes it hard to identify intentionally updated users.
Increase spam accounts. With this change it will help identify accounts which have been recently updated to add spam.
=> [#4636] Fix User#updated_at being changed by cron job

public/robots.txt
Closes https://github.com/mysociety/alaveteli/issues/311.
The comment notes that it can be removed "later in 2012", so I think
we've waited long enough now.
https://github.com/mysociety/alaveteli/issues/311 appears fixed –
possibly by a Rails upgrade – so I think this is safe to remove.
Just ties up loose ends.
=> [#311] Remove unused robots.txt rule

app/assets/stylesheets/responsive/_request_style.scss, app/views/comment/_single_comment.html.erb, app/views/request/_incoming_correspondence.html.erb, app/views/request/_outgoing_correspondence.html.erb
Fixes #5419 
Requires https://github.com/mysociety/whatdotheyknow-theme/pull/615
This refactors the `cplink__button` styles to:
- make tags and classes consistent across all views
- remove the main button class styling introduced in [1]
- re-add padding and text decoration rules
- fix border radius on the right of the "Link to this" button
[1] https://github.com/mysociety/alaveteli/commit/3e2861d
Button styles changed in #5380 and caused unexpected issue with other buttons
I considered reverting the changes style changes from #5380 but in the end it was easier to just fix the CSS, and it turned out there were existing issues which needed fixing too - see the before Gif below. 
A look through the Alaveteli source doesn't find any other buttons which need fixing - except …
=> [#5419] Fix issue with report button styling

app/models/public_body.rb
Required by #3970 
Uses `sanitize_sql` instead of the removed (internal) `sanitize` method to construct the SQL statement
To prevent raising a `NoMethodError` under Rails 5.1:
```
NoMethodError:
undefined method `sanitize' for #<Class:…>
```
=> [Rails 5.1] Avoid raising errors by calling `sanitize` when construction SQL statements

spec/mailers/track_mailer_spec.rb
Required by #3970 
* Uses factories instead of mocks for better specs
* Stubs the `find_each` method to supply a mock using `receive_message_chain` rather on the User model rather than trying to stub `User::ActiveRecord_Relation`
Trying to stub `User::ActiveRecord_Relation` in Rails 5.1 raises an error when running the specs:
```
Failure/Error: klass = User::ActiveRecord_Relation
NameError:
uninitialized constant User::ActiveRecord_Relation
```
=> [Rails 5.1] Fix track_mailer specs

app/views/admin_censor_rule/_about.html.erb, app/views/admin_censor_rule/_form.html.erb, app/views/admin_censor_rule/_warnings.html.erb, app/views/admin_censor_rule/index.html.erb, app/views/admin_general/_admin_navbar.html.erb, app/views/admin_request/show.html.erb
Minor improvement on https://github.com/mysociety/alaveteli/issues/2056
Expands inline help around censor rules.
TL;DR is that I've added the "About" section – previously only on the global censor rules page – to the censor rule form, so that there's as much info as possible available at the point of editing the records.
Helps inexperienced censor rule users to learn about them.
Its mostly just shuffling existing content around, with a few minor tweaks.
=> Censor rules help

app/views/admin_general/_admin_navbar.html.erb
Fixes https://github.com/mysociety/alaveteli/issues/5442
Add Spam Addresses to admin navigation
Makes it easier to find out about this feature.
=> [#5442] Add Spam Addresses to admin navigation

config/initializers/new_framework_defaults.rb
Required by #3970 
Allows the new (since Rails 5.0) default to apply instead of overriding it. No longer halts ActiveSupport callback chains by returning false.
This method is now deprecated Rails 5.2 - with a warning in the last version of Rails 5.1 - and causes spec errors (was supplied as a stopgap to allow missed manual callback halting via `throw(:abort)` to be caught and fixed.
https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#halting-callback-chains-via-throw-abort
Removes the deprecation warning which was making specs expecting blank output fail:
```
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. 
```
We had intended to do this after the Rails 5.0 upgrade once we were sure it was not logging …
=> [Rails 5.1] Remove ActiveSupport.halt_callback_chains_on_return_false override

Vagrantfile
Seems like there's a new option for preserving script output colour,
rather than the default of displaying stdout and stderr in green and red
respectively.
Setting `keep_color: true` disables Vagrant's highlighting and prints
colours defined in install scripts.
This tidies up provisioning output.
[1] https://www.vagrantup.com/docs/provisioning/shell.html#keep_color
BEFORE
AFTER
=> Preserve install script colours

spec/controllers/admin_censor_rule_controller_spec.rb, spec/controllers/admin_comment_controller_spec.rb, spec/controllers/admin_incoming_message_controller_spec.rb, spec/controllers/admin_outgoing_message_controller_spec.rb, spec/controllers/admin_public_body_categories_controller_spec.rb, spec/controllers/admin_public_body_controller_spec.rb, spec/controllers/admin_public_body_headings_controller_spec.rb, spec/controllers/admin_request_controller_spec.rb, spec/controllers/admin_user_controller_spec.rb, spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb, spec/controllers/api_controller_spec.rb, spec/controllers/comment_controller_spec.rb, spec/controllers/followups_controller_spec.rb, spec/controllers/general_controller_spec.rb, spec/controllers/help_controller_spec.rb, spec/controllers/info_request_batch_controller_spec.rb, spec/controllers/public_body_controller_spec.rb, spec/controllers/request_controller_spec.rb, spec/controllers/track_controller_spec.rb, spec/controllers/user_controller_spec.rb, spec/controllers/user_profile/about_me_controller_spec.rb, spec/views/general/frontpage.html.erb_spec.rb, spec/views/public_body/list.html.erb_spec.rb, spec/views/public_body/show.html.erb_spec.rb
Connected to #5069 and compatible with earlier versions too:
https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_dispatch/testing/test_response.rb#L20-L21.
Fixes Rails 5.2 depreciation warning.
```
DEPRECATION WARNING:
The success? predicate is deprecated and will be removed in Rails 6.0.
Please use successful? as provided by Rack::Response::Helpers.
```
To maintain clean and easy to read RSpec output.
=> Don't use deprecated success? predicate

bin/bundle_next, bin/rails_next, bin/rspec_next
Connected to #3970 
Use the Rails next gemfile with Bundler, Rails and RSpec commands by
running:
- bin/bundle_next
- bin/rails_next
- bin/rspec_next
=> Add binstubs to easily use the Rails next gemfile

app/views/alaveteli_pro/metrics_mailer/weekly_report.text.erb, lib/alaveteli_pro/metrics_report.rb, spec/lib/alaveteli_pro/metrics_report_spec.rb, spec/mailers/alaveteli_pro/metrics_mailer_spec.rb, spec/mailers/previews/alaveteli_pro/metrics_mailer_preview.rb, spec/models/comment_spec.rb, spec/models/info_request_spec.rb
- Add the number of expired embargoes on the weekly metrics report.
- Includes some code refactoring.
We've recently started tracking this and including here will save us time.
=> Add expired embargoes to weekly metric report

app/models/info_request_event.rb, lib/yaml_compatibility.rb, spec/fixtures/files/yaml_compatibility_4_2.yml, spec/fixtures/files/yaml_compatibility_5_0.yml, spec/fixtures/files/yaml_compatibility_5_1.yml, spec/fixtures/files/yaml_compatibility_public_body_tag.yml, spec/fixtures/files/yaml_compatibility_tmail.yml, spec/lib/yaml_compatability_spec.rb, spec/models/info_request_event_spec.rb
Fixes #5263 
Fixes #5265 
Fixes #5464 
Fixes #5463
Fixes #5465
This helps load old InfoRequestEvent instances which contain YAML from
older Rails version or includes old classes which don't exist in the app
any more.
To retain compatibility with old Alaveteli versions.
This uses the a similar method to Ruby's `YAML.safe_load` method [1] but we are own `ClassLoader` which can map to different classes instead of restricting which classes can be loaded [2].
[1] https://github.com/ruby/psych/blob/0910ae5575786d57783eafd4d03ebc0d077cd2ed/lib/psych.rb#L352-L360
[2] https://github.com/ruby/psych/blob/0910ae5575786d57783eafd4d03ebc0d077cd2ed/lib/psych/class_loader.rb#L93-L99
=> YAML compatibility class

script/load-sample-data
Fixes #5469
Required for #5323
This was failing due to the new YAML compatibility fixtures. Ignore these files when determining which fixtures to load.
=> [#5469] Fix load-sample-data script

spec/support/gaze.rb, spec/support/shared_examples_for_mailers.rb, spec/support/shared_examples_for_network_errors_during_send.rb, spec/support/shared_examples_for_phase_counts.rb, spec/support/shared_examples_for_request_summaries.rb, spec/support/shared_examples_for_viewing_requests.rb
Don't require spec_helper in support files
These are all required by `spec/spec_helper.rb`.
https://stackoverflow.com/a/35788352/387558
Just a random commit I had in a debug branch that we might as well rescue
=> Don't require spec_helper in support files

.ruby-style.yml
`Naming/AccessorMethodName` may generate the need for a handful of
method renames, but that's not a bad thing.
=> Add some hound checks

Gemfile, Gemfile.lock, Gemfile.rails_next.lock, config/routes.rb
We don't really use this and the styles don't work, so removing to
reduce maintenance.
=> Remove flipper-ui gem

spec/integration/signin_spec.rb
Fixes https://github.com/mysociety/alaveteli/issues/5478.
Make sure xapian index is initialized before specs run
Prevent transient CI failures
Similar to c4e296753ff8c55385680601ae9aa51539351c5e.
Couldn't replicate the transient spec failure locally, but pretty sure this is the same problem as https://github.com/mysociety/alaveteli/issues/2079.
=> [#5478] Make sure xapian index is initialized before specs run

.travis.yml
See #4842 & #5037
Bump bundler gem on Travis
No need to install older versions now were not supporting Ruby <2.3
=> Bump bundler gem on Travis

app/models/comment.rb, app/models/info_request.rb, app/models/outgoing_message.rb, app/models/public_body.rb, app/models/user.rb, spec/models/user_spec.rb
Replaces `each` with `find_each` when reindexing associated events
Lots of associations may be loaded and iterated through in these situations, so this avoids loading them in to memory.
I guess it would be nice to benchmark this, as we'll end up with more DB queries.
This _seems_ like the right thing to do, but open to suggestion!
=> Reindex events in batches

app/views/alaveteli_pro/account_request/_marketing_batch_features.html.erb, app/views/alaveteli_pro/account_request/_marketing_hero.html.erb, app/views/alaveteli_pro/account_request/_marketing_pro_features.html.erb, app/views/alaveteli_pro/account_request/_marketing_standard_features.html.erb
https://github.com/mysociety/alaveteli-professional/issues/594
We added a marketing-highlight class around key Pro features for WDTK,
but didn't port them back here.
Part of reconciling WDTK with core after https://github.com/mysociety/alaveteli/pull/5493 – this PR allows us to drop the override completely.
The styles already exist in core, so
this just adds the correct markup.
=> Backport WDTK marketing-highlight to core

app/controllers/statistics_controller.rb
Fixes #5490 
Fix statistics for new installations
Undefined method exception was being raised due to no public info
requests in the database.
Using the Ruby 2.3+ safe navigation operator.
=> [#5490] Fix statistics for new installations

Gemfile.lock, Gemfile.rails_next.lock, gems/alaveteli_features/alaveteli_features.gemspec
For Alaveteli Features update the summary and use bounded requirements.
Fixes warnings:
```
WARNING:  description and summary are identical
WARNING:  open-ended dependency on flipper (>= 0) is not recommended use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on flipper-active_record (>= 0) is not recommended use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on rake (>= 0, development) is not recommended use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on rspec (>= 0, development) is not recommended use a bounded requirement, such as '~> x.y'
WARNING:  open-ended dependency on rspec-rails (>= 0, development) is not recommended use a bounded requirement, such as '~> x.y'
WARNING:  See …
```
=> Fix specs when using bundler 2.1

app/views/request_mailer/new_response.text.erb, spec/mailers/previews/request_mailer/new_response_preview.rb
Fixes #5460 
Update new response email to take into account if the info request is embargoed or not.
Adds mailer previews [[1](http://0.0.0.0:3000/rails/mailers/request_mailer/new_response/public)] [[2](http://0.0.0.0:3000/rails/mailers/request_mailer/new_response/embargoed)] for this mail
Original copy was incorrect and confusing when dealing with embargoed requests. 
In the original version the locale string has had a new line added which is why its wrapping differently. See #3065. 
Public:
Embargoed:
=> [#5460] Update new response email

app/assets/stylesheets/admin.scss
Make the admin footer sticky
Clearer differentiation between main content and footer.
BEFORE
AFTER
=> Sticky admin footer

app/controllers/request_controller.rb, app/views/request/_act.html.erb, app/views/request/_attention_requested.html.erb, app/views/request/_batch.html.erb, app/views/request/_sidebar.html.erb, app/views/request/_similar.html.erb, app/views/request/show.html.erb, spec/controllers/request_controller_spec.rb, spec/views/request/_attention_requested.html.erb_spec.rb, spec/views/request/_sidebar.html.erb_spec.rb, spec/views/request/_similar.html.erb_spec.rb, spec/views/request/show.html.erb_spec.rb
https://github.com/mysociety/alaveteli/pull/5501
* Extracts each sidebar section to a partial
* Cleans most sidebar-related templates
* Adds specs for logic-heavy templates
* Extracts ivars from partials
Sidebar specs are failing in https://github.com/mysociety/alaveteli/pull/5501, and it wasn't much effort to just clean up all this mess to make it easier to do what I was after for the citations.
Resolving some hound warnings on partials I didn't really want to touch, mainly 3df8c06
=> Sidebar cleanup

app/controllers/admin_public_body_change_requests_controller.rb, app/views/admin_public_body/_form.html.erb, app/views/admin_public_body_change_requests/_response.html.erb, app/views/admin_public_body_change_requests/edit.html.erb, doc/CHANGES.md, spec/controllers/admin_public_body_change_requests_controller_spec.rb
Fixes #5427
* Various cleanup
* Add close without response to change request edit
* Add change request summary to edit form
The admin summary allows change requests to be closed without
responding to the user, or closed with a response to the user. The edit
form only allows the latter.
This is problematic because we send the edit form URL to the admin
contact address when we notify them of a new change request. If they
want to close without responding, they've got to go back to the admin
summary, find the change request, and close it that way.
The behaviour for "close" and "close and respond" already exists; this just adds it 
ADMIN SUMMARY
No change here, but just for context:
EDIT FORM BEFORE
EDIT FORM AFTER
EDIT BODY AFTER
No change from original
I ended up rendering the summary …
=> [#5427] Close change request without responding

app/views/request/_incoming_correspondence.text.erb, doc/CHANGES.md, spec/support/load_file_fixtures.rb, spec/views/request/_incoming_correspondence.text.erb_spec.rb
Fixes #5504 
Fixes HTML output in text template.
HTML isn't human-readable, which is the intention of the template.
Added some specs, though only enough to verify the bugfix; adding more would be too much effort right now.
Needed to stub `current_user` and `current_ability` as per https://stackoverflow.com/a/5022406/387558
=> [#5504] Fix HTML output in text template

spec/factories/alaveteli_pro/draft_info_request_batches.rb, spec/factories/alaveteli_pro/embargo_extensions.rb, spec/factories/alaveteli_pro/embargos.rb, spec/factories/alaveteli_pro/request_summaries.rb, spec/factories/alaveteli_pro/request_summary_categories.rb, spec/factories/announcements.rb, spec/factories/censor_rules.rb, spec/factories/comments.rb, spec/factories/draft_info_requests.rb, spec/factories/foi_attchments.rb, spec/factories/holidays.rb, spec/factories/incoming_messages.rb, spec/factories/info_request_batches.rb, spec/factories/info_request_events.rb, spec/factories/info_requests.rb, spec/factories/mail_server_logs.rb, spec/factories/notifications.rb, spec/factories/outgoing_messages.rb, spec/factories/post_redirects.rb, spec/factories/public_bodies.rb, spec/factories/public_body_change_requests.rb, spec/factories/track_things.rb, spec/factories/users.rb, spec/factories/webhooks.rb
Required for https://github.com/mysociety/alaveteli/pull/5398.
Remove remaining static attributes
FactoryBot 5.0.0 removes static attributes [1]. This commit allows us to
upgrade to 5.0.0 and beyond.
[1] https://github.com/thoughtbot/factory_bot/blob/master/NEWS.md#500-february-1-2019
=> Remove remaining static attributes

script/rails-deploy-before-down
Part of #5516
* Currently breaking – see https://github.com/mysociety/alaveteli/issues/5516
* `config/test.yml` uses Gaze, so tests don't use the local database
(but they should! https://github.com/mysociety/alaveteli/issues/5518).
Specs are failing; deploys probably are too
=> [#5516] Don't download geoip in specs

config/general.yml-example, doc/CHANGES.md, lib/configuration.rb, lib/tasks/geoip.rake
Fixes https://github.com/mysociety/alaveteli/issues/5516
* Add MAXMIND_LICENSE_KEY config. Allows us to supply a `license_key`
parameter to the new direct download URL [2].
* Update `geoip:download_data` task to use the new authenticated URL.
As of December 30 2019 GeoLite2 databases are no longer served from a
public URL [1]. Downloads now require a license key, obtained through a
free maxmind.com account.
* Removed existing db (`rm vendor/data/*`)
* Added key to `MAXMIND_LICENSE_KEY`
* Downloaded database with `rake geoip:download_data`
* Tested some lookups:
```ruby
AlaveteliGeoIP.country_code_from_ip('204.xx.xxx.78')
AlaveteliGeoIP.country_code_from_ip('81.xxx.xxx.143')
```
Can also see records of download in MaxMind account download history:
---
[1] …
=> [#5516] Account for new MaxMind license restrictions

app/models/alaveteli_pro/subscription.rb, app/models/alaveteli_pro/subscription_collection.rb, app/models/pro_account.rb, spec/models/alaveteli_pro/subscription_collection_spec.rb, spec/models/alaveteli_pro/subscription_spec.rb, spec/models/pro_account_spec.rb
* Adds the `AlaveteliPro::Subscription#past_due?` helper
* Adds the `AlaveteliPro::SubscriptionCollection#past_due` scope
* Allows `ProAccount#active?` to consider a `past_due` subscription as
"active", in that we still consider a `past_due` sub as "OK" – we're
assuming the payment problem is temporary, or rely on the
auto-cancelling to clean up if the user becomes delinquent.
When a subscription goes `past_due` (most commonly after a failed
payment) we send an email suggesting the user update their card at
`/profile/subscriptions`. We only allow access to
`AlaveteliPro::SubscriptionsController` if the user has an _active_
subscription.
Prior to this commit, we defined "active" explicitly as the
`Stripe::Subscription#status` being `"active"`. This means that when a
sub moves to `past_due` …
=> Fix double-billing edge case

app/controllers/alaveteli_pro/plans_controller.rb, app/controllers/alaveteli_pro/subscriptions_controller.rb, app/models/alaveteli_pro/subscription.rb, app/models/alaveteli_pro/subscription_collection.rb, app/models/pro_account.rb, spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb, spec/models/alaveteli_pro/subscription_collection_spec.rb, spec/models/alaveteli_pro/subscription_spec.rb, spec/models/pro_account_spec.rb
* Consider all Stripe subscriptions "active"
* Rename ProAccount#active? to ProAccount#subscription?
* Replace conditionals with guard clauses
Fixes Pro account access check regression.
Avoids confusion between "a user being subscribed to Pro" and a `Stripe::Subscription` with a status of `active`.
Minor code cleanup.
=> Rename ProAccount#active? to ProAccount#subscription?

app/models/public_body.rb
Auto-correct Style/EmptyCaseCondition
Code cleanup
Manually removed the `then` after the conditionals – the autocorrect kept them.
=> Auto-correct Style/EmptyCaseCondition

app/assets/stylesheets/responsive/_one_time_passwords_layout.scss, app/assets/stylesheets/responsive/_one_time_passwords_style.scss
Highlight importance of saving OTP
We had an instance of a user needing their OTP reset and read out over a
video call. It doesn't happen frequently (this particular case is the
first that I know of), but if/when it does, it's extremely expensive (in
terms of time) to resolve. On reflection, we don't really highlight the
importance of saving the OTP, so this commit makes it much clearer.
=> Highlight importance of saving OTP

app/controllers/alaveteli_pro/subscriptions_controller.rb, app/models/alaveteli_pro/with_tax.rb, config/general.yml-example, doc/CHANGES.md, lib/configuration.rb, spec/models/alaveteli_pro/with_tax_spec.rb
https://github.com/mysociety/asktheeu-theme/issues/77
Allows setting a correct tax rate for Pro pricing plans.
[Spanish VAT rate](https://www.avalara.com/vatlive/en/country-guides/europe/spain/spanish-vat-rates.html) (where AsktheEU are based) is 21% – we hard-coded to 20%.
Had to replace the constant as it was getting frozen in tests.
=> Add STRIPE_TAX_RATE

db/seeds.rb, doc/CHANGES.md, script/rails-deploy-while-down
Fixes #4029
Always db:seed on deploy
If `ENABLE_ALAVETELI_PRO` is set without the correct seeds in place, the site will not work as expected.
Tested by:
* Deleted `pro` and `pro_admin` roles
* Ran `script/rails-post-deploy`
* Script exited successfully; roles now exist
=> [#4029] Always db:seed on deploy

app/mailers/track_mailer.rb, app/models/info_request_batch.rb, app/models/user.rb, spec/models/info_request_batch_spec.rb, spec/models/user_spec.rb
Fixes https://github.com/mysociety/asktheeu-theme/issues/103
* Sends batch requests in the locale they were made under (some assumptions made – see 038813c)
* Replace `User#get_locale` with `User#locale`
* Minor cleanup
The authority name was not being interpolated in to the outgoing messages of batch requests if made in a non-default locale.
Some assumptions made – see 038813c
**BEFORE**
**AFTER**
=> [#eu103] Respect the locale an InfoRequestBatch was created in when sending

.travis.yml
Required by #5440
Test Ruby 2.7 on Travis
See what we need to fix in order to add Ruby 2.7 support.
We don't require 2.7 to pass for now.
=> [#5440] Test Ruby 2.7 on Travis

spec/lib/acts_as_xapian_spec.rb
Connects to #4574 
Move fixture creation to before/after each spec instead of at the start
of the whole suite. This is how we've implemented other specs which call
`update_xapian_index`.
Should fix transient spec error:
```
ActiveRecord::RecordNotFound: Couldn't find RawEmail with 'id'=1
```
=> [#4574] Refactor Xapian fixture setup

spec/factories/info_request_batches.rb, spec/factories/info_request_events.rb, spec/factories/outgoing_messages.rb
Fix issues creating InfoRequestEvent factories
Without this change we couldn't correctly set InfoRequest on nested
association for OutgoingMessage, IncomingMessage and Comment, such as:
```ruby
e = FactoryBot.build(:sent_event, info_request: info_request)
e.outgoing_message.info_request == info_request #=> false
```
But now this would evaluate as true.
I've corrected the one place I've found within others factories where this is an issue. There may well be specs which might need updating for this, lets see what colour CI is...
=> Fix issues creating InfoRequestEvent factories

Gemfile, Gemfile.lock, Gemfile.rails_next.lock, app/controllers/alaveteli_pro/batch_downloads_controller.rb, app/helpers/download_helper.rb, app/services/info_request_batch_metrics.rb, app/services/info_request_batch_zip.rb, app/views/alaveteli_pro/info_request_batches/_info_request_batch.html.erb, config/initializers/date_formats.rb, spec/controllers/alaveteli_pro/batch_downloads_controller_spec.rb, spec/factories/incoming_messages.rb, spec/factories/info_request_events.rb, spec/models/incoming_message_spec.rb, spec/services/info_request_batch_metrics_spec.rb, spec/services/info_request_batch_zip_spec.rb
Depends on #5558
Fixes https://github.com/mysociety/alaveteli-professional/issues/360
Adds ability for pro users to downloads an zip archive of their batch requests
Using a live streaming zip file approach we may need to run this in the background if the performance on production isn't good.
=> [pro#360] Zip download of batch requests

lib/alaveteli_geoip.rb, spec/lib/alaveteli_geoip_spec.rb
Fixes: #5430
Fix IP country lookup
When the GeoIP database can't find a country or continent prevent errors
from being raised. Can happen if the IP is associated to an anonymous
proxy.
=> [#5430] Fix IP country lookup

app/views/request_mailer/requires_admin.text.erb
This will make support easier, especially for batch requests where
almost identical emails can be received.
Taken from: https://github.com/mysociety/whatdotheyknow-theme/pull/661
=> Add Public Body name to "requires admin" email

app/controllers/alaveteli_pro/batch_downloads_controller.rb, app/services/info_request_batch_zip.rb, spec/controllers/alaveteli_pro/batch_downloads_controller_spec.rb, spec/services/info_request_batch_zip_spec.rb
Connected to mysociety/alaveteli-professional#360
Fixes #5587 
1. Checks messages can be read before allowing them to be exported
2. Prevents exporting message body as an attachment
3. Ensures attachments filepaths are unique
In order to get the feature shipped
=> [pro#360] Fixes for Zip download of batch requests

.travis.yml
Configure Travis to use [conditional jobs](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Conditional-Jobs) to limit the number of builds required to get a PR green.
We don't need to always test the next Ruby & Rails versions.
- Ruby 2.3.3, which comes with Debian Stretch, is now only tested on
master and develop as this isn't used by default any more.
- Ruby-head is now only tested on master and develop as its allowed to
fail.
- Next version of Rails is now only tested on master/develop or any
branch beginning with `rails`.
Travis can be slow. Implemented while waiting for builds to finish.
=> Limit number of Travis CI builds

app/views/public_body/view_email.html.erb, doc/CHANGES.md
Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/659
Instead of linking to help/contact, link to the change request form where we're asking users to contact us in relation to public body email updates.
This automatically links the suggestion with the authority and makes it easier for admins to accept/reject the suggestion.
Nothing to see really – the `href` of the link changes.
=> [wdtk#659] Link to change request

app/controllers/request_controller.rb, app/models/user.rb, app/views/comment/_single_comment.html.erb, app/views/statistics/_people_leaderboard.html.erb, app/views/user/_user_listing_single.html.erb, app/views/user/show/_show_profile.html.erb, doc/CHANGES.md, spec/controllers/request_controller_spec.rb, spec/factories/users.rb, spec/models/user_spec.rb
Fixes #5171
* Hides profile photos of banned users
* Bit of refactoring
* So that we don't show spam profile photos
**ACTIVE SPAMMER**
**BANNED SPAMMER**
Signed in, the spammer sees that they can change the profile photo, but we [prevent them actually doing that](https://github.com/mysociety/alaveteli/blob/develop/app/controllers/user_controller.rb#L268) later on. I don't think showing the link at this point is a problem.
Non-logged in:
Tried adding a profile photos factory but for some reason it kept [erroring on file format](https://github.com/mysociety/alaveteli/blob/e13195da1fbae55fefcf8157f9235b7a0809ba8e/app/models/profile_photo.rb#L79), even though I was just doing `data { load_file_fixture('parrot.png') }`. No big deal for now though IMO.
=> [#5171] Hide banned users photo

app/controllers/attachments_controller.rb, app/models/incoming_message.rb, spec/controllers/attachments_controller_spec.rb, spec/integration/incoming_mail_spec.rb
Connected to #5580 
Refactor attachments controller. 
Preparing for allowing "share by link" to work with attachments.
A lot of commits to show the process and hopefully be easy to review...
I haven't touched the fragment caching in this yet. This should be address in a separate issue. See #1549
=> Refactor attachments controller

app/models/role.rb, app/views/admin_user/_form.html.erb, app/views/admin_user/index.html.erb, spec/models/role_spec.rb
Connected to #5593 
Adds `Role.grantable_roles` method to limit which roles can be granted via the users admin UI.
When adding new roles in #5593, these new roles are showed in the UI when they shouldn't.
=> Update grantable roles in user admin UI

script/install-as-user, script/site-specific-install.sh
As of c5608b59b14afc0cefd724a2181f15f15584c8bc mailcatcher is installed
as a global gem, rather than in the application Gemfile bundle.
`script/install-as-user` is run as the application user, so doesn't have
permission to install gems globally.
This commit moves the install of mailcatcher to
`script/site-specific-install.sh`, which is run as root.
Also only installs the gem when `$DEVELOPMENT_INSTALL` is set.
Requires https://github.com/mysociety/alaveteli/pull/5610 to test on a new VM.
=> Fix installer permission issues

lib/tasks/incoming_messages.rake, script/parse-unparsed-pro
Fixes https://github.com/mysociety/alaveteli/issues/4919.
Removes the `parse_unparsed_pro` task.
This was a temporary task that ran via cron to address performance
problems with parsing incoming messages belonging to info requests in
large batches.
The underlying performance problem got fixed [1] so this can now be
removed.
[1] https://github.com/mysociety/alaveteli/pull/4959
=> Remove parse_unparsed_pro

config/initializers/money.rb
Set money gem rounding mode
To remove deprecation warning from spec output
Using the new default of ROUND_HALF_UP
> Indicates that digits >= 5 should be rounded up, others rounded down
Instead of ROUND_HALF_EVEN
> Round towards the even neighbor
=> Set money gem rounding mode

app/helpers/alaveteli_pro/info_requests_helper.rb, app/views/alaveteli_pro/info_requests/_embargo_create_form.html.erb, app/views/alaveteli_pro/info_requests/_embargo_extension_form.html.erb, spec/fixtures/locale/es/app.po, spec/helpers/alaveteli_pro/info_requests_helper_spec.rb
Connected to issue with #5608
Don't initialise new instances of Embargo or EmbargoExtenstion in forms as we might check for the presence of these associations later in the view rendering.
This happens a lot at the moment with CanCanCan abilities checking if an info request is public or private by checking `info_request.embargo`.
Due to `info_request.embargo` now being `nil` I had to allow for this in the `embargo_extension_options` helper - this also needed specs as it wasn't covered initially.
=> Refactor embargo forms

app/models/project.rb, app/models/project_membership.rb, app/models/project_resource.rb, app/models/role.rb, app/models/user.rb, config/initializers/alaveteli_features.rb, db/migrate/20200311141432_create_projects.rb, db/migrate/20200311141504_create_project_memberships.rb, db/migrate/20200314215007_create_project_resources.rb, db/seeds.rb, lib/configuration.rb, spec/factories/project_memberships.rb, spec/factories/project_resources.rb, spec/factories/projects.rb, spec/fixtures/roles.yml, spec/models/project_membership_spec.rb, spec/models/project_resource_spec.rb, spec/models/project_spec.rb
https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/11
Add initial data models for new projects feature.
For the project membership I originally attempted to use Rolify's `resourcify` class method and related methods but in the end it worked out easier to create a separate ProjectMembership model. We're not using currently using the Role#resource polymorphic association for an other role/resource so it seems sensible to keep separate and the Role model simpler.
=> [fnf#11] Add data models for projects feature

app/views/alaveteli_pro/info_requests/_embargo_extension_form.html.erb, app/views/alaveteli_pro/info_requests/_embargo_form.html.erb
Cleans up and reduces complexity in `_embargo_extension_form.html.erb`, similar to https://github.com/mysociety/alaveteli/pull/5615
Similar question about how we create the form url as in https://github.com/mysociety/alaveteli/pull/5615.
=> Refactor embargo extension form

app/helpers/alaveteli_pro/info_requests_helper.rb, app/views/alaveteli_pro/info_requests/_embargo_create_form.html.erb, config/initializers/inflections.rb, spec/helpers/alaveteli_pro/info_requests_helper_spec.rb
Further refactoring of `embargo_create_form` after https://github.com/mysociety/alaveteli/pull/5612.
Reduce complexity.
4b43545 takes the approach of creating a new instance of `AlaveteliPro::Embargo` to build the form, but there's an alternative option and I'm sure which I prefer.
```erb
<%= form_for(AlaveteliPro::Embargo.new, html: { class: 'js-embargo-form' }) do |f| %>
```
I like this because the URL is figured out automatically.
There's a second option here, since we're not actually using the instance, of doing:
```erb
<%= form_with(url: alaveteli_pro_embargoes_path, html: { class: 'js-embargo-form' }) do |f| %>
```
I like this because it's clearer that we're not relying on a local instance of anything. On the downside, it's not as resource oriented.
=> Further refactoring of embargo_create_form

app/controllers/attachments_controller.rb, app/helpers/info_request_helper.rb, app/views/request/_bubble.html.erb, app/views/request/_view_html_prefix.html.erb, spec/helpers/info_request_helper_spec.rb
https://github.com/mysociety/alaveteli/issues/5542
Extracts some prep commits from https://github.com/mysociety/alaveteli/pull/5608
This PR is mostly about refactoring attachment paths
Makes it easier to review the core implementation of share by link without also needing to think about unrelated refactoring.
=> [#5542] share by link prep 2

app/controllers/attachments_controller.rb, app/controllers/concerns/fragment_cachable.rb, spec/controllers/attachments_controller_spec.rb, spec/integration/errors_spec.rb
https://github.com/mysociety/alaveteli/issues/5542
Extracts some prep commits from https://github.com/mysociety/alaveteli/pull/5608
This PR is mostly about refactoring fragment caching
Makes it easier to review the core implementation of share by link without also needing to think about unrelated refactoring.
=> [#5542] share by link prep 3

config/environments/development.rb
`perform_caching` is configurable by creating `tmp/caching-dev.txt`.
This line was preventing that working, as even if the file exists the
configuration was getting overwritten by this line re-setting it to
`false`.
=> Remove duplicate perform_caching config

.ruby-style.yml
This is the default in rubocop [1] and the recommended approach in the
Ruby Style Guide [2]. For some reason Hound keeps warning us to use
`fail` instead.
[1] https://docs.rubocop.org/en/stable/cops_style/#stylesignalexception
[2] https://rubystyle.guide/#prefer-raise-over-fail
=> Force Style/SignalException to use only_raise

app/controllers/projects/projects_controller.rb, app/models/ability.rb, app/models/project.rb, app/views/projects/projects/show.html.erb, config/routes.rb, spec/controllers/projects/projects_controller_spec.rb, spec/factories/projects.rb, spec/models/ability_spec.rb, spec/models/project_spec.rb
Part of https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/20
* Sets up permissions for reading a `Project`
* Adds a basic `ProjectsController` so that we can view a project
So that Project members can view a project, and gives us a place to hang other features off.
In standup I said I'd wite some notes on the direction of travel for the controllers.
Here's what I think we'll end up with at the end:
```ruby
Projects::BaseController
Projects::ProjectsController < Projects::BaseController
Projects::ClassificationsController < Projects::BaseController
Projects::ExtractsController < Projects::BaseController
Projects::VerificationsController < Projects::BaseController
Projects::FollowupsController < Projects::BaseController
```
Note that the task queue controllers …
=> [fnf#20] Projects home
