app/models/project.rb
spec/models/project_spec.rb

Turned `Project#info_requests` into a proper `has_many` association. This allows helper methods such as `#count`, `#include?`, `#find_by` etc to be chained.
Any method in `ActiveRecord::FinderMethods` or `ActiveRecord::Calculations` should work as we would normally expect.
Was trying to do something like https://github.com/mysociety/alaveteli/commit/0a70657699378cbbe33ab83e6665073310fa773f but for `InfoRequest`. Without this change all requests would be loaded and evaluated in Ruby so this change will perform better.
Would recommend hiding whitespace changes to see a simpler diff

[fnf] Refactor Project#info_requests method

---

app/controllers/alaveteli_pro/classifications_controller.rb
app/controllers/classifications_controller.rb
app/controllers/concerns/classifiable.rb
app/views/classifications/message.html.erb
config/routes.rb
spec/controllers/alaveteli_pro/classifications_controller_spec.rb
spec/controllers/classifications_controller_spec.rb
spec/support/shared_examples_for_adding_classification_message.rb

Connects to https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/13
Depends #5628
Fixes #5577
Fixes https://github.com/mysociety/alaveteli-professional/issues/484
Brings features from the non-Pro info request classification to the Pro version, such as:
1. Classification messages - ask the Pro for details if they select `error_message` or `requires_admin`
2. Status update info request event logging
Also refactors non-Pro classification controller specs to make them more consistent. Initially I though this would be useful for adding specs for the Pro classification controllers, but in the these have been written from scratch.
Both of these should help with Pro support admin.

[fnf#13] Classifications - prep 2

---

app/views/alaveteli_pro/info_requests/_after_actions.html.erb
app/views/request/_after_actions.html.erb
app/views/request/_request_header.html.erb
app/views/request/_request_subtitle.html.erb
app/views/request/show.html.erb
app/views/track/_tracking_links_simple.html.erb
spec/views/alaveteli_pro/info_requests/_after_actions.html.erb_spec.rb
spec/views/request/_after_actions.html.erb_spec.rb

Cleans up rendering of `request/request_header`.
Extracts instance variables out to partials to make dependencies clearer.
Makes it easier to render `request/request_header` for Projects views.

[fnf#20] Clean request/request_header

---

app/controllers/alaveteli_pro/classifications_controller.rb
app/controllers/concerns/classifiable.rb
app/controllers/projects/base_controller.rb
app/controllers/projects/classifications_controller.rb
app/controllers/projects/extracts_controller.rb
app/models/ability.rb
app/models/project.rb
config/routes.rb
spec/controllers/classifications_controller_spec.rb
spec/controllers/projects/base_controller_spec.rb
spec/controllers/projects/classifications_controller_spec.rb
spec/models/ability_spec.rb
spec/models/project_spec.rb
spec/support/shared_examples_for_adding_classification_message.rb

Closes https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/13
Adds permissions and controller actions to allow project based info request classification by any member of a given project.
There is some implementation crossover with #5636 but should be anything contentious.
This PR doesn't add any UI to show a form which submits to the controller action.

[fnf#13] Project classifications

---

app/models/info_request_batch.rb
app/views/info_request_batch/_downloads.html.erb
app/views/info_request_batch/show.html.erb
spec/models/info_request_batch_spec.rb

Missed from https://github.com/mysociety/alaveteli-professional/issues/360
Missed from https://github.com/mysociety/transparency-adessium/issues/9
Adds CSV and ZIP download links to batch sidebar
The batch show page is the canonical home for a batch – should be able to use these features there.
This allows non-pro users to download the same information. Makes life easier to do this because pros should still be able to download their now-public requests. You can only download your _own_ requests though, not other users'.

Add download links to batch sidebar

---

app/assets/stylesheets/responsive/alaveteli_pro/_projects_layout.scss
app/assets/stylesheets/responsive/alaveteli_pro/_projects_style.scss
app/assets/stylesheets/responsive/all.scss
app/views/projects/projects/_project_nav.html.erb
app/views/projects/projects/show.html.erb

Part of https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/20
- Adds basic layout and styles for the project homepage
- So that projects have an index page and waymarkers to tasks
- Uses `<progress>` which I've never used before and might require some further cross-browser testing
- Lots of harcoded figures and elements to be replaced

[fnf#20] Basic styling, layout and HTML stubs of project homepage

---

app/controllers/application_controller.rb

https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/60
* Clean up ApplicationController#authenticated? 
* Allow authenticated? to receive optional post_redirect
In https://github.com/mysociety/alaveteli/pull/5648 we create a `PostRedirect` through checking whether they're signed in. This doesn't redirect to the right place in all cases, so the easy option for now is to build an action-specific `PostRedirect` and pass it through.
Here's how I want to use it in `Projects::ContributorsController`:
```ruby
class Projects::ContributorsController < Projects::BaseController
before_action :authenticate, except: [:destroy]
def create
end
def destroy
return unless authenticate!
end
private
def authenticate
authenticated?(…)
end
def authenticate!
post_redirect = …
```

[fnf#60] Refactor ActionController#authenticated?

---

app/helpers/info_request_helper.rb
spec/helpers/info_request_helper_spec.rb

Fixes: https://github.com/mysociety/whatdotheyknow-theme/issues/684
See: https://github.com/mysociety/alaveteli/pull/5625
See: https://github.com/mysociety/alaveteli/pull/5602
Fix broken Google Docs viewer attachment pages
We need to use the full URL instead of just the path.

[wdtk#684] Fix broken Google Docs viewer attachment pages

---

.codeclimate.yml
app/models/dataset.rb
app/models/dataset/key.rb
app/models/dataset/key_set.rb
app/models/dataset/value.rb
app/models/dataset/value_set.rb
app/models/project.rb
app/views/projects/dataset/key_sets/_key_set.html.erb
app/views/projects/dataset/keys/_base_key.html.erb
app/views/projects/dataset/keys/_boolean_key.html.erb
app/views/projects/dataset/keys/_key.html.erb
app/views/projects/dataset/keys/_numeric_key.html.erb
app/views/projects/dataset/keys/_text_key.html.erb
app/views/projects/extracts/_sidebar.html.erb
app/views/projects/extracts/show.html.erb
db/migrate/20200501183039_create_dataset_key_sets.rb
db/migrate/20200501183049_create_dataset_keys.rb
db/migrate/20200501183102_create_dataset_value_sets.rb
db/migrate/20200501183111_create_dataset_values.rb
spec/factories/dataset_key_sets.rb
spec/factories/dataset_keys.rb
spec/factories/dataset_value_sets.rb
spec/factories/dataset_values.rb
spec/factories/projects.rb
spec/models/dataset/key_set_spec.rb
spec/models/dataset/key_spec.rb
spec/models/dataset/value_set_spec.rb
spec/models/dataset/value_spec.rb
spec/models/project_spec.rb

mysociety/transparency-fnf-whatdotheyknow-projects#20
Adds basic dataset model to store extractions
So we can start work storing the project submission data.
Will need to be rebased/merged with the work done in https://github.com/mysociety/alaveteli/compare/develop...fnf20-projects-extract-design
While there is UI implement this isn't finial and will change.

[fnf#20] Extraction data models

---

app/controllers/projects/classifies_controller.rb
app/views/projects/classifies/show.html.erb
config/routes.rb
spec/controllers/projects/classifications_controller_spec.rb
spec/controllers/projects/classifies_controller_spec.rb

Work on https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/23
Adds a basic `Projects::ClassifiesController#show`
Gives us something to work with to start rendering the classification form.
See commit message notes.
No sidebar yet – just rendering the request into the template.

[fnf#23] Classification show controller stub

---

app/models/project.rb
spec/models/project_spec.rb

Part of https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/28.
Adds a query method for requests to be classified.
Allows us to pick out suitable requests for classification
Once we've implemented https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/23 we can add progress percentage on the project homepage with something like:
```ruby
@classification_progress =
((@project.classifiable_requests.count / @project.info_requests.count.to_f) * 100).floor
```

[fnf#28] Add Project#classifiable_requests

---

app/helpers/classifications_helper.rb
app/views/request/_describe_state.html.erb
app/views/request/_state_transition.html.erb
spec/helpers/classifications_helper_spec.rb

Work on https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/23
* Cleanup and extract some components from `request/_describe_state`.
Prep for reusing elements of the form in Projects.

[fnf#23] Cleanup classification form

---

app/views/projects/dataset/keys/_key.html.erb

Use different names/ids to allow clicking on the label to focus the field.

[fnf#20] Fix project extract form fields/labels

---

app/assets/stylesheets/responsive/_global_style.scss
app/assets/stylesheets/responsive/alaveteli_pro/_extract_layout.scss
app/assets/stylesheets/responsive/alaveteli_pro/_extract_style.scss
app/assets/stylesheets/responsive/all.scss
app/views/projects/dataset/keys/_base_key.html.erb
app/views/projects/dataset/keys/_boolean_key.html.erb
app/views/projects/extracts/_form.html.erb
app/views/projects/extracts/_sidebar.html.erb
app/views/projects/extracts/show.html.erb

Adds layout and basic styling to the projects 'extract' screen
To allow us to continue the buildout of the projects UI to eventually test the whole flow

[fnf#20] Projects extract design

---

app/assets/stylesheets/responsive/_global_style.scss
app/assets/stylesheets/responsive/alaveteli_pro/_classify_layout.scss
app/views/projects/classifies/_sidebar.html.erb
app/views/request/_state_transition.html.erb

https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/23
Adds basic layout and styling to enable use of classification functionality in WDTK projects
Part of making the MVP projects work available to testers
There is code here that could be shared with similar implementations (https://github.com/mysociety/alaveteli/pull/5659), we will fix in the future

[fnf#23] Add classify form design

---

app/assets/stylesheets/responsive/alaveteli_pro/_projects_layout.scss
app/views/projects/projects/show.html.erb

Add classify task to project homepage, and styles needed to make multiple tasks look right
https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/23
Adds the 'classify' task to the project homepage
So contributors can start this task
Only front-end HTML and CSS - note the buttons don't actually link anywhere yet, nor does the progress bar work

[fnf#23] Add classify task to project homepage

---

app/controllers/projects/invites_controller.rb
config/routes.rb
db/migrate/20200515141039_add_invite_token_to_projects.rb
spec/controllers/projects/invites_controller_spec.rb
spec/factories/projects.rb

Work on https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/60
Allows users to join a project as a contributor through an invite URL.
Allow project owners to share the project with non-WDTK users.
Went for adding a simple attribute on `Project`. I do want to extract this out to a concern / polymorphic model, but this gets the job done quickly and isn't too concrete – we can migrate the tokens over to the improved solution later. This allows us to ship faster.
**Owner**
Log in as owner; GET the invite URL
Get "already member" message
**Non-member**
GET the invite URL and get redirected to sign in to join the project
Sign in with existing user
Get added to the project
**Contributor**
Log in as contributor; GET the invite URL
Get "already member" message

[fnf#60] Project invites

---

app/controllers/projects/contributors_controller.rb
app/controllers/projects/projects_controller.rb
app/models/ability.rb
app/models/project.rb
app/views/projects/projects/show.html.erb
config/routes.rb
spec/controllers/projects/contributors_controller_spec.rb
spec/models/ability_spec.rb
spec/models/project_spec.rb

Part of https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/60
Requires https://github.com/mysociety/alaveteli/pull/5642
Allows contributors to leave a project.
Allow contributors to leave a project if they don't want to receive communications about the project anymore.
* Owners can’t be removed
* Owners can remove any contributor
* Contributors can only remove themselves

[fnf#60] Allow contributors to leave a project

---

app/assets/stylesheets/responsive/alaveteli_pro/_classify_layout.scss
app/assets/stylesheets/responsive/all.scss
app/controllers/projects/classifies_controller.rb
app/views/projects/classifies/_describe_state.html.erb
app/views/projects/classifies/_sidebar.html.erb
app/views/projects/classifies/show.html.erb
app/views/request/_state_transition.html.erb
spec/controllers/projects/classifies_controller_spec.rb

Work on https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/23
Requires https://github.com/mysociety/alaveteli/pull/5663
Adds Projects classification form and basic styling
To allow contributors to classify requests in a project

[fnf#23] Add classify form

---

app/assets/javascripts/general.js
app/assets/stylesheets/responsive/_global_style.scss
app/assets/stylesheets/responsive/alaveteli_pro/_extract_layout.scss
app/views/projects/classifies/_sidebar.html.erb
app/views/projects/extracts/_form.html.erb

to temporarily give us skip functionality on the project extract form
Adds a Javascript-driven 'skip' button to project pages, hidden unless the visitor has JavaScript enabled and loaded
To temporarily 'fake' the skip functionality by refreshing the window until a queue-based solution is made
Only currently on the extract form, but can be added to classify when available

[fnf] Add a JS refresh button 

---

app/controllers/projects/classifications_controller.rb
app/views/classifications/message.html.erb
spec/controllers/projects/classifications_controller_spec.rb

https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/23
Allows submitting a classification message via a project classification.
Prior to this commit we weren't passing the `:url_title` param, so couldn't find the `InfoRequest` the classification was for.
**BEFORE**
**AFTER**
You see flash success message and get redirected back to the homepage (though soon to be redirected to another request after https://github.com/mysociety/alaveteli/pull/5669 is merged).

[fnf#23] Fix submission of classification message via Projects

---

app/models/project.rb
app/views/projects/projects/show.html.erb
spec/models/project_spec.rb

Add classification progress to the project homepage
Show users whether there's any work to do
Simple approach for now. Just calculate proportion of requests classified vs needing to be classified.
All requests classified:
I think we need to rephrase "workload" now. Doesn't really make sense that when we're all done "Workload is 100%"?

[fnf#28] Classification progress

---

app/helpers/info_request_helper.rb
app/views/alaveteli_pro/info_requests/_sidebar.html.erb
app/views/projects/classifies/_sidebar.html.erb
app/views/projects/extracts/_sidebar.html.erb
spec/helpers/info_request_helper_spec.rb

Extract js_correspondence_navigation helper
We're starting to reuse this in a few places, so create a helper to
generate the placeholder div.
No behaviour change:

Extract js_correspondence_navigation helper

---

app/controllers/projects/classifications_controller.rb
app/controllers/projects/classifies_controller.rb
spec/controllers/projects/classifications_controller_spec.rb
spec/controllers/projects/classifies_controller_spec.rb

Work on https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/23
* Redirect to project homepage if there are no classifiable requests
* Redirect to more classifications after classifying a request
Links up the actions as expected. 
Message after all classifications done:

[fnf#23] Classify workflow

---

app/controllers/classifications_controller.rb
app/controllers/concerns/classifiable.rb
app/controllers/projects/classifications_controller.rb
app/controllers/projects/extracts_controller.rb
app/models/project.rb
app/models/project/submission.rb
app/views/projects/extracts/_form.html.erb
app/views/projects/extracts/_sidebar.html.erb
app/views/projects/extracts/show.html.erb
config/routes.rb
db/migrate/20200509082917_create_project_submissions.rb
spec/controllers/alaveteli_pro/classifications_controller_spec.rb
spec/controllers/projects/classifications_controller_spec.rb
spec/controllers/projects/extracts_controller_spec.rb
spec/factories/info_request_events.rb
spec/factories/project_submissions.rb
spec/models/project/submission_spec.rb

Depends on #5654
mysociety/transparency-fnf-whatdotheyknow-projects#20
- Adds an extraction POST action which stores form data as Dataset::ValueSet/Value instances.
- Adds project submission model to record Project classifications and extractions

[fnf#20] Project submissions

---

app/views/projects/projects/show.html.erb

https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/30
* Make leave project less prominent
* Add missing translation wrapper
* Leaving is the last thing we want people to do
* Need translation wrapper for eventual re-use
**BEFORE**
**AFTER**

[fnf#30] Make leave project less prominent

---

app/assets/stylesheets/responsive/alaveteli_pro/_extract_layout.scss
app/views/projects/dataset/keys/_base_key.html.erb

* Use textarea for text DataSet::Key
* Ensure dataset keys have bottom margin
Improvements to extract UI usability.
**BEFORE**
**AFTER**

[fnf#20] Minor tweaks

---

app/views/projects/projects/show.html.erb

https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/30
Remove the project nav from the project homepage
Feels a bit weird that it repeats the title and "contact owner" is
already pretty prominent on that page. Only thing we lose is the link to
"tasks". I think they are fairly obvious as you’re going to just scroll
down the page and see the progress bars.
We do lose that little hint that "hey, you’re on this page and there’s
something for you to do", but maybe we can think of a better way of
doing that instead of the nav.

[fnf#30] Remove the project nav from the project homepage

---

app/views/projects/classifies/show.html.erb
app/views/projects/extracts/show.html.erb
app/views/request/_request_header.html.erb
app/views/request/show.html.erb

https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/30
Hides the action menu in project task queues
We want users focused on doing the task at hand, which is provided in the sidebar.

[fnf#30] Hide action menu

---

app/controllers/projects/classifications_controller.rb
app/controllers/projects/classifies_controller.rb
app/controllers/projects/extracts_controller.rb
app/models/dataset/value_set.rb
app/models/info_request.rb
app/models/project.rb
app/models/project/info_request_extension.rb
app/models/project/info_request_query.rb
app/models/project/submission.rb
app/views/projects/projects/show.html.erb
db/migrate/20200520073810_add_info_request_to_project_submission.rb
spec/controllers/projects/classifications_controller_spec.rb
spec/controllers/projects/extracts_controller_spec.rb
spec/factories/project_submissions.rb
spec/models/dataset/value_set_spec.rb
spec/models/project/submission_spec.rb
spec/models/project_spec.rb

1. Add Project#info_request.classifiable
2. Add Project#info_request.classified
3. Add Project#info_request.extractable
4. Add Project#info_request.extracted
5. Adds Project#extraction_progress
In order to generate Project info request queues for contributors to work on.
~~Still need to add `extractable_requests` in some form like https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/20#issuecomment-630893728~~

[fnf#28] Queues

---

app/models/ability.rb
spec/models/ability_spec.rb

Owners and contributors need to be able to view project requests which
are embargoed.
So owners and contributors can classify / extract responses

[fnf] Allow project members to view embargoed requests

---

spec/controllers/alaveteli_pro/pages_controller_spec.rb
spec/controllers/alaveteli_pro/plans_controller_spec.rb
spec/controllers/general_controller_spec.rb

Connects to #5069 
Update specs to use be_successful expectation
Fixes deprecation warning:
```
The success? predicate is deprecated and will be removed in Rails 6.0.
Please use successful? as provided by Rack::Response::Helpers.
```
Also see: fb575f8

[Rails 5.2] Update specs to use be_successful expectation

---

spec/controllers/track_controller_spec.rb

Connects to #5069 
Update expected Cache-Control headers
Rails 5.2 now normalises the directives [1] to remove conflicts so the
most restrictive one gets applied. Explained in this comment [2] better
than I can.
See:
[1] https://github.com/rails/rails/pull/30367
[2] https://github.com/rails/rails/issues/32557#issuecomment-381305169

[Rails 5.2] Update expected Cache-Control headers

---

app/models/mail_server_log.rb

Connects to #5069 
Update renamed private method call
Method renamed upstream
See: https://github.com/rails/rails/commit/dff37ff

[Rails 5.2] Update renamed private method call

---

app/controllers/attachments_controller.rb
app/helpers/info_request_helper.rb
app/models/user.rb
spec/controllers/attachments_controller_spec.rb
spec/helpers/info_request_helper_spec.rb

https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/35
Allow project members to view project request attachments.
For project request classifications and extractions.
We've done something similar as part of #5608 we might want to consider combining into a common approach when we work on that again.

[fnf] Viewing project attachments

---

app/controllers/projects/classifies_controller.rb
app/models/project/queue/base.rb
app/models/project/queue/classifiable.rb
app/views/projects/classifies/_sidebar.html.erb
config/routes.rb
spec/controllers/projects/classifies_controller_spec.rb
spec/factories/projects.rb
spec/models/project/queue/classifiable_spec.rb
spec/support/project_queue_context.rb
spec/support/project_queue_examples.rb

Adds a user-specific classifications queue
As per initial feedback (https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/35), if a contributor views an attachment in a request, then clicks back to go back and classify it, we actually get a different random request.
This preserves the current request the user is working on.

[fnf#28] User-specific classifications queue

---

app/controllers/projects/extracts_controller.rb
spec/controllers/projects/extracts_controller_spec.rb

Clear skips after no more extractable requests left

[fnf#28] Clear skipped extractions

---

app/controllers/request_game_controller.rb
app/models/info_request.rb
app/models/public_body.rb
lib/acts_as_xapian/acts_as_xapian.rb
spec/models/info_request_spec.rb

Connects to #5069 
Resolve dangerous query method deprecations by either:
1. Using ActiveRecord query methods where possible
2. Marking raw SQL as sanitised using Arel
Fixes or prevents deprecation warning:
```
Dangerous query method (method whose arguments are used as raw SQL)
called with non-attribute argument(s) ... Non-attribute arguments will
be disallowed in Rails 6.0. This method should not be called with
user-provided values, such as request parameters or model attributes.
Known-safe values can be passed by wrapping them in Arel.sql().
```

[Rails 5.2] Resolve dangerous query method deprecations

---

app/models/public_body_heading.rb

Connected to #5069 
Fix category header association inverse of option
This was causing an error [1] on Rails 5.2.4 after a fix implemented
upstream [2].
[1] https://github.com/mysociety/alaveteli/issues/5069#issuecomment-639372587
[2] https://github.com/rails/rails/pull/35799

Fix category header association inverse of option

---

app/controllers/alaveteli_pro/batch_request_authority_searches_controller.rb
app/services/alaveteli_pro/access.rb
app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb
spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb
spec/integration/alaveteli_pro/request_creation_spec.rb
spec/services/alaveteli_pro/access_spec.rb

Remove `:pro_batch_access` feature flag
Batch is stable enough to be used by all Pro users. This removes the
feature flag so that any Pro user gets access.
Access to Batch is now just controlled by having access to "Pro".

Remove :pro_batch_access feature flag

---

app/views/alaveteli_pro/info_request_batches/_info_request_batch.html.erb

Closes https://github.com/mysociety/alaveteli-professional/issues/360
Remove :info_request_batch_zip_download feature flag
This has been live for a while now, so removing the flag.

[pro#360] Remove :info_request_batch_zip_download feature flag

---

.vagrant.yml.example
Vagrantfile

Allow the VM to get get an IP address on the local network via DHCP.
This makes it easy to view the development instance from another device
on the network – your smartphone for example.
Only use this on networks you trust.
The public network address is _in addition to_ the private network
address.
See the Vagrant documentation for more information on this setting [1].
[1] https://www.vagrantup.com/docs/networking/public_network.html

Add public_network vagrant setting

---

app/views/comment/_single_comment.html.erb
app/views/followups/new.html.erb
app/views/projects/classifies/show.html.erb
app/views/projects/extracts/show.html.erb
app/views/request/_correspondence.html.erb
app/views/request/_correspondence_footer.html.erb
app/views/request/_incoming_correspondence.html.erb
app/views/request/_outgoing_correspondence.html.erb
app/views/request/events/_comment.html.erb
app/views/request/events/_followup_resent.html.erb
app/views/request/events/_followup_sent.html.erb
app/views/request/events/_resent.html.erb
app/views/request/events/_response.html.erb
app/views/request/events/_send_error.html.erb
app/views/request/events/_sent.html.erb
app/views/request/show.html.erb

https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/30
* Hide correspondence footers in projects
* Hide correspondence footers in followups
* The footers don't make sense in the context of a project
* The footers are too long on mobile (https://github.com/mysociety/alaveteli/issues/5698)

[fnf#30] Hide correspondence footers

---

script/rails-deploy-before-down

We rely quite heavily on dependabot's automated gem updates. However,
it's easy to miss the fact that some development dependencies aren't
mergeable because they aren't installed when running tests, and the
build is green.
This will make builds error when a gem can't be installed due to a Ruby
version constraint. It shouldn't affect performance as we cache gems.

Install development dependencies on Travis

---

Gemfile
Gemfile.lock
Gemfile.rails_next.lock
script/annotate-models

Pinned at 3.1.0 because 3.1.1 drops Ruby 2.3 compatibility.
Bumps [annotate](https://github.com/ctran/annotate_models) from 2.7.2 to 3.1.0.
- [Release notes](https://github.com/ctran/annotate_models/releases)
- [Changelog](https://github.com/ctran/annotate_models/blob/develop/CHANGELOG.md)
- [Commits](https://github.com/ctran/annotate_models/compare/v2.7.2...v3.1.0)
Supersedes https://github.com/mysociety/alaveteli/pull/5719
> **Breaking:** when option `models` is not set - models will not be annotated by default.
>
> Add `'models'=>'true'` to your config manually or use `--models` option if using CLI.
>
> https://github.com/ctran/annotate_models/blob/develop/CHANGELOG.md#300
Need to update `script/annotate-models` to include this.
> Bump required ruby version to >= 2.4
>
> …

Bump annotate from 2.7.2 to 3.1.0

---

app/assets/stylesheets/responsive/alaveteli_pro/_projects_layout.scss
app/controllers/projects/downloads_controller.rb
app/helpers/download_helper.rb
app/models/ability.rb
app/models/project/export.rb
app/models/project/export/info_request.rb
app/views/projects/projects/show.html.erb
config/routes.rb
spec/controllers/projects/downloads_controller_spec.rb
spec/models/ability_spec.rb
spec/models/project/export/info_request_spec.rb
spec/models/project/export_spec.rb

Closes https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/34
Allows project owners to download data collected by the project classifications and extractions.
Only other way to do this was with developer help.
Duplication around CSV generation with the Info Request Batch downloads - ultimately this should be extracted into its own service object.

[fnf#34] Project data download

---

Gemfile
Gemfile.lock
Gemfile.rails_next.lock

This isn't used in the core application, instead is a dependency of other gems we use. Was added in a02a71c where we pinned some gems to support Ruby 1.9.x.
See #5738

Drop public_suffix gem

---

spec/controllers/request_controller_spec.rb
spec/integration/errors_spec.rb
spec/integration/localisation_spec.rb
spec/integration/sign_in_with_redirect_spec.rb
spec/support/shared_context_for_local_requests.rb
spec/support/shared_context_for_show_exceptions.rb

Fixes #1431 
Fixes #4346
Fixes: 
```
1) When errors occur when considering all requests local (by default all in development) should show a full trace for general errors
Failure/Error: expect(response.body).to match('<div id="traces"')
expected "" to match "<div id=\"traces\""
```
This seems to be one of the most common spec failures.
All the seeds I've tried, including the ones on the linked issues, now work. I've also ran this in a loop for a while without seeing failures.
```
rspec spec/integration/errors_spec.rb --seed=16271
rspec spec/integration/errors_spec.rb --seed=46014
rspec spec/integration/errors_spec.rb --seed=58016
```

[#1431] Fix transient spec failure

---

app/models/spam_address.rb
spec/models/spam_address_spec.rb
spec/spec_helper.rb

Fixes #5624
Supersedes https://github.com/mysociety/alaveteli/pull/5634
* Ignore case when checking spam in SpamAddress
* Minor code style cleanup
Reduce admin time by not having to create a `SpamAddress` for each case that spammers use.
https://github.com/mysociety/alaveteli/pull/5634#discussion_r422912006 suggests using Postgres `citext` extension.
Unfortunately, enabling requires either the database user being a superuser, or manual intervention. Neither is a great option, so this keeps things simple from an operations point of view. I'm happy with that given this is such a small class. We can revisit if we need similar behaviour in a more complex or performance-dependent class.

[#5624] Ignore spam address case

---

locale/en/app.po

These strings have added newlines and spaces compared to the original
`msgid` source string.
While the whitespace shouldn't matter for Alaveteli they are shown in
Transifex as the string to be translated rather than the `msgid` string
so can result in translator confusion.

Remove whitespace in translated EN strings.

---

app/views/alaveteli_pro/comment/_suggestions.html.erb
app/views/comment/_suggestions.html.erb
lib/tasks/gettext.rake

https://github.com/mysociety/alaveteli/pull/5711#issuecomment-650079260
Updates our gettext rake tasks to be compatible with gettext v3
Running `gettext:clean` and `gettext:find` was broken so we can't do a release at the moment. 
There will be some differences in PO files because previously, in our strings we had `\\n` this apparently was wrong and fixed upstream so these are now replaced as `\n`, as a result, this means:
1. The `no-wrap` doesn't wrap new lines any more - because it is actually detecting the new lines
2. The ordering has slightly changed

Fix gettext rake commands

---

app/models/censor_rule.rb
lib/alaveteli_text_masker.rb
spec/lib/alaveteli_text_masker_spec.rb
spec/models/censor_rule_spec.rb

Fixes #3546
Fixes #4064
The original implementation assumed the binary would be in ASCII-8BIT
encoding but this is not always the case. I'm unsure at this stage if
something has changed, such as how uncompressed data is extracted from
to the pdftk tool, or if this case has never been handled.
This change forces censor rule into the same encoding and ensures the 
correct number of replacement bytes are used. 
Increasing amount of exception emails.

[#3546] Fix issue applying censor rule to binary data

---

app/models/censor_rule.rb
app/models/foi_attachment.rb
app/models/info_request.rb
lib/alaveteli_text_masker.rb
lib/tasks/temp.rake
spec/lib/alaveteli_text_masker_spec.rb
spec/models/censor_rule_spec.rb
spec/models/foi_attachment_spec.rb
spec/models/info_request_spec.rb

#3546
Adds a temporary rake task to check for attachments with censor rules that will be visible after fixing #3546.
Admins couldn't check that censor rules were being correctly applied to the outputted attachments because the application was erroring. After merging #5474 these attachments will now be visible, but we don't have a way of automatically verifying that the censor rules are being applied correctly. This prints a list of URLs for admins to manually verify.
Added the monkey-patches from https://github.com/mysociety/alaveteli/issues/3546#issuecomment-658051334 to the production codebase because they're useful, and it's more stable than forgetting about them buried in a rake task.

[#3546] Identify broken binary censor rules

---

.github/workflows/rubocop.yml
.hound.yml

There seems to be ongoing issues with HoundCI, and the lately it seems
to be ignoring out RuboCop config completely.

Use GitHub actions to run RuboCop linter

---

lib/tasks/geoip.rake

Fixes #5825
Connected to #5550 
1. Prevent exceptions from being raised if the MaxMind licence key isn't set
2. Task doesn't need to run if Alaveteli is configured with a different GeoIP database
3. Improve logging messages.
In config/general.yml, if you have;
1. `GEOIP_DATABASE: /usr/share/GeoIP/GeoIP.dat`, a notice will be logged:
```
Skipping MaxMind geoip data file download as GEOIP_DATABASE has been set
in config/general.yml to a non-default value
```
2. An unset `MAXMIND_LICENSE_KEY` value, a warning will be logged:
```
Can't download the latest MaxMind geoip data file. Please add
MAXMIND_LICENSE_KEY setting to config/general.yml
```
3. An invalid `MAXMIND_LICENSE_KEY` value, a error will be raised:
```
Error downloading MaxMind geoip data file
401 Unauthorized
Please check the …
```

Fix geoip download rake task

---

spec/controllers/alaveteli_pro/embargo_extensions_controller_spec.rb
spec/factories/users.rb

Extracted from https://github.com/mysociety/alaveteli/pull/5784
Bit of user factory cleanup and bit of cleanup in `spec/controllers/alaveteli_pro/embargo_extensions_controller_spec.rb`
Reducing complexity in test suite.

Clean embargo extensions controller spec

---

config/application.rb
config/environments/test.rb
lib/alaveteli_localization.rb
spec/lib/alaveteli_localization_spec.rb

Fixes #4853
When upgrading the i18n gem past 0.9.3+ [1] we re-introduced a bug [2]
where some translations wouldn't be loaded into memory.
Locales are loaded based on what `I18n.available_locales` has been set
to. This works fine for two-letter locales such as `en` or `cy` but
can break for locales with underscores or hyphens. For example both
`fr_BE` and `is_IS` are broken as they will attempt to load translations
from the rails-i18n gem locale YAML files [3], where these locales with
don't exist so the parent locale will be used, `fr` and `is`.
The problem is these parent locales haven't been loaded as they aren't
set in `I18n.available_locales` so this commit adds parent locales to be
loaded.
Specs have been added to ensure this isn't overlooked again.
[1] …

[#4853] Fix issue where locale strings wouldn't be loaded

---

docs/pro/index.md
docs/pro/pricing.md

Fixes https://github.com/mysociety/alaveteli/issues/5834
Fixes https://github.com/mysociety/alaveteli/issues/5836
Adds some more pro-related documentation to help pages
Help re-users enable Pro

Pro extra help pages

---

docs/pro/index.md
docs/pro/pricing.md

Fixes https://github.com/mysociety/alaveteli/issues/5839
Fixes https://github.com/mysociety/alaveteli/issues/5832
Fixes https://github.com/mysociety/alaveteli/issues/5831
* Add brief description of Pro signup options
* Add STRIPE_TAX_RATE to documentation
* Add ISO_CURRENCY_CODE to documentation
* Add ENABLE_PRO_SELF_SERVE to documentation
Help us explain pro setup to re-users
Screenshot of `Add brief description of Pro signup options` – the rest are just new key/values in the existing definition list.

Add missing pro config keys to documentation

---

docs/pro/index.md

Fixes https://github.com/mysociety/alaveteli/issues/5835.
Add documentation on assigning first pro_admin
Undocumented

Add documentation on assigning first pro_admin

---

.github/dependabot.yml

We're unlikely to support capistrano 3.x.x as we don't use it
internally, so ignore gem bumps until we decide what to do about it.
Supersedes https://github.com/mysociety/alaveteli/pull/5796.

Ignore capistrano gem bumps

---

docs/pro/index.md

Fixes https://github.com/mysociety/alaveteli/issues/5852.
* Reorders sections in the order that they should be completed.
* Adds note clarifying that you need to deploy before adding roles.
Avoid confusion of Pro user roles not being available before deploying.

[#5852] Clarify order of tasks when enabling Pro

---

docs/pro/index.md

Fixes https://github.com/mysociety/alaveteli/issues/5855.
Add placeholder around why POP polling is required for Pro.
Not using the POP poller would make Batch pretty unusable.
This is a bit of a placeholder. To _really_ understand this you need to have a bit of behind-the-scenes knowledge of the codebase. I think its good enough to emphasise that you should use the poller though.

[#5855] Recommend POP Poller when enabling Pro

---

lib/mail_handler/backends/mail_backend.rb
spec/fixtures/files/iso8859_1_with_extended_character_set.email
spec/lib/mail_handler/backends/mail_backend_spec.rb

#5865
Force raw email strings into ASCII-8BIT instead of Ruby's default of UTF-8.
Internally in the Mail gem's `Mail.read` method it reads from a file using `rb` (read, binary) mode which returns an ASCII-8BIT string.
Since the latest deploy we started bouncing some emails due to an exception being raised.

Fix mail ingress

---

lib/alaveteli_localization.rb
lib/alaveteli_localization/hyphenated_locale.rb
lib/alaveteli_localization/locale.rb
lib/alaveteli_localization/underscorred_locale.rb
spec/lib/alaveteli_localization/hyphenated_locale_spec.rb
spec/lib/alaveteli_localization/locale_spec.rb
spec/lib/alaveteli_localization/underscorred_locale_spec.rb
spec/support/alaveteli_localization/spec_helpers.rb

Reduces complexity of `AlaveteliLocalization`, and in particular `AlaveteliLocalization.set_locales`
Too complex to debug other localisation issues.
There are a few public methods where we're not yet parsing the values into `AlaveteliLocalization::Locale` classes. I think it would be nice to do this, but there's probably wider-reaching impact, so perhaps something for another day.

Cleanup alaveteli localization

---

app/controllers/public_body_controller.rb

Fixes #5890
Use the new Rails 5 method `redirect_back` which allows us to define a
fallback location if the browser doesn't supply HTTP referrer header.

[#5890] Update redirect_to back method

---

app/controllers/application_controller.rb

Fixes: https://github.com/mysociety/asktheeu-theme/issues/106
Fixes: https://github.com/mysociety/alaveteli/issues/5484
This changes ordering before action locale callbacks
We need `set_gettext_locale` to run before `collect_locales` this is
because the URL locale from the params is passed into
`AlaveteliLocalization.set_session_locale` and used to set
`FastGettext.locale`.
This is used then used, via `AlaveteliLocalization.locale` in the
`collect_locales` callback to set the `@locales` varibale used when
render the locale switcher.

[eu#106] Fix the locale switcher current locale

---

config/application.rb
config/initializers/alaveteli.rb
lib/alaveteli_localization.rb
lib/alaveteli_localization/hyphenated_locale.rb
lib/alaveteli_localization/locale.rb
lib/alaveteli_localization/underscorred_locale.rb
spec/lib/alaveteli_localization/hyphenated_locale_spec.rb
spec/lib/alaveteli_localization/locale_spec.rb
spec/lib/alaveteli_localization/underscorred_locale_spec.rb
spec/lib/alaveteli_localization_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/5382
* Significant cleanup of `AlaveteliLocalization`
* Ensure the underscore locale is included in i18n fallbacks
Lack of correct fallback results in calling methods on `nil` where we're expecting a translated attribute.
There are a few public methods where we're not yet parsing the values into `AlaveteliLocalization::Locale` classes. I think it would be nice to do this, but there's probably wider-reaching impact, so perhaps something for another day.

[#5382] Ensure the underscore locale is included in i18n fallbacks

---

spec/models/incoming_message_spec.rb

Adds some basic coverage to `IncomingMessage#specific_from_name?`
Created in https://github.com/mysociety/alaveteli/pull/5391 – rescuing as still useful.

Add specs for IncomingMessage#specific_from_name?

---

lib/alaveteli_localization/locale.rb
spec/lib/alaveteli_localization/locale_spec.rb

* Don't parse already parsed Locales
* Extract conditional from Locale.parse
Minor optimisations
Not 100% on bbfacdf, but I think on balance it's an improvement?

Minor optimisation in Locale.parse

---

docs/customising/config.md
docs/installing/email.md
docs/running/server.md

Fixes https://github.com/mysociety/sysadmin/issues/1345
This adds some notes to the GitHub pages documentation on POP server configuration for bulk mail users.
To provide re-users with some basic guidance on how a  POP mailbox might be integrated.
N/A
N/A
There are potentially many ways this could be configured and integrated with Alaveteli, so these initial notes are simply intended to provide some pointers and suggestions.
We can look at extending them as we get feedback from re-users.

Update documentation with POP mailbox suggestions and examples

---

config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb

Sometimes it's useful to be able to use a non-default log level.
This commit allows any log level to be set through `LOG_LEVEL` in the
environment.
If an invalid log level is set the application will fail to boot with a
`NameError`, e.g:
$ LOG_LEVEL=foobarbaz bin/rails runner "puts Rails.application.config.log_level"
uninitialized constant ActiveSupport::Logger::FOOBARBAZ (NameError)
If `LOG_LEVEL` is not set, the default for that environment will be
used.

Allow setting log level through the environment

---

lib/i18n_fixes.rb
spec/fixtures/locale/de/app.po
spec/fixtures/locale/hr/app.po
spec/lib/i18n_interpolation_spec.rb

Fixes https://github.com/mysociety/sobanukirwa-theme/issues/93
Improves our custom override to the `n_` method to:
1. Handle any number of source strings
2. Handle counts being passed in as an string instead of integer.
The `fr` locale works differently to the `en` & `rw` locales. In the PO file `Plural-Forms` is set to `n > 1` [1] which errors when passed a string. Where as other locales have plural forms such as `n != 1` which would return false when given a string.
This is happening on Rwanda as the count is coming from a blog JSON feed so I've improved our override to call `#to_i` on the count to ensure we compare ints with ints.
[1] https://github.com/mysociety/sobanukirwa-theme/blob/master/locale-theme/fr/app.po#L22

[rwanda#93] i18n override improvements

---

app/views/admin_censor_rule/_form.html.erb
app/views/admin_comment/edit.html.erb
app/views/admin_comment/index.html.erb
app/views/admin_public_body/_form.html.erb
app/views/admin_public_body/_locale_fields.html.erb
app/views/admin_public_body/_one_list.html.erb
app/views/admin_public_body/index.html.erb
app/views/admin_public_body/show.html.erb
app/views/admin_request/_some_requests.html.erb
app/views/admin_request/index.html.erb
app/views/admin_request/show.html.erb
app/views/admin_track/_some_tracks.html.erb
app/views/admin_track/index.html.erb
app/views/admin_user/_user_table.html.erb
app/views/admin_user/index.html.erb
app/views/admin_user/show.html.erb
doc/CHANGES.md

Fixes #1353.
Remove translation markup from admin interface.
Reduce work for translators and make admin interface clearer.
Easy ticket to close while I was searching for other issues that https://github.com/mysociety/alaveteli/pull/5893 is likely to fix.
There are a couple of places where we'll still see localisation in the admin interface.
1. Translated model attributes. We generate these at [release time](https://github.com/mysociety/alaveteli/wiki/Release-Manager's-checklist) through `rake gettext:store_model_attributes` provided by https://github.com/grosser/gettext_i18n_rails. I don't know if there's a good reason for doing this, as we [tell people not to bother translating these](https://alaveteli.org/docs/customising/translation/#general-notes-on-translation-in-transifex).
2. …

[#1353] Remove translation markup from admin interface

---

app/controllers/admin_raw_email_controller.rb
app/models/public_body.rb
app/models/raw_email.rb
spec/models/public_body_spec.rb
spec/models/raw_email_spec.rb

* Extract controller code to `PublicBody.with_domain`
* Extract controller code to `RawEmail#domain_from_email`
Reduce controller complexity and add test coverage.

Admin raw email controller extractions

---

doc/CHANGES.md
lib/typeahead_search.rb
spec/lib/typeahead_search_spec.rb

The maximum length of a search query is 252 bytes. People often paste
long strings into the typeahead search which results in an exception
being raised.
Instead of raising an exception, just truncate the query.
We could tell the user the string is too long, but I don't think it's
worth it in this case. The typeahead search is pretty opaque to users –
it just happens as they enter content – and with a string that long I
don't think we'll lose much by truncating it.
Fixes https://github.com/mysociety/alaveteli/issues/5815.

[#5815] Truncate search queries that are too long

---

app/assets/stylesheets/admin.scss
doc/CHANGES.md

This commit forces long strings to wrap, and uses monospace text for
clearer presentation of the data that gets used in the replacement
process.
Long text or replacement attributes would overflow the table cell and
overlap other parts of the UI, making it difficult to understand the
rules applied without editing each rule.
**BEFORE**
**AFTER**

Prevent overflowing of long censor rules

---

.github/workflows/rubocop.yml

Failures for this check are not always technical errors – they're more a
case of requiring human judgement as to whether to fix or not.
Documentation reference: https://github.com/reviewdog/action-rubocop/blob/d3161530d1ad5da4bac484302ecddcba02d186e6/README.md#level

Make RuboCop failures warnings rather than errors

---

spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb
spec/integration/alaveteli_pro/admin_spec.rb
spec/integration/alaveteli_pro/batch_request_spec.rb
spec/integration/create_request_spec.rb
spec/lib/acts_as_xapian_spec.rb

Fixes #4574  - this seems the last error often see so lets close this issue and open new ones for individual errors as they come up in the future.
Don't run `get_fixtures_xapian_index` in a `before :all` spec suite
callback hook as it requires database fixtures for `raw_emails` to be
present but these are only loaded after the callback hook is run.
Instead use a `before :each` hook to run between individual specs.
The use of the `:all` hooks seems to stem from [1] where we change
implementation to call the `ActsAsXapian` directly but then later
reverted in [2] but this didn't switch back to the `:each` hook.
This broken implementation probably then inspired new spec files when
Pro features were added.
[1] https://github.com/mysociety/alaveteli/commit/cf9f0b6
[2] …

[#4574] Update spec before hooks

---

app/controllers/public_body_controller.rb
app/helpers/public_body_helper.rb
app/models/concerns/public_body_derived_fields.rb

Requires https://github.com/mysociety/commonlib/pull/72
For Ruby 2.4+ this now uses core Ruby string `#upcase` method instead of using the Unicode gem. This seems to helpped with issues various issues seen in production.
Once #5222 is done we can remove the gem completely.
Closes #5870 #5871 #5873  #5874 #5876 #5877 #5878 #5879

Remove unicode gem

---

lib/mail_handler/backends/mail_backend.rb
script/handle-mail-replies.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb

Sometimes we receive messages with outlook attachments that can't be
parsed due to an issue in mapi [1].
There's a potential fix [2] but it conflicts [3] with an existing patch
we apply [4].
This at least allows users to download the raw attachment, rather than
us preventing the entire request from loading because we raise an
exception.
Part of https://github.com/mysociety/alaveteli/issues/5783.
[1] https://github.com/aquasync/ruby-msg/issues/15
[2] https://github.com/aquasync/ruby-msg/pull/16
[3] https://github.com/mysociety/alaveteli/issues/5783#issuecomment-655740838
[4] https://github.com/mysociety/ruby-msg/pull/3
> Do not introduce global variables.
We actually rely on `$alaveteli_dir` in this case, as we use it in [`MailHandler::ReplyHandler.load_rails`](https://github.com/mysociety/ …

[#5783] Improve resilience to unparsable outlook attachments

---

app/views/admin_general/index.html.erb
app/views/admin_public_body_change_requests/edit.html.erb
doc/CHANGES.md

Fixes https://github.com/mysociety/alaveteli/issues/5933.
Tweak change request button colours
**admin_public_body_change_requests/edit**
"Close and respond" is more frequently used than "Close", so make it the
primary button.
"Close" is not a destructive action, so just make it a standard button.
**admin_general/index**
Mirror the above changes to the buttons in this view.
We don't want to "primary" buttons, so this makes "Add authority" a
"success" button (green) as that's a clear indication of accepting the
change, with "Close and respond" being the primary fallback option.
**BEFORE**
**AFTER**

[#5933] Tweak change request button colours

---

config/general.yml-example

Clarify supported blog feed providers
Currently we only knowingly support WordPress.
Clarifying issue raised on [alaveteli-dev](https://groups.google.com/g/alaveteli-dev/c/tjoKDvhnLUU/m/u2yQg-goBQAJ).

Clarify supported blog feed providers

---

docs/customising/config.md

Counterpart to https://github.com/mysociety/alaveteli/pull/5961
Currently we only knowingly support WordPress.
Currently we only knowingly support WordPress.
Clarifying issue raised on [alaveteli-dev](https://groups.google.com/g/alaveteli-dev/c/tjoKDvhnLUU/m/u2yQg-goBQAJ).

[gh-pages] Clarify supported blog feed providers

---

app/models/info_request.rb

Fixes #5269
Limit number of info requests guessed by subject 
Receiving a request with a subject like "Freedom of Information Request"
which ends up in the holding pen will cause issues for administrations.
The number of info request guesses would be far too large and this
potentially breaks the admin UI due to the page timing out when
rendering each info request guess.
This change limits to just 25 info requests. While it would be good to
allow these requests to be paginated. It's more likely the admin would
inspect the raw email instead of going through pages of guesses.

[#5269] Limit incoming message guesses

---

Vagrantfile

This is to make onboarding for new users a little tiny bit easier
Partial fix for #5982. The rest of the fix will be done on the main documentation

Add documentation on installing vagrant plugin 

---

app/controllers/general_controller.rb
spec/controllers/general_controller_spec.rb

Add private request count to stats
Make it easier for us to understand total request count by showing
overall number of private requests as well as public requests.
Fixed hash style.

Add private request count to stats

---

app/models/refusal_advice.rb
app/models/refusal_advice/action.rb
app/models/refusal_advice/block.rb
app/models/refusal_advice/question.rb
app/models/refusal_advice/store.rb
app/models/refusal_advice/suggestion.rb
config/initializers/theme_loader.rb
spec/fixtures/refusal_advice/data/eir.yml
spec/fixtures/refusal_advice/data/foi.yml
spec/fixtures/refusal_advice/data/foi_and_eir.yml
spec/fixtures/refusal_advice/eir_questions.yml
spec/fixtures/refusal_advice/eir_suggestions.yml
spec/fixtures/refusal_advice/foi_questions.yml
spec/fixtures/refusal_advice/foi_suggestions.yml
spec/models/refusal_advice/action_spec.rb
spec/models/refusal_advice/block_spec.rb
spec/models/refusal_advice/question_spec.rb
spec/models/refusal_advice/store_spec.rb
spec/models/refusal_advice/suggestion_spec.rb
spec/models/refusal_advice_spec.rb

Part of https://github.com/mysociety/alaveteli/issues/5937.
Parses refusal advice from YAML into usable Ruby objects.
Allows flexibility in keeping all advice in a single file, or spreading
over several files.
Handles name-spacing questions under a legislation key.
Refusal advice can be defined in a single file…
```yml
foi:
- id: have-confirmation
label:
plain: Has the authority confirmed or denied?
options:
- label: "Yes"
value: "yes"
- label: "No"
value: "no"
eir:
- id: is-confirmation-too-costly
show_if:
- id: some-other-question
operator: is
value: "no"
label:
partial: path/to/partial
options:
- label: "Yes"
value: "yes"
- label: "No"
value: "no"
```
…or a file per legislation…
```yml
foi:
- id: have-confirmation
label:
plain: Has the authority confirmed or denied?
options:
- label: …
```

[#5937] JRCT – Parse refusal advice YAML files

---

lib/tasks/temp.rake

Re-parses any incoming messages that look like they were affected by a
regression in Mail [1] that caused some multipart emails to be parsed as
a single part.
To identify affected messages we look for 'Content-Type' in the cached
body text, since that should almost never be seen there. It doesn't
really matter if we re-parse a few false-positives, since caches will
get generated on next view.
The date to look for messages defaults to the commit date [2] that we
introduced the gem version that causes the regression, but is tunable
for re-users who may upgrade much later than us.
[1] https://github.com/mysociety/alaveteli/issues/5905
[2] https://github.com/mysociety/alaveteli/commit/c581d83285
There are currently ~100 examples that match the criteria on WDTK:
```sql
=> SELECT COUNT(*)
FROM …
```

Add temp:reparse_multipart_incoming_with_unicode

---

app/assets/javascripts/wizard.js

Fixes #6008
Alterative to #6009
Prevents errors from being thrown by Uglifier on asset compilation.
4d2ab5a941 introduces ES6 syntax, which Uglifier doesn't support by default [1].
[1] https://github.com/lautis/uglifier#es6--es2015--harmony-mode

[#6008] Remove ES6 syntax from JS

---

app/models/refusal_advice.rb
config/initializers/theme_loader.rb
spec/models/refusal_advice_spec.rb

Fixes #6006
Fix broken help/unhappy page when not using a theme
Before attempting to retrieve refusal advice we need to check its been
configured. If for example we're not using theme then the paths aren't
set up and will return `nil`.
This is the case when running CI by default.
Also allows `RefusalAdvice.default` to be called with no argument
instead of requiring `nil` if there is no info request.

[#6006] fix broken help/unhappy page when not using a theme

---

app/models/legislation.rb
app/models/refusal_advice.rb
spec/models/legislation_spec.rb
spec/models/refusal_advice_spec.rb

* Reduces Demeter violations
* Reduces exposure of encapsulated data [1]
[1] https://www.garethrees.co.uk/2020/06/14/use-protected-attr-readers/

Add Legislation#to_sym

---

spec/spec_helper.rb

Fixes #6018
Remove before test suite callback 
Don't set show exceptions for integration tests. This can hide failures
by returning the in-browser development exception viewer and a 200
response instead of 500.
The lines removed were added as part of https://github.com/mysociety/alaveteli/commit/071b5aab0fc1b05b90ac60bc1f259c6b409f7120 the rest of the "consider all requests local" work added at the same time was rewritten recently in #5621 so I believe this callback can now be removed.

[#6018] fix hidden exceptions in integration specs

---

app/models/incoming_message.rb
app/models/legislation/reference.rb
spec/models/incoming_message_spec.rb
spec/models/legislation/reference_spec.rb

Fixes #6020
- Rename legislation reference main element
- Add LegislationReference equality method
- Add LegislationReference#parent method
- Update IncomingMessage#refusals
Request refusal partial from #5971 was rendering the same reference more than
once these changes ensures we show unique parent reference.
A parent reference being a reference with all sub-sections removed. In this case
we can ignore sub-sections as the refusal wizard isn't using these.

[#6020] render unique references for refusals

---

script/load-sample-data

Fixes #6027
When loading sample data we need to ignore refusal advice as there is no
database table to inject these fixtures into.
To fix the `script/load-sample-data`

[#6027] Ignore refusal advice fixtures

---

lib/has_tag_string/has_tag_string.rb
spec/models/has_tag_string_tag_spec.rb

The original implementation would add the tag irrespective of whether it
was already present, as it simply concatenated the existing and given
strings together.
This makes the method do what it says, and also fixes minor style
issues.
* Fixes quote style
* Fixes redundant self

Fix HasTagString#add_tag_if_not_already_present

---

script/update-xapian-index

We have an internal issue where this task occasionally gets stuck and could do with a portable way to automate handling this situation.
https://github.com/mysociety/sysadmin/issues/1373
This traps a `SIGTERM` sent to the bash script that wraps the call to rake to update the Xapian index. We need to ensure that any children are killed so we use a `SIGKILL` to do this before exiting.
This means that should the update process hang, a `SIGTERM` can be sent to this wrapper and the children will be handled. Given the wrapper may be called from cron or similar, this provides a simple interface to cleaning up.
This is essentially a non-functional change and the script will continue to act as it has in the past. The only difference in a given deployment may be in configuring a management system or …

Add signal handling to Xapian update wrapper script

---

app/controllers/attachments_controller.rb
app/controllers/concerns/prominence_headers.rb
app/controllers/request_controller.rb
doc/CHANGES.md
spec/controllers/attachments_controller_spec.rb
spec/controllers/request_controller_spec.rb

Fixes #5496.
* Cleanup
* Set noindex header for backpaged content
We'd like to use backpaged as a sort of "archive" admin ability.
Backpaging + noindex means that existing links to requests will be preserved (rather than e.g. if hidden or set to requester only) but will be more difficult to find through internal & external search.
Couple of gotchas that I'd like to address at some point, though not necessarily now:
* Inclusion of `ProminenceHeaders` is order-dependent, which is a bit gross
* Should be able to ask the requested record what it's prominence is (e.g. `FoiAttachment#prominence`), rather than having to find the associated `InfoRequest`. The gotcha here is that both `InfoRequest` and `IncomingMessage` have prominence, so which one wins out? Something to consider another time I …

[#5496] Set noindex header for backpaged content

---

app/controllers/attachments_controller.rb
spec/controllers/attachments_controller_spec.rb

#5496
Don't cache backpage attachments
We need to serve the attachment from Rails in order to set the
X-Robots-Tag added in 8e7ac48.
Spec is currently skipped because the attachment seems to be already
cached prior to the spec running, so something to investigate and fix.
Need this commit to resolve a case though.

[#5496] Dont cache backpage attachments

---

lib/user_spam_scorer.rb

These are domains that were frequent spam user accounts on Croatian Alaveteli site (Imamo pravo znati)
n/a
Adds new domains to the spam domain list.
To fight the spam more effectively in the future.
n/a
n/a
n/a

Add spam additional spam domains

---

README.md

This makes the shield badges look consitent. Noticed this when moving to GitHub actions

Update README shield badges

---

app/controllers/attachments_controller.rb
spec/controllers/attachments_controller_spec.rb

This reverts part of #6049
Specs broken and view as HTML for "backpaged" attachments were returning 404s
We only need to check if a message is public to allow an attachment to
be viewed in browser.
Attachments are viewed in browser using the Google Docs viewer and these
need to be publicly accessible. We raise a 404 when the messages are
private.
We don't need to raise a 404 when the messages are not cacheable. Not
caching attachments is to ensure X-Robots-Tag header is present and
shouldn't have an impact on if an attachment can be viewed in browser.

Fix 'view as HTML' for non-cacheable attachments

---

docs/running/hiding_information.md
docs/running/requests.md

#5496
Tweak backpage prominence documentation
As of 8e7ac48 backpaged requests get a noindex header, reducing external
search engine visibility.
**docs/running/hiding_information.md**
**docs/running/requests.md**

[#5496] Tweak backpage prominence documentation

---

app/models/refusal_advice/store.rb
config/initializers/alaveteli.rb
config/initializers/theme_loader.rb
lib/patches/active_support/configuration_file.rb
lib/tasks/gettext.rake
spec/fixtures/refusal_advice/data/data.yml.erb
spec/models/refusal_advice/store_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/6003.
Allow refusal advice data to be translated
So that refusal advice can be presented in all locales that the site supports.
Uses existing translation mechanism for translations so that we can benefit from crowdsourcing of the translations and handling of falling back to default locale.
Uses Rails' `ActiveSupport::ConfigurationFile` [1] to parse ERB embedded in the YAML configuration files. Once we upgrade to Rails 6.1 (https://github.com/mysociety/alaveteli/issues/6011) we'll get a deprecation warning telling us to remove the patch.
[1] https://github.com/rails/rails/blob/v6.1.0/activesupport/lib/active_support/configuration_file.rb
```sh
$ cat config/refusal_advice/data.yml.erb
foi:
group:
- id: <%= _('Refusal Advice') %>
$ …
```

[#6003] Allow refusal advice data to be translated

---

app/models/legislation.rb
spec/models/legislation_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/6020
Memoise Legislation.all
Add Legislation#==
Addresses review feedback from configuring refusals [1] and fixes an equality error [2].
[1] https://github.com/mysociety/alaveteli/pull/6015#pullrequestreview-569293283
[2] https://github.com/mysociety/alaveteli/issues/6020
Would ideally like a more real life spec for the failure in https://github.com/mysociety/alaveteli/issues/6020, but not sure we have a good place for it, and it's pretty edge case so not a huge concern?

 Legislation tweaks

---

app/models/legislation.rb
spec/models/legislation_spec.rb

Part of #6002.
Allows refusals to be configured without theme overrides.
Theme overrides are gross and more difficult to maintain.
Configure in theme like:
```ruby
Legislation.refusals = {
foi: ['s 12', 's 14', 's 31'],
eir: []
}
```

[#6002] Add refusals configuration

---

app/models/concerns/taggable.rb
app/models/outgoing_message/snippet.rb
app/models/public_body.rb
db/migrate/20210114132408_create_outgoing_message_snippets.rb
db/migrate/20210114161442_create_outgoing_message_snippets_translations.rb
spec/factories/outgoing_message_snippets.rb
spec/models/outgoing_message/snippet_spec.rb

Connected to #5911 
1. Adds an `OutgoingMessage::Snippet` model
2. Extract out taggable concern from `PublicBody`

[#5911] Create snippets model

---

app/assets/stylesheets/responsive/_request_layout.scss
app/assets/stylesheets/responsive/_request_style.scss
app/controllers/classifications_controller.rb
app/models/incoming_message.rb
app/models/info_request.rb
app/models/info_request/state.rb
app/views/request/_incoming_correspondence.html.erb
app/views/request/_incoming_refusals.html.erb
spec/models/incoming_message_spec.rb
spec/models/info_request/state_spec.rb
spec/models/info_request_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/5909.
Requires https://github.com/mysociety/alaveteli/pull/6080 to fix the duplicates.
Ideally I'd like to have a way of getting a bit more explanation of these refusal reasons – certainly on the public requests – rather than just their names.
Show identified refusals on incoming messages.
Help speed up classification and provide a way of linking through to refusal advice.
Feels like these take up quite a lot of the space with the heading, so maybe make it a little more concise without losing too much (197b3bc)?
When the request needs classification link the user down to the classification form.
When the request has been classified in a state where refusals are identified, point the user to `/help/unhappy` to challenge it.
Just show that …

[#5909][JRCT] Show identified exemptions

---

app/helpers/refusal_advice_helper.rb
app/views/help/refusal_advice/_question.html.erb
spec/helpers/refusal_advice_helper_spec.rb

Extracted from #6086
Refactor refusal advice helper
Combined two very similar methods into one. This reduces duplication and
prevents CodeClimate warning and also simplifies the view.

Refactor refusal advice helper

---

app/controllers/application_controller.rb
app/controllers/projects/contributors_controller.rb
app/views/user/sign.html.erb

Extracted from #6086
Refactor controller authentication
Allow authentication direct from before action callback hook. This
creates a post redirect with no "reason" parameters. This is fine
because it's already dealt with in the mailers and with a minor change
also in the views.

Refactor controller authentication

---

app/models/refusal_advice/action.rb
spec/models/refusal_advice/action_spec.rb

https://github.com/mysociety/alaveteli/issues/6103
Allows optional `RefusalAdvice::Action#header`.
We noticed some duplication in some actions, so allow the use of just
the `title` if we want to say the same thing in both attributes.

[#6103] Optional action header

---

app/models/refusal_advice.rb
spec/models/refusal_advice_spec.rb

#6103
Allow empty refusal advice questions
Might want to have questions for FOI, but only actions for EIR.

[#6103] Allow empty refusal advice questions

---

app/assets/javascripts/wizard.js
app/assets/stylesheets/responsive/_wizard_layout.scss
app/models/refusal_advice/action.rb
app/models/refusal_advice/block.rb
app/models/refusal_advice/question.rb
app/models/refusal_advice/suggestion.rb
app/views/help/_refusal_advice.html.erb
app/views/help/refusal_advice/_action.html.erb
app/views/help/refusal_advice/_next_steps.html.erb
app/views/help/refusal_advice/_question.html.erb
app/views/help/refusal_advice/_suggestion.html.erb
spec/models/refusal_advice/action_spec.rb
spec/models/refusal_advice/block_spec.rb
spec/models/refusal_advice/question_spec.rb
spec/models/refusal_advice/suggestion_spec.rb

#6103
Reworks the refusal wizard:
- Rename methods/classes to be more logical
- Some YAML options are now optional
- In-lines the actions within the list of next steps
- Allows expanding of the actions so they are visible regardless of being suggested by the wizard

[#6103][JRCT] Refusal advice updates

---

app/assets/javascripts/wizard.js
app/controllers/application_controller.rb
app/controllers/refusal_advice_controller.rb
app/helpers/refusal_advice_helper.rb
app/models/info_request_event.rb
app/models/refusal_advice.rb
app/models/refusal_advice/action.rb
app/views/help/_refusal_advice.html.erb
app/views/help/refusal_advice/_action.html.erb
app/views/help/refusal_advice/_next_steps.html.erb
app/views/help/refusal_advice/_question.html.erb
app/views/help/refusal_advice/_suggestion.html.erb
config/routes.rb
spec/controllers/refusal_advice_controller_spec.rb
spec/helpers/refusal_advice_helper_spec.rb
spec/models/refusal_advice/action_spec.rb

Connected to #5911 
Fixes #6103
Stores the answers, and suggested actions from the refusal advice wizard. This gets stored as an `InfoRequestEvent` record.
So we can filter the snippets on the new follow up form.

[#5911][JRCT] Store wizard answers

---

lib/acts_as_xapian/acts_as_xapian.rb
lib/typeahead_search.rb
spec/lib/typeahead_search_spec.rb

Fixes #6089
Update expected exception message when wildcard searches error allowing
fallback to an non-wildcard search to continue.
Poor search performance
Locally in dev and test env all was working fine. I could only replicate in production, this is due to the size of the index. A large index can't always do a wildcard search, for example, when searching for `Cabinet Office` it will raise an exception with the message like: 
`WildcardError: Wildcard office* expands to more than 1000 terms`
This message seems to have changed at some point when upgrading Xapian in the past.

[#6089] Fix typeahead searches

---

config/environments/production.rb

4d2ab5a941 introduces ES6 syntax, which Uglifier doesn't support by
default [1].
This commit enables the experimental "Harmony mode", along with
disabling `mangle` and `compress` as per the usage recommendations [2].
This doesn't seem like a good long-term solution, since development of
Harmony mode has stopped and may be removed. This at least allows us to
deploy 4d2ab5a941 for now.
Fixes https://github.com/mysociety/alaveteli/issues/6008.
[1] https://github.com/lautis/uglifier#es6--es2015--harmony-mode
[2] https://github.com/lautis/uglifier#usage
[3] https://github.com/lautis/uglifier/issues/142#issuecomment-404872931

[#6008] Use Uglifier's experimental Harmony mode for ES6

---

lib/typeahead_search.rb
spec/lib/typeahead_search_spec.rb

~~Improve typeahead exception notifications~~
- ~~Correctly pass instance options into notifier as data argument~~
- ~~Map model option into a string value~~
- ~~Add query string to exception data~~
Removes typeahead exception notifications
We may want to drop these notifications completely now the max wildcard expansion limit has been increased in production?

Removes typeahead exception notifications

---

app/helpers/admin/translated_record_form.rb
app/helpers/admin/translated_record_helper.rb
lib/alaveteli_localization.rb
spec/helpers/admin/translated_record_form_spec.rb
spec/helpers/admin/translated_record_helper_spec.rb
spec/lib/alaveteli_localization_spec.rb

In service of #5911.
Add `TranslatedRecordForm` form builder
Make it easier to add translated record admin interfaces.
Extracted from https://github.com/mysociety/alaveteli/tree/5911-snippets-admin. I'd like to rebase https://github.com/mysociety/alaveteli/tree/5911-snippets-admin on top of this to make sure it all actually works, as a couple of tweaks were made while writing tests.

[JRCT] Translated record form

---

app/views/user/sign.html.erb

Fixes #6129
This commit fixes broken headers when signing in by checking if the web reason param is either nil or empty by using the `#blank?` method.
In 2866a97 we made a minor change to the controller authentication which introduced an issue where the wrong string was being used on the sign view.

[#6129] Fix broken headers when signing in

---

doc/CHANGES.md
lib/mail_handler/backends/mail_backend.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb

Fixes #5964
* Minor cleanup
* Handle UTF8 characters in RFC822 attachment subject lines
Couldn't parse some `.msg` attachments.
Basically copied the previous fix.
Could all do with cleanup, but this at least resolves the bug.
Downloading raw emails `1698613` and `1671979` and then parsing them locally doesn't error. In the latter case I seem to be left with a 0KB attachment, but I can't open locally so don't really know what the issue is there. In any case, at least it doesn't break the entire request.

[#5964] Handle UTF8 characters in RFC822 attachment subject lines

---

app/models/incoming_message.rb
spec/models/incoming_message_spec.rb

I had thought the issue was that we didn't have a `Legislation#==`
definition (a6dfc49dc), but that was masking the true problem.
Because `#uniq` method works by making each element a Hash key (which
are unique) [1], we were ending up with different Hash keys even though
semantically our "parents" are the same.
I'm not sure this is the most satisfactory thing to do, but it works
well enough for now. Basically we say "at the end of the day I'm going
to convert these legislation references to a string, so `uniq` on that."
Also gives doubles unique names for two reasons.
1. The change caused the "returns references which are refusals" spec to
fail since – I assume – calling `#to_s` on the double was returning
the non-unique names ("refusals")
2. It makes it easier to understand which items …

[#6020][JRCT] Fix IncomingMessage#refusals returning duplicates

---

.github/workflows/rubocop.yml

Fix Rubocop Github action
This has been failing silently for the past week. I think this is due to
the container now running on Ubuntu 20.04. There have been warnings in
the GitHub actions UI this would happen:
> Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details,
> see https://github.com/actions/virtual-environments/issues/1816

Fix Rubocop Github action

---

app/controllers/admin_announcements_controller.rb
app/controllers/admin_public_body_categories_controller.rb
app/controllers/admin_public_body_controller.rb
app/controllers/admin_public_body_headings_controller.rb
app/controllers/concerns/translatable_params.rb
spec/controllers/concerns/translatable_params_spec.rb

Extracted from #6127 
This remove duplication in our controllers by returning a empty hash if
the given params is falsey.
It reverses the argument order and switches to named arguments to so in
controllers we don't need to use curly brackets which makes indentation
consistent and results in more readable code.

Refactor TranslatableParam concern

---

app/controllers/admin/outgoing_messages/snippets_controller.rb
app/models/ability.rb
app/models/outgoing_message/snippet.rb
app/views/admin/outgoing_messages/snippets/_form.html.erb
app/views/admin/outgoing_messages/snippets/_locale_fields.html.erb
app/views/admin/outgoing_messages/snippets/edit.html.erb
app/views/admin/outgoing_messages/snippets/index.html.erb
app/views/admin/outgoing_messages/snippets/new.html.erb
app/views/admin/translated_record/_locale_tabs.html.erb
app/views/admin_general/_admin_navbar.html.erb
config/routes.rb
spec/controllers/admin/outgoing_messages/snippets_controller_spec.rb
spec/models/ability_spec.rb

Fixes #5911
Depends on #6126 
Depends on #6128
Add admin UI for snippets
So we can add resfual advice which will be offered as outgoing message snippets when composing followup replies and requests for internal reviews.
Do we want to put this behind a feature flag?

[#5911][JRCT] Add admin UI for snippets

---

app/models/refusal_advice.rb
spec/models/refusal_advice_spec.rb

Updates expected refusal advice tag
This matches what is expected in the `RefusalAdvice#snippets` and will allow snippets to have a single key+value tag, EG:
`refusal_advice:section-12`
Rather than needing two tags:
`refusal_advice refusal:section-12`

Updates expected refusal advice tag

---

app/controllers/followups_controller.rb
app/models/refusal_advice.rb
app/views/followups/_snippets.html.erb
spec/controllers/followups_controller_spec.rb
spec/factories/info_request_events.rb
spec/models/refusal_advice_spec.rb

Connected to #5911 
Retreving this commit as it was dropped from #6087 due to dependency on #6086 
Renders refusal advice previous answers filter option on new followup form 
So we can filter snippets to offer relevate advice when composing an followup reply

[#5911][JRCT] Add refusal advice previous answers filter

---

app/models/refusal_advice/suggestion.rb
spec/models/refusal_advice/suggestion_spec.rb

These aren't being used and it doesn't seem like we'll need them
anymore.

[JRCT] Remove unused RefusalAdvice::Suggestion methods

---

app/views/request/_incoming_refusals.html.erb

Internally we use`refusals` over `exemptions` so we should update this interpolation key.
I'm assuning this is fine and will merge if CI is green.

Update string translation interpolation key

---

docs/running/server.md

This simply suggests ensuring this is set-up should the hosting company support it.

Add a reference to IPv6 and AAAA records to production server page

---

.github/workflows/ci.yml

This fixes libv8 installation under GitHub action containers.
Bundler 2.2 build from source instead of using the prepackaged binary.
See: https://github.com/rubyjs/libv8/issues/310

Use bundler 2.1 on CI

---

app/controllers/alaveteli_pro/embargo_extensions_controller.rb

Minor cleanup of `AlaveteliPro::EmbargoExtensionsController`
Was reading this in relation to a Pro support query and found it a bit hard work so cleaned it up as I read.
Not intended to be a full refactoring; just making it a little better than it was before.

Embargo extensions cleanup

---

.github/workflows/ci.yml

Use bundler 2.2.15 on CI
Something has changed. Last week using this version meant the libv8 gem
needed by mini_racer wouldn't compile. We reverted back to 2.1.x which
correctly used the precompiled binary which comes with the gem. This
resulted in a new issue on Ruby 2.3 where there was a error when setting
up bundler for rake tasks. This week this now isn't failing - I'm assume
there was a change in either the CI container image, GitHub actions, or
bundler, Maybe there was something funky in Ruby 2.3 bundler cache.
Anyway it seems like its now resolved.
Fixes: #6180

Use bundler 2.2.15 on CI

---

.github/workflows/ci.yml

Still seeing issues with CI builds failing. These were working yesterday
using bundler 2.2 but now it is broken again - maybe bundler was cached
when I tested yesterday? I don't know, I'm sure I removed caching.
This change reverts back to v2.1 for all Rubies except Ruby 2.3 which
fails with a load error - instead on Ruby 2.3 use v1.17.
See: #6177 #6180 #6187

Fix broken CI builds

---

config/general.yml-example

We upcase the namespace because, at least at the time of writing the
feature, Stripe coupons need to be all uppercase
Fixes https://github.com/mysociety/alaveteli/issues/6186.

[#6186] Clarify that STRIPE_NAMESPACE must be uppercase

---

docs/pro/pricing.md

We upcase the namespace because, at least at the time of writing the
feature, Stripe coupons need to be all uppercase
Fixes https://github.com/mysociety/alaveteli/issues/6186.

[#6186] Clarify that STRIPE_NAMESPACE must be uppercase (gh-pages)

---

app/views/admin/outgoing_messages/snippets/edit.html.erb

It's generally expected that our destroy buttons have a second check.

[JRCT] Confirm snippet destruction

---

app/views/general/blog.html.erb
doc/CHANGES.md
spec/views/general/blog.html.erb_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/6066.
Allow author to be an optional blog feed attribute
While we only support Wordpress feeds (e0b5d00), we can be more
resilient to failure on missing fields. We don't _need_ an author for
the page to be useful, so this makes it optional.
Allows standard Jekyll feed to work
We don't really need `pubDate` either, but that was harder to clean up.
The whole template could do with cleaning up really, but this fixes the immediate problem and was basically quicker than responding to the issue with a comment.

[#6066] Allow author to be an optional blog feed attribute

---

app/assets/javascripts/snippets.js

Fix snippet filtering
Filter on the whole tags instead of doing a "start with" filter as this
would match `s12-a10` when filtering for `s12-a1`.

Fix snippet filtering

---

app/assets/javascripts/snippets.js

Fixes #6205 
Fix copying escaped values in snippets
Snippets might contain escaped characters like &quot; or &#39;. This
change ensures these are replaced with their plain text equivalent.

Fix copying escaped values in snippets

---

app/assets/javascripts/wizard.js
app/helpers/refusal_advice_helper.rb
app/helpers/refusal_advice_question_form.rb
app/models/info_request.rb
app/views/help/_refusal_advice.html.erb
spec/helpers/refusal_advice_helper_spec.rb
spec/models/info_request_spec.rb

Depends on #6139 - although it doesn't need to if we don't want that PR
Fixes #6026
Makes improvments to the wizard JS so it will:
1. automatically check identified refusals
2. use a new wizard question option class
The app can identified refusals references so it makes sense to automattically check these checkboxes.

[#6026][JRCT] Automatically check identified refusals

---

config/alert-tracks-debian.example
config/crontab-example
config/poll-for-incoming-debian.example
config/run-with-rbenv-path.example
config/send-notifications-debian.example
config/sysvinit-passenger.example
config/sysvinit-thin.example
lib/tasks/config_files.rake

Connected to #6052
Convert templates from Ugly to ERB
Our Ugly implementation isn't fully complete compared to the mySociety
deployment scripts where Ugly templates are parsed using Perl.
Switching to ERB allows us to use conditionals. This will allow us to
selectively use rbenv for daemons and crontab.

Convert templates from Ugly to ERB

---

app/assets/stylesheets/responsive/_request_style.scss
app/views/request/_request_subtitle.html.erb
app/views/request/request_subtitle/allow_new_responses_from/_anybody.html.erb
app/views/request/request_subtitle/allow_new_responses_from/_authority_only.html.erb
app/views/request/request_subtitle/allow_new_responses_from/_nobody.html.erb
spec/views/request/show.html.erb_spec.rb

Fixes #5976
Warn users when a request is authority_only
We tell users when a request is completely closed to responses
(db5805b), but we don't show when it's `authority_only`. This sometimes
causes problems if e.g. an authority changes their `request_email` or
responses come from a shared contact centre.
See commit message notes.

[#5976] Warn users when a request is authority_only

---

app/controllers/track_controller.rb

Allows different feed pages by accessible by adding URL `page=n` GET
parameter.
Fixes #986

Remove hard coded feed page

---

app/views/request/_form.html.erb
spec/integration/alaveteli_dsl.rb
spec/integration/create_request_spec.rb

A few users seem to get confused that the preview stage is mandatory
before sending.
> I have filled in my reply in the box provided but I cannot find how to
> actually send it. Is there a box I should click or button I should
> press?
This is a quick fix to make it clear that previewing _is_ the next step
that must be taken.
Fixes https://github.com/mysociety/alaveteli/issues/6242.

[#6242] Clarify that preview is not the final step

---

Vagrantfile
bin/vagrant-buster
config/general.yml-example
config/packages
config/packages.generic
config/packages.ubuntu-bionic
doc/CHANGES.md
script/install-as-user

Fixes https://github.com/mysociety/alaveteli/issues/5226
See https://github.com/mysociety/sysadmin/issues/867
Requires https://github.com/mysociety/commonlib/pull/70
1. Switches the wkhtmltox package
2. Adds vagrant buster box
To support the Debian version
These are commits from commonlib package repo changes

[#5226] Add buster support

---

vendor/assets/stylesheets/normalize.scss

Apply https://github.com/necolas/normalize.css/commit/55ed05a79c0fd7a9a2c330c6925b982a7d5b307c
`display: block` results in [inconsistent arrow behaviour](https://gist.github.com/garethrees/923897c7505bf8b7269dfc2b40dccf9a).
Looks like we should update normalize, but for now this fixed my immediate problem and is inline with latest normalize.
Prior to this change no arrows were shown
Only other place we use `<details>` is [rendering snippets](https://github.com/mysociety/alaveteli/blob/4dd8339db0bf5ec30d1d6a7d178a8ead34140410/app/views/outgoing_message/snippets/_snippet.html.erb#L4-L13) and the behaviour remains the same.

Fix summary style

---

app/models/refusal_advice.rb
app/models/refusal_advice/store.rb
spec/models/refusal_advice/store_spec.rb
spec/models/refusal_advice_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/6246.
`RefusalAdvice#questions` and `RefusalAdvice#actions` expects a `Legislation` to be configured. 
It allows empty values, but currently we have not even configured EIR.
This leads to failures when we try to render the refusal advice for an EIR request.
```ruby
InfoRequest.find_by(url_title: 'example_title_40').legislation.to_s
```
BEFORE
AFTER

[#6246] Handle unconfigured legislation questions

---

app/assets/javascripts/wizard.js

Fixes #6256
Fix refusal wizard being hidden
When going to /help/unhappy directly and not via a info request the
refusal advice form should be visible. This fixes a error which cause
the JS to exit early before the form was rendered.

Fix refusal wizard being hidden

---

app/mailers/request_mailer.rb
app/views/request_mailer/requires_admin.text.erb
spec/mailers/request_mailer_spec.rb

I frequently wonder whether to remove this when I reply to user support
requests. Most of the time I don't bother, since one needs authorisation
to view the page, but it still doesn't _look_ good to reveal to
outsiders.
We also tend to redact these URLs from SAR responses, which creates
significant extra work.
This commit removes the URL. It adds an extra click for admins who need
to act on the request, but personally speaking I almost always use the
public URL first to review the content before visiting the admin page to
act.

Remove Admin URL from requires admin notifications

---

app/views/projects/dataset/keys/_numeric_key.html.erb

This is more appropriate for the expected value and makes the intent
clearer. We also get HTML validations for free.
At present neither the HTML validations nor the `Dataset::Key::FORMATS`
allow decimal values. We could update the format `Regexp` and add a
`step` attribute to the form field if we wanted to accept decimal
values.
Part of https://github.com/mysociety/transparency-fnf-whatdotheyknow-projects/issues/30

Use number_field for numeric Dataset::Key

---

app/views/projects/projects/_project_nav.html.erb

The arrow emphasises that you're going "back" to the homepage. Spotted
after watching a new user struggle to find their way back to the
homepage.
The initial version I tried used the `&larr;` outside of the link, but
it felt a bit disconnected so I thought it was worth the minor extra
complexity of interpolation.

Make navigation to project homepage clearer

---

app/models/public_body_change_request.rb

All Ruby objects inherit from Object, which includes the Kernel module,
which in turn, has an open method. Redefining `.open` was creating lots
of WARN level messages in the logs:
W, [2019-10-10T14:17:40.179390 #30917]  WARN -- : Creating scope
:open. Overwriting existing method PublicBodyChangeRequest.open
Since we're not using `Kernel.open`, we can explicitly undefine it prior
to defining our own `.open` in the form of a `scope`.
Fixes https://github.com/mysociety/alaveteli/issues/5405.

[#5404] Undef Kernel.open before creating open scope

---

_layouts/page.html
docs/index.md
docs/running/resources_for_owners.md

https://github.com/mysociety/alaveteli-project/issues/128#issuecomment-866860198
Adds a new content page to Alaveteli.org detailing various resources
To give new information for Alaveleti site owners
My local copy of this is missing images from the header and footer but I think that's just me

Add new resources for owners page, include in nav menus

---

app/models/censor_rule.rb
config/initializers/alaveteli.rb
doc/CHANGES.md
lib/core_ext/warning.rb
spec/lib/core_ext/warning_spec.rb
spec/models/censor_rule_spec.rb

We allow the regexp to be created from a user inputted string.
In some cases, we see rules that don’t have correct escaping, e.g:
Regexp.new('foo]')
This warning behaviour is not configurable, so instead I’ve added
Warning.with_raised_warnings. This simply makes any call to Warning.warn
raise the given message instead of outputting it to stderr.
We then use the raised exception to massage the message into a
RegexpError, which we already have handling that presents this as an
ActiveModel error to the user.
Fixes https://github.com/mysociety/alaveteli/issues/5967
```ruby
r.text
r.replacement
r.apply_to_text('foo] bar')
```

[#5967] Prevent CensorRules being saved when Regexp is bad

---

app/views/user/show.html.erb
app/views/user/show/_show_same_name_users.html.erb
config/routes.rb
doc/CHANGES.md

Fixes https://github.com/mysociety/alaveteli/issues/1732
Fixes https://github.com/mysociety/alaveteli/issues/2406
* Truncate list of alternative users shown on profiles
* Don't render same_name_users on your own profile
Feature has become unusable now that the site has scaled.
Just fixed this quickly while looking at something else.

[#1732] Truncate same name user list

---

app/controllers/user_controller.rb
spec/controllers/user_controller_spec.rb

Fixes #3873
Handle `UserController#signup` `ActionController::ParameterMissing` error
Just frustrating to get exception notifications about this all the time
First commit is just style tweaks to make this change easier.
You can delete the form fields of the signup form using web inspector, then submit the form.

[#3873] Handle UserController#signup ParameterMissing

---

app/controllers/users/sessions_controller.rb
spec/controllers/users/sessions_controller_spec.rb

Fixes #4857
Handle `Users::SessionsController#signin` `ActionController::ParameterMissing` exception
Reduce exception notifications from bot signin attempts
The params in #4857 do look genuine, so there _might_ be a way that this happens through the normal flow. I still think this is worth merging since we can investigate any other cases if we get notified via user support queries.
You can delete the form fields of the signin form using web inspector, then submit the form.

[#4857] Handle Users::SessionsController#signin ParameterMissing

---

app/views/followups/_form_title.html.erb

Fixes #6138
Adds a back link to the request internal review page if the user has come from the refusal advice wizard
To allow the user to go back and amend their answers (and to show them that they can)
Used a `<br />` tag - possibly bad but seemed like the simplest way to add space with little complexity

 Add a back link to request internal review

---

app/assets/stylesheets/responsive/_wizard_layout.scss

#5938 
Hides the wizard and wizard content from clients without javascript
The wizard is (currently) JS dependant so won't work with JS disabled or where the JS files haven't loaded

Hide wizard content from non js users

---

app/helpers/pagination_helper.rb
doc/CHANGES.md
spec/fixtures/locale/es/app.po
spec/helpers/pagination_helper_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/1163
Add a helper to translate (via gettext) the strings provided by will_paginate.
will_paginate calls the `will_paginate_translate` method internally when rendering the links:
https://github.com/mislav/will_paginate/blob/8113fddf4b506867e9af3aa59fe2df314b79860c/lib/will_paginate/view_helpers.rb#L77-L78

Add pagination translations

---

app/models/alaveteli_pro/draft_info_request_batch.rb
app/models/concerns/info_request/draft_title_validation.rb
app/models/concerns/info_request/title_validation.rb
app/models/draft_info_request.rb
app/models/info_request.rb
app/models/info_request_batch.rb
spec/models/alaveteli_pro/draft_info_request_batch_spec.rb
spec/models/concerns/info_request/draft_title_validation.rb
spec/models/concerns/info_request/title_validation.rb
spec/models/draft_info_request_spec.rb
spec/models/info_request_batch_spec.rb
spec/models/info_request_spec.rb

Fixes #6217.
* Extract InfoRequest::TitleValidation concern and use in `InfoRequest` and `InfoRequestBatch`
* Some minor cleanup
* Add `title` validation to `DraftInfoRequest` and `AlaveteliPro::DraftInfoRequestBatch`
Extremely long titles cause unhandled database errors.
* Added a somewhat new pattern of defining concern shared examples and explicitly including them in the class under test. Open to suggestion here.
* Not sure about including a concern in a concern (f5076bf).

[#6217] Draft request validation

---

app/models/legislation.rb
spec/models/legislation_spec.rb

Fixes #6318
Remove class variable to ensure Legislation objects are initialised in
the current locale.

Fix legislation localised strings

---

app/helpers/pagination_helper.rb
spec/helpers/pagination_helper_spec.rb

#1163 
Add pagination page_gap translation.
Needed so this is rendered correctly on sites using locales without i18n
translations (eg CZ). Without this "Page gap" is rendered.
Opted not to pass this through to gettext. All will_paginate i18n YAML I
can see on Github use `...` as their page gap

Add pagination page_gap translation

---

app/views/request/_incoming_refusals.html.erb

Prepends 'site name has identified' to refusal identification message
Fixes https://github.com/mysociety/alaveteli/issues/6282
Adds the site name to make it clear it's come from the site rather than the authority
In response to feedback this wasn't clear
Decided against adding an icon or illustration as this felt just fine as is
issues/6282-refine-refusal-identification-message

Clarify refusal message origin

---

public/robots.txt

We're receiving a "Crawl politeness" notification on WDTK because Bing
is interpreting this commented line as an uncommented directive.
The unsubscribe link on the notification emails just takes you to the
homepage and does nothing.
Just going to remove since we're not using the directive.
Fixes https://github.com/mysociety/sysadmin/issues/1454
[1] https://www.bing.com/webmasters/help/crawl-error-alerts-e29a3f3e

Remove commented Bing Crawl-delay

---

docs/developers/index.md
docs/getting_started.md
docs/installing/ami.md
docs/installing/index.md
docs/installing/manual_install.md

Be explicit about dropping support for the Amazon AMI.
Make it clear to reusers that this isn't something we support or maintain.
Left the references to communicate the change until we decide to completely remove the references.

Drop support for Amazon AMI

---

app/assets/javascripts/wizard.js

Fixes issue introduced in a90a1b8
Update JS so the hidden form inputs which pass through which advice has been shown to
the user gets updated. 
This has meant suggested actions have not been stored and snippets not shown.

Fix updating refusal advice suggestion hidden inputs

---

app/views/outgoing_message/snippets/_snippet.html.erb

Fixes #6094
Ensure snippets end with a new line
In some browsers, when pasting using right click, it will highlight the
whole line. This causes the line to be removed when pasting snippets if
they don't end with a new line.

[#6094] Ensure snippets end with a new line

---

.github/workflows/ci.yml
lib/quiet_opener.rb
spec/lib/quiet_open_spec.rb

Depends on #6033 
Fixes #5440 
Linking to https://github.com/mysociety/alaveteli/pull/6118, since there's a conditional in this PR to do this for Ruby 2.7. Older Xapian gem doesn't install on 2.7
Linking to https://github.com/mysociety/sysadmin/issues/1409, since that's an enabler for us running this PR on WDTK
1. ~~Moves "Rails next" gemfile into subdirectory~~
2. ~~Add a Xapian gemfile for a more recent version with support for Ruby 2.7~~
3. ~~Updates acts as xapian for to support the next Xapain bindings~~
4. Includes Ruby 2.7 in CI

[#5440] Add Ruby 2.7 support

---

app/controllers/application_controller.rb
app/controllers/general_controller.rb
app/controllers/request_controller.rb
app/controllers/services_controller.rb
lib/tasks/geoip.rake

Missed other occurrences of Kernel#open and requires for open-uri.
See: https://github.com/mysociety/alaveteli/commit/d796a63

Fix Kernel deprecated for Ruby 2.7

---

app/assets/javascripts/wizard.js
app/assets/stylesheets/responsive/_wizard_style.scss

https://github.com/mysociety/whatdotheyknow-theme/issues/832
Adds functionality whereby if you're visiting the /help/unhappy page with a known url hash eg `#internal_review` it opens the associated `details` element and highlights it with a css fading style
It wasn't clear that the page has the relevant information when it's hidden inside a closed `details` element
The JavaScript is hard coded to the known ID tags of the sections - this means if we ever add new ones it will need updating

Unfold the details tag if they've come to the page with a hash link

---

script/install-as-user

After `vagrant up`  the install script creates an
`alaveteli` -> `/home/vagrant/alaveteli` symlink in the repository which
isn't useful either inside the guest or on the host. It also appears as
a new file in git, which one has to remember to remove.
This commit fixes the issue by only creating the symlink if the
`REPOSITORY` and `LINK_DESTINATION` differ.
Fixes https://github.com/mysociety/alaveteli/issues/1384

[#1384] Only symlink repository different from destination

---

script/site-specific-install.sh
spec/support/xapian_index.rb

Supersedes https://github.com/mysociety/alaveteli/pull/6393.
As described in 47bfdea, sometimes running specs in Vagrant results in
unrecoverable corruption of the Xapian DB.
We're not sure exactly what the problem is, but our best guess is
something to do with slow file sync of the VirtualBox share after the
index is replaced.
Moving the Xapian database outside of the VirtualBox share _seems_ to
prevent the problem, so when provisioning a Vagrant development
environment write a custom `config/xapian.yml` to write the test
databases to `/tmp/xapiandbs`. It doesn't matter that these are
inaccessible from the host machine or get trashed on restart. We only
create this file if it doesn't already exist
This change also allows us to remove the hack introduced in 47bfdea.
Related to #1292

[#1292] Create a config/xapian.yml for Vagrant dev install

---

config/test.yml
lib/attachment_to_html/adapter.rb
lib/attachment_to_html/adapters/pdf.rb
lib/attachment_to_html/adapters/rtf.rb
spec/lib/attachment_to_html/adapters/pdf_spec.rb
spec/lib/attachment_to_html/adapters/rtf_spec.rb

This is needed so I can run tests locally without failures.
Instead of using system packages or homebrew I provision utilities using
nix-shell. Each utility is installed in its own directory and these
paths might change over time:
```
/nix/store/9vv5556b9w8kjl71m1iyzg25jfpwgllx-pdftk-3.2.1/bin/pdftk
/nix/store/15xkf5bdyw2cw39ymqz121dh9xskk697-poppler-utils-21.06.1/bin/pdftohtml
...
```
This means they can't be found in the default utility search paths.
Using nix-shell's shellHook option I can symlink utilities into the
local bin directory:
```
ln -sf ${pdftk}/bin/pdftk bin/pdftk
ln -sf ${poppler_utils}/bin/pdftohtml bin/pdftohtml
...
```
And these symlinks are ignored by adding them to `.git/info/exclude`.
This change makes it possible to provision and find utilities into the
local bin …

Add local bin directory to test ENV utility path

---

lib/mail_handler/reply_handler.rb
script/handle-mail-replies.rb
spec/lib/mail_handler/reply_handler_spec.rb

Fixes #5649
Fix mail forwarding on to both addresses
Mail sent `To: team@` and `Cc: pro_team@` was not getting sent to `team@`, because we were overwriting it.
This works by setting multiple recipients when we shell out to `sendmail`.
Prior to this PR, and for most messages, we do `/usr/sbin/sendmail -i team_delivery@example.com`.
As of this PR, when we have a case of `To: team@` and `Cc: pro_team@`, we'll now do `/usr/sbin/sendmail -i "team_delivery@example.com,pro_team_delivery@example.com"`
I literally started 5 branches to try to tidy this up in various ways.
I tried a basic attempt at making `MailHandler::ReplyHandler` a class – there's no reason it should be a bag of functions – but that got complicated because of the interplay between the unparsed email and the parsed …

[#5649] Fix internal email forwarding

---

app/controllers/admin_general_controller.rb
app/controllers/application_controller.rb
app/controllers/general_controller.rb
app/models/statistics.rb
app/models/statistics/general.rb
spec/controllers/general_controller_spec.rb
spec/models/statistics/general_spec.rb

Reduce complexity of controller (and its tests) by extracting logic to a
more appropriate model.
Allows us to remove a non-controller method from ApplicationController.
Also allows easier access from the command line:
bin/rails runner "pp Statistics::General.new.to_h"
Just general cleanup that looked quick and easy while working on https://github.com/mysociety/alaveteli-project/issues/135.
It's a heavily coupled class, but I'm not sure there's a great way around that.
Still appears to work 😅 
At some point we should migrate the current `Statistics` class to e.g. `Statistics::PublicBodies` and `Statistics::Users` or something like that.

Extract Statistics::General from GeneralController

---

app/views/admin_user/_form.html.erb

Fix misleading admin help
Users are automatically reindexed after editing. There's no need to
"rebuild the search index" now.
BEFORE
AFTER

Fix misleading admin help

---

app/helpers/application_helper.rb
app/views/admin/outgoing_messages/snippets/index.html.erb
app/views/admin_comment/edit.html.erb
app/views/admin_comment/index.html.erb
app/views/admin_general/_change_request_summary.html.erb
app/views/admin_incoming_message/bulk_destroy.html.erb
app/views/admin_public_body/_one_list.html.erb
app/views/admin_request/_some_annotations.html.erb
app/views/admin_request/_some_requests.html.erb
app/views/admin_request/show.html.erb
app/views/admin_track/_some_tracks.html.erb
app/views/admin_user/_user_table.html.erb

none
1. Makes the timestamps in the admin UI consistent.
2. Refactor to use the same helper
3. Adds title attribute to the `time_ago_in_words` text to show exact timestamp
4. Simplify views and conditionals
I expected to be able to hover "1 month ago" text in the admin to see the exact timestamp and was surprised when this wasn't a thing.
Timestamps rendered as `YYYY-MM-DD HH:MM:SS TZ` in all places expect:
1. the User#index table where we show the last updated at date
2. the Comment#index table where we show the created at date

Refactor admin dates

---

app/models/info_request.rb
spec/models/info_request_spec.rb

Replacement for #6355
Fixes #6322
Reworks how the `InfoRequest#law_used` attribute is set. 
Requests to authorities which are EIR only had `law_used` set to `foi` this was coming from the database column default value.

[#6322] Fix info request law used

---

spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb
spec/controllers/general_controller_spec.rb
spec/controllers/public_body_controller_spec.rb
spec/controllers/request_controller_spec.rb
spec/controllers/track_controller_spec.rb
spec/controllers/user_controller_spec.rb
spec/integration/alaveteli_pro/admin_spec.rb
spec/integration/alaveteli_pro/batch_request_spec.rb
spec/integration/create_request_spec.rb
spec/integration/search_request_spec.rb
spec/integration/signin_spec.rb
spec/integration/track_alerts_spec.rb
spec/integration/xapian_search_highlighting_spec.rb
spec/lib/acts_as_xapian_spec.rb
spec/lib/typeahead_search_spec.rb
spec/mailers/track_mailer_spec.rb
spec/models/info_request_spec.rb
spec/models/xapian_spec.rb
spec/support/xapian_index.rb

Fixes #5960
Moves the initial build of the Xapian index to be after the fixture data has been created. This means it’s not done after any RSpec before callbacks or `let!` blocks where other records might be created and indexed and then shared with other specs.
Also improves the interface for the specs so we only ever need to call `update_xapian_index` instead of that and `get_fixtures_xapian_index` to save confusion and reindex multiple times for the same specs.
Fix transient spec failures.
I had tried to improve the `load_raw_emails_data` calls as part of this refactor as this seems closely tied to the Xapian indexing but there are still issues with this. I think improvements here could speed up tests as `RawEmail#data=` writes to the disk which is done a lots during our spec suite.
In …

[#5960] Refactor and improve Xapian spec setup

---

lib/acts_as_xapian/acts_as_xapian.rb

Fixes #6420
Update Xapian configuration loading
Configuration file might exist but not have any configuration for the
current environment so without this change config eval to nil.

Update Xapian configuration loading

---

app/models/statistics/general.rb
spec/controllers/general_controller_spec.rb
spec/models/statistics/general_spec.rb

Fixes #6414
Allow args given to `Statistics::General#to_json`
Somehow missed this in https://github.com/mysociety/alaveteli/pull/6337 – maybe I didn't reload the Rails server?!

[#6414] Fix /version.json

---

script/install-as-user
script/site-specific-install.sh

Migrate test database for development installs.
Always annoying having to remember to migrate the test db after a fresh VM provision.

Migrate test database for development installs

---

.ruby-style.yml
app/controllers/request_controller.rb
app/models/citation.rb
doc/CHANGES.md
spec/controllers/request_controller_spec.rb
spec/models/citation_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/6409
Render newest citations instead of oldest
Rendering the oldest 3 is confusing when adding citations, since the
rendered list doesn't change as you add more after the third.

[#6409] Render newest citations instead of oldest

---

_includes/footer.html
docs/installing/next_steps.md
docs/running/upgrading.md

We moved away from IRC in ~ 2017. This doesn't cover any of the
basically abandoned `/es` translations.
Noted in a [mailing list thread](https://groups.google.com/g/alaveteli-dev/c/qjssIF3NXz4/m/x8EZv8-qCAAJ) that it was inactive – obviously we shouldn't be linking to this.

Remove IRC mentions

---

app/views/admin_general/index.html.erb

We prefer written communication at WhatDoTheyKnow so this isn't
appropriate. How to get an authority address is a question of site
policy, so that should be documented elsewhere, since it'll vary from
country to country.
Resolves the comment https://github.com/mysociety/alaveteli/issues/6424#issuecomment-892484833

[#6424] Remove "try phoning" prompt for missing emails

---

app/models/survey.rb

Issue loading these methods in production even though they work fine in
development and test environments. It's possible to do the same using
Ruby core methods instead.

Replace Addressable::URI

---

app/controllers/admin_general_controller.rb
app/views/admin_general/index.html.erb
spec/controllers/admin_general_controller_spec.rb

We show the total count of bodies without email, but don't for old
unclassified requests. This commit fixes that.
Noted in https://github.com/mysociety/alaveteli/issues/6423.
Now shows a count (25) greater than the limit of the list (20):

[#6423] Show true count of old unclassified requests

---

spec/support/shared_examples_for_network_errors_during_send.rb

On some systems (namely macOS) when `Errno::ETIMEDOUT` is raised the
exception message is 'Operation timed out' and causes this spec to fail.

Update network error spec expectation

---

app/assets/javascripts/wizard.js

Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/832
Improved the functionality introduced by #6356 by adding the ability to highlight the `<details>` elements being opened after page load
Functionality improvement requested after #6356 went live

Fire flash style when the URL hashes are clicked after page load

---

lib/normalize_string.rb
spec/lib/basic_encoding_spec.rb

Fixes #5609
Changes made here will rescue the exception and re-raise our `EncodingNormalizationError` error which will return binary data when `#convert_string_to_utf8_or_binary` is called or scrubbed data when `#convert_string_to_utf8` is called. It will handle any other encoding which isn't fully supported by Ruby.
When attempting to force Windows 1258 data into UTF-8 errors are raised, such as:
>  Encoding::ConverterNotFoundError: code converter not found (Windows-1258 to UTF-8)
This is due to [Ruby not supporting conversions yet](https://bugs.ruby-lang.org/issues/7742).

[#5609] Handle Encoding::ConverterNotFoundError exceptions

---

app/controllers/alaveteli_pro/info_requests_controller.rb
spec/controllers/alaveteli_pro/info_requests_controller_spec.rb

Fixes #4497
This change redirects the user to the new info request action if the draft isn't available.
The info request preview is getting requested without a `draft_id` parameter resulting in `undefined method 'title' for nil:NilClass` errors.

[#4497] Fix error on Pro info request previews

---

lib/mail_handler/backends/mail_backend.rb
spec/fixtures/files/empty-8bit.email
spec/lib/mail_handler/backends/mail_backend_spec.rb

Fixes #6407
This change ensures we always return unfrozen strings from `MailHandler.get_part_body`.
In one edge case, where we receive an empty email parts with `8bit` content transfer encoding and `text/*` content type we would see errors:
>  can't modify frozen String: ""

[#6407] Fix frozen email body

---

app/views/admin_public_body/import_csv.html.erb

`name` and `request_email` _columns_ must be present, but
`request_email` _values_ may be blank.
Fixes https://github.com/mysociety/alaveteli/issues/6444.

[#6444] Clarify CSV import documentation

---

app/models/censor_rule.rb
app/models/foi_attachment.rb
app/models/incoming_message.rb
app/models/raw_email.rb
lib/acts_as_xapian/acts_as_xapian.rb
lib/normalize_string.rb
spec/lib/acts_as_xapian_spec.rb
spec/lib/basic_encoding_spec.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb
spec/lib/mail_handler/mail_handler_spec.rb
spec/models/censor_rule_spec.rb
spec/models/foi_attachment_spec.rb
spec/models/incoming_message_spec.rb
spec/models/info_request_event_spec.rb
spec/models/info_request_spec.rb
spec/models/post_redirect_spec.rb
spec/models/raw_email_spec.rb

This method is included in all Ruby versions we currently support.

Remove conditionals checking for String#encode

---

app/views/classifications/message.html.erb
app/views/reports/new.html.erb

Adds HTML validation to require users provide more reasons for reporting
content.
Almost all reporting reasons need further detail, so this is a better
balance for the majority of cases.
Could go further and add validations at the model layer, but this should
prevent the majority of incomplete reports.
Fixes https://github.com/mysociety/alaveteli/issues/4612.

[#4612] Require report reasons

---

lib/normalize_string.rb
spec/lib/basic_encoding_spec.rb

Fixes #6046
Rescue from `Encoding::InvalidByteSequenceError` same as how we've
recently handled `Encoding::ConverterNotFoundError` [1].
This means for some attachments with the incorrect charset we might
scrub invalid characters. This seems to happen for right single
quotation marks, EG so "don’t" will be displayed as "dont".
This is the same behaviour as other email clients, such as Apple Mail.
[1] https://github.com/mysociety/alaveteli/pull/6451

[#6046] Fix invalid byte sequence error

---

app/controllers/request_controller.rb
app/models/info_request.rb
app/models/info_request_batch.rb
spec/models/info_request_spec.rb

Fixes #4160
Trim the leading and trailing whitespace from the request title when
checking for existing requests.
When a user is directed to signin before a request is made it results in
a `PostRedirect` being created and an email is sent to the requester to
confirm their email address. This mail includes a link to `/new` which
will finish creating their request.
The `PostRedirect` includes the all form data as it was entered into the
new `InfoRequest` form (including any extra whitespace). The comparison
to existing records can then break. We already handle whitespace in the
body to account for line endings difference but the title was a direct
comparison which would fail. Existing records have whitespace stripped
when saving into the database.
Includes a method rename which cause …

[#4160] Uncaught duplicate requests

---

app/views/layouts/default.html.erb

Fixes #6435
Remove popup banner and JS from show request PDFs
We need to remove the popup due to WDTK theme using opacity CSS selector
for these elements this is causing the wkhtmltopdf-static command to seg
fault:
> QPixmap: Cannot create a QPixmap when no GUI is being used
> ...
> Segmentation fault
Also need to remove JS from the page as this causes SSL socket errors:
> QSslSocket: cannot resolve ...
> QSslSocket: cannot call unresolved function ...

[#6435] Remove popup banner and JS from request correspondence PDFs

---

config/application.rb
lib/deeply_nested_params.rb
spec/lib/deeply_nested_params_spec.rb

Fixes #6361
This Rack middleware will catch the `RangeError` exception, returning a
400 Bad Request response instead.
Rack will raise an `RangeError` when request have parameters which are
nested too deeply. Rack defaults to allow 100 levels deep but this still
isn't enough for some malformed requests resulting in email exception
notifications.

[#6361] Add middleware to handle RangeError raised by Rack

---

app/controllers/admin_raw_email_controller.rb
app/controllers/alaveteli_pro/batch_downloads_controller.rb
app/controllers/alaveteli_pro/public_bodies_controller.rb
app/controllers/alaveteli_pro/stripe_webhooks_controller.rb
app/controllers/alaveteli_pro/subscriptions_controller.rb
app/controllers/api_controller.rb
app/controllers/application_controller.rb
app/controllers/attachments_controller.rb
app/controllers/general_controller.rb
app/controllers/health_checks_controller.rb
app/controllers/outgoing_messages/delivery_statuses_controller.rb
app/controllers/projects/downloads_controller.rb
app/controllers/public_body_controller.rb
app/controllers/request_controller.rb
app/controllers/services_controller.rb
app/controllers/statistics_controller.rb
app/controllers/track_controller.rb
app/controllers/user_controller.rb
spec/controllers/alaveteli_pro/batch_downloads_controller_spec.rb
spec/controllers/followups_controller_spec.rb
spec/controllers/general_controller_spec.rb
spec/controllers/projects/downloads_controller_spec.rb
spec/controllers/request_controller_spec.rb
spec/integration/errors_spec.rb

Fixes #6408
Fixes #4228
Adds a before action to `ApplicationController` to set the default response to HTML for all actions.
We obviously have actions which response to JSON, CSV, ZIP, PNG, etc so for these actions, in their own controller, we call `skip_before_action` to bypass the default.
This prevents `ActionView::MissingTemplate` exceptions when JSON is requested for a route which we have explicitly said responds to it.
With this change `ActionController::UnknownFormat` errors will be raised which we already catch within `ApplicationController` and return a 406 response to the user.
This means we are now responding with 406 bad request, where we used to respond with either a 403 forbidden or a 404 not found.
It means we can't handle invalid format, for `GeneralController#search` we …

[#6408] Update controllers default response to be HTML

---

app/controllers/user_controller.rb
app/controllers/users/confirmations_controller.rb
app/models/post_redirect.rb
app/views/user/bad_token.html.erb
doc/CHANGES.md
spec/controllers/users/confirmations_controller_spec.rb
spec/factories/post_redirects.rb
spec/models/post_redirect_spec.rb

~~(Fixes) https://github.com/mysociety/alaveteli_security/issues/23~~ – this PR is about token re-use, not session expiry
~~(Fixes) https://github.com/mysociety/alaveteli_security/issues/25~~ – collection issue
Fixes https://github.com/mysociety/alaveteli_security/issues/26 – appears reproducible because the generated token is the same in each attempt, but this PR correctly prevents the previous token being used after a successful reset.
Fixes https://github.com/mysociety/alaveteli_security/issues/27 – prevents re-use of token.
Fixes https://github.com/mysociety/alaveteli_security/issues/24
Use ActiveSupport::MessageVerifier and generate token with the current
value so if the password or email is changed the token then won't work
anymore.

Expire used and old change password/email tokens

---

app/views/admin_public_body/_locale_fields.html.erb
doc/CHANGES.md

Enlarge PublicBody#notes form field
The current sizing makes the textarea extend "under" the sidebar div,
hiding the resize handle. This makes it difficult to work with notes
that make more extensive use of HTML. Also adds more height by default
to make up for the reduced width.
**BEFORE**
**AFTER**

Larger body notes form field

---

app/models/user.rb
app/models/user/one_time_password.rb

Extract OTP functionality to a concern to reduce complexity of `User`.
Migrating the specs to shared examples (e.g. 14f1f958) would be quite
time-consuming. Given this is not a shared concern there's less benefit
in doing so, and our current 2FA implementation isn't particularly great
nor well-used.
The main benefit here is to extract out an infrequently changed piece of
`User`.
Also adds `#otp_enabled_and_required?` for minor readability improvement
of the `:verify_otp_code` validation conditional.

Add User::OneTimePassword

---

app/models/ability.rb
app/models/info_request.rb
app/models/user.rb
spec/models/user_spec.rb

Deprecates class-based User role viewing permissions in favour of instance methods.
Removes unnecessary complexity now that we have the safe navigation operator.

Deprecate class-based User role viewing permissions

---

app/models/public_body.rb
spec/models/public_body_spec.rb

Extract the task of reindexing all events from `reindex_requested_from`
to make the behaviour a little clearer and allow us to call
`reindex_all_events` manually from the console
(`@public_body.send(:reindex_all_events`) if we need to reindex a
specific body.
Also adds missing specs for the behaviour.
Extracted from a case [1] where we needed to manually reindex a body
because the UI timed out due to the large number of requests.
[1] https://github.com/mysociety/whatdotheyknow-theme/issues/879#issuecomment-907130512

Refactor PublicBody#reindex_requested_from

---

config/general.yml-example
config/test.yml

Fixes: #6630
Update theme repo URLs
Switch from the `git` protocol to `https`. This is required as GitHub
are strengthening their security around the use of the git protocol.
See: https://github.blog/2021-09-01-improving-git-protocol-security-github/

[#6630] Fix CI builds

---

app/views/public_body/_alphabet.html.erb
app/views/public_body/list.html.erb

`list_public_bodies_by_tag` generates a more human-friendly URL than
passing the `tag` parameter:
app.list_public_bodies_path(tag: 'foo')
app.list_public_bodies_by_tag_path('foo')
Both routes are handled by `PublicBodyController#list`, so there's no
real behaviour change here.
In the case of the alphabet listing, using a `tag` param is technically
incorrect, since it's not searching by tag (so an advanced Xapian search
wouldn't find these). At least using `list_public_bodies_by_tag_path`
masks this to the end user.
The only marginally different thing to be aware of is that `…by_tag`
URL-encodes a multi-tag `String`, whereas when using a param the tags
get separated by a `+`. This is expected and correct behaviour. Though
the `+` is slightly more readable in this instance, overall the …

Use human-friendly URLs to body listings

---

bin/config
config/packages
config/packages.generic
config/packages.ubuntu-bionic
config/packages.ubuntu-focal
config/packages_development
docker/Dockerfile
script/load-mail-server-logs
script/mailin
script/rails-deploy-before-down

Instead of using yaml2sh from commonlib this commits adds a new Ruby
script at bin/config which can retrieve individual configuration
variables from config/general.yml.
To get a configuration variable run:
bin/config SITE_NAME
This bin command doesn't initialise the Rails stack so is fast
It also *doesn't* use lib/configuration.rb Ruby module, although it
could if some configuration variables had defaults assigned. These are:
1. BUNDLE_PATH
2. SHARED_DIRECTORIES
3. SHARED_FILES
4. SHARED_FILES_PATH
5. STAGING_SITE
As I understand it these haven't be given a default because they are
only used from the installation shell scripts. Which seems reasonable to
me.

Remove dependency on Python

---

app/controllers/statistics_controller.rb
spec/controllers/statistics_controller_spec.rb

Fixes #6566
Fix JSON statistics
Broken since #6523 where a instance variable was renamed in the HTML
response but not the JSON response. Also added spec to check the format
of the JSON response.

[#6566] Fix JSON statistics

---

script/load-mail-server-logs
spec/script/load_mail_server_logs_spec.rb

Fixes #6639
Fix the load-mail-server-logs script
The script cd into the `script` directory which means the new
`bin/config` command isn't found when retriving the MTA_LOG_PATH config.
This change replicates `script/mailin so it cd into the root directory
and the config can now be returned.
Also adds specs for this script to prevent other errors in the future.

[#6639] Fix the load-mail-server-logs script

---

app/controllers/request_controller.rb
spec/controllers/request_controller_spec.rb

Fixes #6641
Fix authentication for uploading response
Broken due to bad refactoring in #6587
Need to return false to prevent the action from being rendered.

[#6641] Fix authentication for uploading response

---

app/views/admin_comment/edit.html.erb
app/views/admin_holidays/_form.html.erb
app/views/admin_outgoing_message/edit.html.erb
app/views/admin_public_body/new.html.erb
app/views/admin_public_body_categories/_heading_list.html.erb
app/views/admin_public_body_categories/index.html.erb
app/views/admin_public_body_headings/new.html.erb
app/views/admin_request/edit.html.erb
app/views/admin_spam_addresses/index.html.erb
app/views/admin_user/edit.html.erb
doc/CHANGES.md

Noticed when inbox pairing that some of these were blue and some green.
While context is more important than consistency, none of these buttons
warranted a different colour than each other. Used `btn-success` as the
preferred colour for "Save" since it implies "done!". `btn-primary`
should be used for _initiating_ the primary action of a page, whereas
save usually completes the workflow.

Use consistent colour admin interface save buttons

---

app/controllers/admin_users_sessions_controller.rb
spec/controllers/admin_users_sessions_controller_spec.rb

Fixes: #6628
Fix login as feature
Since #6511 we check users login token when authenticating. This has
broken our login as feature as the login token present in the session
belongs to the admin user.
This change updates the session and introduces a spec to show the
authenticated user is updated.
I thought about using our new-ish `sign_in` helper method but this clears the session resulting in the black admin bar from being removed. This might be fine as to get back to a fully functional admin user we do need to sign out and sign back in again already.

[#6628] Fix login as feature

---

app/models/user/login_token.rb

**Add `User#update_login_token!`**
Allows us to call it in the console manually – useful for updating users
in development who haven't had a `login_token` set.
**Rename `User#update_login_token` to `set_login_token`**
Update implies that `update` is called under the hood, but we don't
actually save the record in these methods. Renames to `set_login_token`
for clarity of behaviour.

Tweak `User#update_login_token`

---

Vagrantfile
bin/vagrant-bullseye
doc/CHANGES.md

Requires https://github.com/mysociety/sysadmin/issues/1530
Requires https://github.com/mysociety/commonlib/pull/77
~Requires https://github.com/mysociety/alaveteli/issues/6489 or https://github.com/mysociety/alaveteli/issues/6656~
Requires #6053 
Fixes #6294 
Adds Debian Bullseye support
Framework modernisation
~~I have build a Vagrant box with the above PRs merged and `wkhtmltox` replaced with `wkhtmltopdf` and all specs pass.~~

[#6294] Add Debian Bullseye support

---

config/crontab-example
doc/CHANGES.md

Fix PATH setting for crontab
This change was required to get a jobs to run correctly when Ruby is
installed via rbenv.
This has been tested and put in place on both Sweden and Romania installs.

Fix PATH setting for crontab

---

doc/CHANGES.md
lib/configuration.rb

Fixes #6659
Add deprecation warning for HTML_TO_PDF_COMMAND
As with other external commands we need are only going to support one
option (`wkhtmltopdf`). Doing so will make it easier to pass command
specific arguments to the tool in order to support later versions.
See: https://github.com/mysociety/alaveteli/issues/6489
Will mean release 0.40 will see deprecation notices which we normally resolve before release but this isn't a heavily used feature so is fine for now.

[#6659] Add deprecation warning for HTML_TO_PDF_COMMAND

---

app/assets/stylesheets/responsive/alaveteli_pro/_dashboard_layout.scss
doc/CHANGES.md

On mobile devices the lack of bottom margin results in other UI elements
being directly attached to the dashboard navigation.
The two main places this happens are:
1. On the pro dashboard the announcement element is directly against the
nav.
2. On the pro requests list the "All requests" header is directly
against the nav.
BEFORE
AFTER

Improve spacing of pro request navigation folders

---

app/models/incoming_message.rb

This is not used so doesn't do anything.
Spotted while having a little look at https://github.com/mysociety/alaveteli/issues/6379.

Remove unused variable

---

app/views/alaveteli_pro/plans/_pricing_tiers.html.erb
app/views/alaveteli_pro/plans/index.html.erb

Extract pricing_tiers partial
Makes it easier to override a specific part of `plans/index.html.erb` in
themes. Intention for this is to add a link to our annual plan.
Also minor cleanup.

Extract pricing_tiers partial

---

app/controllers/user_controller.rb
config/routes.rb
doc/CHANGES.md
public/robots.txt
spec/controllers/user_controller_spec.rb

Adds an action that renders a simple message stating that signups from
Tor have been blocked. Alaveteli itself doesn't use this action.
Instead, use a webserver-level redirect to `/tor` if this blocking is in
place.
Opted to add to `UserController` since it's conceptually related to
`UserController#signup`.
Fixes https://github.com/mysociety/alaveteli/issues/6624
```
$ curl -I http://192.168.56.30:3000/tor
HTTP/1.1 403 Forbidden
Content-Type: text/html; charset=utf-8
Vary: Cookie
Cache-Control: max-age=86400, public
X-Request-Id: 7fd8e240-1860-4f15-a003-259dc70f9dac
X-Runtime: 0.829214
X-Frame-Options: sameorigin
X-Content-Type-Options: nosniff
X-XSS-Protection: 1
X-Permitted-Cross-Domain-Policies: none
Connection: close
Server: thin
```

[#6624] Add /tor route for blocked Tor signups

---

.ruby-style.yml
bin/rails
bin/rake
bin/setup
config.ru
config/application.rb
config/boot.rb
config/environment.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/assets.rb
config/initializers/backtrace_silencers.rb
config/initializers/content_security_policy.rb
config/initializers/filter_parameter_logging.rb
config/initializers/inflections.rb
config/initializers/new_framework_defaults_6_0.rb
config/initializers/new_framework_defaults_6_1.rb
config/initializers/permissions_policy.rb

Connected to #6011 
1. Reorder configuration so all custom config is at the bottom of environment files
2. Exclude app configuration from line length and quote style Rubocop cops 
3. Regenrated app config for Rails 6.0 to reduce diff for 4.
4. Generate app config for Rails 6.1
Framework modernisation

[#6011] Add Rails 6.1 application config

---

app/controllers/user_controller.rb
app/views/user/_show_user_info.html.erb
doc/CHANGES.md
spec/controllers/user_controller_spec.rb
spec/views/user/_show_user_info.html.erb_spec.rb

We get lots of spam signups which mainly populate the `about_me` with
links to some form of junk site. Many of these spam signups originate
through another spam user profile, so presumably they're searching for
particular terms in the spam text in order to find sites that can be
targeted.
This commit aims to reduce the attractiveness of Alaveteli to spammers
by hiding the `about_me` text from the wider web, except for when the
user has been manually confirmed as genuine.
We'll show the text to logged in users, unless the user being viewed has
been banned or closed as before.
Fixes https://github.com/mysociety/alaveteli/issues/6627.

[#6627] Reduce prominence of User#about_me

---

app/controllers/request_controller.rb
spec/controllers/request_controller_spec.rb

Make it clearer that we're referring to possible spam from a given User
ID.
Also tweak code to improve line length and hash style.

Tweak possible spam exception notification message

---

app/controllers/admin_user_controller.rb
app/models/comment.rb
app/models/info_request.rb
app/models/user.rb
doc/CHANGES.md
spec/controllers/admin_user_controller_spec.rb
spec/models/user_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/6669
Minor refactoring
Reindex comments after bulk visibility change
Comments must be reindexed after a visibility change otherwise they
appear in search-driven lists. The most obvious is the user profile
page.
The behaviour could be improved since with this implementation every
comment given is reindexed, rather than only those where the visibility
actually changes. This would require more extensive changes to not use
`update_all`.

[#6669] Reindex comments after bulk visibility change

---

.github/workflows/ci.yml

Fixes #6683
Add PostgreSQL 13 to CI testing
We will be switching to PG 13 soon when we switch to Bullseye.

[#6683] Add PostgreSQL 13 to CI testing

---

app/models/outgoing_message.rb
doc/CHANGES.md
spec/models/outgoing_message_spec.rb

Use the translated salutation in favour of the hard-coded English
salutation.
The one downside here is that we wouldn't catch "Dear Person Name," now,
but that shouldn't be a huge problem since all the auto-generated
salutations use the public body name.
Fixes https://github.com/mysociety/alaveteli/issues/2748.
Bit of a faff to test. Here's a console session with some annotations to demonstrate correct behaviour:
```ruby
message = OutgoingMessage.find(37) ; nil
message.get_text_for_indexing(strip_salutation = false)
AlaveteliLocalization.with_locale(:es) { message.send(:public_body).name }
message.get_text_for_indexing(strip_salutation = true)
AlaveteliLocalization.with_locale(:es) { message.get_text_for_indexing(strip_salutation = true) }

[#2748] Localise salutation stripping

---

app/models/censor_rule.rb
app/views/admin_censor_rule/_form.html.erb
doc/CHANGES.md

Fixes https://github.com/mysociety/alaveteli/issues/6487
Adds canned Censor Rule replacements
We frequently write the same text into the `CensorRule#replacement` form
field, so this commit adds a set of defaults that can be selected
through a `<datalist>` element.
Reusers can add to the defaults or set their own in the theme:
CensorRule.canned_replacements << '[A new reason]'
CensorRule.canned_replacements = [
'[A new reason]',
'[Another reason]'
]
Used a `cattr_accessor` so haven't added specs. Open to thoughts.
No placeholder or datalist when there aren't any canned replacements:
Screenshots a tiny bit out of date:
* I opted to make _both_ fields wider after taking them
* I capitalised "**S**elect or add your own"

[#6487] Canned censor rule replacements

---

spec/support/xapian_index.rb

Remove custom test Xapian db setup
We had been attempting to restore the test Xapian db to a know state
between each spec but this is causing issues making the some specs
flaky.
The purpose of this setup was to prevent the spec suite from needing to
recreate the database from scratch for each spec. As we use Xapian
extensively throughout the application this reduced the total time to
run the spec suite up significantly but unfortunately there are still
some confusing issues so lets remove for now so we're unblocked. We can
attempt a setup like this again in the future.

Remove custom test Xapian db setup

---

Gemfile.lock
Gemfile.rails_next.lock

This seems to be required if developing on a different platform to the
one being deployed to.
See: https://github.com/rubygems/rubygems/issues/4269#issuecomment-758086638
Added by running: `bundle lock --add-platform x86_64-linux`

Add x86_64-linux platform to the lockfiles

---

app/views/track_mailer/event_digest.text.erb
spec/views/track_mailer/event_digest.text.erb_spec.rb

Fixes #6756
Handle external requests in event digest
If a external request, which doesn't have an associated user record, is
updated and matches a TrackThing then an exception will be raise causing
the alert track daemon to fail.
This change check to see if the request is external and substitute "An
anonymous user" in place of the user name. This is the same string which
appears on the request#show view.

[#6756] External request handling for event digest

---

lib/alaveteli_localization/railtie.rb

Fixes #5382
Add `after_initialize` block to set locales
When upgrading to Rails 6 [1] this was moved from an standard
initializer to `before_configuration` block as this was required for a
new deprecation warning which happened to includes an I18n translation,
requiring the default locale to be configured before the default Rails
initializers ran.
Downside to this is it broke the fallback options for locales with
underscores (EG `en_RW`). This change required to get these locales
working correctly again when loading content from Globalize translation
tables.
[1] See https://github.com/mysociety/alaveteli/commit/02ea505
Unfortunately we can't easily test this ans the test environment is run
with `config.cache_classes = true`, this is disabled in development,
hence the conditional added to …

[#5382] Add `after_initialize` block to set locales

---

_layouts/default.html

Make it clearer that there's a whole Alaveteli community. The footer and
a main section on the homepage have a "Contact" link that also links to
`/community`, so I don't think we're losing anything by making this
change. It's pretty natural to scroll to the footer to find the contact
details IME.
Fixes https://github.com/mysociety/alaveteli/issues/1897

[#1897] Add "Community" link to main navigation

---

app/controllers/admin_user_controller.rb
spec/controllers/admin_user_controller_spec.rb

Fixes #6730
This reverts commit 2ccd7c0ab203a251d9458347e8cc01ad2f5b7f80.

[#6730] Revert "Scope modify_comment_visibility to comment author"

---

app/assets/stylesheets/responsive/_wizard_layout.scss

Fixes #6732
Changed the property from max-height to height, apparently there is a bug in chrome where the overflow:hidden on a fieldset element does not work properly.
Sorry @gbp I'm not really sure who should I ask for review, now that @garethrees is on leave.

Fixed overflowing problem on "Get help on refusal"

---

config/crontab-example
doc/CHANGES.md
lib/tasks/storage/storage.rb

Related to #6531 
1. Add a `disk_service?` check to ensure we are deleting files from the correct service.
2. Add example cronjob
To ensure raw emails already uploaded to the cloud aren't accidental deleted.

Add storage rake tasks check

---

config/crontab-example

Fix storage cronjob
Needed to:
1. add quotes so only one argumnet if passed to `run-with-lockfile`
2. cd in the application directory so the `config.ru` is found.
I merged the original commit too soon and need to make these changes on the production server to get this working.

Fix storage cronjob

---

app/assets/javascripts/admin/admin.js
app/views/admin_request/_some_annotations.html.erb
doc/CHANGES.md

Allows admins to select/deselect all annotations in an annotations list.
Makes it easier to hide all annotations when dealing with misuse.
Fixes https://github.com/mysociety/alaveteli/issues/3324.

[#3324] Add select all button for annotations

---

app/controllers/comment_controller.rb
app/controllers/request_controller.rb
app/models/user.rb
app/views/comment/rate_limited.html.erb
doc/CHANGES.md
spec/controllers/comment_controller_spec.rb
spec/controllers/request_controller_spec.rb
spec/models/user_spec.rb
spec/views/comment/rate_limited.html.erb_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/6783.
Cap number of annotations a user can make in a day
Reduce the impact of users signing up to spam the site with comments.
Currently uses the same rate limit configuration as requests, but we can always add a new configuration value if we want to tune independently.
Rather than lots of configuration options, we might want a single rate limit base, and then use a multiplier for each content type that's either fixed (e.g. `base * 1.25`) or based on a user attribute (e.g. `base * user.years_active`). We can merge any dynamic attributes with the fixed `CONTENT_LIMIT` in `User#content_limit`.
I've created a simplified version of the templated rendered when the user gets rate limited to avoid unnecessary complexity. We care less about …

[#6783] Cap number of annotations a user can make in a day

---

spec/controllers/comment_controller_spec.rb

These specs don't need to use the fixture "world", so convert them to
use factories.
Can't remove `silly_comment` just yet because the remaining uses are
linked to the `InfoRequestEvent` records that reference it.

Remove unnecessary silly comment fixture use

---

spec/fixtures/comments.yml
spec/fixtures/info_request_events.yml
spec/models/statistics/leaderboard_spec.rb

Not used anywhere. We'll lose some sample data, but getting rid of
fixtures seems like a bigger win.

Remove sensible comment fixture

---

app/models/public_body.rb
app/views/admin_public_body/show.html.erb
doc/CHANGES.md
spec/models/public_body_spec.rb

Show who made each edit on public body admin pages
We already store `PublicBody::Version#last_edit_editor`, so this just
presents it alongside the relevant comment related to that version.
I've handled the case where we can't find a `User` record for an editor
since a `User#url_name` may change if an admin requests anonymisation
and then the link would break. Ideally we'd use an association between
the records rather than having to do a lookup based on a `String`, but
this adds some value now with what we have.
Fixes https://github.com/mysociety/alaveteli/issues/6556
I was considering whether to handle `version.last_edit_editor` being `nil` or `blank?`, but that doesn't appear to be a possible case according to WDTK data:
```ruby
PublicBody::Version.where(last_edit_editor: nil).count …
```

[#6556] Show who made each edit on public body admin pages

---

app/views/layouts/admin.html.erb
doc/CHANGES.md

Prefixing the site name makes it difficult to differentiate between
several admin tabs. This puts the page title first and then adds the
"Admin" on the end.
We lose a _little_ here in that it's less obvious a given tab is an
_admin_ page rather than a public page, but an easy indicator is whether
the record is prefixed with the model class name (e.g. "User – Bob
Smith"). Public pages would just be "Bob Smith".
**BEFORE**
**AFTER**

Improve admin layout document titles

---

app/views/admin_user/show.html.erb
doc/CHANGES.md

Adds a couple of extra one-click ban reasons to the one-click "Ban for
spamming" admin button.
Ideally we'd move these to canned reasons for the `User#ban_text` form
field, but there's a bit of complication with that being a `<text_area>`
rather than an `<input>`. For now this adds some common reasons that
help with common cases.
A simplified version of https://github.com/mysociety/alaveteli/issues/6699.
Couldn't get the [split button dropdown](https://getbootstrap.com/2.2.0/components.html#buttonDropdowns) to join properly, but doesn't matter too much in this context.

[#6699] Extra one click ban reasons

---

app/models/comment.rb
spec/models/comment_spec.rb

Add method to hide a `Comment` alongside logging an event on the
request. Don't need to do anything about reindexing as that's handled in
a callback.
This isn't called anywhere in the app yet, but makes it easier to hide
comments via the Rails console.

Add Comment#hide

---

app/helpers/admin_helper.rb
app/models/comment.rb
app/views/admin_comment/index.html.erb
app/views/admin_request/_some_annotations.html.erb
app/views/admin_request/show.html.erb
app/views/admin_user/show.html.erb
spec/helpers/admin_helper_spec.rb
spec/models/comment_spec.rb

Make it easier to see comment metadata (author, prominence, associated request) in comment listings.
Comments associated to another record (`User` / `InfoRequest`)
Full list of comments:
Improve bulk action buttons:

Admin comment metadata improvements

---

app/views/admin_user/show.html.erb
spec/integration/admin_spec.rb

* Make "Edit" a standard button – it's not really a "primary" action;
just an occasional action.
* Group "Edit" and "Public page" as these are closely related (i.e
seeing the record in slightly different ways).
* Bring the "login as" button into the main `btn-toolbar`.
* Use a `link_to` for "login as" to reduce template complexity.
* Add a `btn-toolbar` around the "ban for" `btn-group` for alignment.
Makes the page feel less messy which makes it more pleasant to be in
when you're working with the interface.
I did wonder about the button class of "Login as". We seem to use
`btn-info` for creating secondary associated content (like Censor
Rules), which is not what we're doing here. However, `btn-warning` felt
too strong, and a plain `btn` didn't feel differentiated enough. For now
it's fine …

Minor styling of user admin button toolbar

---

app/views/admin_user/show.html.erb

Help reduce cognitive burden on admins by reordering lists of content
by most important.
* Requests are the primary content that we care about, so put those
first.
* Annotations are closely linked to requests, so then render them. This
helps with spotting abuse when you can get an overview of a user's
content-creation activity.
* Post Redirects and Track things are more incidental, so render those
next.
* Censor rules are very occasionally used and for consistency I've left
them last on the page.
This was motivated by some vexatious users having 10s/100s of track
things, requiring several scrolls to assess the published requests and
annotation content.

Reorder content lists on user admin page

---

app/helpers/admin_helper.rb
app/models/user.rb
app/views/admin_request/_some_annotations.html.erb
app/views/admin_request/_some_requests.html.erb
app/views/admin_user/_user_table.html.erb
spec/factories/users.rb
spec/models/user_spec.rb

Add prominence_icon to admin user listings
Allows an at-a-glance look at whether a User is banned, inactive or
otherwise in a compact method. When banned a user gets “Account
Suspended” prepended to their name, and in some cases an orange “banned”
label, but in other more information-dense listings we either don’t show
this or it’s hard to parse out.
This makes it easy to tie banned users to hidden content or hidden
content to unbanned users.
Main benefit is in a listing like this where we can get a quick overview of a group of content:
Also tweaks the users index. Not much more information than before, but marginally less messy.

Add prominence_icon to admin user listings

---

app/controllers/user_controller.rb
config/general.yml-example

Prevent probable spam from signing up in order to prevent them creating
content.
I've cowboyed this in to deal with current sustained misuse of
WhatDoTheyKnow. We'll want to add some tests and/or extract to
`UserSpamScorer`.

Block signups from RESTRICTED_COUNTRIES

---

app/controllers/admin_user_controller.rb
app/helpers/admin/bootstrap_helper.rb
app/helpers/admin_helper.rb
app/helpers/application_helper.rb
app/views/admin_user/banned.html.erb
app/views/admin_user/index.html.erb
app/views/layouts/admin/users.html.erb
spec/helpers/admin/bootstrap_helper_spec.rb

Make it easier to navigate around user-related admin pages.
`inside_layout` from https://justincypret.com/blog/nested-layouts-in-rails

Add admin/users subnav

---

config/crontab-example
lib/tasks/storage/storage.rb
lib/tasks/temp.rake

Fixes #6833
Refactoring logging and changed to only output when the `--quiet` argument isn't used
We're receiving emails with progress bar output
Only stdout is silenced, errors are still outputted

[#6833] Improve storage rake logging

---

app/models/foi_attachment.rb
config/storage.yml-example
lib/tasks/storage.rake
lib/tasks/storage/attachments.rake

Fixes #6532
Migrate FoiAttachment to use ActiveStorage
When the `ActiveStorage::Blob` file isn't attached then use the old file
store.

[#6532] Migrate FoiAttachment to use ActiveStorage

---

app/views/admin_user/edit.html.erb

This is disabled for banned users in order to preserve the email address
to enforce the ban, so make that clear in the documentation.
Fixes https://github.com/mysociety/alaveteli/issues/6872.

[#6872] Update close and anonymise inline docs

---

lib/tasks/storage/attachments.rake
lib/tasks/storage/storage.rb

See #6532
See #6705
Adds a checks if the `FoiAttachment` exists on disk before migrating.
It is fine for `FoiAttachment` to be missing from disk as we deal with
that within the `FoiAttachment#body` method.
We previously needed to `#reload` the instance (adding in [1]) if the
file was missing but now this isn't necessary any more.
[1] https://github.com/mysociety/alaveteli/pull/6705

[#6532] Update FoiAttachment storage migrate task

---

app/assets/config/manifest.js
app/assets/stylesheets/admin/_print_style.scss
app/assets/stylesheets/admin/print.scss
app/views/admin_general/stats.html.erb
app/views/admin_public_body/_one_list.html.erb
app/views/admin_public_body/index.html.erb
app/views/admin_request/index.html.erb
app/views/layouts/admin.html.erb

This PR fixes #6684 
Allows users to print the page without having to open each one of the accordion items. This PR also includes UI improvements such spacing, fonts, hide interactive elements when printing. 
The admin pages were having issues with the printing styles. Closed accordions items and missing styles were affecting the readability of the pages when getting printed.
Mostly just changes in the css have been implemented, however I have added a few extra classes on the markup to be able to select certain elements in some of the pages.
[Alaveteli admin_ Public authority – Another Public Body.pdf](https://github.com/mysociety/alaveteli/files/8087853/Alaveteli.admin_.Public.authority.Another.Public.Body.pdf)
[Alaveteli admin_ Listing public …

[#6684] Admin print improvements

---

Gemfile
Gemfile.lock
Gemfile.rails_next.lock

https://github.com/mysociety/sysadmin/issues/1527
Add SFTP ActiveStorage service
Allows mirroring to remote servers of attached files. This will be
useful when migrating to a new application server.
Can be configured in `config/storage.yml`, with:
```
attachments_sftp:
service: SFTP
root: remote/path
user: username
host: host.name.tld
```

Add SFTP ActiveStorage service

---

app/views/request/new.html.erb

Fixes #6800 
This replaces the generic header text used when _public body questions_ are rendered, and ensures that the correct semantic tagging is in place.
To aid reuse on WDTK theme, and improve legibility - a simpler heading allows us more flexibility.
Nothing of note - thanks to @garethrees for help with the translation parameter, hopefully I've done it right!
This is best tested against WDTK theme - a PR will follow there to amend the existing public body questions for Home Office (and add some others) imminently.

[#6800] Tweak heading used for public body questions

---

.github/workflows/ci.yml

When commonlib is updated upstream when need to immediately update else
CI is red. Changing the `actions/checkout` option to allow builds to
checkout older commits.
Fixes:
```
fatal: Fetched in submodule path 'commonlib', but it did not contain
<SHA>. Direct fetching of that commit failed.
```

Fix CI builds after submodules are updated

---

app/controllers/admin_request_controller.rb

Neither `InfoRequest#move_to_user` or `InfoRequest#move_to_public_body`
does anything with the `:reindex` option – events are always reindexed.
`InfoRequest#move_to_public_body` was added in 0c77f6e7f95 and then
replaced controller code in 8b5188e9f. It looks like the `reindex`
option has never worked in that context. See the Pull Request for more
[1].
Same story with `InfoRequest#move_to_user`. It was extracted from
controller code in 1fa16e7219, and there too I mistakenly added the
unused `reindex` option.
Also fixes line length issues.
[1] https://github.com/mysociety/alaveteli/pull/2408

Remove non functional option

---

spec/fixtures/users.yml

We never test whether this fixture user is confirmed or not. As we use
the fixtures for sample data, it's more useful to have this one already
confirmed.

Create admin_user fixture as confirmed

---

app/views/admin_general/_change_request_summary.html.erb
doc/CHANGES.md

Show public body change request notes in admin summary so that more of
the process can be managed within Alaveteli itself rather than swapping
back and forth between the app and the email support system.
A quick win from https://github.com/mysociety/alaveteli/issues/5368.

[#5368] Show body change request notes in admin summary

---

app/views/admin_public_body/edit.html.erb
app/views/admin_public_body/new.html.erb
doc/CHANGES.md

If we're editing a public body via a change request, show the additional
notes when editing the body. This provides the admin with better inline
context about the edit and allows quicker copy-pasting of details added
to the notes field.
A quick win from https://github.com/mysociety/alaveteli/issues/5368.
Won't get the notes until https://github.com/mysociety/alaveteli/pull/6798 is merged, but there's no dependency in either direction.

[#5368] Show change request notes on body edit page

---

app/helpers/admin/link_helper.rb
app/helpers/admin_helper.rb
app/models/info_request_batch.rb
app/views/admin/citations/_list.html.erb
app/views/admin_censor_rule/_form.html.erb
app/views/admin_comment/edit.html.erb
app/views/admin_general/_to_do_list.html.erb
app/views/admin_general/timeline.html.erb
app/views/admin_incoming_message/_intro.html.erb
app/views/admin_public_body/missing_scheme.html.erb
app/views/admin_raw_email/show.html.erb
app/views/admin_request/_some_annotations.html.erb
app/views/admin_request/_some_requests.html.erb
app/views/admin_request/show.html.erb
app/views/admin_track/_some_tracks.html.erb
app/views/admin_user/_user_table.html.erb
app/views/admin_user/show.html.erb
doc/CHANGES.md
spec/helpers/admin/link_helper_spec.rb
spec/helpers/admin_helper_spec.rb
spec/models/info_request_batch_spec.rb

Makes it easier for admins to see when a citation was added to a request
and who added it, or what citations a user has added and to which
requests.
Supersedes https://github.com/mysociety/alaveteli/pull/6848.
Instead of a table format, use the "Thing" → "By" → "On" trio used in other lists. This makes the partial more flexible in that it makes more sense when rendered in multiple views.
In the future, if `Citation` gets its own admin/show page, we can link internally rather than the `Citation#source_url`, add a `prominence_icon`, etc.
I've currently handled batches by giving `InfoRequestBatch` a hard-coded prominence value so we can continue the pattern of using `prominence_icon` to link to the public record page, and then not rendered a link to the admin batch page, which can be added …

Show citations on admin pages

---

config/initializers/health_checks.rb
lib/health_checks/checks/limit_check.rb

https://github.com/mysociety/sysadmin/issues/1440
Add health check for Xapian job queue length
If the job queue isn't being processed we need to alerted so the issue
can be resolved.
To prevent batch requests from triggering this check we ignore jobs
created within the last 30 minutes.

[sysadmin#1440] Add health check for Xapian job queue length

---

app/controllers/admin_users_sessions_controller.rb
app/controllers/application_controller.rb
app/views/admin_general/_admin_navbar.html.erb
config/routes.rb
spec/controllers/admin_users_sessions_controller_spec.rb

Fixes #1785
When an admin has logged in as another user, this adds the ability to revert back to their own account.
Too many incidences where I've forgotten I was signed in as someone else and thinking the admin has broken.
Todo: specs ?

[#1785] Allow admins to revert back to their own account

---

app/controllers/admin_user_controller.rb
app/views/admin_user/_user_table.html.erb
app/views/admin_user/banned.html.erb
app/views/admin_user/index.html.erb
app/views/layouts/admin/users.html.erb
config/routes.rb
spec/views/admin_user/_user_table.html.erb_spec.rb

Following on from https://github.com/mysociety/alaveteli/pull/6823
Combine `AdminUser#banned` with the `#index` action which includes searching, filtering and ordering so these can be done to within the banned user scope.
Also adds scopes for `active` and `closed` users because why not.

Add AdminUser scopes

---

app/controllers/admin_user_controller.rb
app/views/admin_user/index.html.erb
app/views/layouts/admin/users.html.erb

Move it above the subnav tabs – feels wrong for a main page heading to
be "in between" elements.
This also moves the setting of `@title` from the view to the controller
to remove logic from views. In the `index` action we need to use
conditional assignment in case its been set via one of the filter lists
(banned, active, etc).

Reposition the admin user list heading

---

app/models/user/login_token.rb

Fixes: #6914
Generate login tokens UUID with valid namespace
We have generate our own random (UUIDv4) namespace for use when
generating login tokens.
Fix deprecation warning under Rails 7
See: https://github.com/rails/rails/issues/37681
When upgrading to Rails 7 we will need to set:
`config.active_support.use_rfc4122_namespaced_uuids = true`

[#6914] Generate login tokens UUID with valid namespace

---

.github/workflows/ci.yml
doc/CHANGES.md
docker/Dockerfile-postgres

Fixes #5574
Drop support for PostgreSQL 9.6
Recommend upgrading to at least version 13.5 as this is the default in
Debian Bullseye and  what mySociety is running in production.

[#5574] Drop support for PostgreSQL 9.6

---

app/views/admin_user/_scopes.html.erb
app/views/admin_user/index.html.erb
app/views/admin_user/show.html.erb
app/views/layouts/admin/users.html.erb

Couple of quick fixes for the recent changes to the user admin index/show actions.
- Rendering scope tabs on `#show`
- Double rending of title on `#show`
- Ordering buttons would redirect to the all users scope.
Fixes:

User admin scopes fixes

---

app/assets/stylesheets/responsive/_password_changes_style.scss
app/assets/stylesheets/responsive/all.scss

This PR increases the width of email box, so it can fit longer emails.
Tested on mobile so there is no overflow on small screen sizes.
@garethrees let me know if you prefer this fix to go in _global_styling.scss instead of creating a new file, like I have done in this PR.
As I saw good list of well organised files, I thought it would be better this way, but maybe it's not worthy it for such small file.
Fixes: #6493

Increased width of email box when changing password

---

.github/git-io-urls.md
app/models/public_body.rb
doc/CHANGES.md

GitHub shutting down git.io and as a consequence, will stop redirecting
the shortened URLs [1]
[1] https://github.blog/changelog/2022-04-25-git-io-deprecation

Expand git.io URLs

---

docs/pro/index.md
docs/pro/pricing.md

GitHub shutting down git.io and as a consequence, will stop redirecting
the shortened URLs [1]
[1] https://github.blog/changelog/2022-04-25-git-io-deprecation

[gh-pages] Expand git.io URLs

---

app/views/alaveteli_pro/info_requests/_embargo_form.html.erb

Added bold class to "Publish now" button. (The font-weight for this button has been increased so it pops out
more than his sibling element)
Fixes: #6568

Added styling for "Publish now" button

---

app/assets/stylesheets/responsive/_new_request_layout.scss

This PR fixes:
-Uneven vertical aligmnet on questions that break into two lines.
-Decrease the vertical space between lines on question with two lines.
Fixes: #5088

Added UI fix to radio elements when making a request

---

app/assets/stylesheets/admin.scss
app/controllers/admin/users/sign_ins_controller.rb
app/controllers/application_controller.rb
app/models/user.rb
app/models/user/sign_in.rb
app/views/admin/users/_sign_in_table.html.erb
app/views/admin/users/sign_ins/index.html.erb
app/views/admin_user/_scopes.html.erb
app/views/admin_user/show.html.erb
config/crontab-example
config/general.yml-example
config/routes.rb
db/migrate/20220225094330_create_user_sign_ins.rb
db/migrate/20220225214524_add_country_to_user_sign_ins.rb
doc/CHANGES.md
lib/configuration.rb
lib/tasks/users/sign_ins.rake
spec/controllers/admin/users/sign_ins_controller_spec.rb
spec/factories/user/sign_ins.rb
spec/integration/signin_spec.rb
spec/models/user/sign_in_spec.rb
spec/models/user_spec.rb

If a retention period is configured, create a record associated with the
user of the signin and the IP address used to do so.
A rake/cron task is provided to purge records older than the retention
period.
A version of https://github.com/mysociety/alaveteli/issues/2691
---
View/search all recorded sign ins:
View a given user's sign ins. Check how many others have signed in with the IP:
Click the IP address to go through to the main listing filtered by that IP (or country, added after screenshot):
Filter by partial IP:
Filter by country:

[#2691] Track IP addresses associated with User signins

---

app/helpers/admin/censor_rules_helper.rb
app/helpers/admin_helper.rb
app/models/censor_rule.rb
app/views/admin_censor_rule/_form.html.erb
app/views/admin_censor_rule/_show.html.erb
app/views/admin_request/show.html.erb
doc/CHANGES.md
spec/helpers/admin/censor_rules_helper_spec.rb
spec/models/censor_rule_spec.rb

Show all applicable censor rules on a request page
Opted to add a new helper to show the _class_ the rule is applicable to
rather than using `Admin::CensorRulesHelper#censor_rule_applies_to`
because showing the `both_links` content is quite messy in this small
table cell context.
Clicking edit takes you through to the edit form for the rule, and
that’s what will then allow you to click through the `both_links` to the
censorable record.
Fixes https://github.com/mysociety/alaveteli/issues/485
Also a minor refactoring of displaying the record the censor rule applies to

[#485] View all applicable censor rules

---

app/assets/stylesheets/admin.scss
app/views/admin_public_body/import_csv.html.erb
doc/CHANGES.md

Make error messages on CSV upload more prominent
Currently errors such as ~"invalid email address on line x" are shown in
black on grey text along with the full list of authorities. Errors
should be in red, large, and at the top of the results page.
This also improves code readability by using `#present?` instead of
negating `#empty?`, and fixes missed space after erb opening tag.
Fixes https://github.com/mysociety/alaveteli/issues/4801

[#4801] CSV import error prominence

---

app/views/admin_incoming_message/_actions.html.erb
doc/CHANGES.md

Add the clarification request button to incoming message actions.
This is the more natural place to look for the button, and provides a
little more space for us to explain what it does.
Essentially the same implementation as in `views/admin_request/show`,
but here we have `IncomingMessage#response_event` to do the second part
of the conditional. Also use a normal button rather than primary as it's
not the primary action in this context.
Fixes https://github.com/mysociety/alaveteli/issues/5338
Rendered button with help:
Click the button and it marks as a request for clarification:
Button no longer renders for that message:
IDK what's up with the spacing, but it's an existing problem with the whole "Actions" section.

[#5338] Add clarification request button to actions

---

app/models/censor_rule.rb

> Censor rules often end up mid-sentence, so shouldn't start with a
> capital letter
I've left "Personally Identifiable Information" capitalised as that's a
proper noun and commonly referred to as PII.
Fixes https://github.com/mysociety/alaveteli/issues/6844.

[#6844] Lowercase canned CensorRule replacements

---

config/httpd.conf-example

Fixes https://github.com/mysociety/sysadmin/issues/1624
Configure Passenger/Ruby to require bundler. Our Gemfile now contains
different versions of gems which shipped with Ruby 2.7. 
Without this change the application couldn't be launched.
This has been run in production since March 30th

Update Apache config

---

app/assets/javascripts/alaveteli_pro/batch_authority_search/browse.js
app/assets/javascripts/alaveteli_pro/batch_mode/mode-switcher.js
app/assets/javascripts/alaveteli_pro/draft_batch_summary/body-list.js
app/assets/javascripts/alaveteli_pro/draft_batch_summary/initialise.js

Fixes #6863
Fix batch category selection being reset
When adding the first body the draft is created and the ID needs to be
passed through to subsequential requests. We already handled this for
the 'Add' and 'Remove' buttons. What wasn't handled was the anchors to
load another category's public bodies.
This wraps the URL for AJAX calls with a method extracted from the mode
switcher which already handled injecting the correct draft ID.
Also updates browser address bar with draft ID when this is changed.

[#6863] Fix batch category selection

---

app/models/incoming_message.rb
spec/models/incoming_message_spec.rb

Improve performance by using Active Record query to filter the events
with SQL rather than using Ruby.
Also refactors the spec to be more in line with current practice
(explicit subject, let, factories).

Refactor `InfoRequestEvent#response_event`

---

lib/alaveteli_spam_term_checker.rb
spec/lib/alaveteli_spam_term_checker_spec.rb

Fixes #7070
Update spam term regexp due to false positives
Regexp was matching requests about ADHD or PhD which should be allowed
to be created.

[#7070] Update spam term regexp due to false positives

---

config/general.yml-example
config/test.yml
lib/alaveteli_geoip.rb
lib/configuration.rb
spec/lib/alaveteli_geoip_spec.rb
spec/support/gaze.rb

Fixes #2905
Remove integration with Gaze
We don't use this at all anymore. Instead uses should switch to the
MaxMind GeoIP database.

[#2905] Remove integration with Gaze

---

app/controllers/request_controller.rb
app/controllers/user_controller.rb

Make this consistent with the spam signup notifications. Removes 2nd and
3rd argument from the `handle_blocked_ip` method as these are the same
as the values returned by the helper methods in `ApplicationController`.

Add user IP and country to spam request notice

---

app/views/admin_public_body/import_csv.html.erb

Errors are more problematic than notes, so display them first.
Fixes https://github.com/mysociety/alaveteli/issues/4801.

[#4801] Render CSV errors before notes

---

app/models/incoming_message.rb
app/views/general/_advanced_search_tips.html.erb

This is only called in `views/general/_advanced_search_tips` so it's
redundant here.

Remove IncomingMessage.get_all_file_extensions

---

app/models/incoming_message.rb
app/models/incoming_message/cache_attributes_from_raw_email.rb

Extract duplication when caching RawEmail attrs
All these methods do the same thing – override the accessor to ensure
`parse_raw_email!` is called, and then call the original accessor.
`parse_raw_email!` caches each attribute from the `RawEmail` on
`IncomingMessage`.
This commit extracts that duplication to a concern, with an explicit
DSL method for defining which attributes should be cached. This makes it
clear that there's "something different" about these methods, rather
than invisibly overriding them in the concern directly.
Existing specs on IncomingMessage cover this behaviour.

Add IncomingMessage::CacheAttributesFromRawEmail

---

app/assets/javascripts/alaveteli_pro/alaveteli_pro.js
app/assets/javascripts/alaveteli_pro/batch_authority_search/count.js
app/assets/stylesheets/responsive/alaveteli_pro/_batch_request_authority_search_layout.scss
app/helpers/alaveteli_pro/batch_request_authority_searches_helper.rb
app/views/alaveteli_pro/batch_request_authority_searches/index.html.erb
spec/helpers/alaveteli_pro/batch_request_authority_searches_helper_spec.rb

Fixes #7018
Display the number of authorities added to a draft batch. Dynamically update this as authorities and added or removed.
To make pro users more aware of the amount of requests they are sending and the amount of work their batch is going to generate. 
It seemed logical to display along side the "Write Request" button. This button is in different locations on the search/browse modes so now this count is too.
Attempted to handle plural terms other locales have more but limited to `zero`, `one`, `many` given the effort required (either lots of duplication or adding some sort of gettext JS library) to implement them all.
https://user-images.githubusercontent.com/5426/174986565-8c5e1e76-fbf5-4eb7-93b3-6d45fe609cc5.mov

[#7018] Add batch authority count

---

app/views/public_body/show.html.erb
spec/integration/alaveteli_pro/request_creation_spec.rb
spec/integration/create_request_spec.rb
spec/views/public_body/show.html.erb_spec.rb

Sometimes users use Alaveteli to make general or unsuitable requests. It
is likely they are less digitally literate and believe the authority
page to be an official or general contact form.
This tweak makes it clearer that users will be making an info request.
Part of https://github.com/mysociety/alaveteli/issues/7102

[#7102] Make it clearer that users are making info requests

---

app/controllers/admin_incoming_message_controller.rb
app/controllers/admin_outgoing_message_controller.rb
app/controllers/admin_raw_email_controller.rb
app/controllers/admin_request_controller.rb
spec/controllers/admin_incoming_message_controller_spec.rb
spec/controllers/admin_outgoing_message_controller_spec.rb
spec/controllers/admin_raw_email_controller_spec.rb
spec/controllers/admin_request_controller_spec.rb

Fixes #6999
This PR prevent (non-pro) admin users from having access to embargoed requests content (metadata, incoming and outgoing emails).
As described in the linked issue, it is currently possible for an admin user to craft a url that will bypass auth checks and access embargoed content.
Based on @laurentS work in the initial PR #7047

[#6999] Prevent admin users from accessing embargoed content

---

app/assets/stylesheets/responsive/_categorization_game_style.scss
app/helpers/classifications_helper.rb
app/models/request_classification.rb
app/views/request_game/play.html.erb
doc/CHANGES.md
spec/helpers/classifications_helper_spec.rb

A first version of https://github.com/mysociety/alaveteli/issues/438.
Add a short animated highlight for users who reach a classification
milestone in a league table.
A little end-of-week fun to quash an @FOImonkey riot 😏 
There's probably mathematical function that would give us the classification milestones, but I figured going up to 1 million will be alright for a while.
https://user-images.githubusercontent.com/282788/175616085-9a71b748-e6aa-4af3-a71f-08423982a051.mov
The lack of table cell padding isn't a new addition – it's like that on `develop`. I think it just looks fine on WDTK because there's more content.

[#438] Highlight user classification milestones

---

app/views/admin_public_body/_one_list.html.erb
app/views/admin_public_body/index.html.erb
doc/CHANGES.md

Fixes #6941
* Protect mass-tag update buttons in body lists
* Cleans up search form and button prominence
Reduce chance of mass-mistakes through bulk actions
**Before**
**After**
**Protected mass-add**
**Protected mass-remove**

[#6941] Confirm mass tag admin actions

---

app/models/info_request_batch.rb
spec/models/info_request_batch_spec.rb

Fixes #5584
Update existing batch validation
Only run validation for new batches. There might be existing batches
with duplicate requests. We should be able to update these to remove
any `embargo_duration` value when necessary.

[#5584] Update existing batch validation

---

lib/has_tag_string/has_tag_string.rb
spec/models/has_tag_string_tag_spec.rb

Allows for easier construction of a `HasTagStringTag` within application
code by encapsulating the logic of splitting the tag's name and value.

Add HasTagString::HasTagStringTag.from_string

---

app/views/admin_incoming_message/_actions.html.erb

Fix markup for "Was clarification request" button
Move within the control group to fix positioning.
Before:
After:

Fix markup for "Was clarification request" button

---

_config.yml

Fixes #7190 
This changes the request counter on alaveteli.org from "800,000+" to "1,000,000+".
@FOIMonkey noted the milestone - this is worth celebrating!
Nothing fancy - a rainbow would have been nice, mind you! 🌈
N/A

[#7190] Over one million requests!

---

app/controllers/admin/notes_controller.rb
app/controllers/admin/tags_controller.rb
app/helpers/admin/tag_helper.rb
app/models/concerns/notable.rb
app/models/note.rb
app/models/public_body.rb
app/views/admin/notes/_form.html.erb
app/views/admin/notes/_locale_fields.html.erb
app/views/admin/notes/_note.html.erb
app/views/admin/notes/_show.html.erb
app/views/admin/notes/edit.erb
app/views/admin/notes/new.html.erb
app/views/admin/tags/_notes.html.erb
app/views/admin/tags/_tagging.html.erb
app/views/admin/tags/show.html.erb
app/views/admin_public_body/show.html.erb
config/routes.rb
db/migrate/20220720085105_create_notes.rb
spec/controllers/admin/notes_controller_spec.rb
spec/controllers/admin/tags_controller_spec.rb
spec/factories/notes.rb
spec/helpers/admin/tag_helper_spec.rb
spec/models/concerns/notable.rb
spec/models/concerns/notable_and_taggable.rb
spec/models/note_spec.rb
spec/models/public_body_spec.rb

Fixes #4478
Fixes #6994
Adds new notes model and admin controller. Associated as a "concrete note" with `PublicBody` via a new `Notable` concern. Also can be assoicated as a "tagged note" via a `notable_tag` column.
Easier handling of notes, especially via tags, so notes don't need to be manually added to multiple authorities.
Have extract out these new issues from #4478
These will be done as separate PRs.

[#4478] New notes model and admin controller

---

app/models/application_record.rb
app/models/censor_rule.rb
app/models/comment.rb
app/models/concerns/admin_column.rb
app/models/incoming_message.rb
app/models/info_request.rb
app/models/info_request_event.rb
app/models/outgoing_message.rb
app/models/outgoing_message/snippet.rb
app/models/public_body.rb
app/models/user.rb
app/views/admin/outgoing_messages/snippets/_snippet.html.erb
app/views/admin_comment/edit.html.erb
app/views/admin_public_body/_public_body.html.erb
app/views/admin_public_body/show.html.erb
app/views/admin_request/_info_request.html.erb
app/views/admin_request/_some_annotations.html.erb
app/views/admin_request/show.html.erb
app/views/admin_user/_user_table.html.erb
app/views/admin_user/show.html.erb
spec/models/comment_spec.rb

Refactors `AdminColumn` module and the usage of it's `#for_admin_column` method to be simpler, more flexible and consistent across models.
Now uses string to define sets columns instead of using `ActiveRecord::ConnectionAdapters::Column` objects (driven from the DB schema), this allows us to add "virtual" columns (eg any methods on a instance) to be exposed as an admin column.
When working on #6949 I wanted to rename current `params_yaml` to `params` be this resulted in the admin column not being rendered. I was on a train with not much else I could work on so ended doing this refactoring.

Refactor AdminColumn module

---

app/helpers/notes_helper.rb
app/models/public_body.rb
spec/helpers/notes_helper_spec.rb
spec/models/public_body_spec.rb

Depends on #7212 
Depends on #7242 
Fixes #387
Show public body notes by tag
This updates the markup but doesn't really change how the notes look yet - design work will be done in a separate branch.
This only has two commits, after dependent branches are merged:
- 0a2fc5a32c1a89366fd8643bde715a4c0d184177
- 92223f33e2d0363a0b17e32483408ca19e7875ee

[#387] Notes by tag

---

app/controllers/admin/tags_controller.rb
spec/controllers/admin/tags_controller_spec.rb

Fixes #7225
This commit changes the filtering to allow:
1. tag name or value filtering with query `foo`
2. tag name and value filtering with query `foo:bar`
3. begins with tag value filtering with query `:bar`
4. full tag name filtering with query `foo:`

[#7225] Update tag controller filtering

---

doc/CHANGES.md
lib/alaveteli_file_types.rb

https://github.com/mysociety/alaveteli/issues/7027#issuecomment-1225364665
Use correct mime type for cached CSV attachments
Currently they fall back to `application/octet-stream` in `AttachmentsController#content_type`
BEFORE
$ curl --silent -I http://localhost:3000/request/124/response/10/attach/2/foo.csv | grep 'Content-Type:'
Content-Type: application/octet-stream; charset=utf-8
AFTER
$ curl --silent -I http://localhost:3000/request/124/response/10/attach/2/foo.csv | grep 'Content-Type:'
Content-Type: text/csv; charset=utf-8

Use correct mime type for cached CSV attachments

---

app/controllers/admin/post_redirects_controller.rb
app/views/admin_user/show.html.erb
config/routes.rb
doc/CHANGES.md
spec/controllers/admin/post_redirects_controller_spec.rb

We often spot user accounts with unconfirmed requests that don't meet
our house rules. The only way to prevent a user going on to confirm the
request is by destroying its associated `PostRedirect`, which until this
commit could not be performed through the admin UI.
This action currently only handles post redirects with an associated
`User`. We do create post redirects _without_ associated an associated
`User` record, but those are not displayed in the admin UI anywhere, so
I don't think that's an immediate issue.
Fixes https://github.com/mysociety/alaveteli/issues/3500

[#3500] Allow admins to destroy post redirects

---

app/helpers/admin/link_helper.rb
app/views/admin_incoming_message/_intro.html.erb
app/views/admin_outgoing_message/_intro.html.erb
app/views/admin_outgoing_message/edit.html.erb
doc/CHANGES.md
spec/helpers/admin/link_helper_spec.rb

Add incoming & outgoing message to both_links & Rationalise links in incoming & outgoing edit view 
When administering messages it’s quite annoying to have different ways –
or no way at all – of getting back to the public content or the admin
page for the request.
This commit rationalises the two admin views so that there’s the ability
and consistency of being able to navigate to the right content.
The one thing that’s been dropped is the link to “List all”, but that’s
easily available from the main admin nav bar.
The use of both_links also adds richer information in the form of
showing the current prominence for both request and message.

Rationalise message admin links

---

spec/models/alaveteli_pro/draft_info_request_batch_spec.rb
spec/models/concerns/info_request/draft_title_validation.rb
spec/models/concerns/info_request/title_validation.rb
spec/models/concerns/notable.rb
spec/models/concerns/notable_and_taggable.rb
spec/models/concerns/taggable.rb
spec/models/draft_info_request_spec.rb
spec/models/info_request_batch_spec.rb
spec/models/info_request_spec.rb
spec/models/outgoing_message/snippet_spec.rb
spec/models/public_body_spec.rb

Extracted from #7257 will be useful for #7246 
1. Refactoring of existing spec model concerns
2. Extraction of `Taggable` concern specs

Taggable specs

---

app/models/public_body.rb
app/views/admin_public_body/_form.html.erb
doc/CHANGES.md
lib/has_tag_string/has_tag_string.rb
spec/models/public_body_spec.rb

Automatically apply and remove the `missing_email` tag to bodies that
have a missing email so that users can find them via a public search and
help to source the addresses.
The changelog suggests a one-shot script to mass-apply the tag to
existing bodies that are missing an email.
Fixes https://github.com/mysociety/alaveteli/issues/3477.

[#3477] Automatically tag bodies missing a request address

---

lib/tasks/temp.rake

Depends on #7243
Fixes #7216
Add rake task to migrate notes
Legacy notes will be removed in the next release

[#7216] Add rake task to migrate notes

---

app/controllers/admin_public_body_controller.rb
app/views/admin_public_body/_locale_fields.html.erb
app/views/admin_public_body/show.html.erb

Depends on #7243
Minor legacy notes admin updates to fix the rendering on old notes and prevent creating/editing of old notes.

Legacy notes admin updates

---

app/models/info_request.rb
app/views/admin_request/show.html.erb
app/views/request/show.html.erb
spec/models/info_request_spec.rb

Depends on #7243
Fixes #6912
Adds our `Notable` concern to `InfoRequest`. Adds notes to the request admin, and rendered notes in the frontend UI - ready for styling as part of #6920.

[#6912] Add request notes

---

app/assets/stylesheets/responsive/_notes_layout.scss
app/assets/stylesheets/responsive/_notes_styles.scss
app/assets/stylesheets/responsive/alaveteli_pro/_new_request_style.scss
app/assets/stylesheets/responsive/all.scss

Related to #7240 and #7243
Added styling to notes when visiting:
- Authority page
- Request page
- New request page

Styling for notes

---

app/controllers/admin_incoming_message_controller.rb
app/controllers/admin_outgoing_message_controller.rb
app/models/incoming_message.rb
app/models/outgoing_message.rb
app/views/admin_incoming_message/edit.html.erb
app/views/admin_outgoing_message/edit.html.erb
spec/controllers/admin_incoming_message_controller_spec.rb
spec/controllers/admin_outgoing_message_controller_spec.rb
spec/models/incoming_message_spec.rb
spec/models/outgoing_message_spec.rb

Supersedes https://github.com/mysociety/alaveteli/pull/7075
Fixes #7074
1. Refactoring of existing spec model concerns
2. Extraction of `Taggable` concern specs
3. Allow individual message to be tagged within the admin UI.

[#7074] Taggable incoming/outgoing messages

---

app/assets/javascripts/alaveteli_pro/authority_select.js
app/helpers/alaveteli_pro/public_bodies_helper.rb
app/views/alaveteli_pro/public_bodies/_notes.html.erb
spec/controllers/alaveteli_pro/public_bodies_controller_spec.rb
spec/helpers/alaveteli_pro/public_bodies_helper_spec.rb

Fixes #7265 
Fix rendering of notes for Pro authority search
After selecting an authority we should render the notes as HTML using
the `render_notes` helper.
This is matches how the notes are render when click the "Make a Freedom
of Information request to this authority" button on the public authority
page.

[#7265] Fix rendering of notes for Pro authority search

---

lib/tasks/temp.rake

If a translated locale had a blank notes string an error would be raised
when migrating notes to the new `Note` model.
Fixes #7277

Fix broken notes migration rake task

---

app/helpers/notes_helper.rb
spec/helpers/notes_helper_spec.rb

Fixes #7282
Don't rendering the notes container element if there are no notes to
render.
Prevents styling on the container element from displaying.

[#7282] Update notes rendering

---

app/views/admin_public_body/edit.html.erb

Fixes #7260
* Add breadcrumbs to admin body edit page
* Fix admin edit public body page title
Makes it easier to navigate to / open the body show page with version
history when handling change requests and other edits.
Uses `both_links` so eye links to public show page; name links to admin show page.

[#7260] Body edit breadcrumbs

---

app/views/admin_public_body/_form.html.erb
app/views/admin_public_body/_locale_fields.html.erb

Cheap improvement to avoid mistakenly typing/pasting invalid URLs when
editing public bodies.
Doesn't validate at the model layer so we may want to add that in
future, but for the main use case the client-side validation is nicer as
it highlights invalid values in red before you even submit the form.:
Also cleans up a few bits of ruby/markup.
Makes publication scheme field the same width as other URLs.
Fixes https://github.com/mysociety/alaveteli/issues/7187.

[#7187] Add client-side validation to body URL fields

---

app/views/admin_raw_email/show.html.erb
app/views/admin_request/_info_request.html.erb

Make it quicker to navigate to public view of bodies from request lists.
BEFORE
AFTER
BEFORE
AFTER

Use `both_links` in more places

---

app/views/admin_general/timeline.html.erb

So that you can hover over and see the full event time.

Wrap timeline event times in time tag

---

app/views/admin_incoming_message/_actions.html.erb

Clean up some of the code around message redelivery.
Mainly a bit of yak-shaving because I thought it would be a good idea to use `input-append` for the button 🙄

Improve message redelivery markup and UI

---

app/assets/stylesheets/admin.scss
app/views/admin_raw_email/_holding_pen.html.erb
app/views/admin_raw_email/_intro.html.erb
app/views/admin_raw_email/show.html.erb

Improve the admin raw email & holding pen views
Just some small quality of life and code cleanup improvements.
Improved raw email page header and breadcrumbs:
Improved holding pen details:
Loads more cleanup to be done, but at least this now extracts the holding pen partial.

Admin raw email view

---

app/views/admin_general/_change_request_summary.html.erb

When looking at a change request in the admin todo list, admins often want to open the body page to look at the version history.
This makes it easier to do so by linking to the body using our conventional `both_links` method.
Fixes https://github.com/mysociety/alaveteli/issues/6902.
BEFORE
AFTER

[#6902] Use both_links for update change requests

---

app/controllers/public_body_controller.rb
config/crontab-example
doc/CHANGES.md
lib/public_body_csv.rb
lib/tasks/public_body.rake
spec/controllers/public_body_controller_spec.rb
spec/fixtures/all-authorities.csv
spec/lib/public_body_csv_spec.rb

Fixes #3983
Update `all-authorities.csv` generation to happen nightly and serve cached file when endpoint is requests.
Request timeouts and blocking processes.
This basically what I had ready to go before https://github.com/mysociety/alaveteli/issues/3983#issuecomment-1241700693

[#3983] Update `all-authorities.csv` generation

---

app/helpers/admin/link_helper.rb
app/views/admin_request/show.html.erb
spec/helpers/admin/link_helper_spec.rb

We have a `both_links` for outgoing and incoming messages so we can use it here for more conventional behaviour.
Adds the benefit of being able to quickly understand the prominence of various messages on a thread.
Mutes the more incidental metadata about the messages.
BEFORE
AFTER
Adds quite a bit of duplication of the request name, but I think it's good to keep `both_links` flexible enough to be used in any context (e.g. a page of its own). Just dropping it down to `#outgoing-123` would make it pretty meaningless to view on e.g. a page of failed-to-send outgoing messages.

Use both_links on message listings

---

app/views/request/_outgoing_correspondence.html.erb

None
This PR fixes a small annoyance for non-English sites whereby the status of outgoing email delivery is not translated.
Before :cry: 
After :grinning: :fr: :croissant: 
As this is a publicly visible item made quite prominent by colours/icons, it's better if it translates.
The template was not actually calling `to_s!` as implemented in `app/models/mail_server_log/delivery_status/translated_constants.rb`. This should fix the problem. There is a possible loophole though, as `humanize` does not seem to correctly adjust accented characters in French, for instance `échoué` should become `Échoué`, but appears to be left untouched.

Translate delivery statuses

---

app/views/request/_hidden_correspondence.text.erb
app/views/request/_incoming_correspondence.text.erb
app/views/request/_outgoing_correspondence.text.erb
app/views/request/show.text.erb

For request downloads ZIP files we sometimes, when `wkhtmltopdf`, isn't available or errors will generate a text version of `request#show`.
This commit fixes the text version rendering by removing leading extra unneeded indentation.
```
This is a plain-text version of the Freedom of Information request "Public request 1".  The latest, full version is available online at http://localhost:3000/request/public_request_1.
From: Paul Pro
To: Ministry of Silly Walks
Date: September 29, 2022
Dear [Authority name],
Public request 1
-------------------------------
This message has been hidden. There are various reasons why we might have done this, sorry we can't be more specific here.
-------------------------------
From:, Ministry of Silly Walks
To: Paul Pro
Date: September 29, 2022
Attachment: …
```

Fix text rendering of requests

---

app/assets/javascripts/admin/admin.js
app/controllers/services_controller.rb
spec/controllers/services_controller_spec.rb

Connected to #6746
1. Adds authenication to the action
2. Changes the action to return JSON
When hiding requests in #6746 we are going to set the `prominence_reason` when hiding requests to save admins manually entering the reason we can return a default reason from this endpoint.

[#6746] Update hidden request explanation action

---

app/controllers/admin_comment_controller.rb
app/controllers/admin_incoming_message_controller.rb
app/controllers/admin_outgoing_message_controller.rb
app/controllers/admin_request_controller.rb
app/controllers/api_controller.rb
app/models/alaveteli_pro/embargo.rb
app/models/comment.rb
app/models/info_request.rb
app/models/outgoing_message.rb
spec/factories/info_requests.rb
spec/mailers/request_mailer_spec.rb
spec/mailers/track_mailer_spec.rb
spec/models/alaveteli_pro/request_summary_spec.rb
spec/models/comment_spec.rb
spec/models/incoming_message_spec.rb
spec/models/info_request_spec.rb
spec/support/shared_examples_for_viewing_requests.rb

Fix:
- Hash style
- Line length
- Indentation
- String quotes
- Sorting params (old before new)
Changes to these calls in #7335 are casuing Rubocop to error and display a ❌ for the Github check.

Minor cleanup for `log_event` calls

---

app/assets/javascripts/alaveteli_pro/stripe.js
app/controllers/alaveteli_pro/subscriptions_controller.rb
spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb

Fixes https://github.com/mysociety/alaveteli-professional/issues/618
Ensure users are active, and not banned, before allowing Stripe subscription sign up.

[pro#618] Check users are active before Pro subscription

---

app/helpers/link_to_helper.rb
app/views/request/_attachments.html.erb
spec/helpers/link_to_helper_spec.rb

Fixes #7358
Add incoming_message_dom_id helper. Delegate to `dom_id` if the incoming message has a main body part. If not then return `nil`.
Some incoming emails don't have main body part and only have attachments parts.

[#7358] Add incoming_message_dom_id helper

---

app/models/info_request/prominence.rb
app/views/admin_public_body/show.html.erb
app/views/admin_request/_prominence_counts.html.erb
app/views/admin_user/show.html.erb
doc/CHANGES.md

Make it easy to quickly see the distribution of prominence states for
requests on body and user admin pages.
The use case for this was wanting to know if a request hidden due to a
data breach was the first for the authority in question or yet another
in a long history of breaches.
We do try to minimise reduced prominence to specific messages or even
attachments after https://github.com/mysociety/alaveteli/issues/1005 [1], so only showing request prominence counts
doesn't tell the whole story, but it's a start.
**Public Body Admin Page**
**User Admin Page**

Add request prominence counts in admin UI

---

app/controllers/request_game_controller.rb
doc/CHANGES.md

We only count searchable requests (i.e. not private or reduced prominence) for the total on the homepage, so mirror that here.

Fix the RequestGame total count

---

app/views/admin_raw_email/show.html.erb

* Don't need the "Raw email" heading as that's at the top of the page.
* Fix quote and hash style.
* Use muted text for incidental UI clarification text.
BEFORE
AFTER

Minor cleanup of download raw email admin UI

---

app/views/admin_incoming_message/_actions.html.erb

Uses a `btn-group` to group raw-email related actions on the associated
incoming message admin page. This saves some page length.
BEFORE
AFTER

Clean up incoming message raw email actions

---

app/assets/javascripts/admin/admin.js
app/assets/stylesheets/admin.scss
app/controllers/admin_request_controller.rb
app/controllers/services_controller.rb
app/helpers/prominence_helper.rb
app/models/concerns/admin_column.rb
app/models/info_request.rb
app/views/admin_request/edit.html.erb
app/views/admin_request/hidden_user_explanation.text.erb
app/views/admin_request/show.html.erb
db/migrate/20220928093559_add_prominence_reason_to_info_request.rb
spec/factories/info_requests.rb
spec/fixtures/info_requests.yml
spec/helpers/prominence_helper_spec.rb
spec/models/info_request_spec.rb
spec/views/admin_request/hidden_user_explanation.text.erb_spec.rb

Fixes #6746
Adds prominence reason to `InfoRequest`
Easier to recall why the prominence has been set the way it has. Good for historical cases.

[#6746] Add InfoRequest prominence reason

---

app/views/admin_user/show.html.erb

Fixes #7376
Truncate `PostRedirect#email_token` so the admin UI doesn't overflow.

[#7376] Fix overflow in admin UI

---

app/models/mail_server_log/delivery_status.rb
app/views/outgoing_messages/delivery_statuses/show.html.erb
app/views/request/_outgoing_correspondence.html.erb
spec/models/mail_server_log/delivery_status_spec.rb

Only called in two places and is clearer to just use `#to_s` or `#to_sym` as appropriate.
Noticed on reviewing https://github.com/mysociety/alaveteli/pull/7325.

Remove `DeliveryStatus#simple`

---

app/controllers/public_tokens_controller.rb
app/models/ability.rb
spec/models/ability_spec.rb

Extracted from #7327 
Adds `Ability.guest` helper
This is better than calling `Ability.new(nil)`

Add guest ability helper

---

app/models/public_body.rb
spec/models/public_body_spec.rb

If an authority is defunct we don't want suggestions for a request email.
Fixes https://github.com/mysociety/alaveteli/issues/7372.

[#7372] Don't tag defunct bodies with missing email tag

---

spec/fixtures/users.yml

A user for responding to requests as an FOI Officer. The user doesn't really have any special capability due to all fixture users having an `@localhost` email address, but useful for development to have a distinct user for making replies.

Add Ollie Officer fixture user

---

app/controllers/alaveteli_pro/classifications_controller.rb
spec/controllers/alaveteli_pro/classifications_controller_spec.rb

Fixes #7370
Update Pro classification controller auth
Former pro users still need to be able to update their request statuses.
This change removes the `before_action` callback to authenticate the pro users. This means all requesters can use this endpoint to classify their request but in reality only current and former Pro users will as this is only linked to from the Pro UI.

[#7370] Update Pro classification controller auth

---

app/models/ability.rb
spec/controllers/outgoing_messages/delivery_statuses_controller_spec.rb
spec/models/ability_spec.rb

Useful for #7391 
Use `CanCanCan` subject (with scope [1]) and condition [2] DSL to improve the ability definitions around prominence for requests and messages.
[1]: https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_abilities_with_blocks.md#block-conditions-with-activerecord-scopes
[2]: https://github.com/CanCanCommunity/cancancan/blob/develop/docs/hash_of_conditions.md
Replaces big nested case statements within `can_view_with_prominence?` making it easier to make changes and to add other resources with prominence.

Refactor prominence abilities

---

app/controllers/admin/foi_attachments_controller.rb
app/controllers/attachments_controller.rb
app/controllers/request_controller.rb
app/helpers/prominence_helper.rb
app/models/ability.rb
app/models/foi_attachment/prominence.rb
app/models/incoming_message.rb
app/models/info_request_event.rb
app/views/admin/foi_attachments/edit.html.erb
app/views/request/_attachments.html.erb
app/views/request/_incoming_correspondence.text.erb
app/views/request/hidden_attachment.html.erb
spec/controllers/admin/foi_attachments_controller_spec.rb
spec/controllers/attachments_controller_spec.rb
spec/integration/alaveteli_prominence_dsl.rb
spec/integration/prominence/viewing_attachment_as_html_spec.rb
spec/integration/prominence/viewing_raw_attachment_spec.rb
spec/integration/prominence/viewing_request_page_spec.rb
spec/models/ability_spec.rb
spec/models/incoming_message_spec.rb

Supersedes #7327 
Fixes #1005
Allows admins to edit attachment prominence and reason.
Add prominence checks for attachments when:
- viewing requests/messages
- viewing attachments
- ZIP downloads
- Xapian indexing
Easier admin of responses and attachments.

[#1005] Hide individual attachments

---

app/controllers/outgoing_messages/delivery_statuses_controller.rb
app/models/ability.rb

Connected to #1005
1. Removes CanCanCan Ability scopes
2. Fixes exception rendering delivery statues

[#1005] Hide individual attachment fixes 

---

app/models/outgoing_message.rb
app/views/admin_outgoing_message/_admin_columns.html.erb
app/views/admin_outgoing_message/edit.html.erb
app/views/admin_request/show.html.erb

Add basic admin columns for OutgoingMessages
Makes it easier to look at the record in its entirety rather than
skipping back and forth between the request page and folding accordions.
An OutgoingMessage is essentially an Email, so it's useful to see the
To, From and Subject "headers" that got applied. These are dynamic so
_could_ end up being different to what was actually sent at the time,
but rarely change so this should be good enough until we cache these
values.
Added after wanting this while trying to diagnose a delivery issue on AskTheEU.

Add OutgoingMessages admin columns

---

app/views/admin_incoming_message/_admin_columns.html.erb
app/views/admin_incoming_message/edit.html.erb
app/views/admin_request/show.html.erb

Did https://github.com/mysociety/alaveteli/pull/7390, so might as well do the counterpart here.
* Extract incoming message actions from table
* Render admin columns on incoming message admin page
* Other minor cleanup
Admin columns now on incoming message edit page.
Actions now in a well rather than in the table header.

Add IncomingMessage admin columns

---

app/helpers/prominence_helper.rb
app/views/request/_attachments.html.erb
app/views/request/_attention_requested.html.erb
app/views/request/_hidden_request_messages.html.erb
app/views/request/_prominence.html.erb
spec/helpers/prominence_helper_spec.rb

Sometimes `IncomingMessage#get_main_body_text_part` does not have a main
body text part and returns `nil`, but we pass that to
`conceled_prominence?` when checking whether to render the prominence
message.
This commit fixes by using the safe navigation operator so that passing
`nil` is safe.
Also tweaks some code style issues:
* Use square brackets for a word array – they're more conceptually
similar to an Array ([]) and we don't use braces elsewhere for these.
* Pass a `prominenceable` to `conceled_prominence` so that the specs are
clearer that the value doesn't need to be an `InfoRequest`. This makes
it clearer to pass `nil` for the spec for the case that this commit is
testing against.
Also fixes spelling of ProminenceHelper#concealed_prominence?
Fixes …

[#7423] Fix `ProminenceHelper#concealed_prominence?` with `nil` argument

---

app/models/foi_attachment.rb
app/views/admin_incoming_message/_foi_attachments.html.erb
spec/models/foi_attachment_spec.rb

Make it clear which attachment is the main body part when viewing lists of attachments associated with an incoming message.
A part of https://github.com/mysociety/alaveteli/issues/7416.

[#7416] Label the main body attachment

---

app/views/admin_user/_post_redirects.html.erb
app/views/admin_user/show.html.erb

More consistency with other admin lists, and helps when printing a User admin page to PDF for SAR disclosures.
Also cleans up the table and extracts to partial.
Helps with https://github.com/mysociety/alaveteli/issues/6917.
**NO POST REDIRECTS**
**SOME POST REDIRECTS**

Add "None yet" to PostRedirect listings

---

app/views/admin/tags/index.html.erb
app/views/admin/tags/show.html.erb
app/views/admin/users/sign_ins/index.html.erb
app/views/admin_announcements/index.html.erb
app/views/admin_comment/index.html.erb
app/views/admin_general/timeline.html.erb
app/views/admin_public_body/index.html.erb
app/views/admin_request/_some_requests.html.erb
app/views/admin_track/index.html.erb
app/views/admin_user/_user_table.html.erb

More consistency with other admin lists, and helps when printing a User
admin page to PDF for SAR disclosures.
Helps with https://github.com/mysociety/alaveteli/issues/6917.
**No requests:**
**Some requests:**
Per-page limit temporarily set to 2 for the purposes of the screenshot:
```diff
diff --git a/app/controllers/admin_user_controller.rb b/app/controllers/admin_user_controller.rb
index 5d6df278a..c824da8cd 100644
--- a/app/controllers/admin_user_controller.rb
+++ b/app/controllers/admin_user_controller.rb
@@ -54,7 +54,7 @@ def show
@comments = @admin_user.comments.not_embargoed
end
@info_requests = @info_requests.paginate(:page => params[:page],
-                                             :per_page => 100)
+                                             :per_page => 2)
end
def edit …
```

[#6917] Add "None yet" to request listings

---

app/views/admin_user/_user_table.html.erb

To check whether a user is a spammer, admins have to open the user page, review the text, ban the user (if spam), then go back to the results list to look at the next one.
Having "About me" in the results list means the admin doesn't need to leave the list, as we already have the "Ban" button in the unfolded accordion.
Fixes https://github.com/mysociety/alaveteli/issues/5599

[#5599] Render User#about_me in the admin list of users

---

app/models/incoming_message.rb
app/models/raw_email.rb
spec/models/incoming_message_spec.rb
spec/models/raw_email_spec.rb

A bit of cleanup while looking at https://github.com/mysociety/alaveteli/issues/2686.
* Move destroying raw email file
* Make RawEmail#destroy_file_representation! private
In 812a1e8 I've just moved the `#destroy_file_representation!` spec to the bottom of the file, used `#send` to call the method, and added the `TODO`.

Refactor destruction of raw email file representation

---

app/models/info_request_event.rb
app/models/refusal_advice.rb
app/views/admin_comment/edit.html.erb
app/views/admin_general/timeline.html.erb
app/views/admin_request/show.html.erb
db/migrate/20220408125559_add_jsonb_column_to_info_request_events.rb
doc/CHANGES.md
lib/tasks/temp.rake
spec/controllers/admin_incoming_message_controller_spec.rb
spec/controllers/admin_outgoing_message_controller_spec.rb
spec/controllers/admin_raw_email_controller_spec.rb
spec/controllers/alaveteli_pro/classifications_controller_spec.rb
spec/controllers/api_controller_spec.rb
spec/controllers/classifications_controller_spec.rb
spec/controllers/projects/classifications_controller_spec.rb
spec/controllers/reports_controller_spec.rb
spec/factories/info_request_events.rb
spec/fixtures/info_request_events.yml
spec/integration/admin_outgoing_message_edit_spec.rb
spec/integration/classify_request_spec.rb
spec/models/alaveteli_pro/embargo_spec.rb
spec/models/comment_spec.rb
spec/models/info_request_event_spec.rb
spec/models/info_request_spec.rb

Fixes #5485
See #6949 
1. Adds a `InfoRequestEvent#param` JSONB column - this will replace the `#params_yaml` column.
2. Updates event param assignment to better handle model object instances and model object IDs so both get stored as an global ID, EG: `user: { gid: 'gid://alaveteli/User/1' }`
3. Adds rake task to sanitise and populate the new JSONB column from the old YAML column.
YAML column could contain full ruby objects which we shouldn't be storing - [CVE-2022-32224](https://github.com/advisories/GHSA-3hhc-qp5v-9p2j). The latest Ruby patch release has fixed this by limiting the permitted classes which could be decoded. We don't need to store any objects really, in fact we shouldn't as this has the potential to cause issues for GDPR requests as user information could be stored.
Also …

[#5485] Add `InfoRequestEvent#param` JSONB column

---

doc/CHANGES.md
lib/tasks/users.rake
lib/user_stats.rb
spec/lib/user_stats_spec.rb

Using this for possible input into some outreach planning, and a CSV is easier to work with.

Use CSV output and ignore case for `users:count_per_domain` stats

---

app/assets/stylesheets/responsive/_notes_layout.scss

Not much to say about word-break; it's pretty standard [1].
Fixes https://github.com/mysociety/alaveteli/issues/7453.
[1] https://css-tricks.com/almanac/properties/w/word-break/
**BEFORE**
**AFTER**

[#7453] Prevent long URLs escaping notes container

---

Gemfile
Gemfile.lock
Gemfile.rails_next.lock
doc/CHANGES.md
lib/tasks/temp.rake

Fixes #7470
[Add rake task to convert legacy YAML](https://github.com/mysociety/alaveteli/commit/28991ccd9fd16932977e22fb7efb50b6ef196f54)
In WDTK we have YAML stored which was generate by the old `Syck` library
which can't be parsed by the newer `Psych` library.
This rake task fixes the YAML so it can be parsed.

[#7470] Add rake task to convert legacy YAML

---

app/helpers/info_request_helper.rb
spec/helpers/info_request_helper_spec.rb

The bracketed content can cause the request author to react negatively to the report and generate support mail. Being a bit more matter-of-fact might reduce this.
**BEFORE**
**AFTER**

Tweak phrasing of admin attention status

---

config/initializers/health_checks.rb

Update Xapian queue health check
Increase period to match the Xapian update job default timeout. So in theory this should result in less warnings as the timeout will end jobs allowing the queue to continue being processed.
Sometimes the timeout doesn't work and the health check will still alert for an issue, just 30 minutes later than normal.

Update Xapian queue health check

---

app/views/admin_general/_status_update.html.erb

Due to changes in the event params storage there isn't a `user_id` key anymore and we can just fetch the user object.

Update timeline status update events

---

app/views/request_mailer/new_response_reminder_alert.text.erb
app/views/request_mailer/old_unclassified_updated.text.erb
app/views/request_mailer/overdue_alert.text.erb
app/views/request_mailer/stopped_responses.text.erb
app/views/request_mailer/very_overdue_alert.text.erb
spec/views/request_mailer/new_response_reminder_alert.text.erb_spec.rb
spec/views/request_mailer/old_unclassified_updated.text.erb_spec.rb
spec/views/request_mailer/overdue_alert.text.erb_spec.rb
spec/views/request_mailer/stopped_responses.text.erb_spec.rb
spec/views/request_mailer/very_overdue_alert.text.erb_spec.rb

We had some user feedback [1] that interpolating the request title into some phrases could be quite confusing because it wasn't obvious where the request title started and ended, and how it fits in to what we're trying to communicate.
[1] https://twitter.com/MrDanack/status/1578072110739722243
Might be worth writing a script to update the translation strings here, as this creates some extra work for translators which isn't totally necessary.

Quote request title in notification emails

---

app/views/general/_frontpage_extra.html.erb
app/views/general/frontpage.html.erb

Adds a blank, overrideable template to add theme content below the body and request lists.
Doesn't render anything by default:
Adding a theme override:
```diff
diff --git a/lib/views/general/_frontpage_extra.html.erb b/lib/views/general/_frontpage_extra.html.erb
new file mode 100644
index 0000000..28bf6d1
--- /dev/null
+++ b/lib/views/general/_frontpage_extra.html.erb
@@ -0,0 +1 @@
+<h1>Foo!</h1>
```

Frontpage extra override

---

doc/CHANGES.md
lib/alaveteli_text_masker.rb

Update text masking to use tempfiles for PDF attachments when running `pdftk` external commands
Large PDFs attachments, with lots of images are sometimes received.
These will normally will be compressed and expand to much larger files
size. This can cause memory issues due to how we are passing the data
around the application to external commands such as `pdftk`.
Passing this data via STDIN to `pdftk` to seems to be the main issue
here where we are seeing uncompressed PDFs over 900Mb not able to be
re-compressed despite leaving the process running for over 1 hour.
This change switches to use tempfiles when uncompressing or compressing
PDF attachments which, in testing on my development and WDTK production
environment, allows the whole `apply_masks` process which includes
uncompressing and …

Update text masking for PDF attachments

---

.github/workflows/ci.yml
README.md
doc/CHANGES.md
script/handle-mail-replies
script/load-mail-server-logs
script/mailin

Fixes #7497
Add support for Ruby 3.2 
Framework modernisation

[#7497] Add support for Ruby 3.2

---

app/assets/stylesheets/responsive/_new_request_style.scss
app/views/request/new.html.erb

Fixes https://github.com/mysociety/whatdotheyknow-theme/issues/1411
Removed #request_header_text container as the inner note container contains all the layout/styling we need.

[wdtk#1411] Fix rendering of notes on request#new view

---

app/models/raw_email.rb
spec/models/raw_email_spec.rb

Fixes #7530
Remove the `RawEmail` before destroy callback and spec.
This spec was causing CI failures - 4 in the last couple of days. In fact the spec was testing the old implementation. The whole callback now isn't needed as this is automatically done by `ActiveStorage`.

[#7530] Remove RawEmail before destroy callback and spec

---

spec/controllers/public_body_controller_spec.rb

Remove old `should` syntax and replace with the newer `expect` syntax.
Added in #7301

Fix deprecation warning when running spec suite

---

app/models/public_body.rb
db/migrate/096_create_translation_tables.rb
db/migrate/20220902112339_remove_public_body_notes.rb
lib/tasks/temp.rake
spec/controllers/general_controller_spec.rb
spec/controllers/public_body_controller_spec.rb
spec/factories/public_bodies.rb
spec/fixtures/note_translations.yml
spec/fixtures/notes.yml
spec/fixtures/public_bodies.yml
spec/fixtures/public_body_translations.yml
spec/lib/public_body_csv_spec.rb
spec/models/public_body_spec.rb
spec/spec_helper.rb
spec/views/alaveteli_pro/public_bodies/_search_result.html.erb_spec.rb

Requires https://github.com/mysociety/alaveteli/issues/6647
Fixes #7254
Remove `PublicBody#notes`
This has been replace by a separate Note model.
Had wanted to use Factories over Fixtures for notes but too many specs needed updates and this wasn't really the right time to switch.
It seems the searching of public bodies by their note content on `/body/list/all` isn't working which is why a spec has been disabled. Will open an issue to restore this functionality.

[#7254] Remove PublicBody#notes

---

docker-compose.yml
docker/Dockerfile
docker/env
docker/reset
docker/server
docker/setup

Allow docker/compose to specify which Ruby version will be used
With #7496 we should allow users to specify with version of Ruby they want to run. Defaults `3.0` - the minimal supported version. 
Use the `RUBY_VERSION` environment variable or a `ruby-version` file in the root directory to specify which version of Ruby should be used in the docker development environment.
After changing the environment variable or the `.ruby-version` file you'll need to rebuild the docker image by running: `docker/reset`

Allow docker/compose to specify which Ruby version will be used

---

app/models/public_body.rb
db/migrate/20230209094128_remove_public_body_version_notes.rb
spec/factories/public_bodies.rb
spec/fixtures/public_bodies.yml
spec/fixtures/public_body_versions.yml
spec/models/public_body_spec.rb

Connected to #7269 
Remove PublicBody::Version#notes column
This column has already been removed on `PublicBody` and replaced with a separate `Note` model.

Remove PublicBody::Version#notes column

---

app/mailers/outgoing_mailer.rb
app/models/foi_attachment.rb
app/models/mail_server_log/delivery_status.rb
app/models/mail_server_log/exim_line.rb
app/models/mail_server_log/postfix_line.rb
lib/acts_as_xapian/acts_as_xapian.rb
spec/controllers/attachments_controller_spec.rb
spec/models/mail_server_log/delivery_status_spec.rb
spec/models/mail_server_log/exim_line_spec.rb
spec/models/mail_server_log/postfix_line_spec.rb
spec/support/email_helpers.rb

N/A
Fulfils the requirements for the FormatString cop ([which links to the Style Guide, here](https://rubystyle.guide/#sprintf))
Helps keep the codebase up to date with ideal Ruby style
I used the automated fix for all bar `acts_as_xapian.rb` (where it wasn't available), and ran the tests to ensure none had stopped passing.

Rubocop refactor formatstring

---

script/rails-deploy-before-down

GitHub Actions doesn't run `script/rails-post-deploy` so this is unneeded.

Remove unused CI conditionals

---

config/httpd.conf-example

Update Phusion Passenger config for latest version or Passenger/Apache.
Couldn't run Passenger without these changes
As far as I can see don't need to replace `PassengerResolveSymlinksInDocumentRoot` with anything.

Update Phusion Passenger config

---

script/install-as-user

Remove configuration of Ruby 2.7 option on install
Not needed now we've dropped support for Ruby 2.7.

Remove configuration of Ruby 2.7 option on install

---

script/rails-deploy-before-down

Fixes #6417
Fix bundler deprecation warnings
Also ensures when switch from a production to development install that the correct gems are installed by unsetting the `deployment` and `without` options.

[#6417] Fix bundler deprecation warnings

---

app/models/info_request.rb
spec/models/info_request_spec.rb

Want to use these values in help pages so that configuration changes do not go out of sync with explanatory text.

Extract old request magic variables

---

app/views/admin_public_body/_public_body.html.erb

It's now convention to use `both_links` when displaying admin records, so update this partial to use it. We can now quickly get to the public page from the admin bodies index.
The partial is also used when rendering tagged bodies:

Use both_links for admin bodies index

---

app/models/info_request_event.rb
spec/models/info_request_event_spec.rb

Dynamically add a scope per event type to make querying the model easier.
Just an improvement over add `where(event_type: 'foo')` everywhere that I spotted could be made when doing https://github.com/mysociety/whatdotheyknow-theme/issues/1495.
The specs check the generated SQL because setting message expectations didn't work. For example:
before { expect(described_class).to receive(:where) }
it { described_class.public_send(event_type) }
In this example I was expecting the `where` to be called, but it never got called. Perhaps Rails is doing something different with scopes? I tried adding a `#to_a` call to the example to force the query to actually run, but nope.
I think asserting that the generated SQL gives us enough confidence for what this is doing, so went with that.
Wonder whether …

Add InfoRequestEvent#event_type scopes

---

app/controllers/users/messages_controller.rb
app/models/user.rb
app/views/users/messages/rate_limited.html.erb
spec/controllers/users/messages_controller_spec.rb
spec/models/user_spec.rb

Adds basic no-op rate limiting mechanics.
Requires `User#exceeded_user_message_limit?` to be overridden at theme level.

User to user message rate limit

---

app/helpers/admin/link_helper.rb

Adds a little more visibility of what a comment contains. Makes it less likely you need to click in to _every_ comment to find an issue.
The default value is 30.
BEFORE
AFTER

Increase comment both_links truncate length

---

app/controllers/users/messages_controller.rb
app/models/user.rb
app/views/users/messages/opted_out.html.erb
db/migrate/20230223145243_add_receive_user_messages_to_user.rb
spec/controllers/users/messages_controller_spec.rb
spec/factories/users.rb
spec/fixtures/users.yml
spec/models/user_spec.rb

Adds initial handling of opting out of the user messaging system. All users are opted in by default, as they are prior to this commit, but now developers can at least switch this flag on request.
A basic version of https://github.com/mysociety/alaveteli/issues/1971.

[#1971] Add basic user message opt out

---

app/assets/stylesheets/responsive/_new_request_layout.scss
app/assets/stylesheets/responsive/_new_request_style.scss
app/assets/stylesheets/responsive/_request_style.scss
app/assets/stylesheets/responsive/alaveteli_pro/_new_request_layout.scss
app/assets/stylesheets/responsive/alaveteli_pro/_new_request_style.scss
app/views/alaveteli_pro/info_request_batches/_message_preview.html.erb
app/views/alaveteli_pro/info_requests/_message_preview.html.erb
app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb
app/views/alaveteli_pro/info_requests/new.html.erb
app/views/request/new.html.erb
app/views/request/preview.html.erb
doc/CHANGES.md

Fixes #6154
Attempts to make it clearer that the user name is sent to authorities and published alongside the request.
1. Adds a `From` field to the request header
2. Reorganises the sidebar advice and highlights the bit about it being public
Try to reduce support cases where the user is surprised at the above.
All the code here was a bit of a mess. I've fixed the styling of the request header across regular and pro. Some of it is a bit hacky, but better than before.
Making a request before signing in
Making a request when signed in
Making a single pro request
(Preview stage same as above)
Making a batch pro request
(Preview stage same as above)
Reorganised sidebar advice (not signed in)
Sidebar advice showing user name when signed in

[#6154] Make it clearer usernames are published

---

docker/Dockerfile

Fixes #7612
Add git safe directory config to Docker image
When running the app via Docker errors are being raised due to how the repository is mounted in the container which results in a mismatch in file ownership.

[#7612] Add git safe directory config to Docker image

---

app/models/project/info_request_extension.rb
spec/controllers/projects/extracts_controller_spec.rb
spec/models/project_spec.rb

Fixes #7618
Fix project request scopes
Check the project submissions belong to the current project when calling `Project#extractable` or `Project#extracted`.
This fixes an issue where requests which have been added to more than one project appears to be extracted due to being processed in the other project.

[#7618] Fix project request scopes

---

app/controllers/followups_controller.rb
doc/CHANGES.md
spec/controllers/followups_controller_spec.rb

Ex-pro users should still be able to manage requests even if they're still private; they just can't extend privacy periods or create new ones.
We don't need to check that the `current_user` is a Pro here; we first search the user's requests, irrespective of privacy state, and assign to the instance variable. If that isn't found – which means the user is trying to follow up to someone else's request – we only search public requests in order to display the notice to sign in to the request author's account.
Fixes https://github.com/mysociety/alaveteli/issues/7456.

[#7456] Allow ex-pro users to followup to private requests

---

app/models/user.rb
app/models/user_message.rb
db/migrate/20230301110831_add_user_messages_count_to_users.rb
spec/factories/users.rb
spec/fixtures/users.yml
spec/models/user_spec.rb

Gives us a quick way of seeing if a user has sent any user messages.
* Add User#user_messages counter cache
* Show User#user_messages_count in the Admin UI
Need to run the following on deployment to prime our counter caches:
```ruby
UserMessage.find_each { |msg| User.reset_counters(msg.user.id, :user_messages) }
```
Don't need to worry about re-users as they won't have been recording user messages before the addition of the counter cache.

Show user messages count in admin UI

---

script/rails-deploy-before-down

When re/running the installer:
1. update `RAILS_ENV` file based on the `STAGING_SITE` configuration
2. don't nuke customised settings in `config/rails_env.rb`.
When switching to Puma #7581 there are other ENV variables which might need to be customised in  `config/rails_env.rb`, such as:
- `RAILS_MAX_THREADS`
- `RAILS_MIN_THREADS`
- `WEB_CONCURRENCY`
- `PORT`
The `config/rails_env.rb` file seems the correct place for over `config/general.yml` as we don't really need to expose these settings for a majority of re-users.
Without these changes we risk accidental removing these when the installer is re-run.

Update setting RAILS_ENV in install scripts

---

script/site-specific-install.sh

Spun out of https://github.com/mysociety/alaveteli/pull/7584#pullrequestreview-1299692221
Add STAGING_SITE and DEVELOPMENT_INSTALL check
If these values aren't compatible with each other then error, ask the user to make a change and exit early.

Add STAGING_SITE and DEVELOPMENT_INSTALL check

---

script/install-as-user

Fixes #7583
Set `STAGING_SITE` when generating initial config
We need this configuration value in `script/rails-deploy-before-down` to correctly set `RAILS_ENV` to `production` when not doing a development install.

Set STAGING_SITE when generating initial config

---

app/controllers/comment_controller.rb
app/models/comment.rb
app/models/user.rb
app/views/comment/rate_limited.html.erb
doc/CHANGES.md
spec/controllers/comment_controller_spec.rb
spec/models/comment_spec.rb
spec/models/user_spec.rb

Allow admins to always be able to create comments.
Add comment creation interval rate limit.
Calculates whether too many comments are being created too quickly.
We don't want to allow a user to sign up and smash through their daily
limit in 5 minutes, then create a new account to do the same, and so on.
This ensures that the allocation is used sensibly. It hopefully won't
affect the majority of genuine users.
Uses the existing rate limiting mechanism for the daily cap, with an extra line on the rendered page to account for this addition.

Add comment creation interval rate limit

---

app/models/project/info_request_extension.rb
spec/models/project_spec.rb

Fixes #7631
Fix Project request extractable scope
Requests were being returned in this scope when they has already been extracted. This was due to the query matching the extract submission for different project.
Moving the project conditional from the `WHERE NOT` into the `LEFT JOIN` limits the submission objects we're inspecting to the current project.

[#7631] Fix Project request extractable scope

---

app/controllers/projects/leaderboards_controller.rb
app/controllers/projects/projects_controller.rb
app/models/project/leaderboard.rb
app/views/projects/projects/show.html.erb
config/routes.rb
spec/controllers/projects/leaderboards_controller_spec.rb
spec/models/project/leaderboard_spec.rb

Fixes #7542 
This adds leaderboards to the Project page. If the user is authorised to download the project data, they also have the option to download the leaderboard.
To allow users who use projects to manage leaderboard data on their own.
N/A
This may require a modification to the styling of the buttons.

Project leaderboards

---

app/models/user.rb
app/views/users/messages/rate_limited.html.erb
doc/CHANGES.md
spec/models/user_spec.rb

Follows the same pattern as comments.
Set the default to the configured max requests per day for now – can implement more fine-grained limits in future if necessary.

Add daily limit to user message creation

---

app/controllers/admin_user_controller.rb
app/models/info_request_batch.rb
app/views/admin/info_request_batches/_info_request_batch.html.erb
app/views/admin/info_request_batches/_list.html.erb
app/views/admin_user/show.html.erb
doc/CHANGES.md
spec/models/info_request_batch_spec.rb
spec/views/admin_user/show.html.erb_spec.rb

Make it easier to see distinct batches when viewing a user record.
Currently you have to open up requests to get to the batch record, and
there's always the possibility that the user has created to batches with
identical titles – maybe after missing some authorities from the initial
list.
Fixes some minor code style issues and adds `InfoRequestBatch.not_embargoed` scope.
The batches are not yet sent – "Sent at" is not yet populated.
The batches get sent, and now "Sent at" is populated
Viewing the user's page as Joe Admin, who doesn't have `pro_admin` role:

Add list of batch requests to admin user page

---

app/models/profile_photo.rb
app/models/user.rb
app/views/admin_user/edit.html.erb
spec/factories/profile_photos.rb
spec/factories/users.rb
spec/models/user_spec.rb

Add some task-specific methods for better composability and future ability to add a UI button for each action to give us more control over how we handle various user requests.
A precursor to:
* https://github.com/mysociety/alaveteli/issues/285
* https://github.com/mysociety/alaveteli/issues/5052
* https://github.com/mysociety/alaveteli/issues/4922
* https://github.com/mysociety/alaveteli/issues/4910

Close; Anonymise; Erase

---

app/models/info_request.rb
app/models/info_request/batch_pagination.rb
app/views/alaveteli_pro/info_requests/_batch.html.erb
app/views/info_request_batch/_pagination.html.erb
app/views/request/_batch.html.erb
doc/CHANGES.md
spec/models/info_request/batch_pagination.rb
spec/models/info_request_spec.rb

Add "Next" and "Prev" pagination links to the sidebar of info requests that belong to a batch request.
This allows users to navigate through requests in the batch without having to click "in and out" via the batch page.
To minimise implementation complexity the pagination doesn't have a beginning and end. We just cycle back around to the first request in the batch when we hit the last one; same for paginating in reverse. If we didn't do this we'd have to have conditionals for disabling the particular navigation option when we hit an end.

Add ability to paginate through batch requests

---

app/models/blog.rb
app/models/blog/post.rb
app/views/general/blog.html.erb
db/migrate/20230314171033_create_blog_posts.rb
spec/factories/blog/posts.rb
spec/models/blog/post_spec.rb
spec/models/blog_spec.rb
spec/views/general/blog.html.erb_spec.rb

Connected to #6589 
Requires #7632
Adds blog post model for storing posts in the database
Can't import tags from the WordPress blog feed so we're going to add an admin UI and make the posts taggable.

[#6589] Adds blog post model

---

spec/models/blog_spec.rb

Broke in #7642 
Fix transient spec failure. Add known initial `Blog::Post#title` value. 
This fixes some CI failures due to order the specs run.

Fix transient spec failure

---

app/controllers/admin/blog_posts_controller.rb
app/helpers/admin/link_helper.rb
app/models/blog/post.rb
app/views/admin/blog_posts/_blog_post.html.erb
app/views/admin/blog_posts/_form.html.erb
app/views/admin/blog_posts/_intro.html.erb
app/views/admin/blog_posts/edit.html.erb
app/views/admin/blog_posts/index.html.erb
app/views/admin/tags/_tagging.html.erb
app/views/admin_general/_admin_navbar.html.erb
config/routes.rb
spec/controllers/admin/blog_posts_controller_spec.rb
spec/helpers/admin/link_helper_spec.rb
spec/models/blog/post_spec.rb

Connected to #6589
Requires #7642
Add blog admin UI
To add tags to blog posts by making then taggable.

[#6589] Add blog admin UI

---

db/migrate/20220902112339_remove_public_body_notes.rb
db/migrate/20230127132719_remove_info_request_event_params_yaml.rb

Connected to #6949 
Add checks before removing old notes or params_yaml columns.
If a re-user skips 0.42.0.0 upgrade notes then they could lose data. Add a check to ensure we prevent this.
```
> rails db:migrate
snip
== 20220902112339 RemovePublicBodyNotes: migrating ============================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:
We can't run the RemovePublicBodyNotes database migration.
We have dectected PublicBody::Translation objects which haven't been
migrated to the new Note model.
Please deploy Alaveteli 0.42.0.0 and run the upgrade tasks:
https://github.com/mysociety/alaveteli/blob/0.42.0.0/doc/CHANGES.md#upgrade-notes
./alaveteli/db/migrate/20220902112339_remove_public_body_notes.rb:4:in `up'
```
```
> rails db:migrate
snip …
```

Add checks before removing old notes or params_yaml columns

---

config/environments/development.rb
docker-compose.yml
docker/Dockerfile
docker/entrypoint.sh

Add MailHog Docker container
Replace MailCatcher gem as it isn't compatible with Ruby 3.2 yet. Uses a separate container instead of running multiple processes in the app container.
Maps the web UI port to the same used by MailCatcher.

Add MailHog Docker container

---

app/assets/stylesheets/responsive/_lists_style.scss
app/helpers/taggable_helper.rb
app/views/public_body/_body_listing_single.html.erb
doc/CHANGES.md
spec/helpers/taggable_helper_spec.rb

The small "Defunct" label at the bottom of the authority listing is easily missable. This adds all tags as CSS classes to hook off, and applies styling to the case where an authority is defunct to make it clearer that it's "gone".
Not a "fix", but mitigates:
* https://github.com/mysociety/alaveteli/issues/721
* https://github.com/mysociety/alaveteli/issues/7107
* https://github.com/mysociety/alaveteli/issues/7651
In search results:
In listings:
With theme applied:

Reduce prominence of defunct bodies in lists

---

spec/controllers/request_controller_spec.rb
spec/views/request/_after_actions.html.erb_spec.rb
spec/views/request/show.html.erb_spec.rb

Needed for #7674 
Update integration specs
These specs are either outdated with our current implementation or just broken but the errors are hidden due to an issue upstream in Capybara.
Depending on the block notation used Capybara will return different results:
```
expect(page).to have_selector("input") { false }
expect(page).to have_selector("input") do
false
end
```
This has been fixed in Capybara v3.39.0
See: https://github.com/teamcapybara/capybara/issues/2616

Update integration specs

---

app/views/admin_general/_edit_comment.html.erb

Fixes #7682
Fix admin timeline edit comment events
When an comment is edited the admin timeline breaks. This is due to changes in how the event params are stored in #7173.
We should now use `event.comment` which loads the correct `Comment` from the database without needing the manually load from the view.

[#7682] Fix admin timeline edit comment events

---

app/views/alaveteli_pro/plans/_pricing_tiers.html.erb

Started to cause some confusion for WhatDoTheyKnow users wondering if their plan will change price after a period of months. Makes less sense to include this in Alaveteli core now; we have a variety of installs running Pro, some quite new but some quite established.

Remove "Introductory Pricing" phrase

---

app/views/admin_general/stats.html.erb

Makes some stats easier to read.
Fixes https://github.com/mysociety/alaveteli/issues/7663.
Also includes some minor code cleanup:
* Quote style
* ERB tag padding
* Line spacing
Hacked the controller to render some delimited values for the hero unit. Too much faff to do the same for the state of requests/tracks, but it's a built in rails helper so not much surprising happening here.

[#7663] Use number_with_delimiter for admin stats

---

app/views/admin/blog_posts/_about.html.erb
app/views/admin/blog_posts/index.html.erb

Addition to https://github.com/mysociety/alaveteli/issues/6589
Add some basic documentation so that admins know they can match blog posts to related content via tags.

[#6589] Add inline documentation for blog posts

---

app/assets/javascripts/admin.js
app/assets/javascripts/admin/censor-rules.js
app/views/admin_censor_rule/_form.html.erb

Fixes #4625 
This change introduces a new JavaScript file, censor-rules.js, to handle the functionality for the admin censor rules section. Specifically, it adds a "Use previous comment" feature to the form for editing censor rules. 
The purpose of this change is to streamline the editing process for admin users. By providing a "Use previous comment" option, admins can easily reuse the last edit comment as the reason for the current update, saving time and effort when making similar or related changes to censor rules.
This PR consists of the following changes:
- Including the new censor-rules.js file in admin.js to make it available for use in the admin section of js files.
- Creating the censor-rules.js file, where a click event listener is added to the "Use previous comment" link. When …

Add previous comment feature in censor rule edit form

---

.tx/config

The old transifex client [1] has been replaced by a new CLI [2]. There are some configuration changes required to make the new interface work.
[1] https://github.com/transifex/transifex-client
[2] https://github.com/transifex/cli

Update transifex config

---

script/site-specific-install.sh

Update default Ruby check
Allow the preferred version to be specified in `.ruby-verison` file rather then the example file.
This will allow re-users to upgrade to a later version of Ruby without changing a core file and possibly causing Git warnings: `cannot pull with rebase: You have unstaged changes`

Update default Ruby check

---

spec/controllers/statistics_controller_spec.rb
spec/fixtures/info_requests.yml
spec/fixtures/public_bodies.yml
spec/fixtures/users.yml
spec/models/public_body_spec.rb

Update counter caches of seeded data
Inconsistent state causing unexpected issues in development
Steps followed: https://github.com/mysociety/alaveteli/wiki/Updating-fixture-data-counter-caches-columns

Update counter caches of seeded data

---

app/models/user.rb
app/views/comment/rate_limited.html.erb
app/views/users/messages/rate_limited.html.erb

Allow `User.content_limits` to be configurable per-install via theme customisation.
For example, we could tune the `user_messages` daily limit like:
User.content_limits = {
info_requests: AlaveteliConfiguration.max_requests_per_user_per_day,
comments: AlaveteliConfiguration.max_requests_per_user_per_day,
user_messages: 2
}
Can probably tidy up the use of `content_limits` _and_ `content_limit`, but that would currently involve reworking the specs – this is good enough for now.

Configurable user content limits

---

app/views/admin_incoming_message/bulk_destroy.html.erb

Fixes #7745
Fix admin bulk deletion of incoming messages
The ID of the info request was being used as the format of the request instead of defaulting to HTML.
This mean the execution was terminated by the `html_response` before controller action callback.

[#7745] Fix admin bulk deletion of incoming messages

---

app/controllers/alaveteli_pro/invoices_controller.rb
app/models/alaveteli_pro/invoice.rb
app/models/alaveteli_pro/invoice_collection.rb
app/models/pro_account.rb
app/views/alaveteli_pro/general/_log_in_bar.html.erb
app/views/alaveteli_pro/invoices/_invoice.html.erb
app/views/alaveteli_pro/invoices/index.html.erb
app/views/alaveteli_pro/subscriptions/index.html.erb
config/routes.rb

Fixes #7114
Add pro subscription invoice controller
Allow user to view and download upcoming or paid invoices using Stripe
hosted pages.
Was a quick spike to see how much work was involved, needs specs, pagination and UI to be thought about.
View receipt
View invoice and pay

[#7114] Add pro subscription invoice controller

---

.ruby-style.yml
spec/views/admin_public_body/show.html.erb_spec.rb
spec/views/admin_request/_params.html.erb_spec.rb
spec/views/admin_request/show.html.erb_spec.rb
spec/views/admin_user/show.html.erb_spec.rb
spec/views/alaveteli_pro/batch_request_authority_searches/_search_results.html.erb_spec.rb
spec/views/alaveteli_pro/dashboard/_projects.html.erb_spec.rb
spec/views/alaveteli_pro/info_requests/new.html.erb_spec.rb
spec/views/alaveteli_pro/public_bodies/_search_result.html.erb_spec.rb
spec/views/comment/new.html.erb_spec.rb
spec/views/followups/_followup.html.erb_spec.rb
spec/views/general/_log_in_bar.html.erb_spec.rb
spec/views/request/_describe_state.html.erb_spec.rb
spec/views/request/show.html.erb_spec.rb
spec/views/request_game/play.html.erb_spec.rb
spec/views/user/sign.html.erb_spec.rb

#7739 
Corrects `Layout/LineLength` cops in the `spec/views` directory/
Part of overall linting.

Layout/LineLength cops in spec/views

---

app/mailers/request_mailer.rb
lib/mail_handler/backends/mail_backend.rb
spec/controllers/followups_controller_spec.rb
spec/fixtures/files/bcc-contact-reply.email
spec/fixtures/files/incoming-request-plain.email
spec/integration/admin_spec.rb
spec/integration/alaveteli_pro/receive_response_spec.rb
spec/integration/download_request_spec.rb
spec/integration/incoming_mail_spec.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb
spec/mailers/request_mailer_spec.rb
spec/models/incoming_message_spec.rb
spec/models/info_request_spec.rb
spec/support/email_helpers.rb

Fixes #6158 
This adds the BCC and Envelope-to headers to the data checked for spam addresses before emails are sent to the holding pen.
[Reduce the noise from the holding pen](https://github.com/mysociety/alaveteli/milestone/53)
The actual changes to things that Alaveteli will do here are somewhat trivial in comparison to spec changes - this PR also includes some refactoring of the existing helper-code for email specs, to make it slightly more flexible without it being a breaking change, as this flexibility was required for the feature.

Spam addresses in BCC and Envelope-to headers are caught

---

app/views/admin_user/_form.html.erb

No limit is now used for more than just requests. We use it as an override to any limitable content.

Tweak `User#no_limit` admin documentation

---

app/views/admin/notes/_show.html.erb

#7279
Adds 50 chars of the note body to the table on the public authority/request admin pages.
It annoys me, but it will also help admins to know which note is which.

[#7279] Show truncated `Note#body` in admin UI

---

app/helpers/link_to_helper.rb
app/models/info_request.rb
app/models/outgoing_message.rb
app/views/request/_outgoing_correspondence.html.erb
app/views/request/_outgoing_correspondence.text.erb
db/migrate/20230412084830_add_from_name_to_outgoing_messages.rb
spec/factories/info_requests.rb
spec/factories/outgoing_messages.rb
spec/fixtures/outgoing_messages.yml
spec/models/info_request_spec.rb
spec/models/outgoing_message_spec.rb
spec/views/public_body/show.html.erb_spec.rb

Connected to #285
- Add `OutgoingMessage#from_name` and `OutgoingMessage#safe_from_name`
- Add `InfoRequest#from_name` and `InfoRequest#safe_from_name`
So censor rules are applied to user names on the request pages. This will be useful for RtE cases or when we allow users to change their own names.
There are some differences to the [proposed implementation](https://github.com/mysociety/alaveteli/issues/285#issuecomment-1503004562):
1. I haven't "Update `OutgoingMessage#from` to use the cached `from_name` value." because this method needs to use the unredacted name as it is used when sending emails. This is why we now have `safe_*` methods. 
Opted to use `safe_` prefix because we already had `IncomingMessage#safe_from_name`.

[#285] Add OutgoingMessage#from_name

---

app/models/user.rb
spec/models/user_spec.rb

Fixes #7780
Update User#can_make_comments?
Allow active users with `no_limit` set to always make comments and bypass the exceeded limit/creation rate checks.
Was fixed in WDTK theme although it appears maybe non-active users might currently be able to make comments if this flag was set.

[#7780] Update User#can_make_comments?

---

db/migrate/20220902112339_remove_public_body_notes.rb

Fixes #7805
Update old migration
Reload `PublicBody` translation columns after removing the old `notes` column. This prevents the annotate models/specs/fixtures/factories from being updated unnecessarily with the latest schema version number.
This has been bugging me for ages.

[#7805] Update old migration

---

Gemfile
Gemfile.lock

Fixes #7532
Bump sprockets to unreleased 3.x branch
This branch is not in active development but contains some backports for ERB deprecations warnings we're seeing.
Full changes: https://github.com/rails/sprockets/compare/v3.7.2...3.x
Bumping to the latest 4.x release is not viable as this introduces `Sprockets::DoubleLinkError` which prevents multiple files with the same output path which is exactly how our themes work. In the future we should look to move to `propshaft`.

[#7532] Bump sprockets to unreleased 3.x branch

---

app/views/alaveteli_pro/batch_request_authority_searches/_public_bodies.html.erb

Fixes #7813
Drop fragment cache for batch category picker
With output cached the category picker doesn't function correctly due to the wrong draft ID being cached.
We could add the draft to the cache key but I think performance isn't a concern here anymore since some other improvements we made for #6862
Ultimately the categories UI shouldn't include the draft ID (or detect is a body has been added or not), the JS should handle rendering and handle the "Add" events.
I think it is how it is due to us trying to keep the interface working for non-JS users but this isn't worth the hassle especially as Pro users need JS to sign up via Stripe.

[#7813] Drop fragment cache for batch category picker

---

app/controllers/users/names_controller.rb
app/models/outgoing_message.rb
app/models/user.rb
app/views/followups/_followup.html.erb
app/views/user/show/_show_profile.html.erb
app/views/users/names/edit.html.erb
config/routes.rb
lib/tasks/temp.rake
spec/controllers/users/names_controller_spec.rb
spec/fixtures/outgoing_messages.yml
spec/models/user_spec.rb

Requires #7735
Connected to #285
- Allows users to edit their own user name
- Displays previously used user names on their profile.
Often requested feature which will reduce admin burden.

[#285] Allow user to edit their name

---

app/controllers/admin_outgoing_message_controller.rb
app/controllers/admin_user_slug_controller.rb
app/models/outgoing_message.rb
app/models/user.rb
app/views/admin_outgoing_message/edit.html.erb
app/views/admin_request/show.html.erb
app/views/admin_user/show.html.erb
config/routes.rb
spec/controllers/admin_user_slug_controller_spec.rb
spec/models/outgoing_message_spec.rb

Requires #7735
Connected to #285
- Allow admins to edit user names on outgoing messages
- Allow admins to see a users previous `slugs`.
Gives admins visibility to see if an user has renamed their account.

[#285] Show user name edits to admins 

---

config/httpd.conf-example
config/nginx.conf.example

Fixes #7810
Add Nginx and Apache config for favicon
Prevents 406 responses and instead respond with the favicon in the Rails asset pipline.

[#7810] Add Nginx and Apache config for favicon

---

app/models/alaveteli_pro/embargo.rb

#7829 
This PR reduces the batch size used when expiring embargoes, from the default 1000 to 200.
At madada.fr, we have seen crashes in this code when large numbers of embargoed requests are expired.
Not much to add, this should have no negative side effects, outside of marginally slowing down execution as there will be 5 times more DB queries sent. As this is a background job, there should be no material impact.

Reduce batch size to limit memory usage during task execution #7829

---

app/models/user.rb
app/views/admin_user/edit.html.erb
lib/tasks/temp.rake
spec/models/user_spec.rb

Connected to #285 
Adds some changes post deploy of the self serve account renaming
Noticed a few missing features/issues.

Account renaming post fixups

---

lib/configuration.rb
script/handle-mail-replies.rb
spec/script/handle-mail-replies_spec.rb

Fixes #7842
Loads required file from commonlib when calling this script.
The script doesn't load Rails or the commonlib.
Also adds the ability to override configuration variables using ENV variables. This is needed so the external command has Pro enabled.

[#7842] Fix handling of mail replies

---

app/models/incoming_message.rb
lib/mail_handler/backends/mail_backend.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb
spec/lib/mail_handler/mail_handler_spec.rb

Fixes #7876
Fix embedded attachment processing
For attachments which are embedded within a RFC822 attachment, were unable process some attachment if they were received a long time ago.
This is down to changes in the underlying mail gem which results in slight difference in the headers which get appended to the attachment body.
This change fixes this by only matching against the body of embedded attachments, ignoring headers and any slight changes.

[#7876] Fix embedded attachment processing

---

lib/mail_handler/backends/mail_backend.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb

Fixes #7880
Fix attachment processing encoding issues
Switch to binary unsafe line end conversion helpers. This fixes an issue where attachments couldn't be masked correctly due to encoding, line endings and the presence of non-ASCII characters.
When we have different encodings, say UTF-8 attachment from the raw email and an 8BIT binary data from Active Storage, the safe line end conversion helpers won't operate when the binary data has non-ASCII characters [1].
This meant in the hex digest never matching and the original unmasked attachment body not being retrievable. With this change this is fixed.
Using the unsafe conversion helpers is fine in this case as the strings are only used to generate MD5 hex digests.
[1] https://github.com/mikel/mail/blob/10a4443/lib/mail/utilities.rb#L248-L25 …

Fix attachment processing encoding issues

---

lib/mail_handler/backends/mail_backend.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb

Fixes #7886
- Minor refactor
- Fixes attachment processing when there is trailing white space in previously extracted attachments.

[#7886] trailing white space attachment processing

---

app/views/admin_request/_some_annotations.html.erb

Uses style similar to outgoing and incoming message metadata.
**BEFORE**
**AFTER**

Use muted style for admin comment created date

---

app/views/admin_request/show.html.erb

We show the sent time for incoming messages in the admin interface for the request show page, so add the equivalent for outgoing messages to make it easier to understand the timeline of correspondence.
**BEFORE**
**AFTER**

Show the last sent time on outgoing messages

---

app/assets/stylesheets/admin.scss
app/views/admin_public_body/_one_list.html.erb

It's still too easy to use the mass tag manipulation form as a search box. We do now have a confirmation alert, but it's still annoying.
This commit adds a "toolbox" section so that infrequently used tools can be hidden away until needed.
I did look at using the Bootstrap collapse [1] element, but it wasn't quite right as I only wanted one heading that collapses the whole section. The Bootstrap component added lots of extra markup, so went with a simple `<summary>` tag for an initial implementation. We can tweak it further if other tools get added.
[1] https://getbootstrap.com/2.2.0/javascript.html#collapse
Closed by default:
Open to use:

Add admin toolbox section to public body list

---

app/views/users/names/edit.html.erb

* Improve phrasing of user name change notes
* Add note on reindexing requests after name change
BEFORE
AFTER

Improve notes on user name change form

---

app/jobs/notify_cache_job.rb
app/models/censor_rule.rb
app/models/comment.rb
app/models/foi_attachment.rb
app/models/info_request.rb
app/models/info_request_event.rb
app/models/public_body.rb
app/models/user.rb
config/general.yml-example
lib/configuration.rb
spec/controllers/admin/foi_attachments_controller_spec.rb
spec/controllers/admin_incoming_message_controller_spec.rb
spec/factories/info_request_events.rb
spec/jobs/notify_cache_job_spec.rb
spec/models/censor_rule_spec.rb
spec/models/comment_spec.rb
spec/models/foi_attachment_spec.rb
spec/models/info_request_event_spec.rb
spec/models/info_request_spec.rb
spec/models/public_body_spec.rb
spec/models/user_spec.rb

Add a cached_urls method to the Comment, FoiAttachment, InfoRequest, PublicBody and User models, containing the entries that those models wish to invalidate when an event is logged via log_event or when the censor rules change. Entries are either a fixed path to be purged or a regex beginning with '^' to be banned.
Adds a NotifyCacheJob that for each of the object's cached_urls, for each locale, for each host in VARNISH_HOSTS, makes BAN or PURGE HTTP requests to the host, to invalidate the relevant entries.

Add ability to ask external caches to invalidate.

---

app/models/incoming_message.rb
lib/mail_handler/backends/mail_backend.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb
spec/lib/mail_handler/mail_handler_spec.rb

Fixes #7877
Fixes uuencoding attachment processing by moving the decoding of these attachments from `IncomingMessage` into `MailHandler`
So attachments can be have censor rules and masks applied using the original raw attachment as a starting point.

[#7877] Fix uuencoding attachment processing

---

lib/mail_handler/backends/mail_backend.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb

Fixes #7877
Missed issue with #7900 when attachments contain different line endings.

[7877] Fix uuencoding attachment processing

---

config/environments/development.rb

> DEPRECATION WARNING: The config.web_console.whitelisted_ips is
> deprecated and will be ignored in future release of web_console.
> Please use config.web_console.allowed_ips instead

Fix deprecation warning

---

app/mailers/request_mailer.rb
app/models/guess.rb
app/models/info_request.rb
app/views/admin_raw_email/_holding_pen.html.erb
spec/controllers/admin_raw_email_controller_spec.rb
spec/integration/admin_spec.rb
spec/mailers/request_mailer_spec.rb
spec/models/guess_spec.rb
spec/models/info_request_spec.rb

---
Fixes #4990
This changes the behaviour of the holding pen such that if an email is similar enough to the expected email for an info request that it only has one Guess attributed, it'll get attached to that IR instead of being sent to the holding pen.
Reduce holding pen noise
- Originally, the 'subject' part of the Guess implementation was also used for this feature, but this has been removed, as it will be assigned as a perfect score regardless of how close it is.

Redeliver holding pen emails if there's a single guess

---

app/models/info_request.rb
spec/models/info_request_spec.rb

The been_published check joins to the event table, so this call was e.g. returning one row per event. Fixes #4776.
After merging, something like:
```
delete from info_request_events where id in (
with e1 as materialized (
select info_request_id,min(id) min_id,params,count(*) c
from info_request_events
where event_type='edit' and params->>'editor' = 'InfoRequest.stop_new_responses_on_old_requests'
group by info_request_id,params
having max(created_at)-min(created_at) <'1 hour'::interval
)
select e2.id
from e1, info_request_events e2
where e1.info_request_id=e2.info_request_id and e1.params=e2.params and e2.id>e1.min_id
);
```
would delete the duplicate rows (8,266,693 at current count).

Stop duplicate log entries when closing requests.

---

lib/mail_handler/backends/mail_backend.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb

Fixes #7915
Fix processing of attachments encoded as Latin 1
When body has been encoded at Latin 1 / ISO-8859-1 we should ensure the strings are converted back to UTF-8 before generating their hexdigest.
This fixes applying masks and censor rules to some attachments.

Fix processing of attachments encoded as Latin 1

---

spec/controllers/admin_request_controller_spec.rb
spec/controllers/attachments_controller_spec.rb
spec/controllers/request_controller_spec.rb
spec/factories/foi_attchments.rb
spec/factories/incoming_messages.rb
spec/factories/info_request_events.rb
spec/factories/info_requests.rb
spec/integration/download_request_spec.rb
spec/integration/errors_spec.rb
spec/models/foi_attachment_spec.rb
spec/models/incoming_message_spec.rb
spec/models/info_request_event_spec.rb
spec/models/info_request_spec.rb
spec/support/email_helpers.rb

Refactor `IncomingMessage` and `FoiAttachment` factories
This work, while not strictly necessary, will make it easier to create test examples for feature by ensuring the underlying `RawEmail` has the correct data so the messages don't need to be reparsed or mocked.

Refactor IncomingMessage and FoiAttachment factories

---

app/controllers/alaveteli_pro/payment_methods_controller.rb
app/controllers/alaveteli_pro/subscriptions_controller.rb
app/models/pro_account.rb
spec/models/pro_account_spec.rb

Connected to https://github.com/mysociety/alaveteli-professional/issues/622
Update Pro subscription sign up
Pass the whole Stripe token through to `ProAccount`, this allows the token to by checked prior to Pro sign up.

[pro#622] Update Pro subscription sign up

---

app/views/notification_mailer/daily_summary.text.erb
spec/fixtures/files/notification_mailer/daily-summary.txt
spec/views/notification_mailer/daily_summary.text.erb_spec.rb

Apple Mail (and potentially others) renders the next line immediately after this line, so it reads as a continuation which gets confusing:
> Here's your daily request summary from WhatDoTheyKnow Production,
> and supply of foo…
After this change we'll have:
> Here's your daily request summary from WhatDoTheyKnow: Production,
> and supply of foo…

Add colon after request summary intro

---

docker-compose.yml

> If you're using docker-compose, you can add these flags to
> docker-compose.yml:
>
>    app:
>      tty: true
>      stdin_open: true
> And then attach to your process with docker attach project_app_1.
> pry-rails works here now. Ensure less is installed on your container
> for the optimal pry experience.
>
> – https://stackoverflow.com/a/37264588

Enable pry binding via Docker

---

app/assets/stylesheets/responsive/_request_layout.scss
app/assets/stylesheets/responsive/_request_style.scss
app/controllers/request_controller.rb
app/views/request/_after_actions.html.erb
app/views/request/request_subtitle/allow_new_responses_from/_authority_only.html.erb
app/views/request/request_subtitle/allow_new_responses_from/_nobody.html.erb
spec/controllers/request_controller_spec.rb
spec/views/request/show.html.erb_spec.rb

Fixes #7185. I imagine it may want a different template instead of my reuse here, but hopefully is the right idea.

Disable manual upload on closed requests.

---

app/models/incoming_message.rb
spec/controllers/admin_request_controller_spec.rb
spec/controllers/attachments_controller_spec.rb
spec/controllers/request_controller_spec.rb
spec/factories/foi_attchments.rb
spec/factories/incoming_messages.rb
spec/factories/info_request_events.rb
spec/factories/info_requests.rb
spec/integration/download_request_spec.rb
spec/integration/errors_spec.rb
spec/models/foi_attachment_spec.rb
spec/models/incoming_message_spec.rb
spec/models/info_request_event_spec.rb
spec/models/info_request_spec.rb
spec/support/email_helpers.rb

Connected to #7875
Depends on #7919
Block incoming messages parsing if hidden attachments will be removed.
To ensure hidden attachments aren't accidentally made visible again.

[#7875] Block incoming messages parsing

---

app/views/request/_attachments.html.erb

Remove call to `IncomingMessage#get_body_for_html_display`.
This isn't used as we're passing a block to the `tag.div` helper. This also isn't cached so nothing is used and work is duplicated.

Fix incoming message rendering

---

Gemfile
Gemfile.lock
app/jobs/info_request_expire_job.rb
config/sidekiq.yml-example

Queue `InfoRequestExpireJob` on a Xapian Sidekiq queue which has concurrency disable so only one job is processed at a time.
Calls to `InfoRequestExpireJob` when passed a `User` would block processing of other jobs such as attachment processing and cause support mail.
The order of the queues in `config/general.yml` is important (as they aren't weighted). the worker threads will always prioritise the first queue (`default`) so attachment processing and other jobs get priority.
Because we dealing with Xapian we also want to ensure only one Xapian related task is happening at any one time (although currently the expire job, isn't actually running Xapian indexing, but having multiple expire job, for the same resource running at the same time, could cause issues too) adding the …

Add Xapian Sidekiq queue

---

app/controllers/concerns/user_spam_check.rb
app/models/user/with_request.rb
config/initializers/user_spam_scorer.rb
lib/user_spam_scorer.rb
spec/lib/user_spam_scorer_spec.rb
spec/models/user/with_request_spec.rb

Fix IP address spam sign up check
Allow scorer to access user IP from the current request object so we can detect users which match IPs and block sign up.
This doesn't seem to be working as expected.

Fix IP address spam sign up check

---

app/controllers/admin_incoming_message_controller.rb
spec/controllers/admin_incoming_message_controller_spec.rb

Fix minor bug redelivering to multiple & some minor code cleanup
When passing multiple destinations as a CSV [1], we're expecting to
strip these values down to an Array of two stripped ID numbers [2].
This wasn't happening as the `each` call wasn't returning the stripped
values. As such, we're left with some invalid ID numbers [3] that don't
get found later on.
This fixes this issue by using `map`, which returns the stripped values.
I've also added some specs. They're not the totally complete, but they
do fail prior to using `map` and pass afterwards, so good enough for
this specific issue.
[1] e.g. `"105, 106"`
[2] i.e. `["105", "106"]`
[3] i.e. `["105", " 106"]` – note the preceding space

Fix incoming redelivery to multiple

---

app/views/admin_user/edit.html.erb

Improve description of account options.
https://github.com/mysociety/alaveteli/issues/7906

[#7906] Improve description of user danger zone

---

app/controllers/attachment_masks_controller.rb
app/jobs/foi_attachment_mask_job.rb
app/models/foi_attachment.rb
app/models/incoming_message.rb
spec/controllers/attachment_masks_controller_spec.rb
spec/jobs/foi_attachment_mask_job_spec.rb
spec/models/foi_attachment_spec.rb

Fixes: #7875
1. 614025af5cf1308c68c3c579294f7654080c7ed9 update attachment masking to call `IncomingMessage#parse_raw_email!(true)` when the original attachment body can't be retrieved. This should rebuild the attachment in the database and correct the mis-matched hexdigest which allows the original attachment to be found again in the future.
2. 3a56b195acc3fb9bb8f988b2ffd31b3556872085 allow mask jobs to be called inline and rescue when the attachment has been rebuilt
3. 90d64a3ffcf7b0d5294d4743be2201f630ca2a01 updates the mask controller to account for attachments being replaced in the database.
4. ebc639250b6a8a82f36b91a61b412ef8bc41bbe1 protect against exceptions on the `request#show` and other actions where the attachment can be masked for the first time.
To ensure all attachments are …

[#7875] Fix attachment processing

---

app/models/foi_attachment.rb
spec/models/foi_attachment_spec.rb

Fixes #7934
Fix processing of unsaved attachments
This change prevents calling the `FoiAttachmentMaskJob` before the attachments has been saved. This was causing issues saving attachments in `ActiveStorage` as it was happening twice and the wrong version was saved.

[#7934] Fix processing of unsaved attachments

---

app/jobs/foi_attachment_mask_job.rb
app/models/foi_attachment.rb
app/models/incoming_message.rb
spec/jobs/foi_attachment_mask_job_spec.rb
spec/models/foi_attachment_spec.rb

Hopefully fixes #7934
Rework and simplify the changes in https://github.com/mysociety/alaveteli/pull/7932
1. a253194ff4d21487ab3357cb5e38ef73bc571a79 The the Mask job, if an incoming message get reparsed attempt to load the attachment and again and mask, instead of allow the job to finish without the masked body/masked at being set.
2. 616a56dbdb00db00c722e13f08bc8d99d27e97d5 Improve the `#body` to do similar, load the attachment and return the body instead of raising a `RebuildAttachment` exception.
Tackle an increase in `ActiveStorage::FileNotFoundError` exceptions after attachments are dropped from the database when the incoming message is parsed again after the original unmasked body couldn't be found for the masking job. See #7875 .

[#7934] Fix unsaved attachments

---

config/initializers/theme_loader.rb

Fixes: https://github.com/mysociety/asktheeu-theme/issues/124
Fix loading custom states in theme
Let Zeitwerk ignore files which don't match the expected file structure.
Credit to @laurentS for working out the issue in #7917

[EU#124] Fix loading custom states in theme

---

app/models/webhook.rb
spec/fixtures/stripe_webhooks/subscription-started.json
spec/models/webhook_spec.rb

Fixes #6606
Add subscription started state
Before this change weren't handling webhooks for subscription started state resulting in unknown webhook lines in our webhook daily digest.
We never use to receive these but I believe since the change to strong customer authentication we now get a notice that the subscription status moves from `incomplete` to `active`.

[#6606] Add subscription started webhook state

---

app/jobs/foi_attachment_mask_job.rb

Fixes #7934
Fix missing ActiveStorage attachment uploads
The after commit hooks don't seem to be firing in some cases resulting in attachments not being uploaded after the attachment and its file blob record being saved.

[#7934] Fix missing ActiveStorage attachment uploads

---

lib/attachment_to_html/adapters/google_docs_viewer.rb

A quick win from #7027.
The comment link to documentation now links to a page on working with Office files, but CSV is included under the "File types you can convert to Docs, Sheets, or Slides". It wasn't included around the time of the original inclusion [2].
Either way, it appears to work in practice as per a recent experiment [3].
[1] https://support.google.com/docs/answer/6055139?visit_id=638320303798629817-2515806591&rd=2
[2] https://web.archive.org/web/20120118194636/https://support.google.com/docs/bin/answer.py?hl=en&answer=1189935
[3] https://github.com/mysociety/alaveteli/issues/7027#issuecomment-1746696080

[#7027] Add CSV to GoogleDocsViewer

---

app/models/public_body.rb
app/models/public_body/calculated_home_page.rb
spec/models/public_body_spec.rb

Many smaller authorities use a request email address from a general
purpose public email provider. We don't want e.g. gmail.com being set as
the home page for the authority.
This is configurable in the theme by setting the class attribute:
PublicBody.excluded_calculated_home_page_domains << %w[
example.net
]
PublicBody.excluded_calculated_home_page_domains = %w[
example.org
example.net
]
Fixes https://github.com/mysociety/alaveteli/issues/6434

[#6434] Exclude email providers from body home pages

---

app/controllers/admin_public_body_controller.rb
app/models/public_body.rb
app/views/admin_public_body/_form.html.erb
app/views/admin_public_body/_locale_fields.html.erb
lib/tasks/temp.rake

Fixes #1264
Update PublicBody#disclosure_log to be translatable
Consistency with other `PublicBody` attributes.
Adds temp rake task to migrate existing data into the translation column which already exists in the database.
Will need a migration to remove `PublicBody#disclosure_log` in a future release.

[#1264] Update PublicBody#disclosure_log to be translatable

---

docker/bootstrap
docker/reset
docker/setup

Fixes #7823
1. Minor changes to the scripts
2. Ensure Docker environment works without manually performing commands.

[#7823] Update Docker scripts

---

app/controllers/admin_general_controller.rb
app/helpers/admin_general_timeline_helper.rb
app/views/admin_general/timeline.html.erb
spec/controllers/admin_general_controller_spec.rb

Fixes #5371
Adds the ability to filter the timeline by time for all event types
Previously, request events and authority change events could only be displayed for the last two days unless the URL was manually manipulated, which was annoying.

[#5371] Update admin timeline event filtering

---

app/mailers/request_mailer.rb
app/models/info_request.rb
spec/mailers/request_mailer_spec.rb
spec/models/info_request_spec.rb
spec/support/email_helpers.rb

Fixes #7879 
This allows for emails with multiple exact info request addresses in TO, CC, or BCC headers to be sent to multiple info requests unless the info request has already received that exact email, in which case it doesn't send it again, to avoid duplication.
To reduce many emails being sent to the holding pen unnecessarily

[#7879] Handle multiple addresses in headers

---

app/controllers/attachment_masks_controller.rb
app/controllers/attachments_controller.rb
app/views/attachment_masks/done.html.erb
spec/controllers/attachment_masks_controller_spec.rb
spec/controllers/attachments_controller_spec.rb

Update AttachmentMaskController referer handling
Addresses potential cross-site scripting issue identified by Brakeman.
This change uses `MessageVerifier` to encodes the referer when passing it from the `AttachmentController` to the `AttachmentMaskController`, this is needed because we don't know which route the attachment was requested from (public, share by link, project).
We were relying on `redirect_to` raising an `UnsafeRedirectError` exception when the referer param was changes to an external link.
This works for the controller, but we also use the referer param on the `done` view. So once the attachment is available, if the param is manually changed the resulting page would have a download link which points to changed referer param.
We use temporary signed attachment IDs so the …

Update AttachmentMaskController referer handling

---

doc/CHANGES.md
lib/public_body_csv.rb
spec/lib/public_body_csv_spec.rb

https://github.com/mysociety/alaveteli/issues/4808
This adds a new column to the CSV download that includes the internal database ID number for the authority. 
The authorities csv has no columns that are guaranteed not to change if an authority is renamed. 
I'm also using the id number to pass information to the survey platform, and I need to be able to get from that back the ID name and categories . I *could* reconcile this using information from the database, but this CSV is otherwise 99% of what I need, and it's already in public. 
My ruby is rusty, I *think* this should work, but advice is good.

[#4808] Add the internal ID number to the CSV download

---

app/controllers/attachment_masks_controller.rb
app/controllers/attachments_controller.rb
spec/controllers/attachment_masks_controller_spec.rb
spec/controllers/attachments_controller_spec.rb
spec/integration/incoming_mail_spec.rb

Fixes #7977
This updates `AttachmentController#show_as_html` to do attachment masking in the background.
Our "view attachments in the browser" feature, or "view as HTML", is doing a lot of processing inline in the web processes and this sometimes causes memory issues on the server and results in oom-kill running.
Uses the same logic as the `#show` action to check an attachment is masked before proceeding with the action. This means it will time outs after 5 seconds and then redirect the `AttachmentMaskController` to wait for the job to complete before rendering a view saying the attachment is now viewable.

[#7977] Update `AttachmentController#show_as_html` to do attachment masking in the background

---

app/helpers/mailer_helper.rb
spec/helpers/mailer_helper_spec.rb

Generic implementation to help with https://github.com/mysociety/whatdotheyknow-theme/issues/1774
A generic case reference ID generator for use in email Subject lines to prevent incorrect threading by mail clients, and/or to use in the Body for end user ease of reference.

Add MailerHelper#case_reference

---

app/views/admin_raw_email/_holding_pen.html.erb

* Show scores in pill and table
* Add a note about auto-redelivery when there's only a single guess

Show holding pen guess scores

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/changelog.yml
.github/workflows/ci.yml
.github/workflows/rubocop.yml

1. Add workflow to check the changelog is updated
2. Allow changelog check to be skipped
3. Allow rspec to be skipped
4. Update the PR template to help remind devs to do this before the PR is created
5. Updates action versions (fixes depreciation and NodeJS warnings)
6. Update platform versions to `ubuntu@latest`
7. Minor YAML configuration reordering
8. Remove `pr.reopened` workflow event type from RuboCop and CI - we would probably want to rebase in this scenario.
When creating PR we should update the changelog as this helps others see what is upcoming in the next release and makes release Alaveteli versions easier.
This workflow ensures an `docs/CHANGES.md` is modified or the pull request description contains `[skip changelog]`, I've also made sure you can edit the PR description to …

Update GitHub workflows

---

app/controllers/request_controller.rb
app/views/request/details.html.erb
spec/controllers/request_controller_spec.rb
spec/views/request/details.html.erb_spec.rb

Fixes #7189 
Two suggestions, could take one or both - the first changes "edit" to "edit metadata" on the details page, which I think makes it clearer (especially when there's no edit_incoming or edit_outgoing etc) that an edit of a request is editing its metadata rather than text of messages within the request.
And then as suggested on the ticket adds a column to show the keys that have changed as part of an event.

[#7189] Details page showing keys metadata

---

app/helpers/admin/link_helper.rb
app/views/admin_track/_some_tracks.html.erb
spec/helpers/admin/link_helper_spec.rb

We render Tracks in the admin interface but they don't have an "eye" next to them as per other records. This commit adds a basic implementation which just links to the search query of the track.
The current view code in `admin_track/_some_tracks` does some more complex handling, where the "title" of the track links directly to a trackable record if the track has one associated, or falls back to the plain text search query.
We could later move this behaviour to the eye, and then link to an admin page for the track via the search term (in line with other records) when we have an admin page.
The main intent of this commit is just to get the eye in place, such that we can improve the behaviour at a later date.
👁️

Add a basic TrackThing both_links

---

app/assets/stylesheets/admin.scss
app/views/admin/foi_attachments/edit.html.erb
doc/CHANGES.md

Admins often want to view the contents of an incoming message without any masking or censor rules applied.
In some cases you can inspect the raw email, but it's often base64 encoded, which means needing to download the email and open it in a mail client. Even when the email is not base64 encoded, it's often difficult to mentally parse the information out when there are lots of headers, attachment sections and HTML body content.
This commit adds an unmasked view of main body part attachments. This is equivalent to the main body contents of an incoming message that we show in public.
This does require "downloading" the attachment from Active Storage, but at present we use local file storage for attachments, so that's fine. Even if we moved them to S3 it wouldn't be a disaster to fetch them …

[#1106] Admin view of unmasked incoming message

---

app/helpers/info_request_helper.rb
doc/CHANGES.md
spec/helpers/info_request_helper_spec.rb

Finding contact details can take a fair amount of work. Users are often happy to help, but the only signpost we have for this is when submitting the classification. They might not have time to source a new address there and then – and the form itself could be improved – but a reminder for them and other users viewing the requests might help distribute some of this work to the community.
Fixes https://github.com/mysociety/alaveteli/issues/1782.
**Public Request:**
**Private Request:**

[#1782] Help us CTA from delivery error message

---

app/assets/stylesheets/responsive/_search_style.scss
app/views/general/_help_requests.html.erb
app/views/general/_search_latest.html.erb
app/views/request/list.html.erb
config/routes.rb
doc/CHANGES.md

Signpost key request admin contributions 
A basic version of #1513
A basic version of #6871
* Classify requests goes to https://www.whatdotheyknow.com/categorise/play
* Find updated contact details https://www.whatdotheyknow.com/search/latest_status:error_message/requests

[#1513, #6871] Signpost request contributions

---

app/jobs/foi_attachment_mask_job.rb
app/models/foi_attachment.rb
app/models/incoming_message.rb
spec/models/foi_attachment_spec.rb
spec/models/incoming_message_spec.rb

Fixes #7971
Update attachment processing
Handle when incoming messages are re-parsed which can cause attachments to be rebuilt when trying to render the main body part.
Occasionally when main body attachment part will get rebuilt while the content is masked. When this happens we can see errors such as: <code>undefined method `unmasked_body' for nil:NilClass</code>.
This change ensures the masking job doesn't fail and the code will now raise an `MissingAttachment` exception instead.
Rescuing from this in `IncomingMessage#get_main_body_text_internal` allows us to retry straight away as in the second attempt the main part will be the new attachment instance and the part will be rendered.
<hr>

[#7971] Update attachment processing

---

app/controllers/request_game_controller.rb
app/models/request_classification.rb
app/models/statistics/leaderboard.rb
doc/CHANGES.md
spec/models/request_classification_spec.rb
spec/models/statistics/leaderboard_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/7946
Change the `Statistics::Leaderboard` class to only consider active users (i.e. users that haven't closed their account or been banned) from appearing on leaderboards.

Only show active users on leaderboards

---

app/models/info_request.rb
app/models/public_body.rb
app/views/admin_public_body/_form.html.erb
doc/CHANGES.md
spec/controllers/admin_public_body_controller_spec.rb
spec/lib/public_body_csv_spec.rb
spec/models/info_request_spec.rb
spec/models/public_body_spec.rb
spec/support/not_many_requests_helper.rb

Fixes #7361.
Automatically apply and remove a tag to requestable bodies that have a low number of public requests.
Allows users to find them via a public search to help bootstrap basic transparency/site content, and admins can add a tag-based note to suggest generally useful first requests.
The number considered "not many requests" is configurable in the theme by setting `PublicBody.not_many_public_requests_size`.
The changelog suggests a one-shot script to mass-apply the tag to existing bodies where applicable.
It's a bit annoying that I needed to add the `InfoRequest#notify_public_body` hook. Can't think of a less obtrusive way of doing this though.
Added some admin guidance and separated out the "special" and "automatically managed" tags:
Left the spec DRYing up as fixups just in case …

[#7361] Automatically tag bodies with few public requests

---

app/models/info_request.rb
app/models/info_request/state/calculator.rb
app/models/info_request/state/transitions.rb
doc/CHANGES.md
spec/models/info_request/state/calculator_spec.rb
spec/models/info_request_spec.rb

Fixes #3830
Update request base calculated status
Once a requester has asked for a internal review their request's base status shouldn't ever be `waiting_classification` as this limits the possible classification statuses.
Returning `internal_review` allows the requester to classify the request as `I'm still waiting for the internal review` after they receive an acknowledgement of their review.

[#3830] Update request base calculated status

---

app/views/admin/info_request_batches/_admin_columns.html.erb
app/views/info_request_batch/show.html.erb
doc/CHANGES.md

Add admin links to and from batch request show action
For easier admin of batches.

Add admin links to and from batch request show action

---

app/helpers/admin/link_helper.rb

Prepending the info request title adds extra noise when viewing the list of an attachments for an incoming message. We lose a bit of context if rendering `both_links` for an attachment outside of its request/incoming message page, but I don't think we do that at present and it's worth the tradeoff. In a situation where we do want both, then we can add it in in that specific context.
BEFORE
AFTER

Improve clarity of both_links for FoiAttachment

---

app/models/incoming_message.rb

Remove IncomingMessage#destroy_raw_email

---

lib/user_stats.rb

N/A
This tidying makes easier to read and understand the inputs of `list_user_domains` routine.
Making code easier to understand makes it easier to work with.
<hr>

Clarify inputs (arguments) to the list_user_domains routine

---

app/controllers/admin/categories_controller.rb
app/models/category.rb
app/models/concerns/categorisable.rb
app/models/info_request.rb
app/models/public_body.rb
app/views/admin/categories/_scope.html.erb
app/views/admin/categories/edit.html.erb
app/views/admin/categories/index.html.erb
app/views/admin/categories/new.html.erb
app/views/admin_general/_admin_navbar.html.erb
app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb
app/views/public_body/list.html.erb
doc/CHANGES.md
lib/tasks/temp.rake
spec/controllers/admin/categories_controller_spec.rb
spec/models/category_spec.rb
spec/models/concerns/categorisable.rb
spec/models/info_request_spec.rb
spec/models/public_body_spec.rb

Depends on #8023 
Fixes #7811
Add `categorisable` concern and adds this to `InfoRequest`
So we can so groups of requests on [topic pages](https://github.com/mysociety/alaveteli/milestone/62).

[#7811] Allow InfoRequest to be categorised 

---

app/controllers/application_controller.rb
app/helpers/link_to_helper.rb
app/models/blog.rb
app/models/survey.rb
spec/helpers/link_to_helper_spec.rb

Add helper to add query params to a URL
In a couple of places we do this in different ways, this helper will allow us to do this in one line and is tested independently.
This helper will be useful in #7961
<hr>

Add helper to add query params to a URL

---

app/controllers/attachments_controller.rb
app/models/foi_attachment.rb
doc/CHANGES.md
spec/controllers/attachments_controller_spec.rb
spec/models/foi_attachment_spec.rb

Fixes #8040
Fix missing attachments exceptions
There seems to be some missing attachments on WDTK. This seems to stem from when we migrated attachments to `ActiveStorage` where the files either weren't present or weren't migrated correctly. Or I guess have been lost since (hopefully not). Luckily we can alwasy restore from the raw emails. This used to guard against missing attachments before the recent attachment processing changes. This change re-adds this functionality.

[#8040] Fix missing attachments exceptions

---

app/views/request/_attachments.html.erb
doc/CHANGES.md

Makes it easier to navigate directly to the admin page for an attachment. On several occasions admins have navigated to the incoming message – because it's the closest link available – and changed the prominence of the incoming message rather than the attachment.
No user:
Bob (non-admin):
Annie (admin):

Add link to admin attachments

---

app/views/admin/categories/edit.html.erb

Fixes #8054
Fix redirect when category is destroyed
Pass the current model type to the admin category destroy action so we can redirect to the correct/current model index.
<hr>

Fix redirect when category is destroyed

---

app/controllers/admin/notes_controller.rb
app/views/admin/notes/_show.html.erb
app/views/admin/notes/index.html.erb
app/views/admin_general/_admin_navbar.html.erb
config/routes.rb
doc/CHANGES.md
spec/controllers/admin/notes_controller_spec.rb
spec/views/admin/notes/_show.html.erb_spec.rb

Allow admins to view all notes in one place and navigate to any Note's Notable record.
The use case here is that I'm dealing with some support and want to add a note. I know a similar note will have been added in the past, so I want to base my note off that (for speed, consistency, checking I'm saying the right thing, etc). It's basically impossible to find the kind of note I'm thinking of without them in a list.
Ideally this will evolve to include the usual search & sort filtering, but even as-is it helps since I can just paginate to the end to see recent notes (which is likely where what I want will be).
Screenshot paginates 1-per-page to check that it works.

Add basic admin notes index

---

spec/integration/alaveteli_dsl.rb

Allow specs to specify params for the signin path. EG. `r: '/help'` will redirect to the help pages instead of the homepage after login.
This is useful in theme specs. For example with WDTK theme the homepage might attempt to load remote content which isn't stubbed.
<hr>

Update spec login helper

---

app/models/guess.rb
doc/CHANGES.md
spec/models/guess_spec.rb

The default score should be 0 - as in, no match – unless we actually have some sort of similarity on the attribute. Since these are guard clauses for when there is no attribute, we should return a value that implies there isn't a match.
Fixes https://github.com/mysociety/alaveteli/issues/7996

[#7996] Fix default Guess scores

---

app/controllers/admin/foi_attachments_controller.rb
app/models/ability.rb
app/models/foi_attachment.rb
spec/models/foi_attachment_spec.rb

Extracted from #8060
Refactor attachment logging.
Make it easier to log changes to attachments from other parts of the code. IE automated tasks.
No functional difference.
<hr>

Refactor attachment logging

---

app/helpers/public_body_helper.rb
spec/factories/categories.rb
spec/helpers/public_body_helper_spec.rb

Fixes #8081
Update type of authority helper
Updated to use new category system introduced in #8023 over the older `PublicBodyCategory` model which isn't being updated anymore.
<hr>

[#8081] Update type of authority helper

---

config/routes/redirects.rb
spec/routing/redirects_spec.rb

Fixes #8086
Fix request ID redirect with format
Broken existing links.
<hr>

[#8086] Fix request redirect with format

---

app/helpers/public_body_helper.rb
app/models/category.rb
app/models/concerns/categorisable.rb
spec/helpers/public_body_helper_spec.rb
spec/models/category_spec.rb
spec/models/concerns/categorisable.rb

Fixes #8081
Fixes type of authority helper
Add Category list method to return a flat list of categories for a given root. This will be useful in places as this replicates to functionality of the older `PublicBodyCategory` model.
<hr>

[#8081] Fixes type of authority helper

---

app/views/admin_general/_edit_outgoing.html.erb

Fixes #7682
Fix admin timeline edit outgoing events
When an outgoing message is edited the admin timeline breaks. This is due to changes in how the event params are stored in #7173.
<hr>

[#7682] Fix admin timeline edit outgoing events

---

app/views/layouts/default.html.erb

Reduce confusion when reading this section of the file.
Just a quick PR to improve reading this section of code while discussing a technical issue around when the analytics tracking code is rendered.

Fix indentation

---

app/controllers/admin_users_account_anonymising_controller.rb
app/controllers/admin_users_account_closing_controller.rb
doc/CHANGES.md
spec/controllers/admin_users_account_anonymising_controller_spec.rb
spec/controllers/admin_users_account_closing_controller_spec.rb

In practice we often use all three closure actions in a single step – Close; Anonymise; Erase. It's annoying to get taken back to the show page and then have to go back in to edit to take the next action, and so on.
This commit returns you to the edit page for the Close and Anonymise actions. Once an account gets erased, you're returned to the show page to signify the "end" of the possible actions.
Fixes https://github.com/mysociety/alaveteli/issues/7986.

[#7986] Improve redirection flow for user closure actions

---

Gemfile
Gemfile.lock
config/initializers/excel_analyzer.rb
doc/CHANGES.md
gems/excel_analyzer/excel_analyzer.gemspec
gems/excel_analyzer/lib/excel_analyzer.rb
gems/excel_analyzer/lib/excel_analyzer/eml_analyzer.rb
gems/excel_analyzer/lib/excel_analyzer/railtie.rb
gems/excel_analyzer/spec/excel_analyzer/eml_analyzer_spec.rb
gems/excel_analyzer/spec/excel_analyzer/xls_analyzer_spec.rb
gems/excel_analyzer/spec/excel_analyzer/xlsx_analyzer_spec.rb
gems/excel_analyzer/spec/spec_helper.rb
gems/excel_analyzer/spec/support/helpers.rb
lib/alaveteli_file_types.rb
lib/mail_handler/backends/mail_backend.rb
spec/integration/incoming_mail_spec.rb

Fixes #8047
Add automatic parsing of emails with spreadsheets
We want to parse these email automatically so the `Excel Analyzer` runs
and detects issues with hidden data.

[#8047] Add automatic parsing of emails with spreadsheets

---

app/models/foi_attachment.rb
doc/CHANGES.md
spec/models/foi_attachment_spec.rb

Update attachment body assignment
When masking attachments avoid replacing the blob with a new blob, instead update which retains the blob key and existing metadata.
This means no `ActiveStorage::PurgeJob` or an additional `ActiveStorage::AnalyzeJob` for the new blob.

Update attachment body assignment

---

gems/excel_analyzer/lib/excel_analyzer.rb
gems/excel_analyzer/lib/excel_analyzer/xlsx_analyzer.rb
gems/excel_analyzer/spec/excel_analyzer/xlsx_analyzer_spec.rb

Required for #8048
In the ExcelAnalyzer add on_hidden_metadata callback
Allow a configurable block to be called if spreadsheets are received which contain suspect hidden data.
<hr>

[ExcelAnalyzer] add on_hidden_metadata callback

---

spec/models/user/survey_spec.rb
spec/models/user_info_request_sent_alert_spec.rb

Fix specs broken due to extra day in an leap year
These specs are testing for old content created over an year ago. Normally this would be fine but with an extra day in a leap year they break.
This change increases the creation date to 367 days ago.

Fix specs broken due to extra day in an leap year

---

app/views/request/new.html.erb

Removes duplicate text
Fixes #8143
Remove duplicate text on request page
There was duplicate text on the request page
n/a
<hr>
Have you updated the changelog? If this is not necessary, put square brackets around this: [skip changelog]

Removing duplicate text

---

app/models/project/export/info_request.rb
doc/CHANGES.md
spec/models/project/export/info_request_spec.rb

Project::Export uses the first request in the project to generate the CSV headers. However, if the request hasn't had data extracted, the headers for the dataset columns will be blank, even though other requests in the project may have had a dataset extraction.
This commit ensures that headers are always present by looking up the project's key set, and iterating through that to fetch the relevant submission value for that key, or otherwise assigning a nil value.
This has the benefit of ensuring that the keys/values exported are always in sync with the current project key set.
Fixes https://github.com/mysociety/alaveteli/issues/8141.

Fix missing headers when exporting Project data

---

spec/controllers/admin_public_body_controller_spec.rb
spec/controllers/general_controller_spec.rb
spec/integration/statistics_spec.rb
spec/lib/alaveteli_text_masker_spec.rb

Refactor spec configuration option assignment
Some spec examples require certain configuration options to be set, this commit switches to stubbing the option instead of reassigning the option to the required value to get the test to pass.
This means we don't need to revert the value after the test example has been run back to the original value.
<hr>

Refactor spec configuration option assignment

---

app/models/foi_attachment.rb

When an attachment doesn't have a blob the metadata can't be delegated resulting in exceptions on the admin view where the metadata is displayed.
Fix loading of admin attachment view
When an attachment doesn't have a blob the metadata can't be delegated resulting in exceptions on the admin view where the metadata is displayed.
<hr>

Fix loading of admin attachment view

---

config/initializers/alaveteli_features.rb

Update pro batch category feature condition
Since the migration from `PublicBodyCategory` to `Category` this feature could not be enabled for new installs which have no `PublicBodyCategory` instances.
<hr>

Update pro batch category feature condition

---

app/models/foi_attachment.rb
config/sidekiq.yml-example
lib/tasks/storage/storage.rb
spec/models/foi_attachment_spec.rb

Fixes #8181
Fix attachment blob integrity error
Error introduced in https://github.com/mysociety/alaveteli/pull/8125 which meant the on disk attachment could be updated but the checksum wasn't which means `ActiveStorage::IntegrityError` can be raised. This happens when running the storage mirror task and probably at other times too.
Change to the task only need to be temporary until attachments are mirrored.
<hr>
[skip changelog] - not needed as fix for unreleased change

[#8181] Fix attachment blob integrity error

---

app/controllers/application_controller.rb
app/controllers/attachments_controller.rb

Fixes #8190
Fix logout issues
To fix unexpected behaviour and retain user browser sessions.
Not 100% sure of the reason for this issue. I can only replicate this on WDTK and the Alaveteli staging environment. Running in production elsewhere works fine so I guess this could be due to how we have Apache/Varnish configured? /cc @sagepe 
<hr>

[#8190] Fix logout issues

---

doc/CHANGES.md
lib/acts_as_xapian/acts_as_xapian.rb
spec/lib/acts_as_xapian_spec.rb

https://github.com/mysociety/alaveteli/issues/4426
has_normal_search_terms? was only returning true if the query had a stemmed search term in it, such as Zterm. Searching for a word with capital letters, such as NHS, translates to an unstemmed query term “nhs”. This would not match and the search would default to sorting by newest rather than relevance. Unstemmed query terms should still match as a normal search term, not a prefixed one.
The default search results should not change their sort order based solely upon the capitalisation of the search provided.

Treat unstemmed words as normal search terms.

---

app/helpers/admin/citations_helper.rb
app/helpers/admin_helper.rb
app/models/citation.rb
app/views/admin/citations/_list.html.erb
app/views/citations/new.html.erb
db/migrate/20240209162933_change_citation_type_values.rb
doc/CHANGES.md
spec/controllers/citations_controller_spec.rb
spec/helpers/admin/citations_helper_spec.rb
spec/models/citation_spec.rb

* Render an icon depicting citation type
* Broaden `Citation#type` classifications
* Add "campaigning" `Citation#type`

Citations improvements

---

app/models/user.rb
app/models/user/spreadable_alerts.rb
spec/models/user/spreadable_alerts.rb
spec/models/user_spec.rb

Extract a group of methods from `User` that handle spreading alert times throughout the day
Compartmentalise some incidental behaviour. 🧈
Missing a spec for `spread_alert_times_across_day`. This isn't actually called anywhere and I'm not sure it's been called manually for a very very long time, so could remove it.

Extract User::SpreadableAlerts

---

app/views/one_time_passwords/show.html.erb
doc/CHANGES.md

Users *must* remember to save this passcode.
BEFORE
AFTER

Strengthen 2FA warning

---

app/assets/javascripts/admin.js
app/assets/javascripts/admin/notes.js
app/assets/stylesheets/actiontext.css
app/assets/stylesheets/admin.scss
app/assets/stylesheets/responsive/_notes_layout.scss
app/assets/stylesheets/responsive/_notes_styles.scss
app/controllers/admin/notes_controller.rb
app/helpers/notes_helper.rb
app/models/note.rb
app/models/public_body.rb
app/views/active_storage/blobs/_blob.html.erb
app/views/admin/notes/_form.html.erb
app/views/admin/notes/_locale_fields.html.erb
app/views/admin/notes/_note.html.erb
app/views/admin/notes/_show.html.erb
app/views/layouts/action_text/contents/_content.html.erb
app/views/layouts/admin.html.erb
config/application.rb
db/migrate/20240227080436_add_style_to_notes.rb
db/migrate/20240228122324_create_action_text_tables.action_text.rb
doc/CHANGES.md
spec/controllers/admin/notes_controller_spec.rb
spec/factories/notes.rb
spec/factories/public_bodies.rb
spec/fixtures/notes.yml
spec/helpers/notes_helper_spec.rb
spec/models/note_spec.rb
spec/models/public_body_spec.rb

Fixes #7771
Fixes #7809
Add styling and rich text notes
Enable easier styling of note content.
Have added an "original" style which renders notes as they are currently. Eventually we might choose to migrate current notes on WDTK and remove this style.

[#7771 & #7809] Add styling and rich text notes

---

app/controllers/admin/categories_controller.rb
app/helpers/admin/link_helper.rb
app/models/category.rb
app/models/concerns/notable.rb
app/views/admin/categories/_form.html.erb
app/views/admin/categories/_locale_fields.html.erb
doc/CHANGES.md
spec/controllers/admin/categories_controller_spec.rb
spec/models/category_spec.rb

Fixes #7255
Add category notes
So we can create topic pages to display info requests in given categories (via tags). And render notes and other "unstyled" rich text content on the page.

[#7255] Add category notes

---

app/controllers/public_body_controller.rb
app/models/public_body.rb
lib/tasks/export.rake
spec/controllers/public_body_controller_spec.rb
spec/models/public_body_spec.rb

Fixes #8179
Replace old public body categories models
Model has been replaced but we still have references to it in places.
Only remaining references are in the old models and temp rake tasks which migrates to the new Category model.
<hr>

[#8179] Replace public body categories

---

app/controllers/request_controller.rb
app/views/general/_frontpage_requests_list.html.erb
app/views/request/_category.html.erb
app/views/request/_list_results.html.erb
app/views/request/_request_filter_form.html.erb
app/views/request/list.html.erb
config/routes.rb
doc/CHANGES.md
lib/xapian_queries.rb
spec/controllers/request_controller_spec.rb
spec/controllers/track_controller_spec.rb
spec/factories/categories.rb

Fixes #7812
Allow requests to be browsed by tag
So we can view tagged requests and make topic pages.

[#7812] Allow requests to be browsed by tag

---

app/models/info_request.rb
doc/CHANGES.md
spec/models/info_request_spec.rb

Fixes #7693
Update InfoRequest#recipient_name_and_email
Handle when authorities don't have valid email addresses. In this case just return the recipients name.

[#7693] Update InfoRequest#recipient_name_and_email

---

app/models/censor_rule.rb
db/migrate/20240313094449_add_not_null_constraint_to_censor_rule_regexp.rb
doc/CHANGES.md
spec/factories/censor_rules.rb
spec/models/censor_rule_spec.rb

Add default value and not null constraint to `CensorRule#regexp`. While effectively the same behaviour, this makes the intent explicit and prevents empty values appearing in admin tables where we render censor rules.
**BEFORE**
**AFTER**

Add default and constraint to CensorRule#regexp

---

app/views/admin_general/_admin_navbar.html.erb

Mirror the ordering of these items in the main nav as I'm forever clicking Authorities when I want Requests and vice versa.
BEFORE
AFTER

Switch Authorities and Requests in admin nav

---

app/helpers/link_to_helper.rb
spec/helpers/link_to_helper_spec.rb

Use addressable gem over default URI module. This gem handles non RFC2396 compliant URLs. Required to fix #8211 in WDTK theme.

[#8211] Update helper URI module

---

app/controllers/help_controller.rb

Fixes #8212
Rescue from missing contact form params
Prevent exceptions.

[#8212] Rescue from missing contact form params

---

gems/excel_analyzer/lib/excel_analyzer/xlsx_analyzer.rb
gems/excel_analyzer/spec/excel_analyzer/xlsx_analyzer_spec.rb

Update excel suspected problem detection
1. Add specs
2. Fix run callback for single hits
3. Run callback for errors
4. Ignore external_links when there are no other criteria
Allow [WDTK theme code](https://github.com/mysociety/whatdotheyknow-theme/blob/6e904ba7d3ee927e7773f64792cda1ce73a49bd2/lib/excel_analyzer.rb#L1-L17) to hide spreadsheets which contain hidden data. These updates allow us to hide spreadsheets based on out current understanding of the issue.
<hr>

Update excel suspected problem detection

---

app/models/info_request.rb
doc/CHANGES.md
spec/models/info_request_spec.rb

Fixes #8215
Update InfoRequest#set_described_state
Prevent multiple require admin emails from being sent when the state hasn't changed. This happens when multiple bounce message are received and the requester classifies each as `error_message` or `requires_admin` making it hard to keep track of outstanding issues in need of fixing.

[#8215] Update InfoRequest#set_described_state

---

config/routes.rb
doc/CHANGES.md
spec/integration/admin_tag_controller_show_spec.rb

Update admin tag routing constraints
Allow admin pages for tags with `.` or `/` to be loaded successfully. This means tags can be URLs which is currently a use case used on WDTK.
It does mean we can't have member actions on the tags resource but as of now we don't have any. If ever we want an `edit` action we can adjust the constraint to allow this.

Update admin tag routing constraints

---

gems/excel_analyzer/lib/excel_analyzer/xlsx_analyzer.rb
gems/excel_analyzer/spec/excel_analyzer/xlsx_analyzer_spec.rb

Fixes https://github.com/mysociety/whatdotheyknow-private/issues/304
Add threshold for hidden rows
We've had no serious data breaches at this level and it would reduce the number of hidden row hits by over half.
<hr>

[ExcelAnalyzer] Add threshold for hidden rows

---

app/mailers/application_mailer.rb
spec/mailers/contact_mailer_spec.rb

Fixes #8268
Fix issue setting custom from address
We're currently always overriding the from address in `mail_user`, this probably came from a bad merge.
<hr>

[#8268] Fix issue setting custom from address

---

app/assets/javascripts/admin.js
app/assets/javascripts/admin/admin.js
app/views/admin_user/_user_table.html.erb
doc/CHANGES.md

Being able to quickly see that a user has a profile photo – and then be able to preview it – helps detect spam.
Fixes https://github.com/mysociety/alaveteli/issues/5304
**Icon shows presence of a photo:**
**On hover:**

View user profile photos from admin list of users

---

app/assets/stylesheets/responsive/_notes_styles.scss

BEFORE:
* Red: https://webaim.org/resources/contrastchecker/?fcolor=D32A0E&bcolor=FDE7E3 (4.31:1 – bad)
* Yellow: https://webaim.org/resources/contrastchecker/?fcolor=D3710E&bcolor=FDF0E3 (3.05:1 – bad)
* Green: https://webaim.org/resources/contrastchecker/?fcolor=358753&bcolor=CFECDA (3.51:1 – bad)
* Blue: https://webaim.org/resources/contrastchecker/?fcolor=006687&bcolor=EDFBFF (6.1:1 – pretty good)
AFTER:
* Red: https://webaim.org/resources/contrastchecker/?fcolor=8b1c0a&bcolor=FDE7E3 (7.81:1 – pass)
* Yellow: https://webaim.org/resources/contrastchecker/?fcolor=733e08&bcolor=FDF0E3 (7.74:1 – pass)
* Green: https://webaim.org/resources/contrastchecker/?fcolor=1f5031&bcolor=CFECDA (7.4:1 – pass)
* Blue: https://webaim.org/resources/contrastchecker/?fcolor=00526e&bcolor=EDFBFF (8.15:1 – …

Improve note style colour contrast

---

app/views/alaveteli_pro/info_request_batches/_info_request_batch.html.erb
app/views/alaveteli_pro/plans/index.html.erb
app/views/comment/_suggestions.html.erb

Noticed these when pulling new translation from Transifex. 
<hr>

Fix broken HTML in translations

---

.github/workflows/rubocop.yml

Pin to working version. Since v2.15.0 (or reviewdog core v0.19.0) the filter mode doesn't seem to respected.
<hr>

Update reviewdog CI action config

---

config/initializers/health_checks.rb
doc/CHANGES.md
spec/integration/health_checks_spec.rb

Modify the health check to track the oldest job in the queue more effectively.
Previously, the health check inspected the created_at timestamp of the oldest job, which could be misleading if many jobs were queued simultaneously.
Now, during each check, we will determine whether the oldest job in the queue has changed. We will log the current time whenever a change is detected and continue to return this time until we observe a change in the oldest job.
This ensures the health check will only fail if the job queue is stuck, with no jobs processed for over an hour.

Update Xapian indexing health check

---

app/controllers/info_request_batch_controller.rb
app/views/citations/_citation.html.erb
app/views/info_request_batch/_citations.html.erb
app/views/info_request_batch/show.html.erb
app/views/request/_citations.html.erb
doc/CHANGES.md
spec/views/info_request_batch/_citations.html.erb_spec.rb
spec/views/request/_citations.html.erb_spec.rb

Fixes https://github.com/mysociety/alaveteli/issues/6600
Adds list of citations on batch pages.
Citation can already be added to batches (via individual requests). This will make the sidebars consistent and show off good requests and usage of sites.

[#6600] Add citations on batch pages

---

app/controllers/admin_comment_controller.rb
app/controllers/admin_general_controller.rb
app/models/comment.rb
app/models/info_request_event.rb
app/views/admin_comment/edit.html.erb
app/views/admin_general/_destroy_comment.html.erb
config/routes.rb
doc/CHANGES.md
spec/controllers/admin_comment_controller_spec.rb
spec/integration/admin_comment_controller_destroy_spec.rb
spec/models/comment_spec.rb
spec/models/info_request_event_spec.rb

Fixes #6384 
Adds comment deletion to the request admin and comments admin pages, for single annotations and bulk deletion
Sometimes annotations need deleting entirely to comply with GDPR. This stops admins needing to nag the devs to do it.
Pro Admin timeline view:
Normal admin view:
Deletion event log:
Comments admin page
Request admin page:
Single annotation edit page
I think this is almost ready now, but there's undoubtedly room for improvement.

[#6384] Add admin button to delete annotations

---

app/models/alaveteli_pro/invoice.rb
doc/CHANGES.md
spec/models/alaveteli_pro/invoice_spec.rb

Fixes #8344
Fix rendering invoices view
Exceptions when Pro/former-pro users attempted to view their Pro invoices. Happened when there were 100% discounted invoices resulting in no charges.

[#8344] Fix rendering invoices view

---

app/views/layouts/admin.html.erb

Add link to TICTeC ATI homepage from admin footer
While there is a more direct link to the "Knowledge Hub", this feels
like a better place to link to and doesn't clash with the "Community"
link to alaveteli.org.
Fixes https://github.com/mysociety/alaveteli/issues/8354

[#8354] link to tictec knowledge hub

---

.ruby-style.yml

Allow shorthand syntax but allow key values need to be consistent.
Good:
```
{ foo: 'foo', bar: 'bar' }
```
Good:
```
foo = 'foo'; bar = 'bar'
{ foo:, bar: }
```
Bad:
```
foo = 'foo'
{ foo:, bar: 'bar' }
```
<hr>

Configure hash style

---

app/assets/stylesheets/responsive/_popups_layout.scss

Working on another ticket I noticed the markup for the `popup` and realised that there is a close button, however is not visible enough(opacity and size) and the clickable area is also quite small.
- Increases the size of the button
- Get rids of the opacity
- It also positions the close button vertically in the middle, specially on smaller screen it think it looks nicer.
- The content has being centred. For this type of one liner messages it looks a bit nicer and for having a different alignment than the rest of the page it pops up a bit more, but happy if we want to keep it the left aligned.
https://github.com/user-attachments/assets/ee75629d-91f0-40be-baa7-57748480a2a7
<hr>

Layout and spacing improvements to popup banner

---

doc/CHANGES.md
script/mailin

Support multiple exception notifications addresses when handling errors
running script/mailin.

Fix error handling in script/mailin

---

app/assets/stylesheets/responsive/_global_style.scss
app/assets/stylesheets/responsive/alaveteli_pro/_projects_layout.scss
app/controllers/alaveteli_pro/projects_controller.rb
app/controllers/projects/extracts_controller.rb
app/javascript/controllers/projects/key_set/select_controller.js
app/javascript/controllers/projects/key_set_controller.js
app/models/dataset/key.rb
app/models/dataset/value.rb
app/views/alaveteli_pro/projects/_key_set.html.erb
app/views/alaveteli_pro/projects/_select_key.html.erb
app/views/alaveteli_pro/projects/edit_key_set.html.erb
app/views/alaveteli_pro/projects/update_key_set.turbo_stream.erb
app/views/projects/dataset/keys/_select_key.html.erb
db/migrate/20240926164308_add_options_to_dataset_key.rb
doc/CHANGES.md
spec/factories/dataset_keys.rb
spec/models/dataset/key_spec.rb
spec/models/dataset/value_spec.rb

Fixes #8117
Adds a project question select format
Projects owners want to be able to provide a list of options for contributors to pick from.

Dataset select

---

app/models/info_request/prominence/not_embargoed_query.rb
app/models/statistics/leaderboard.rb

Update info request not embargoed query:
1. Remove the SQL select prefix as this will allow the query to be used in join queries
2. Refactor query
<hr>

Update info request not embargoed query

---

app/controllers/admin/citations_controller.rb
app/models/citation.rb
app/views/admin/citations/index.html.erb
doc/CHANGES.md
spec/controllers/admin/citations_controller_spec.rb
spec/models/citation_spec.rb

Allow basic filtering of Citations by source_url.

Add basic Citation search

---

Gemfile
Gemfile.lock

Unpin the gem version. Change to suppress ERB warning has been released.
<hr>

Bump sprockets from `f4d3dae` to `3.7.5`

---

app/views/admin_general/_admin_navbar.html.erb

With the admin navbar showing we see `Empty string passed to getElementById().` warnings due to bootstrap dropdown menus.
Removing the blank href on dropdown toggles fixes this.
<hr>

Fix JS warnings when logged in as admin

---

app/views/request/_tabs.html.erb

This moves the arrow on the tab bar, which was annoying me.
fixes #8431 
Moves the arrow
It makes more sense to point to the browse page
n/a
Hope this is ok! 
<hr>
Have you updated the changelog? If this is not necessary, put square brackets around this: [skip changelog]

Fix the arrow on the topic pages

---

Gemfile
Gemfile.lock
config/storage.yml-example
doc/CHANGES.md

As far as I'm aware this gem isn't used by any Alaveteli site.
It hasn't been updated since 2017 and is preventing installation of
other gems due to restrictive dependencies versions requirements such as
`faraday ~> 0.9` which prevents installation of other gems.

Drop azure-storage

---

app/models/info_request.rb
spec/models/info_request_spec.rb

Fixes #4160
Update InfoRequest.find_existing
Squish extra whitespace and newlines within the title attribute so that it matches request titles stored in the database.
<hr>

[#4160] Update InfoRequest.find_existing

---

app/models/concerns/notable.rb
doc/CHANGES.md
spec/models/concerns/notable_and_taggable.rb

Fixes #7293
Update Notable#all_notes
Update the concern so that records tagged with `name:value` will be associated with notes tagged as `name`.

[#7293] Update Notable#all_notes

---

app/controllers/admin_general_controller.rb

Fixes #8369
Supersedes #8370
Refactor timeline method in AdminGeneralController
- Introduce get_timeline_events method for improved timeline event fetching
- Improve pagination handling for better performance limiting the amount of data loaded into memory
- Optimize SQL queries using UNION ALL for combined event types
- Separate logic for authority changes and info request events
- Remove redundant code and simplify overall structure
Using the "All time" filter on the admin event timeline caused performance issues on sites with a large history. 
Found this branch locally work was done back in Aug.
<hr>

[#8369] Refactor timeline method in AdminGeneralController

---

app/views/request_game/play.html.erb
doc/CHANGES.md

Has been deprecated since 2012 and they've actually removed it over the last year. Would be nice to replace with something else, but for now this just removes the broken element.
Fixes https://github.com/mysociety/alaveteli/issues/2366

[#2366] Remove broken Google Chart

---

app/models/alaveteli_pro/invoice_collection.rb
spec/models/alaveteli_pro/invoice_collection_spec.rb

Fixes #8465
Fix loading Stripe invoices
Broken since the recent refactoring. Need to now call `id` on the Stripe Customer object and pass this into the list invoices API call.
<hr>

[#8465] Fix subscription invoices view

---

locale/cy/app.po

Fixes #8467
Patch Welsh translation
Instead of waiting for the next translation hotfix we can patch this and prevent exception notifications.
<hr>

[#8467] Patch Welsh translation

---

app/controllers/alaveteli_pro/stripe_webhooks_controller.rb
app/models/alaveteli_pro/price.rb
app/models/alaveteli_pro/subscription.rb
app/views/alaveteli_pro/plans/show.html.erb
spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb
spec/models/alaveteli_pro/price_spec.rb
spec/models/alaveteli_pro/subscription_spec.rb
spec/views/alaveteli_pro/plans/index.html.erb_spec.rb

Adds a couple of Stripe fixes for issues preventing signups.
- Change `Price.id` to `Price.to_param` so prices can be loaded
- Correct payment intent status (missing an `s`) should fix incomplete subscriptions
- Update payment failed email, don't send to users without current subscriptions - ie those who are attempting to sign up. 
Getting payments working correctly.
<hr>

Stripe Prices fixes

---

app/mailers/alaveteli_pro/embargo_mailer.rb
app/mailers/alaveteli_pro/subscription_mailer.rb
app/mailers/application_mailer.rb
app/mailers/contact_mailer.rb
app/mailers/info_request_batch_mailer.rb
app/mailers/notification_mailer.rb
app/mailers/request_mailer.rb
app/mailers/survey_mailer.rb
app/mailers/track_mailer.rb
app/mailers/user_mailer.rb
doc/CHANGES.md
spec/fixtures/locale/es/app.po
spec/mailers/alaveteli_pro/embargo_mailer_spec.rb
spec/mailers/alaveteli_pro/subscription_mailer_spec.rb
spec/mailers/info_request_batch_mailer_spec.rb
spec/mailers/notification_mailer_spec.rb
spec/mailers/request_mailer_spec.rb
spec/mailers/survey_mailer_spec.rb
spec/mailers/track_mailer_spec.rb

Issue #5164 PR candidate
Supersede #8469 
Fixes #5164.
Automatic email alerts are sent with the subject localized with the receiving user's locale.
Needed to ensure that the receiving user understands the subject line.
User mails are sent with `ApplicationMailer#mail_user`. The change consists of requiring the `subject:` arg to `mail_user` to be a `proc`, and running the `proc` using the locale of the `user` arg.
All other changes are straightforward rewrites of the 26 other methods that call `mail_user`, and corresponding tests.
Below is a list of the affected methods, where the corresponding tests are, and why some tests are not changed.
```
app/mailers/alaveteli_pro/embargo_mailer.rb
expiring_alert(user, info_requests)
test: spec/mailers/alaveteli_pro/embargo_mailer_spec.rb:124/160 …
```

[#5164] Alert email subject in the receivers language 

---

Gemfile
Gemfile.lock
config/initializers/active_job_uniqueness.rb
lib/redis_connection.rb

Required for #8090
Bump activejob-uniqueness from 0.2.5 to 0.4.0
Need to upgrade this gem due to a dependency on ActiveJob which is preventing upgrade to Rails 7.1+
Dependabot attempted to upgrade this but I closed this PR with [this comment](https://github.com/mysociety/alaveteli/pull/8111#issuecomment-1914420012). This doesn't seem to be an issue anymore.
<hr>

Bump activejob-uniqueness from 0.2.5 to 0.4.0

---

Gemfile.lock
db/migrate/20250110145844_change_flipper_gates_value_to_text.rb
doc/CHANGES.md
gems/alaveteli_features/alaveteli_features.gemspec

Required for Rails 8 compatibility. Including database migration.

Bump flipper-active_record from 0.28.3 to 1.3.2

---

Gemfile
Gemfile.lock

Required for Rails 8 compatibility.

 Bump strip_attributes from 1.12.0 to 1.14.1

---

.github/workflows/ci.yml
Gemfile
Gemfile.lock
README.md
doc/CHANGES.md

Fixes #8056
Add support for Ruby 3.3

[#8056] Add support for Ruby 3.3

---

config/crontab-example
config/environments/development.rb
config/environments/staging.rb

Fixes #8532
Update crontab log level from "info" to "warn".
Crontab emails including "info" messages.

[#8532] Update crontab log level

---

.github/workflows/ci.yml
Gemfile
Gemfile.lock
README.md
app/controllers/refusal_advice_controller.rb
config/initializers/oink.rb
doc/CHANGES.md
spec/spec_helper.rb

Fixes #8530
Add support for Ruby 3.4

[#8530] Add support for Ruby 3.4

---

app/jobs/foi_attachment_mask_job.rb
doc/CHANGES.md

Fixes #8543
See: https://github.com/rails/rails/pull/53490
Update Attachment masking job setup
This change increase the `Regexp.timeout` from 1 sec to 60 secs.
This is needed since Rails 8.0 now defaults to 1 sec to stop possible DoS attacks. Since this is in a background job the timeout duration is less of a concern.

[#8543] Update Attachment masking job setup

---

lib/tasks/config_files.rake

Fixes #8546
Fix exception with rake task
Update options passed into `InfoRequest.reject_incoming_at_mta` to ensure they are cast to integer correct as the method expects. Tests only pass in integers so we should here too.

[#8546] Fix exception with rake task

---

app/models/citation.rb

Fixes #8545
Fix citation JSON exception
Update method declaration. This is called from the controller/view to render to citations as JSON. Rails used to pass an options argument but now doesn't.

[#8545] Fix citation JSON exception

---

.gitignore

Slightly widens the scope of a few `.gitignore` lines to include parent directories in particular. These get created by our deployment automation and as it stands are visible to git.
To prevent build/deployment working copies being cluttered with uncommitted changes. Came up during some internal work looking at our deployment/build systems.
I don't think any of these directories ever need to be in version control, so I don't think this should be a problem unless there's something I have missed.
I don't think a changelog entry is needed for this, either.
<hr>
Have you updated the changelog? If this is not necessary, put square brackets around this: [skip changelog]

Tweaks to `.gitignore` to better ignore some deployment artefacts

---

doc/CHANGES.md
lib/alaveteli_pro/metrics_report.rb
spec/lib/alaveteli_pro/metrics_report_spec.rb

Fixes Pro metric report
Removed hard-coded plan/price IDs and switches to the Stripe prices configured in general.yml.

Fixes Pro metric report

---

spec/controllers/request_controller_spec.rb

Fixes #8561
Fix RequestController transient spec failure
Ensure the Xapian index in the test environment is built and ready for this controller actions to be tested.
<hr>

Fix RequestController transient spec failure

---

.github/workflows/ci.yml

Don't report errors if Coveralls fails for any reason. Their API seems to be having issues and as we don't really need the result of these checks lets ignore the errors.
Also pins Coveralls action to v2 just incase there are ever any braking changes on master.
<hr>

Update GitHub Action workflow

---

app/controllers/alaveteli_pro/stripe_webhooks_controller.rb
doc/CHANGES.md
spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb
spec/fixtures/stripe_webhooks/invoice.payment_succeeded.json

Fixes #8565
Update payment intent descriptions
After successful payments ensure the payment intent description is correct. This helps accounting procedures.

[#8565] Update payment intent descriptions

---

app/models/pro_account.rb
spec/models/pro_account_spec.rb

Fix Stripe customer creation in development
We use `@localhost` email addresses for our development example users. We can't create Stripe customers with these email address as they aren't valid.
This change will allow our pro example users to login and allow non-pro example users to sign up without needing to change their email address.
<hr>

Fix Stripe customer creation in development

---

app/models/user.rb
doc/CHANGES.md
spec/controllers/general_controller_spec.rb
spec/models/user_spec.rb
spec/models/xapian_spec.rb

Limit user indexing to users who've made requests to prevent users stumbling across spam user profiles via the on-site search.
You can wait for this change to eventually percolate as account records are updated, or manually update the search index with the following:
bin/rails runner "User.where(info_requests_count: 0).in_batches.each_record(&:xapian_mark_needs_index)"
Depending on the number of affected records and compute resources, you may wish to throttle the reindexing by running a similar version of this in the rails console:
User.where(info_requests_count: 0).in_batches do |users|
users.each(&:xapian_mark_needs_index)
sleep(360) # Throttle the reindexing
end

Limit user profile indexing

---

app/views/user/show/_show_profile.html.erb
doc/CHANGES.md

Fixes https://github.com/mysociety/sysadmin/issues/2042.
The UK Online Safety Act requires good content reporting capabilities.
We have report links attached to most user generated content, but not here. This is a quick fix to add a report link to user profile pages, which goes to the general contact form.
In future it would be good to have this direct to a more structured form, but this works for now as we consider user profiles more generally.
Visitor
Signed in

Add report link on user profile page

---

app/views/projects/dataset/show.html.erb

Moves the project dataset download button above the table. Projects can include hundreds of requests, which results in a very long table. This makes it easy to miss that you can download the dataset as a CSV, or if you do know, makes for a very long scroll to get there.
**BEFORE**
**AFTER**

Move dataset download button

---

app/views/admin/citations/edit.html.erb
doc/CHANGES.md

URLs tend to be quite long, so editing them is difficult within a short input field. Used the same for title to balance the form.
BEFORE
AFTER

Improve citation form field width

---

app/assets/stylesheets/responsive/_sidebar_style.scss

The compact list is a bit too compact. It's difficult to tell where one citation ends and the next begins, especially when some citations are broken over multiple lines.
BEFORE
AFTER

Add spacing between citations

---

app/mailers/request_mailer.rb
doc/CHANGES.md
spec/mailers/request_mailer_spec.rb

If someone classifies an old request as needing clarification through the request game, the request author will get notified. After this period most authorities will have closed the case so clarification is not the best route.

Only send clarification notifications to recent requests

---

app/models/foi_attachment.rb
app/models/incoming_message.rb
app/models/info_request.rb
db/migrate/20250304205550_add_locked_to_foi_attachments.rb
doc/CHANGES.md
spec/models/foi_attachment_spec.rb
spec/models/incoming_message_spec.rb
spec/models/info_request_spec.rb

Fixes #8622
Add attachment locking
Easier admin and better compliance with GDPR requests. This will open the door to allow us to delete raw emails so we can fully remove PII.

[#8622] Add attachment locking

---

app/assets/stylesheets/admin.scss
app/controllers/admin/foi_attachments_controller.rb
app/helpers/admin/locked_helper.rb
app/models/foi_attachment.rb
app/models/incoming_message.rb
app/models/info_request.rb
app/views/admin/foi_attachments/edit.html.erb
app/views/admin_incoming_message/_foi_attachments.html.erb
app/views/admin_request/show.html.erb
db/migrate/20250304205550_add_locked_to_foi_attachments.rb
db/migrate/20250408105243_add_replaced_at_and_replaced_reason_to_foi_attachments.rb
doc/CHANGES.md
lib/mail_handler/backends/mail_backend.rb
lib/normalize_string.rb
spec/controllers/admin/foi_attachments_controller_spec.rb
spec/factories/foi_attchments.rb
spec/helpers/admin/locked_helper_spec.rb
spec/lib/basic_encoding_spec.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb
spec/models/foi_attachment_spec.rb
spec/models/incoming_message_spec.rb
spec/models/info_request_spec.rb

Fixes #8623
Admin UI for attachment locking & replacement 
Easier admin and better compliance with GDPR requests. This will open the door to allow us to delete raw emails so we can fully remove PII.

[#8623] Admin UI for attachment locking & replacement

---

app/assets/stylesheets/admin.scss
app/controllers/admin/foi_attachments_controller.rb
app/helpers/admin/locked_helper.rb
app/models/foi_attachment.rb
app/models/incoming_message.rb
app/models/info_request.rb
app/views/admin/foi_attachments/edit.html.erb
app/views/admin_incoming_message/_foi_attachments.html.erb
app/views/admin_request/show.html.erb
db/migrate/20250304205550_add_locked_to_foi_attachments.rb
db/migrate/20250408105243_add_replaced_at_and_replaced_reason_to_foi_attachments.rb
doc/CHANGES.md
lib/mail_handler/backends/mail_backend.rb
lib/normalize_string.rb
spec/controllers/admin/foi_attachments_controller_spec.rb
spec/factories/foi_attchments.rb
spec/factories/incoming_messages.rb
spec/helpers/admin/locked_helper_spec.rb
spec/lib/basic_encoding_spec.rb
spec/lib/mail_handler/backends/mail_backend_spec.rb
spec/models/foi_attachment_spec.rb
spec/models/incoming_message_spec.rb
spec/models/info_request_spec.rb

Fixes #8624
Ensures locked attachments aren't masked when caching the main body part in the incoming message instance or when indexing attachments in Xapian.
Easier admin and better compliance with GDPR requests. This will open the door to allow us to delete raw emails so we can fully remove PII.

[#8624] Attachment locking - main body masking

---

README.md

None.
Improves punctuation and semantic consistency amongst `<code>`-ified text in [`f0b4a56370fc08f4c9cb36d7d4e1432f74e07faf/README.md`](https://github.com/mysociety/alaveteli/blob/f0b4a56370fc08f4c9cb36d7d4e1432f74e07faf/README.md?plain=1#L29C75-L44C65:~:text=%23%23%20Installing,\(such%20as%20RVM%20or%20.rbenv).
WHATWG specification adherence and screen reader support.
None.
None are necessary.
None.
<hr>

Improve punctuation and semantic consistency in `README.md`.

---

app/models/foi_attachment.rb
spec/models/foi_attachment_spec.rb

Fixes #8663
Update FoiAttachment default replacement body
This should always be a UTF-8 string. Without this exceptions were being
raised on the admin attachment edit view as we were rendering both
binary and UTF-8 strings.
<hr>

[#8663] Update FoiAttachment default replacement body

---

app/helpers/public_body_helper.rb
spec/helpers/public_body_helper_spec.rb

Fixes #8694
Filter out categories with blank descriptions to improve rendering of the type of authority helper text.

[#8694] Fix type of authority helper

---

app/models/info_request.rb
app/models/public_body.rb
app/models/user.rb
doc/CHANGES.md
spec/models/info_request_spec.rb
spec/models/public_body_spec.rb
spec/models/user_spec.rb

Fixes #8600
Index user profiles once they've made their first request. If their only request is then destroyed de-index the profile.
Follow on from #8599 to ensure profiles are indexed/de-indexed promptly.

[#8600] Index users once they've made their first request

---

app/views/admin/info_request_batches/_admin_columns.html.erb
app/views/admin_incoming_message/_admin_columns.html.erb
app/views/admin_outgoing_message/_admin_columns.html.erb
doc/CHANGES.md

Fixes #8709
Fix admin text columns rendering
Limit the amount of content shown even when expanding the content.
Showing more than 1000 characters might be possible but lets see if this works for the admin.

[#8709] Fix admin text columns rendering

---

config/application.rb

Prevent custom middleware from appearing in logs
Developer experience  
<hr>

Prevent custom middleware from appearing in logs

---

app/controllers/users/messages_controller.rb
app/views/projects/projects/_project_nav.html.erb
app/views/projects/projects/show.html.erb
app/views/user/contact.html.erb
app/views/user/show/_show_profile.html.erb
app/views/users/messages/disabled.html.erb
config/general.yml-example
config/initializers/alaveteli_features.rb
doc/CHANGES.md
lib/configuration.rb
spec/controllers/users/messages_controller_spec.rb

Fixes mysociety/sysadmin#2038
Add configuration to disable user-to-user messaging feature. If "projects" is used then members/contributors will still be able to message the project owner as we now grant access to the user-to-user messaging through a temp signed global ID.
Reduce WDTK service OSA risk around the "Harassment, stalking threats and abuse" illegal harm.

[sys#2038] Add configuration for user-to-user messaging feature

---

app/controllers/admin_outgoing_message_controller.rb
app/models/outgoing_message.rb
app/views/admin_outgoing_message/edit.html.erb
doc/CHANGES.md
spec/controllers/admin_outgoing_message_controller_spec.rb
spec/models/outgoing_message_spec.rb

Feature: Attachment locking - add ability to prevent logging of outgoing message body edits
Sometimes the outgoing messages might contain content which we don't want to retain. Before this PR editing the message in the admin UI would result in the content being stored in the request event log.

Attachment locking - outgoing message body edits logging

---

doc/CHANGES.md
lib/user_spam_scorer.rb
spec/lib/user_spam_scorer_spec.rb

Add ability to define custom spam scoring
This enhancement allows sites to implement custom scoring methods to identify and filter potential spam user registrations.

Add ability to define custom spam scoring

---

app/controllers/application_controller.rb
app/controllers/request_controller.rb
app/controllers/user_controller.rb
config/general.yml-example
doc/CHANGES.md
spec/controllers/request_controller_spec.rb

Update blocked IP helper for permitted countries
While I appreciate we're dealing with double negative here this is a
quick way of implementing a permitted country list using the existing
restricted countries configuration option.

Permitted countries

---

app/mailers/user_mailer.rb
app/views/user/signchangeemail.html.erb
app/views/user/signchangeemail_confirm.html.erb
doc/CHANGES.md
spec/integration/change_email_address_spec.rb

Original PR included the changes in #8763, which subsequently was extracted into its own PR.
Update user email change confirmation process, switching to sending confirmation emails to the old email address.
~~Also adds tracking of user profile email address changes.~~
Helps verify that the request to change the email address is legitimate and initiated by the user. This prevents unauthorised changes that could compromise the account.
~~Email address change tracking is needed so admins are able to assist users when mistakes are made when changing their address as new email addresses aren't validated.~~

Update user email change confirmation process

---

app/views/admin/users/_sign_in_table.html.erb
doc/CHANGES.md

Make it clear that we don't have any sign in data within the retention period. "None yet" makes it look like the user hasn't signed in at all, unless you're familiar with the details of the retention period which some admins may not be.
Fixes https://github.com/mysociety/alaveteli/issues/8799

[#8799] Clarify no sign ins message

---

app/assets/stylesheets/admin.scss
app/controllers/admin/debug_controller.rb
app/controllers/admin_general_controller.rb
app/views/admin/changelog/index.html.erb
app/views/admin/debug/index.html.erb
app/views/admin_general/_admin_navbar.html.erb
config/general.yml-example
config/routes.rb
doc/CHANGES.md
lib/configuration.rb
spec/controllers/admin/debug_controller_spec.rb
spec/integration/admin_spec.rb
spec/lib/configuration_spec.rb

Fixes #1636
Extract `AdminGeneralController#debug` to `Admin::DebugController#index`, tidy up its view, and render a sanitised version of`AlaveteliConfiguration` so that admins can view the configuration without a server ssh session.
Helps less technical users and admins of Alavetelis hosted by mySociety.
Playing around with speaking at chatGPT after work because I was annoyed at having to ssh to figure out the `AlaveteliConfiguration.reply_very_late_after_days` value.
Weird issue with the routing – will try to resolve that before merge

[#1636] Show AlaveteliConfiguration in admin interface

---

app/controllers/concerns/user_spam_check.rb
app/models/user.rb
doc/CHANGES.md
spec/controllers/users/sessions_controller_spec.rb
spec/models/user_spec.rb

Admins may do things that trigger the spam scorer for testing purposes (e.g. use plus accounts). Admins should always be allowed to log in.

Don't spam-check admins

---

lib/tasks/users.rake

Part of https://github.com/mysociety/sysadmin/issues/2046
Improve rake tasks to remove user generate content optimising so tasks run quicker. Initially on WDTK these will still take a long time but running on a rolling basis should be much quicker now.
<hr>

[#2046] improve rake tasks to remove user generate content

---

app/controllers/request_controller.rb
app/models/comment.rb
app/models/concerns/rate_limited.rb
app/models/info_request.rb
app/models/user.rb
app/views/user/rate_limited.html.erb
doc/CHANGES.md
spec/controllers/request_controller_spec.rb
spec/models/info_request_spec.rb
spec/models/user_spec.rb

Fixes https://github.com/mysociety/whatdotheyknow-private/issues/415
Prevents too many requests being created too quickly.
We don't want to allow a user to sign up and smash through their daily limit in 5 minutes, then create a new account to do the same, and so on.
This ensures that the allocation is used sensibly. It hopefully won't affect the majority of genuine users.
Same vibe as https://github.com/mysociety/alaveteli/pull/7602. Extracted out a shared concern (cc https://github.com/mysociety/alaveteli/issues/7620)

Add request creation interval rate limit

---

app/controllers/attachments_controller.rb
doc/CHANGES.md
spec/controllers/attachments_controller_spec.rb

When we extract PDFs to HTML we try to extract the text to HTML text, but many will also include images for parts of the PDF that can't be parsed or don't make sense to parse as text.
Parts of this can fail, leaving missing images. Every missing image in an attachment causes a redirect to the request page, meaning we see large spikes to request pages when accessing attachments with lots of missing images, effectively self-DDOSing the app.
The 303 redirect was introduced in 501b2b8. For top-level attachments this makes more sense, since occasionally the part number / filename can change (through reparsing, and since then we can now modify attachment names), so in that case it's nicer to take users back to at least the request page where the attachment originated as they may be able to find …

404 for not found AttachmentToHTML sub-files

---

app/controllers/users/confirmations_controller.rb
doc/CHANGES.md
spec/controllers/users/confirmations_controller_spec.rb

If an unconfirmed user resets their password, they are logged in and can perform actions like creating requests while their account is still unconfirmed.
The password reset link acts as a confirmation email, so it doesn't seem like there's a reason not to confirm them in this step.
Fixes https://github.com/mysociety/alaveteli/issues/8870.
@gbp can you think of any reasons _not_ to do this?

[#8870] Confirm users after following password reset link

---

app/views/request/_share_by_link.html.erb

Fixes: [Embargoed request private link "Enable" button has odd (absent) styling](https://github.com/mysociety/whatdotheyknow-theme/issues/1957)	https://github.com/mysociety/whatdotheyknow-theme/issues/1957
Adds class `button` to "Enable" and "Disable" buttons, so it matches the style of each theme.
<hr>

Added `button` class to share private link buttons

---

app/models/concerns/rate_limited.rb
app/models/note.rb
app/models/public_body.rb
app/models/public_body/calculated_home_page.rb
app/models/public_body/csv_import.rb
app/models/public_body/foi_officer_access.rb
app/models/user.rb
lib/acts_as_xapian/acts_as_xapian.rb
spec/models/public_body_spec.rb

Update `cattr_*` calls
We noticed in https://github.com/mysociety/whatdotheyknow-theme/pull/2052 that using the defaults value option for `cattr_*` can cause issues when the defaul value itself is sourced from the class attribute. This PR fixes this and updates other `cattr_*` as now I've looked more at the documentation of the method I understand what it is actually doing and in some cases we don't need the instance methods in defined by default.
<hr>

Update `cattr_*` calls

---

app/views/user/_signup.html.erb

Other form fields are within a `<p>` tag to give them margin bottom. In WDTK we customise this view to add another form_item_note underneath the button, which gets jammed up against it.
A `<p>` isn't the most ideal way to fix this but it mirrors what's there without having to mess around with the whole view.
No real change in core but see https://github.com/mysociety/whatdotheyknow-theme/pull/2056 for theme context.

Fix signup button layout

---

app/views/admin_incoming_message/_actions.html.erb
app/views/admin_incoming_message/_holding_pen_actions.html.erb
app/views/admin_raw_email/show.html.erb
doc/CHANGES.md

Minor clean up the admin raw email actions while thinking about https://github.com/mysociety/alaveteli/issues/8803.
---
Actions on the incoming message view as they are now:
But now no actions on the raw email page (since the actions are all taken on the incoming message):
…except when in the holding pen we now have the subset of relevant actions (we _show_ the raw email but take _action_ on the incoming message 🫠):

Clean up raw email actions
